using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using RentAll.Domain.Configuration;
using RentAll.Domain.Enums;
using RentAll.Domain.Interfaces.Services;
using RentAll.Domain.Managers;
using RentAll.Infrastructure.Repositories.Accounting;
using RentAll.Infrastructure.Repositories.Common;
using RentAll.Infrastructure.Repositories.Contacts;
using RentAll.Infrastructure.Repositories.Health;
using RentAll.Infrastructure.Repositories.Maintenances;
using RentAll.Infrastructure.Repositories.Organizations;
using RentAll.Infrastructure.Repositories.Properties;
using RentAll.Infrastructure.Repositories.Reservations;
var appSettings = Options.Create(new AppSettings { DbConnections = [new DbConnection { DbName = "RentAll", ConnectionString = "Server=GESLER;Database=RentAll;Trusted_Connection=True;Encrypt=False;" }] });
var manager = new AccountingManager(new OrganizationRepository(appSettings), new PropertyRepository(appSettings), new AccountingRepository(appSettings, NullLogger<AccountingRepository>.Instance), new MaintenanceRepository(appSettings), new ReservationRepository(appSettings), new JournalEntryRepository(appSettings, NullLogger<JournalEntryRepository>.Instance), new OrganizationManager(new CommonRepository(appSettings), new OrganizationRepository(appSettings)), new ContactRepository(appSettings), new EnabledFeatureFlags(), new HealthRepository(appSettings));
var orgId = Guid.Parse("280CD8DA-F1BE-41F2-AE6E-B45008CF3896");
var userId = Guid.Parse("22222222-2222-2222-2222-222222222222");
var r = await manager.SyncJournalEntriesForHealthFixAsync(orgId, "2", "transfer", [], null, userId);
Console.WriteLine($"Processed={r.DocumentsProcessed} Errors={r.Errors.Count}");
foreach (var e in r.Errors) Console.WriteLine(e);
