<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\RentAll.Domain\RentAll.Domain.csproj" />
    <ProjectReference Include="..\..\RentAll.Infrastructure\RentAll.Infrastructure.csproj" />
  </ItemGroup>
</Project>
