using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Journal Entry
    private async Task<string?> RefreshInvoiceChargeJournalEntriesAsync(Invoice invoice, Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(invoice.OrganizationId))
        {
            await DeleteJournalEntriesForInvoiceChargesAsync(invoice);
            return null;
        }

        if (await TryUseCrossPeriodInvoiceJournalEntryPathAsync(invoice))
        {
            var (crossPeriodEntry, decisionMessage, postAsStandardInvoice) =
                await CreateJournalEntriesFromCrossPeriodInvoiceAsync(invoice, currentUser);

            if (crossPeriodEntry != null)
            {
                await DeleteOwnerDistributionJournalEntriesForInvoiceAsync(invoice);
                return null;
            }

            await LogInvoiceSplitDecisionAsync(invoice, split: false, message: decisionMessage);

            if (postAsStandardInvoice)
            {
                await RefreshStandardInvoiceChargeJournalEntriesAsync(invoice, currentUser);
                return null;
            }

            return string.IsNullOrWhiteSpace(decisionMessage)
                ? "Cross-period refresh failed; charge journal entries were not changed."
                : decisionMessage;
        }

        await RefreshStandardInvoiceChargeJournalEntriesAsync(invoice, currentUser);
        return null;
    }

    private async Task RefreshStandardInvoiceChargeJournalEntriesAsync(Invoice invoice, Guid currentUser)
    {
        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);
        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);

        var allInvoiceEntries = await GetAllJournalEntriesForInvoiceAsync(
            invoice.OrganizationId,
            invoice.OfficeId,
            invoice.InvoiceId);
        var existingInvoiceEntries = allInvoiceEntries
            .Where(entry => entry.JournalEntryKindId is JournalEntryKind.Charge or JournalEntryKind.OwnerExpected)
            .Where(entry => MatchesJournalEntryAccountingPeriod(entry, invoice.AccountingPeriod))
            .ToList();

        await DeleteOwnerDistributionJournalEntriesForInvoiceAsync(invoice);

        var chargeExisting = existingInvoiceEntries.FirstOrDefault(entry => IsInvoiceChargeJournalEntry(entry, accountsReceivableAccountId));

        var rebuiltCharge = await CreateJournalEntryFromInvoiceAsync(invoice, chartOfAccounts, accountingOffice, currentUser);
        JournalEntry? updatedCharge = null;
        if (HasActiveJournalEntryLines(rebuiltCharge))
        {
            updatedCharge = await UpsertAutoGeneratedJournalEntryAsync(
                rebuiltCharge,
                chargeExisting != null ? [chargeExisting] : [],
                currentUser,
                invoice.OrganizationId);
        }
        else if (chargeExisting != null)
        {
            await DeleteOpenJournalEntryAsync(chargeExisting.JournalEntryId, invoice.OrganizationId);
        }

        var retainedEntryIds = new HashSet<Guid>();
        if (updatedCharge != null)
            retainedEntryIds.Add(updatedCharge.JournalEntryId);

        JournalEntry? updatedOwnerShare = null;
        if (TryGetInvoiceRentalLineAmount(invoice, out _))
        {
            var rentPlus4000Base = await GetInvoiceRentPlus4000BaseAsync(invoice);
            updatedOwnerShare = await UpsertJournalEntryFromInvoiceForOwnerShareAsync(
                invoice,
                rentPlus4000Base,
                existingInvoiceEntries,
                currentUser);
        }
        else
        {
            var existingOwnerShare = existingInvoiceEntries.FirstOrDefault(IsInvoiceOwnerShareJournalEntry);
            if (existingOwnerShare != null)
                await DeleteOpenJournalEntryAsync(existingOwnerShare.JournalEntryId, invoice.OrganizationId);
        }

        if (updatedOwnerShare != null)
            retainedEntryIds.Add(updatedOwnerShare.JournalEntryId);

        await DeleteJournalEntriesExceptAsync(
            existingInvoiceEntries.Where(IsInvoiceChargeOrOwnerExpectedJournalEntry),
            retainedEntryIds,
            invoice.OrganizationId,
            currentUser);
    }

    private async Task DeleteOwnerDistributionJournalEntriesForInvoiceAsync(Invoice invoice)
    {
        await DeleteJournalEntriesForSourceAsync(
            invoice.OrganizationId,
            invoice.OfficeId,
            (int)SourceType.OwnerDistribution,
            invoice.InvoiceId);
    }

    private async Task<List<JournalEntry>> GetJournalEntriesForInvoicePaymentLedgerLineAsync(Guid organizationId, int officeId, Invoice invoice, LedgerLine paymentLedgerLine)
    {
        return (await GetAllJournalEntriesForInvoiceAsync(organizationId, officeId, invoice.InvoiceId))
            .Where(entry => IsInvoicePaymentLedgerLineJournalEntry(entry, invoice, paymentLedgerLine))
            .ToList();
    }

    public async Task<int> DeactivateInvoicesByReservationIdAsync(Guid organizationId, Guid reservationId, Guid modifiedBy)
    {
        var reservation = await _reservationRepository.GetReservationByIdAsync(reservationId, organizationId)
            ?? throw new Exception("Reservation not found");
        if (reservation.OfficeId <= 0)
            throw new Exception("Reservation office is required");

        var invoices = (await _accountingRepository.GetInvoicesAsync(new InvoiceGetCriteria
        {
            OrganizationId = organizationId,
            OfficeIds = reservation.OfficeId.ToString(),
            ReservationId = reservationId,
            IncludeInactive = true,
            IncludePaid = true
        })).Where(invoice => invoice.IsActive).ToList();

        var deactivatedCount = await _accountingRepository.DeactivateInvoicesByReservationIdAsync(organizationId, reservationId, modifiedBy);

        foreach (var invoice in invoices)
            await DeleteJournalEntriesForInvoiceChargesAsync(invoice);

        return deactivatedCount;
    }

    public async Task<int> ReactivateInvoicesByReservationIdAsync(Guid organizationId, Guid reservationId, Guid modifiedBy)
    {
        var reservation = await _reservationRepository.GetReservationByIdAsync(reservationId, organizationId)
            ?? throw new Exception("Reservation not found");
        if (reservation.OfficeId <= 0)
            throw new Exception("Reservation office is required");

        var invoices = (await _accountingRepository.GetInvoicesAsync(new InvoiceGetCriteria
        {
            OrganizationId = organizationId,
            OfficeIds = reservation.OfficeId.ToString(),
            ReservationId = reservationId,
            IncludeInactive = true,
            IncludePaid = true
        })).Where(invoice => !invoice.IsActive).ToList();

        var reactivatedCount = await _accountingRepository.ReactivateInvoicesByReservationIdAsync(organizationId, reservationId, modifiedBy);

        foreach (var invoice in invoices)
        {
            var freshInvoice = await _accountingRepository.GetInvoiceByIdAsync(invoice.InvoiceId, organizationId);
            if (freshInvoice == null || !freshInvoice.IsActive)
                continue;

            await RefreshInvoiceChargeJournalEntriesAsync(freshInvoice, modifiedBy);
        }

        return reactivatedCount;
    }
    #endregion
}
