using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Triggers
    public async Task<JournalEntry?> CreateJournalEntryFromInvoiceAsync(Invoice invoice, Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(invoice.OrganizationId))
            return null;

        if (invoice.InvoiceId == Guid.Empty)
            throw new Exception("InvoiceId is required to create a journal entry");

        if (InvoiceCrossesAccountingPeriodBoundary(invoice))
        {
            var crossPeriodEntry = await CreateJournalEntriesFromCrossPeriodInvoiceAsync(invoice, currentUser);
            if (crossPeriodEntry != null)
                return crossPeriodEntry;
        }

        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = invoice.OrganizationId,
            OfficeIds = invoice.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = invoice.InvoiceId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        var existingEntry = existingEntries.FirstOrDefault(e => !e.IsVoided);
        if (existingEntry != null)
            return existingEntry;

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);
        var journalEntry = await BuildJournalEntryFromInvoiceAsync(invoice, chartOfAccounts, accountingOffice, currentUser);
        return await CreateAutoGeneratedJournalEntryAsync(journalEntry);
    }

    public async Task<JournalEntry?> CreateJournalEntryFromPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(invoice.OrganizationId))
            return null;

        if (paymentLedgerLine.LedgerLineId == Guid.Empty)
            throw new Exception("LedgerLineId is required to create a payment journal entry");

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);

        if (IsInvoicePrePayment(invoice, paymentLedgerLine))
            return await CreateJournalEntriesFromPrePaymentAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);

        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = invoice.OrganizationId,
            OfficeIds = invoice.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.InvoicePayment,
            SourceId = paymentLedgerLine.LedgerLineId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        var existingEntry = existingEntries.FirstOrDefault(e => !e.IsVoided);
        if (existingEntry != null)
            return existingEntry;

        var journalEntry = await BuildJournalEntryFromPaymentAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
        return await CreateAutoGeneratedJournalEntryAsync(journalEntry);
    }

    public async Task<JournalEntry> CreateJournalEntriesFromPrePaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        var receivedEntry = await GetOrCreatePrePaymentReceivedJournalEntryAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
        await GetOrCreatePrePaymentApplyJournalEntryAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
        return receivedEntry;
    }

    public async Task<JournalEntry> GetOrCreatePrePaymentReceivedJournalEntryAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = invoice.OrganizationId,
            OfficeIds = invoice.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.InvoicePayment,
            SourceId = paymentLedgerLine.LedgerLineId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        var existingEntry = existingEntries.FirstOrDefault(e => !e.IsVoided);
        if (existingEntry != null)
            return existingEntry;

        var journalEntry = await BuildJournalEntryFromPrePaymentReceivedAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
        return await CreateAutoGeneratedJournalEntryAsync(journalEntry);
    }

    public async Task<JournalEntry> GetOrCreatePrePaymentApplyJournalEntryAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = invoice.OrganizationId,
            OfficeIds = invoice.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = paymentLedgerLine.LedgerLineId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        var existingEntry = existingEntries.FirstOrDefault(e => !e.IsVoided);
        if (existingEntry != null)
            return existingEntry;

        var journalEntry = await BuildJournalEntryFromPrePaymentApplyAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
        return await CreateAutoGeneratedJournalEntryAsync(journalEntry);
    }

    public async Task<List<JournalEntry>> CreateJournalEntriesFromInvoicePaymentAsync(InvoicePayment invoicePayment, Guid currentUser)
    {
        var journalEntries = new List<JournalEntry>();

        if (invoicePayment.PaymentApplications.Count == 0)
            return journalEntries;

        foreach (var paymentApplication in invoicePayment.PaymentApplications)
        {
            var journalEntry = await CreateJournalEntryFromPaymentAsync(paymentApplication.Invoice, paymentApplication.PaymentLedgerLine, currentUser);
            if (journalEntry != null)
                journalEntries.Add(journalEntry);
        }

        return journalEntries;
    }
    #endregion

    #region Journal Entry
    private async Task<JournalEntry> BuildJournalEntryFromInvoiceAsync(Invoice invoice, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser, Guid? sourceIdOverride = null, string? memoSuffix = null)
    {
        var costCodes = await _accountingRepository.GetCostCodesByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);
        var costCodeById = costCodes.ToDictionary(c => c.CostCodeId);
        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var defaultIncomeAccountId = GetDefaultTenantIncome(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var propertyId = await ResolveInvoicePropertyIdAsync(invoice);

        var chargeLines = invoice.LedgerLines
            .Where(l => l.Amount != 0)
            .Where(l =>
            {
                costCodeById.TryGetValue(l.CostCodeId, out var costCode);
                return !IsPaymentLedgerLine(costCode);
            })
            .OrderBy(l => l.LineNumber)
            .ToList();

        var totalAmount = chargeLines.Sum(l => l.Amount);

        if (invoice.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required to create a journal entry for an invoice");

        var transactionDate = invoice.AccountingPeriod;
        var postingDate = invoice.AccountingPeriod;
        var memo = string.IsNullOrWhiteSpace(invoice.Notes)
            ? $"Invoice {invoice.InvoiceCode}"
            : invoice.Notes.Trim();
        if (!string.IsNullOrWhiteSpace(memoSuffix))
            memo = $"{memo} ({memoSuffix.Trim()})";

        var journalEntryLines = new List<JournalEntryLine>();
        var (accountsReceivableDebit, accountsReceivableCredit) = SignedAmountToDebitCredit(totalAmount, positiveIsDebit: true);
        journalEntryLines.Add(new JournalEntryLine
        {
            ChartOfAccountId = accountsReceivableAccountId,
            ReservationId = invoice.ReservationId,
            PropertyId = propertyId,
            ContactId = invoice.ContactId,
            Debit = accountsReceivableDebit,
            Credit = accountsReceivableCredit,
            Memo = $"Accounts Receivable - {invoice.InvoiceCode}",
            CreatedBy = currentUser
        });

        foreach (var line in chargeLines)
        {
            costCodeById.TryGetValue(line.CostCodeId, out var costCode);
            var incomeAccountId = GetChartOfAccountIdByCostCode(
                chartOfAccounts,
                invoice.OfficeId,
                costCode,
                defaultIncomeAccountId);
            var (incomeDebit, incomeCredit) = SignedAmountToDebitCredit(line.Amount, positiveIsDebit: false);

            journalEntryLines.Add(new JournalEntryLine
            {
                ChartOfAccountId = incomeAccountId,
                CostCodeId = line.CostCodeId,
                ReservationId = line.ReservationId ?? invoice.ReservationId,
                PropertyId = propertyId,
                ContactId = invoice.ContactId,
                Debit = incomeDebit,
                Credit = incomeCredit,
                Memo = line.Description,
                CreatedBy = currentUser
            });
        }

        return new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = transactionDate,
            PostingDate = postingDate,
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = sourceIdOverride ?? invoice.InvoiceId,
            Memo = memo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };
    }

    private async Task<JournalEntry> BuildJournalEntryFromPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        if (paymentLedgerLine.Amount == 0)
            throw new Exception("Payment amount cannot be zero");

        if (paymentLedgerLine.LedgerLineDate == default)
            throw new Exception("Payment date is required to create a payment journal entry");

        var costCodes = await _accountingRepository.GetCostCodesByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);
        var costCodeById = costCodes.ToDictionary(c => c.CostCodeId);
        if (!costCodeById.TryGetValue(paymentLedgerLine.CostCodeId, out var paymentCostCode) || !IsPaymentLedgerLine(paymentCostCode))
            throw new Exception("Payment ledger line must use a payment cost code");

        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var undepositedFundsAccountId = GetDefaultUndepositedFunds(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var propertyId = await ResolveInvoicePropertyIdAsync(invoice);
        var reservationId = paymentLedgerLine.ReservationId ?? invoice.ReservationId;

        var amount = paymentLedgerLine.Amount;
        var transactionDate = paymentLedgerLine.LedgerLineDate;
        var postingDate = paymentLedgerLine.LedgerLineDate;
        var memo = string.IsNullOrWhiteSpace(paymentLedgerLine.Description)
            ? $"Invoice Payment - {invoice.InvoiceCode}"
            : paymentLedgerLine.Description.Trim();

        var (undepositedFundsDebit, undepositedFundsCredit) = SignedAmountToDebitCredit(amount, positiveIsDebit: true);
        var (accountsReceivableDebit, accountsReceivableCredit) = SignedAmountToDebitCredit(-amount, positiveIsDebit: true);

        var undepositedFundsLine = new JournalEntryLine
        {
            ChartOfAccountId = undepositedFundsAccountId,
            CostCodeId = paymentLedgerLine.CostCodeId,
            ReservationId = reservationId,
            PropertyId = propertyId,
            ContactId = invoice.ContactId,
            Debit = undepositedFundsDebit,
            Credit = undepositedFundsCredit,
            Memo = memo,
            CreatedBy = currentUser
        };
        var accountsReceivableLine = new JournalEntryLine
        {
            ChartOfAccountId = accountsReceivableAccountId,
            ReservationId = reservationId,
            PropertyId = propertyId,
            ContactId = invoice.ContactId,
            Debit = accountsReceivableDebit,
            Credit = accountsReceivableCredit,
            Memo = $"Accounts Receivable - {invoice.InvoiceCode}",
            CreatedBy = currentUser
        };

        return new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = transactionDate,
            PostingDate = postingDate,
            SourceTypeId = (int)SourceType.InvoicePayment,
            SourceId = paymentLedgerLine.LedgerLineId,
            Memo = memo,
            JournalEntryLines = new List<JournalEntryLine> { undepositedFundsLine, accountsReceivableLine },
            CreatedBy = currentUser
        };
    }

    private async Task<JournalEntry> BuildJournalEntryFromPrePaymentReceivedAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        await ValidatePrePaymentLedgerLineForJournalEntry(invoice, paymentLedgerLine);

        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var prePaymentAccountId = GetDefaultPrePayment(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var propertyId = await ResolveInvoicePropertyIdAsync(invoice);
        var reservationId = paymentLedgerLine.ReservationId ?? invoice.ReservationId;
        var amount = paymentLedgerLine.Amount;
        var transactionDate = paymentLedgerLine.LedgerLineDate;
        var memo = string.IsNullOrWhiteSpace(paymentLedgerLine.Description)
            ? $"Invoice Pre-Payment - {invoice.InvoiceCode}"
            : paymentLedgerLine.Description.Trim();

        var (accountsReceivableDebit, accountsReceivableCredit) = SignedAmountToDebitCredit(amount, positiveIsDebit: true);
        var (prePaymentDebit, prePaymentCredit) = SignedAmountToDebitCredit(amount, positiveIsDebit: false);

        return new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = transactionDate,
            PostingDate = transactionDate,
            SourceTypeId = (int)SourceType.InvoicePayment,
            SourceId = paymentLedgerLine.LedgerLineId,
            Memo = memo,
            JournalEntryLines = new List<JournalEntryLine>
            {
                new()
                {
                    ChartOfAccountId = accountsReceivableAccountId,
                    ReservationId = reservationId,
                    PropertyId = propertyId,
                    ContactId = invoice.ContactId,
                    Debit = accountsReceivableDebit,
                    Credit = accountsReceivableCredit,
                    Memo = $"Accounts Receivable - {invoice.InvoiceCode}",
                    CreatedBy = currentUser
                },
                new()
                {
                    ChartOfAccountId = prePaymentAccountId,
                    CostCodeId = paymentLedgerLine.CostCodeId,
                    ReservationId = reservationId,
                    PropertyId = propertyId,
                    ContactId = invoice.ContactId,
                    Debit = prePaymentDebit,
                    Credit = prePaymentCredit,
                    Memo = memo,
                    CreatedBy = currentUser
                }
            },
            CreatedBy = currentUser
        };
    }

    private async Task<JournalEntry> BuildJournalEntryFromPrePaymentApplyAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        await ValidatePrePaymentLedgerLineForJournalEntry(invoice, paymentLedgerLine);

        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var prePaymentAccountId = GetDefaultPrePayment(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var propertyId = await ResolveInvoicePropertyIdAsync(invoice);
        var reservationId = paymentLedgerLine.ReservationId ?? invoice.ReservationId;
        var amount = paymentLedgerLine.Amount;
        var postingDate = invoice.AccountingPeriod;
        var memo = $"Invoice Pre-Payment Apply - {invoice.InvoiceCode}";

        var (prePaymentDebit, prePaymentCredit) = SignedAmountToDebitCredit(amount, positiveIsDebit: true);
        var (accountsReceivableDebit, accountsReceivableCredit) = SignedAmountToDebitCredit(-amount, positiveIsDebit: true);

        return new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = postingDate,
            PostingDate = postingDate,
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = paymentLedgerLine.LedgerLineId,
            Memo = memo,
            JournalEntryLines = new List<JournalEntryLine>
            {
                new()
                {
                    ChartOfAccountId = prePaymentAccountId,
                    CostCodeId = paymentLedgerLine.CostCodeId,
                    ReservationId = reservationId,
                    PropertyId = propertyId,
                    ContactId = invoice.ContactId,
                    Debit = prePaymentDebit,
                    Credit = prePaymentCredit,
                    Memo = memo,
                    CreatedBy = currentUser
                },
                new()
                {
                    ChartOfAccountId = accountsReceivableAccountId,
                    ReservationId = reservationId,
                    PropertyId = propertyId,
                    ContactId = invoice.ContactId,
                    Debit = accountsReceivableDebit,
                    Credit = accountsReceivableCredit,
                    Memo = $"Accounts Receivable - {invoice.InvoiceCode}",
                    CreatedBy = currentUser
                }
            },
            CreatedBy = currentUser
        };
    }

    private async Task ValidatePrePaymentLedgerLineForJournalEntry(Invoice invoice, LedgerLine paymentLedgerLine)
    {
        if (paymentLedgerLine.Amount == 0)
            throw new Exception("Payment amount cannot be zero");

        if (paymentLedgerLine.LedgerLineDate == default)
            throw new Exception("Payment date is required to create a payment journal entry");

        if (invoice.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required to create pre-payment journal entries");

        var costCodes = await _accountingRepository.GetCostCodesByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);
        var costCodeById = costCodes.ToDictionary(c => c.CostCodeId);
        if (!costCodeById.TryGetValue(paymentLedgerLine.CostCodeId, out var paymentCostCode) || !IsPaymentLedgerLine(paymentCostCode))
            throw new Exception("Payment ledger line must use a payment cost code");
    }

    private async Task DeleteJournalEntriesForInvoicePaymentLedgerLineAsync(Guid organizationId, int officeId, Guid ledgerLineId)
    {
        await DeleteJournalEntriesForSourceAsync(organizationId, officeId, (int)SourceType.InvoicePayment, ledgerLineId);
        await DeleteJournalEntriesForSourceAsync(organizationId, officeId, (int)SourceType.Invoice, ledgerLineId);
    }

    private async Task<Guid?> ResolveInvoicePropertyIdAsync(Invoice invoice)
    {
        if (invoice.PropertyId.HasValue && invoice.PropertyId != Guid.Empty)
            return invoice.PropertyId;

        if (!invoice.ReservationId.HasValue || invoice.ReservationId == Guid.Empty)
            return null;

        if (invoice.ReservationId == SystemOrganization)
            return null;

        var reservation = await _reservationRepository.GetReservationByIdAsync(invoice.ReservationId.Value, invoice.OrganizationId);
        if (reservation == null || reservation.PropertyId == Guid.Empty)
            return null;

        return reservation.PropertyId;
    }
    #endregion

    #region Cross-Period Invoice Journal Entries
    private async Task<JournalEntry?> CreateJournalEntriesFromCrossPeriodInvoiceAsync(Invoice invoice, Guid currentUser)
    {
        if (!invoice.ReservationId.HasValue || invoice.ReservationId == Guid.Empty)
            return null;

        if (!TryCreateCrossPeriodInvoiceSlices(invoice, out var firstPeriodInvoice, out var secondPeriodInvoice))
            return null;

        var existingFirst = await GetNonVoidedJournalEntryAsync(invoice, invoice.InvoiceId, firstPeriodInvoice.AccountingPeriod);
        var existingSecond = await GetNonVoidedJournalEntryAsync(invoice, invoice.InvoiceId, secondPeriodInvoice.AccountingPeriod);
        if (existingFirst != null && existingSecond != null)
            return existingFirst;

        var reservation = await _reservationRepository.GetReservationByIdAsync(invoice.ReservationId.Value, invoice.OrganizationId);
        if (reservation == null)
            return null;

        if (!await TryPopulateCrossPeriodInvoiceLedgerLinesAsync(firstPeriodInvoice, reservation))
            return null;

        if (!await TryPopulateCrossPeriodInvoiceLedgerLinesAsync(secondPeriodInvoice, reservation))
            return null;

        if (!TryApplyApportionedCrossPeriodLinesFromOriginal(invoice, firstPeriodInvoice, secondPeriodInvoice, reservation))
            return null;

        var originalChargeTotal = await SumInvoiceChargeLinesAsync(invoice);
        var splitChargeTotal = await SumInvoiceChargeLinesAsync(firstPeriodInvoice)
            + await SumInvoiceChargeLinesAsync(secondPeriodInvoice);

        if (originalChargeTotal != splitChargeTotal)
            return null;

        var firstSliceChargeTotal = await SumInvoiceChargeLinesAsync(firstPeriodInvoice);
        var secondSliceChargeTotal = await SumInvoiceChargeLinesAsync(secondPeriodInvoice);
        if (firstSliceChargeTotal == 0 || secondSliceChargeTotal == 0)
            return null;

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);

        var firstEntry = existingFirst
            ?? await CreateCrossPeriodSliceJournalEntryAsync(
                firstPeriodInvoice,
                invoice.InvoiceId,
                chartOfAccounts,
                accountingOffice,
                currentUser);

        await CreateCrossPeriodSliceJournalEntryAsync(
            secondPeriodInvoice,
            invoice.InvoiceId,
            chartOfAccounts,
            accountingOffice,
            currentUser,
            memoSuffix: secondPeriodInvoice.AccountingPeriod.ToString("MM/yyyy"));

        return firstEntry;
    }

    private async Task<JournalEntry?> GetNonVoidedJournalEntryAsync(Invoice invoice, Guid sourceId, DateOnly? postingDate = null)
    {
        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = invoice.OrganizationId,
            OfficeIds = invoice.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = sourceId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        return existingEntries
            .Where(e => !e.IsVoided)
            .Where(e => !postingDate.HasValue || e.PostingDate == postingDate.Value)
            .OrderBy(e => e.PostingDate)
            .FirstOrDefault();
    }

    private async Task<JournalEntry?> CreateCrossPeriodSliceJournalEntryAsync(Invoice sliceInvoice, Guid sourceId, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser, string? memoSuffix = null)
    {
        var existingEntry = await GetNonVoidedJournalEntryAsync(sliceInvoice, sourceId, sliceInvoice.AccountingPeriod);
        if (existingEntry != null)
            return existingEntry;

        var journalEntry = await BuildJournalEntryFromInvoiceAsync(
            sliceInvoice,
            chartOfAccounts,
            accountingOffice,
            currentUser,
            sourceId,
            memoSuffix);
        return await CreateAutoGeneratedJournalEntryAsync(journalEntry);
    }

    private async Task<bool> TryPopulateCrossPeriodInvoiceLedgerLinesAsync(Invoice sliceInvoice, Reservation reservation)
    {
        if (!TryParseInvoicePeriod(sliceInvoice.InvoicePeriod, out var periodStart, out var periodEnd))
            return false;

        var invoiceDate = sliceInvoice.InvoiceDate != default ? sliceInvoice.InvoiceDate : sliceInvoice.AccountingPeriod;
        var ledgerLines = await CreateLedgerLinesForReservationIdAsync(reservation, invoiceDate, periodStart, periodEnd);

        sliceInvoice.LedgerLines = ledgerLines;
        sliceInvoice.TotalAmount = ledgerLines.Sum(l => l.Amount);
        return true;
    }

    private async Task<decimal> SumInvoiceChargeLinesAsync(Invoice invoice)
    {
        var costCodes = await _accountingRepository.GetCostCodesByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);
        var costCodeById = costCodes.ToDictionary(c => c.CostCodeId);

        return invoice.LedgerLines
            .Where(l => l.Amount != 0)
            .Where(l =>
            {
                costCodeById.TryGetValue(l.CostCodeId, out var costCode);
                return !IsPaymentLedgerLine(costCode);
            })
            .Sum(l => l.Amount);
    }

    private async Task DeleteJournalEntriesForInvoiceChargesAsync(Invoice invoice)
    {
        await DeleteJournalEntriesForSourceAsync(
            invoice.OrganizationId,
            invoice.OfficeId,
            (int)SourceType.Invoice,
            invoice.InvoiceId);

        if (!TryCreateCrossPeriodInvoiceSlices(invoice, out _, out var secondPeriodInvoice))
            return;

        var legacySecondSourceId = GetInvoiceAccountingPeriodSourceId(invoice.InvoiceId, secondPeriodInvoice.AccountingPeriod);
        await DeleteJournalEntriesForSourceAsync(
            invoice.OrganizationId,
            invoice.OfficeId,
            (int)SourceType.Invoice,
            legacySecondSourceId);
    }
    #endregion

    #region Invoice Journal Entry Static Helpers
    private static readonly Regex RentalFeePeriodRegex = new(
        @"^Rental Fee \((?<start>\d{2}/\d{2})-(?<end>\d{2}/\d{2})\)$",
        RegexOptions.CultureInvariant | RegexOptions.IgnoreCase | RegexOptions.Compiled);

    private static bool InvoiceCrossesAccountingPeriodBoundary(Invoice invoice)
    {
        if (TryParseInvoicePeriod(invoice.InvoicePeriod, out var periodStart, out var periodEnd)
            && (periodStart.Year != periodEnd.Year || periodStart.Month != periodEnd.Month))
        {
            return true;
        }

        var referenceYear = invoice.AccountingPeriod != default
            ? invoice.AccountingPeriod.Year
            : invoice.InvoiceDate.Year;

        foreach (var line in invoice.LedgerLines.Where(l => l.Amount != 0))
        {
            if (!TryParseRentalFeeDateRange(line.Description, referenceYear, out var rentalStart, out var rentalEnd))
                continue;

            if (rentalStart.Year != rentalEnd.Year || rentalStart.Month != rentalEnd.Month)
                return true;
        }

        return false;
    }

    private static bool TryParseInvoicePeriod(string? invoicePeriod, out DateOnly periodStart, out DateOnly periodEnd)
    {
        periodStart = default;
        periodEnd = default;

        if (string.IsNullOrWhiteSpace(invoicePeriod))
            return false;

        var parts = invoicePeriod.Split('-', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length != 2)
            return false;

        if (!DateOnly.TryParse(parts[0], out periodStart) || !DateOnly.TryParse(parts[1], out periodEnd))
            return false;

        return periodEnd >= periodStart;
    }

    private static bool TryParseRentalFeeDateRange(string? description, int referenceYear, out DateOnly rentalStart, out DateOnly rentalEnd)
    {
        rentalStart = default;
        rentalEnd = default;

        if (string.IsNullOrWhiteSpace(description))
            return false;

        var match = RentalFeePeriodRegex.Match(description.Trim());
        if (!match.Success)
            return false;

        if (!TryParseMonthDay(match.Groups["start"].Value, referenceYear, out rentalStart))
            return false;

        if (!TryParseMonthDay(match.Groups["end"].Value, referenceYear, out rentalEnd))
            return false;

        if (rentalEnd < rentalStart)
            rentalEnd = rentalEnd.AddYears(1);

        return true;
    }

    private static bool TryParseMonthDay(string monthDay, int year, out DateOnly date)
    {
        date = default;
        var parts = monthDay.Split('/');
        if (parts.Length != 2)
            return false;

        if (!int.TryParse(parts[0], out var month) || !int.TryParse(parts[1], out var day))
            return false;

        try
        {
            date = new DateOnly(year, month, day);
            return true;
        }
        catch (ArgumentOutOfRangeException)
        {
            return false;
        }
    }

    private static bool IsInvoicePrePayment(Invoice invoice, LedgerLine paymentLedgerLine)
    {
        if (invoice.AccountingPeriod == default || paymentLedgerLine.LedgerLineDate == default)
            return false;

        return paymentLedgerLine.LedgerLineDate < invoice.AccountingPeriod;
    }

    private static bool IsPaymentLedgerLine(CostCode? costCode)
    {
        return costCode?.TransactionType == TransactionType.Payment;
    }
    #endregion

    #region Cross-Period Invoice Journal Entry Static Helpers
    private static bool TryApplyApportionedCrossPeriodLinesFromOriginal(Invoice originalInvoice, Invoice firstSlice, Invoice secondSlice, Reservation reservation)
    {
        var referenceYear = originalInvoice.AccountingPeriod != default
            ? originalInvoice.AccountingPeriod.Year
            : originalInvoice.InvoiceDate.Year;

        var crossingRentals = originalInvoice.LedgerLines
            .Where(l => l.Amount != 0 && IsCrossMonthRentalLine(l, referenceYear))
            .ToList();

        if (crossingRentals.Count == 0)
            return true;

        var primaryRental = crossingRentals[0];
        if (!TryGetCrossMonthApportionmentDays(primaryRental, referenceYear, reservation, out var firstDays, out var totalDays))
            return false;

        if (!TryParseRentalFeeDateRange(primaryRental.Description, referenceYear, out var rentalStart, out var rentalEnd))
            return false;

        var firstMonthEnd = LastDayOfMonth(rentalStart);
        var secondMonthStart = FirstDayOfMonth(rentalEnd);
        var firstPeriodEnd = rentalEnd < firstMonthEnd ? rentalEnd : firstMonthEnd;
        var secondPeriodStart = rentalStart > secondMonthStart ? rentalStart : secondMonthStart;

        RemoveGeneratedRentalFeeLines(firstSlice);
        RemoveGeneratedRentalFeeLines(secondSlice);

        var monthlyRecurringLines = crossingRentals
            .Cast<LedgerLine>()
            .Concat(GetApportionableNonDateSpecificFeeLines(originalInvoice, reservation))
            .ToList();

        foreach (var feeLine in monthlyRecurringLines)
        {
            RemoveMatchingFeeLine(firstSlice, feeLine);
            RemoveMatchingFeeLine(secondSlice, feeLine);
        }

        foreach (var oneTimeLine in GetOneTimeFeeLines(originalInvoice, reservation))
        {
            RemoveMatchingFeeLine(firstSlice, oneTimeLine);
            RemoveMatchingFeeLine(secondSlice, oneTimeLine);
        }

        var totalMonthlyRecurring = monthlyRecurringLines.Sum(l => l.Amount);
        if (!TryApportionAmountByDayRatio(totalMonthlyRecurring, firstDays, totalDays, out var firstMonthPool, out var secondMonthPool))
            return false;

        ApplyPooledMonthlyRecurringApportionment(
            firstSlice,
            secondSlice,
            monthlyRecurringLines,
            firstMonthPool,
            secondMonthPool,
            totalMonthlyRecurring,
            referenceYear,
            rentalStart,
            rentalEnd,
            firstPeriodEnd,
            secondPeriodStart);

        foreach (var oneTimeLine in GetOneTimeFeeLines(originalInvoice, reservation))
            firstSlice.LedgerLines.Add(CreateApportionedFeeLine(oneTimeLine, oneTimeLine.Amount));

        if (!TryApplyMaidServiceToCrossPeriodSlices(
                originalInvoice,
                firstSlice,
                secondSlice,
                reservation,
                rentalStart,
                rentalEnd))
            return false;

        firstSlice.TotalAmount = firstSlice.LedgerLines.Sum(l => l.Amount);
        secondSlice.TotalAmount = secondSlice.LedgerLines.Sum(l => l.Amount);
        return true;
    }

    private static void ApplyPooledMonthlyRecurringApportionment(Invoice firstSlice, Invoice secondSlice, IReadOnlyList<LedgerLine> monthlyRecurringLines, decimal firstMonthPool, decimal secondMonthPool, decimal totalMonthlyRecurring, int referenceYear, DateOnly rentalStart, DateOnly rentalEnd, DateOnly firstPeriodEnd, DateOnly secondPeriodStart)
    {
        var distributedFirst = 0m;

        for (var i = 0; i < monthlyRecurringLines.Count; i++)
        {
            var line = monthlyRecurringLines[i];
            decimal firstAmount;
            decimal secondAmount;

            if (i == monthlyRecurringLines.Count - 1)
            {
                firstAmount = firstMonthPool - distributedFirst;
                secondAmount = line.Amount - firstAmount;
            }
            else
            {
                firstAmount = totalMonthlyRecurring == 0
                    ? 0
                    : firstMonthPool * line.Amount / totalMonthlyRecurring;
                secondAmount = line.Amount - firstAmount;
                distributedFirst += firstAmount;
            }

            if (IsCrossMonthRentalLine(line, referenceYear))
            {
                firstSlice.LedgerLines.Add(CreateApportionedRentalLine(line, firstAmount, rentalStart, firstPeriodEnd));
                secondSlice.LedgerLines.Add(CreateApportionedRentalLine(line, secondAmount, secondPeriodStart, rentalEnd));
            }
            else
            {
                firstSlice.LedgerLines.Add(CreateApportionedFeeLine(line, firstAmount));
                secondSlice.LedgerLines.Add(CreateApportionedFeeLine(line, secondAmount));
            }
        }
    }

    private static bool TryApplyMaidServiceToCrossPeriodSlices(Invoice originalInvoice, Invoice firstSlice, Invoice secondSlice, Reservation reservation, DateOnly rentalStart, DateOnly rentalEnd)
    {
        var maidTemplate = originalInvoice.LedgerLines
            .FirstOrDefault(l => l.Amount != 0 && l.Description.StartsWith("Maid Service", StringComparison.Ordinal));
        if (maidTemplate == null)
            return true;

        if (!TryParseInvoicePeriod(originalInvoice.InvoicePeriod, out var invoicePeriodStart, out var invoicePeriodEnd))
            return false;

        if (!TryParseInvoicePeriod(firstSlice.InvoicePeriod, out var slice1Start, out var slice1End))
            return false;

        if (!TryParseInvoicePeriod(secondSlice.InvoicePeriod, out var slice2Start, out var slice2End))
            return false;

        if (!TryParseMaidServiceVisitCount(maidTemplate.Description, out var originalVisitCount))
            return false;

        if (!TryResolveBilledMaidServiceOccurrenceDates(
                reservation,
                invoicePeriodStart,
                invoicePeriodEnd,
                rentalStart,
                rentalEnd,
                originalVisitCount,
                out var occurrenceDates))
            return false;

        var slice1Count = occurrenceDates.Count(d => d >= slice1Start && d <= slice1End);
        var slice2Count = occurrenceDates.Count(d => d >= slice2Start && d <= slice2End);

        if (slice1Count + slice2Count != occurrenceDates.Count)
            return false;

        RemoveMaidServiceLines(firstSlice);
        RemoveMaidServiceLines(secondSlice);

        if (slice1Count > 0)
            firstSlice.LedgerLines.Add(CreateApportionedMaidServiceLine(maidTemplate, slice1Count, reservation.MaidServiceFee));

        if (slice2Count > 0)
            secondSlice.LedgerLines.Add(CreateApportionedMaidServiceLine(maidTemplate, slice2Count, reservation.MaidServiceFee));

        return true;
    }

    private static bool TryResolveBilledMaidServiceOccurrenceDates(Reservation reservation, DateOnly invoicePeriodStart, DateOnly invoicePeriodEnd, DateOnly rentalStart, DateOnly rentalEnd, int originalVisitCount, out List<DateOnly> occurrenceDates)
    {
        occurrenceDates = [];

        var invoiceBounds = GetMaidServicePeriodBounds(reservation, invoicePeriodStart, invoicePeriodEnd);
        if (invoiceBounds.Start <= invoiceBounds.End)
        {
            var invoicePeriodDates = GetMaidServiceOccurrenceDates(reservation, invoiceBounds.Start, invoiceBounds.End);
            if (invoicePeriodDates.Count == originalVisitCount)
            {
                occurrenceDates = invoicePeriodDates;
                return true;
            }
        }

        var rentalBounds = GetMaidServicePeriodBounds(reservation, rentalStart, rentalEnd);
        if (rentalBounds.Start > rentalBounds.End)
            return originalVisitCount == 0;

        var rentalPeriodDates = GetMaidServiceOccurrenceDates(reservation, rentalBounds.Start, rentalBounds.End);
        if (rentalPeriodDates.Count != originalVisitCount)
            return false;

        occurrenceDates = rentalPeriodDates;
        return true;
    }

    private static (DateOnly Start, DateOnly End) GetMaidServicePeriodBounds(Reservation reservation, DateOnly periodStart, DateOnly periodEnd)
    {
        var startDate = reservation.MaidStartDate > periodStart ? reservation.MaidStartDate : periodStart;
        var endDate = periodEnd > reservation.DepartureDate.AddDays(-7) ? reservation.DepartureDate : periodEnd;
        return (startDate, endDate);
    }

    private static IEnumerable<LedgerLine> GetOneTimeFeeLines(Invoice originalInvoice, Reservation reservation)
    {
        var oneTimeExtraDescriptions = reservation.ExtraFeeLines
            .Where(f => f.FeeFrequency == FrequencyType.OneTime)
            .Select(f => f.FeeDescription)
            .ToHashSet(StringComparer.Ordinal);

        foreach (var line in originalInvoice.LedgerLines.Where(l => l.Amount != 0))
        {
            if (line.Description is "Departure Fee" or "Security Deposit" or "Pet Fee")
            {
                yield return line;
                continue;
            }

            if (oneTimeExtraDescriptions.Contains(line.Description))
                yield return line;
        }
    }

    private static IEnumerable<LedgerLine> GetApportionableNonDateSpecificFeeLines(Invoice originalInvoice, Reservation reservation)
    {
        var monthlyExtraDescriptions = reservation.ExtraFeeLines
            .Where(f => f.FeeFrequency == FrequencyType.Monthly)
            .Select(f => f.FeeDescription)
            .ToHashSet(StringComparer.Ordinal);

        foreach (var line in originalInvoice.LedgerLines.Where(l => l.Amount != 0))
        {
            if (line.Description == "Security Deposit Waiver")
            {
                yield return line;
                continue;
            }

            if (monthlyExtraDescriptions.Contains(line.Description))
                yield return line;
        }
    }

    private static bool TryGetCrossMonthApportionmentDays(LedgerLine originalRental, int referenceYear, Reservation reservation, out int firstDays, out int totalDays)
    {
        firstDays = 0;
        totalDays = 0;

        if (!TryParseRentalFeeDateRange(originalRental.Description, referenceYear, out var rentalStart, out var rentalEnd))
            return false;

        if (rentalStart.Year == rentalEnd.Year && rentalStart.Month == rentalEnd.Month)
            return false;

        var departureDate = reservation.DepartureDate;
        totalDays = CalculateNumberOfDays(
            rentalStart,
            rentalEnd,
            reservation.BillingType,
            IsDepartureMonthYear(rentalEnd, departureDate),
            IsLastDayOfMonth(rentalEnd));

        if (totalDays <= 0)
            return false;

        var firstMonthEnd = LastDayOfMonth(rentalStart);
        var firstPeriodEnd = rentalEnd < firstMonthEnd ? rentalEnd : firstMonthEnd;

        firstDays = CalculateNumberOfDays(
            rentalStart,
            firstPeriodEnd,
            reservation.BillingType,
            IsDepartureMonthYear(firstPeriodEnd, departureDate),
            IsLastDayOfMonth(firstPeriodEnd));

        return firstDays > 0 && firstDays <= totalDays;
    }

    private static bool TryApportionAmountByDayRatio(decimal originalAmount, int firstDays, int totalDays, out decimal firstAmount, out decimal secondAmount)
    {
        firstAmount = 0;
        secondAmount = 0;

        if (totalDays <= 0 || firstDays < 0 || firstDays > totalDays)
            return false;

        var dailyRate = originalAmount / totalDays;
        firstAmount = dailyRate * firstDays;
        secondAmount = originalAmount - firstAmount;
        return true;
    }

    private static bool IsCrossMonthRentalLine(LedgerLine line, int referenceYear)
    {
        if (!TryParseRentalFeeDateRange(line.Description, referenceYear, out var rentalStart, out var rentalEnd))
            return false;

        return rentalStart.Year != rentalEnd.Year || rentalStart.Month != rentalEnd.Month;
    }

    private static bool IsDepartureMonthYear(DateOnly date, DateOnly departureDate)
        => date.Year == departureDate.Year && date.Month == departureDate.Month;

    private static bool IsLastDayOfMonth(DateOnly date)
        => date == LastDayOfMonth(date);

    private static void RemoveMatchingFeeLine(Invoice slice, LedgerLine template)
        => slice.LedgerLines.RemoveAll(l =>
            l.Amount != 0
            && l.CostCodeId == template.CostCodeId
            && string.Equals(l.Description, template.Description, StringComparison.Ordinal));

    private static void RemoveGeneratedRentalFeeLines(Invoice slice)
        => slice.LedgerLines.RemoveAll(l => l.Amount != 0 && RentalFeePeriodRegex.IsMatch(l.Description.Trim()));

    private static void RemoveMaidServiceLines(Invoice slice)
        => slice.LedgerLines.RemoveAll(l => l.Amount != 0 && l.Description.StartsWith("Maid Service", StringComparison.Ordinal));

    private static bool TryParseMaidServiceVisitCount(string description, out int visitCount)
    {
        visitCount = 0;
        var open = description.IndexOf('(');
        var close = description.IndexOf(" times)", StringComparison.Ordinal);
        if (open < 0 || close <= open)
            return false;

        return int.TryParse(description.AsSpan(open + 1, close - open - 1), out visitCount);
    }

    private static LedgerLine CreateApportionedRentalLine(LedgerLine template, decimal amount, DateOnly start, DateOnly end)
        => new()
        {
            LedgerLineId = template.LedgerLineId,
            InvoiceId = template.InvoiceId,
            LineNumber = template.LineNumber,
            ReservationId = template.ReservationId,
            CostCodeId = template.CostCodeId,
            Amount = amount,
            Description = $"Rental Fee ({start:MM/dd}-{end:MM/dd})",
            LedgerLineDate = template.LedgerLineDate,
            CreatedOn = template.CreatedOn,
            CreatedBy = template.CreatedBy,
            ModifiedOn = template.ModifiedOn,
            ModifiedBy = template.ModifiedBy
        };

    private static LedgerLine CreateApportionedFeeLine(LedgerLine template, decimal amount)
        => new()
        {
            LedgerLineId = template.LedgerLineId,
            InvoiceId = template.InvoiceId,
            LineNumber = template.LineNumber,
            ReservationId = template.ReservationId,
            CostCodeId = template.CostCodeId,
            Amount = amount,
            Description = template.Description,
            LedgerLineDate = template.LedgerLineDate,
            CreatedOn = template.CreatedOn,
            CreatedBy = template.CreatedBy,
            ModifiedOn = template.ModifiedOn,
            ModifiedBy = template.ModifiedBy
        };

    private static LedgerLine CreateApportionedMaidServiceLine(LedgerLine template, int visitCount, decimal feePerVisit)
        => new()
        {
            LedgerLineId = template.LedgerLineId,
            InvoiceId = template.InvoiceId,
            LineNumber = template.LineNumber,
            ReservationId = template.ReservationId,
            CostCodeId = template.CostCodeId,
            Amount = visitCount * feePerVisit,
            Description = $"Maid Service ({visitCount} times)",
            LedgerLineDate = template.LedgerLineDate,
            CreatedOn = template.CreatedOn,
            CreatedBy = template.CreatedBy,
            ModifiedOn = template.ModifiedOn,
            ModifiedBy = template.ModifiedBy
        };

    private static bool TryCreateCrossPeriodInvoiceSlices(Invoice source, out Invoice firstPeriodInvoice, out Invoice secondPeriodInvoice)
    {
        firstPeriodInvoice = null!;
        secondPeriodInvoice = null!;

        if (!TryResolveCrossPeriodBounds(source, out var slice1Start, out var slice1End, out var slice2Start, out var slice2End))
            return false;

        var slice1AccountingPeriod = FirstDayOfMonth(slice1Start);
        var slice2AccountingPeriod = FirstDayOfMonth(slice2Start);

        firstPeriodInvoice = CloneInvoiceForCrossPeriodSlice(source, slice1Start, slice1End, slice1AccountingPeriod);
        secondPeriodInvoice = CloneInvoiceForCrossPeriodSlice(source, slice2Start, slice2End, slice2AccountingPeriod);
        return true;
    }

    private static bool TryResolveCrossPeriodBounds(Invoice invoice, out DateOnly slice1Start, out DateOnly slice1End, out DateOnly slice2Start, out DateOnly slice2End)
    {
        slice1Start = default;
        slice1End = default;
        slice2Start = default;
        slice2End = default;

        if (!TryParseInvoicePeriod(invoice.InvoicePeriod, out var periodStart, out var periodEnd))
            return false;

        slice1Start = periodStart;
        slice1End = LastDayOfMonth(periodStart);

        if (periodStart.Year != periodEnd.Year || periodStart.Month != periodEnd.Month)
        {
            slice2Start = FirstDayOfMonth(periodEnd);
            slice2End = periodEnd;
        }
        else if (TryGetCrossingRentalEndDate(invoice, out var rentalEnd))
        {
            slice2Start = FirstDayOfMonth(rentalEnd);
            slice2End = rentalEnd;
        }
        else
        {
            return false;
        }

        return slice1Start <= slice1End && slice2Start <= slice2End;
    }

    private static bool TryGetCrossingRentalEndDate(Invoice invoice, out DateOnly rentalEnd)
    {
        rentalEnd = default;
        var referenceYear = invoice.AccountingPeriod != default
            ? invoice.AccountingPeriod.Year
            : invoice.InvoiceDate.Year;

        var found = false;
        foreach (var line in invoice.LedgerLines.Where(l => l.Amount != 0))
        {
            if (!TryParseRentalFeeDateRange(line.Description, referenceYear, out var rentalStart, out var endDate))
                continue;

            if (rentalStart.Year == endDate.Year && rentalStart.Month == endDate.Month)
                continue;

            if (!found || endDate > rentalEnd)
            {
                rentalEnd = endDate;
                found = true;
            }
        }

        return found;
    }

    private static Invoice CloneInvoiceForCrossPeriodSlice(Invoice source, DateOnly periodStart, DateOnly periodEnd, DateOnly accountingPeriod)
    {
        return new Invoice
        {
            InvoiceId = source.InvoiceId,
            OrganizationId = source.OrganizationId,
            OfficeId = source.OfficeId,
            OfficeName = source.OfficeName,
            InvoiceCode = source.InvoiceCode,
            ReservationId = source.ReservationId,
            ReservationCode = source.ReservationCode,
            PropertyId = source.PropertyId,
            PropertyCode = source.PropertyCode,
            ContactId = source.ContactId,
            ContactName = source.ContactName,
            ResponsibleParty = source.ResponsibleParty,
            InvoiceDate = source.InvoiceDate,
            DueDate = source.DueDate,
            AccountingPeriod = accountingPeriod,
            InvoicePeriod = FormatInvoicePeriod(periodStart, periodEnd),
            TotalAmount = 0,
            PaidAmount = source.PaidAmount,
            Notes = source.Notes,
            IsActive = source.IsActive,
            LedgerLines = new List<LedgerLine>(),
            CreatedOn = source.CreatedOn,
            CreatedBy = source.CreatedBy,
            ModifiedOn = source.ModifiedOn,
            ModifiedBy = source.ModifiedBy
        };
    }

    private static string FormatInvoicePeriod(DateOnly periodStart, DateOnly periodEnd)
        => $"{periodStart:MM/dd/yyyy} - {periodEnd:MM/dd/yyyy}";

    private static DateOnly FirstDayOfMonth(DateOnly date)
        => new(date.Year, date.Month, 1);

    private static DateOnly LastDayOfMonth(DateOnly date)
        => new(date.Year, date.Month, DateTime.DaysInMonth(date.Year, date.Month));

    private static Guid GetInvoiceAccountingPeriodSourceId(Guid invoiceId, DateOnly accountingPeriod)
    {
        var input = $"{invoiceId:D}|{accountingPeriod:yyyy-MM-dd}";
        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(input));
        var guidBytes = new byte[16];
        Array.Copy(hash, guidBytes, 16);
        guidBytes[6] = (byte)((guidBytes[6] & 0x0F) | 0x50);
        guidBytes[8] = (byte)((guidBytes[8] & 0x3F) | 0x80);
        return new Guid(guidBytes);
    }
    #endregion
}
