using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    private async Task TryReplaceJournalEntriesFromWorkOrderAsync(WorkOrder workOrder, Guid currentUser)
    {
        try
        {
            if (workOrder.WorkOrderId == Guid.Empty)
                return;

            if (!await IsAccountingFeatureEnabledAsync(workOrder.OrganizationId) || !ShouldCreateJournalEntryForWorkOrder(workOrder))
            {
                await DeleteJournalEntriesForSourceAsync(
                    workOrder.OrganizationId,
                    workOrder.OfficeId,
                    (int)SourceType.WorkOrder,
                    workOrder.WorkOrderId);

                return;
            }

            var existingEntries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
            {
                OrganizationId = workOrder.OrganizationId,
                OfficeIds = workOrder.OfficeId.ToString(),
                SourceTypeId = (int)SourceType.WorkOrder,
                SourceId = workOrder.WorkOrderId,
                IncludeUnposted = true
            })).ToList();

            var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(workOrder.OrganizationId, workOrder.OfficeId);
            var rebuiltJournalEntry = await BuildJournalEntryFromWorkOrderAsync(workOrder, chartOfAccounts, accountingOffice, currentUser);

            if (!rebuiltJournalEntry.JournalEntryLines.Any(line => line.Debit != 0 || line.Credit != 0))
            {
                await DeleteJournalEntriesForSourceAsync(
                    workOrder.OrganizationId,
                    workOrder.OfficeId,
                    (int)SourceType.WorkOrder,
                    workOrder.WorkOrderId);

                return;
            }

            await PruneOpenDuplicateAutoGeneratedJournalEntriesAsync(existingEntries, workOrder.OrganizationId, currentUser);

            var existingEntry = existingEntries.FirstOrDefault();
            if (existingEntry != null)
            {
                rebuiltJournalEntry.JournalEntryId = existingEntry.JournalEntryId;
                rebuiltJournalEntry.OrganizationId = workOrder.OrganizationId;
                rebuiltJournalEntry.OfficeId = workOrder.OfficeId;
                rebuiltJournalEntry.CreatedBy = existingEntry.CreatedBy;
                rebuiltJournalEntry.ModifiedBy = currentUser;

                foreach (var line in rebuiltJournalEntry.JournalEntryLines)
                {
                    line.JournalEntryId = existingEntry.JournalEntryId;
                    line.JournalEntryLineId = Guid.Empty;
                }

                await UpdateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);

                return;
            }

            var createdJournalEntry = await CreateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "WorkOrder",
                organizationId: workOrder.OrganizationId,
                officeId: workOrder.OfficeId,
                sourceTypeId: (int)SourceType.WorkOrder,
                sourceId: workOrder.WorkOrderId,
                documentCode: workOrder.WorkOrderCode,
                accountingPeriod: null,
                amount: null,
                message: $"Work order {workOrder.WorkOrderCode} journal entry refresh failed: {ex.Message}",
                currentUser: currentUser);
            throw;
        }
    }

    private async Task ReplaceJournalEntriesFromReceiptAsync(Receipt receipt, Guid currentUser)
    {
        try
        {
            EnsureReceiptIsCardReceipt(receipt);
            receipt = await LoadReceiptWithSplitsAsync(receipt);

            if (receipt.ReceiptId == Guid.Empty)
                return;

            if (!await IsAccountingFeatureEnabledAsync(receipt.OrganizationId))
            {
                await DeleteJournalEntriesForSourceAsync(
                    receipt.OrganizationId,
                    receipt.OfficeId,
                    (int)SourceType.Receipt,
                    receipt.ReceiptId);
                await DeleteAllCrossOfficeReceiptCompanionEntriesAsync(receipt);

                return;
            }

            var existingEntries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
            {
                OrganizationId = receipt.OrganizationId,
                OfficeIds = receipt.OfficeId.ToString(),
                SourceTypeId = (int)SourceType.Receipt,
                SourceId = receipt.ReceiptId,
                IncludeUnposted = true
            })).ToList();

            var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(receipt.OrganizationId, receipt.OfficeId);
            var bankCard = await ResolveReceiptBankCardAsync(receipt, accountingOffice);
            var rebuiltJournalEntry = await BuildJournalEntryFromReceiptAsync(receipt, chartOfAccounts, accountingOffice, currentUser);

            if (!HasActiveJournalEntryLines(rebuiltJournalEntry))
            {
                await DeleteJournalEntriesForSourceAsync(
                    receipt.OrganizationId,
                    receipt.OfficeId,
                    (int)SourceType.Receipt,
                    receipt.ReceiptId);
                await DeleteAllCrossOfficeReceiptCompanionEntriesAsync(receipt);

                return;
            }

            await PruneOpenDuplicateAutoGeneratedJournalEntriesAsync(existingEntries, receipt.OrganizationId, currentUser);

            var existingEntry = existingEntries.FirstOrDefault();
            if (existingEntry != null)
            {
                rebuiltJournalEntry.JournalEntryId = existingEntry.JournalEntryId;
                rebuiltJournalEntry.OrganizationId = receipt.OrganizationId;
                rebuiltJournalEntry.OfficeId = receipt.OfficeId;
                rebuiltJournalEntry.CreatedBy = existingEntry.CreatedBy;
                rebuiltJournalEntry.ModifiedBy = currentUser;

                foreach (var line in rebuiltJournalEntry.JournalEntryLines)
                {
                    line.JournalEntryId = existingEntry.JournalEntryId;
                    line.JournalEntryLineId = Guid.Empty;
                }

                await UpdateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
                await SyncCrossOfficeReceiptCompanionJournalEntryAsync(receipt, accountingOffice, bankCard, currentUser);

                return;
            }

            await CreateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);

            await SyncCrossOfficeReceiptCompanionJournalEntryAsync(receipt, accountingOffice, bankCard, currentUser);
        }
        catch (Exception ex)
        {
            var receiptLabel = receipt.ReceiptCode.Trim();
            await LogAccountingErrorAsync(
                trigger: "Receipt",
                organizationId: receipt.OrganizationId,
                officeId: receipt.OfficeId,
                sourceTypeId: (int)SourceType.Receipt,
                sourceId: receipt.ReceiptId,
                documentCode: receiptLabel,
                accountingPeriod: receipt.AccountingPeriod == default ? null : receipt.AccountingPeriod,
                amount: receipt.Amount,
                message: $"Receipt {receiptLabel} journal entry refresh failed: {ex.Message}",
                currentUser: currentUser);
            throw;
        }
    }

    private async Task TryReplaceJournalEntriesFromInvoiceAsync(Invoice invoice, Invoice priorInvoice)
    {
        try
        {
            if (invoice.InvoiceId == Guid.Empty)
                return;

            var costCodeById = await LoadCostCodeByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);

            var priorPaymentLedgerLines = priorInvoice.LedgerLines
                .Where(line => line.LedgerLineId != Guid.Empty && line.Amount != 0)
                .Where(line => costCodeById.TryGetValue(line.CostCodeId, out var costCode) && IsPaymentLedgerLine(costCode))
                .ToList();

            var currentPaymentLedgerLineIds = invoice.LedgerLines
                .Where(line => line.LedgerLineId != Guid.Empty && line.Amount != 0)
                .Where(line => costCodeById.TryGetValue(line.CostCodeId, out var costCode) && IsPaymentLedgerLine(costCode))
                .Select(line => line.LedgerLineId)
                .ToHashSet();

            var paymentIdsToRefresh = new HashSet<Guid>();
            foreach (var removedPaymentLedgerLine in priorPaymentLedgerLines.Where(line => !currentPaymentLedgerLineIds.Contains(line.LedgerLineId)))
            {
                await DeleteJournalEntriesForInvoicePaymentLedgerLineAsync(invoice, removedPaymentLedgerLine);
                if (removedPaymentLedgerLine.PaymentId is { } removedPaymentId && removedPaymentId != Guid.Empty)
                    paymentIdsToRefresh.Add(removedPaymentId);
            }

            await RefreshInvoiceChargeJournalEntriesAsync(invoice, invoice.ModifiedBy);

            foreach (var paymentLedgerLine in invoice.LedgerLines
                         .Where(line => line.Amount != 0)
                         .Where(line => costCodeById.TryGetValue(line.CostCodeId, out var costCode) && IsPaymentLedgerLine(costCode)))
            {
                if (paymentLedgerLine.PaymentId is { } paymentId && paymentId != Guid.Empty)
                {
                    paymentIdsToRefresh.Add(paymentId);
                    continue;
                }

                var existingPaymentEntries = await GetJournalEntriesForInvoicePaymentLedgerLineAsync(
                    invoice.OrganizationId,
                    invoice.OfficeId,
                    invoice,
                    paymentLedgerLine);
                await UpsertJournalEntryFromPaymentAsync(invoice, paymentLedgerLine, existingPaymentEntries, invoice.ModifiedBy);
            }

            foreach (var paymentId in paymentIdsToRefresh)
                await CreateJournalEntriesFromInvoicePaymentDocumentAsync(paymentId, invoice.OrganizationId, invoice.ModifiedBy);

            await PruneOrphanedInvoicePaymentJournalEntriesAsync(invoice, await GetActiveInvoicePaymentLedgerLinesAsync(invoice));
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "Invoice",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.Invoice,
                sourceId: invoice.InvoiceId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: invoice.TotalAmount,
                message: $"Invoice {invoice.InvoiceCode} journal entry refresh failed: {ex.Message}",
                currentUser: invoice.ModifiedBy);
            throw;
        }
    }

    private async Task ReplaceJournalEntriesFromBillAsync(Receipt bill, Guid currentUser)
    {
        try
        {
            EnsureReceiptIsBill(bill);
            bill = await LoadReceiptWithSplitsAsync(bill);

            if (bill.ReceiptId == Guid.Empty)
                return;

            if (!await IsAccountingFeatureEnabledAsync(bill.OrganizationId))
            {
                await DeleteAllBillJournalEntriesAsync(bill);
                return;
            }

            var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(bill.OrganizationId, bill.OfficeId);
            var ownerAccountsPayableAccountId = GetDefaultOwnerAccountsPayable(chartOfAccounts, bill.OfficeId, accountingOffice);
            var pmUtilityIncomeAccountId = GetDefaultPmUtilityIncome(chartOfAccounts, bill.OfficeId, accountingOffice);
            var liabilityAccountId = GetBillReceiptLiabilityAccountId(bill, chartOfAccounts, accountingOffice);

            var existingBillEntries = await GetJournalEntriesForSourceAsync(
                bill.OrganizationId,
                bill.OfficeId,
                SourceType.Bill,
                bill.ReceiptId);
            var (mainExisting, ownerUtilityExisting) = ClassifyBillJournalEntries(
                existingBillEntries,
                ownerAccountsPayableAccountId,
                pmUtilityIncomeAccountId);

            var mainRebuilt = await BuildJournalEntryFromBillAsync(bill, chartOfAccounts, accountingOffice, currentUser);
            JournalEntry? updatedMain = null;
            if (HasActiveJournalEntryLines(mainRebuilt))
            {
                updatedMain = await UpsertAutoGeneratedJournalEntryAsync(
                    mainRebuilt,
                    mainExisting != null ? [mainExisting] : [],
                    currentUser,
                    bill.OrganizationId);
            }
            else if (mainExisting != null)
            {
                await RemoveAutoGeneratedJournalEntryForDocumentSyncAsync(mainExisting, bill.OrganizationId, mainRebuilt, currentUser);
            }

            JournalEntry? updatedOwnerUtility = null;
            var ownerUtilityRebuilt = await BuildJournalEntryFromBillForOwnerUtilityAsync(bill, chartOfAccounts, accountingOffice, currentUser);
            if (ownerUtilityRebuilt != null)
            {
                updatedOwnerUtility = await UpsertAutoGeneratedJournalEntryAsync(
                    ownerUtilityRebuilt,
                    ownerUtilityExisting != null ? [ownerUtilityExisting] : [],
                    currentUser,
                    bill.OrganizationId);
            }
            else if (ownerUtilityExisting != null)
            {
                await RemoveAutoGeneratedJournalEntryForDocumentSyncAsync(ownerUtilityExisting, bill.OrganizationId, ownerUtilityRebuilt, currentUser);
            }

            var retainedBillEntryIds = new HashSet<Guid>();
            if (updatedMain != null)
                retainedBillEntryIds.Add(updatedMain.JournalEntryId);
            if (updatedOwnerUtility != null)
                retainedBillEntryIds.Add(updatedOwnerUtility.JournalEntryId);
            await DeleteJournalEntriesExceptAsync(existingBillEntries, retainedBillEntryIds, bill.OrganizationId, currentUser);

            var existingPayments = await GetJournalEntriesForSourceAsync(
                bill.OrganizationId,
                bill.OfficeId,
                SourceType.BillPayment,
                bill.ReceiptId);

            if (await IsBillCoveredByBillPaymentDocumentAsync(bill.ReceiptId, bill.OrganizationId, bill.OfficeId))
            {
                await DeleteJournalEntriesExceptAsync(existingPayments, Array.Empty<Guid>(), bill.OrganizationId, currentUser);
                return;
            }

            if (bill.PaidAmount == 0)
            {
                await DeleteJournalEntriesExceptAsync(existingPayments, Array.Empty<Guid>(), bill.OrganizationId, currentUser);
                return;
            }

            var paymentOffsetAccountId = existingPayments
                .Select(entry => ResolveBillPaymentOffsetAccountId(entry, liabilityAccountId))
                .FirstOrDefault(accountId => accountId is > 0);

            var paymentApplication = new BillPaymentApplication
            {
                Bill = bill,
                AmountApplied = bill.PaidAmount,
                PaymentDate = bill.PaidDate ?? bill.ReceiptDate,
                ChartOfAccountId = paymentOffsetAccountId ?? GetDefaultBankAccount(chartOfAccounts, bill.OfficeId, accountingOffice),
                Description = bill.PaymentDescription?.Trim() ?? string.Empty,
                PaymentSequence = 0
            };

            var paymentRebuilt = await BuildJournalEntryFromBillPaymentAsync(paymentApplication, chartOfAccounts, accountingOffice, currentUser);
            var updatedPayment = await UpsertAutoGeneratedJournalEntryAsync(
                paymentRebuilt,
                existingPayments,
                currentUser,
                bill.OrganizationId);

            if (updatedPayment != null)
                await DeleteJournalEntriesExceptAsync(existingPayments, [updatedPayment.JournalEntryId], bill.OrganizationId, currentUser);
        }
        catch (Exception ex)
        {
            var billLabel = !string.IsNullOrWhiteSpace(bill.BillNumber)
                ? bill.BillNumber.Trim()
                : bill.ReceiptCode.Trim();
            await LogAccountingErrorAsync(
                trigger: "Bill",
                organizationId: bill.OrganizationId,
                officeId: bill.OfficeId,
                sourceTypeId: (int)SourceType.Bill,
                sourceId: bill.ReceiptId,
                documentCode: billLabel,
                accountingPeriod: bill.AccountingPeriod == default ? null : bill.AccountingPeriod,
                amount: bill.Amount,
                message: $"Bill {billLabel} journal entry refresh failed: {ex.Message}",
                currentUser: currentUser);
            throw;
        }
    }

    private async Task DeleteAllBillJournalEntriesAsync(Receipt bill)
    {
        await DeleteJournalEntriesForBillAsync(bill);
    }

    private async Task DeleteJournalEntriesForSourceByKindAsync(Guid organizationId, int officeId, SourceType sourceType, Guid sourceId, JournalEntryKind journalEntryKind)
    {
        await _journalEntryRepository.DeleteJournalEntriesBySourceIdAsync(
            organizationId,
            (int)sourceType,
            sourceId,
            (int)journalEntryKind);
    }

    private async Task DeleteJournalEntriesForSourceAsync(Guid organizationId, int officeId, int sourceTypeId, Guid sourceId)
    {
        var entries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = organizationId,
            OfficeIds = officeId.ToString(),
            SourceTypeId = sourceTypeId,
            SourceId = sourceId,
            // Must include JEs before the accounting-office start date.
            StartDate = DateOnly.MinValue,
            IncludeUnposted = true
        })).ToList();

        foreach (var entry in entries)
            await DeleteOpenJournalEntryAsync(entry.JournalEntryId, organizationId);
    }

    private static int? ResolveBillPaymentOffsetAccountId(JournalEntry entry, int liabilityAccountId)
    {
        var offsetLine = entry.JournalEntryLines.FirstOrDefault(l =>
            l.ChartOfAccountId > 0 &&
            l.ChartOfAccountId != liabilityAccountId);

        return offsetLine?.ChartOfAccountId;
    }
}
