using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    public async Task<Invoice> UpdateInvoiceAsync(Invoice invoice)
    {
        var existingInvoice = await _accountingRepository.GetInvoiceByIdAsync(invoice.InvoiceId, invoice.OrganizationId);
        if (existingInvoice == null)
            throw new Exception("Invoice not found");

        var priorPaymentLedgerLineIds = existingInvoice.LedgerLines
            .Where(l => l.LedgerLineId != Guid.Empty)
            .Select(l => l.LedgerLineId);

        var updatedInvoice = await _accountingRepository.UpdateByIdAsync(invoice);

        try
        {
            await ReplaceJournalEntriesFromInvoiceAsync(updatedInvoice, priorPaymentLedgerLineIds);
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException($"Invoice was updated but general ledger entry refresh failed: {ex.Message}", ex);
        }

        return updatedInvoice;
    }

    public async Task<Receipt> UpdateBillAsync(Receipt bill, Guid currentUser)
    {
        EnsureReceiptIsBill(bill);

        var updatedBill = await _maintenanceRepository.UpdateReceiptAsync(bill);

        try
        {
            await ReplaceJournalEntriesFromBillAsync(updatedBill, currentUser);
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException($"Bill was updated but general ledger entry refresh failed: {ex.Message}", ex);
        }

        return updatedBill;
    }

    public async Task<Receipt> UpdateReceiptAsync(Receipt receipt, Guid currentUser)
    {
        EnsureReceiptIsCardReceipt(receipt);

        var updatedReceipt = await _maintenanceRepository.UpdateReceiptAsync(receipt);
        var freshReceipt = await _maintenanceRepository.GetReceiptByIdAsync(updatedReceipt.ReceiptId, updatedReceipt.OrganizationId)
            ?? throw new Exception("Receipt not found after update");

        try
        {
            await ReplaceJournalEntriesFromReceiptAsync(freshReceipt, currentUser);
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException($"Receipt was updated but general ledger entry refresh failed: {ex.Message}", ex);
        }

        return freshReceipt;
    }

    async Task ReplaceJournalEntriesFromReceiptAsync(
        Receipt receipt,
        Guid currentUser)
    {
        EnsureReceiptIsCardReceipt(receipt);

        if (receipt.ReceiptId == Guid.Empty)
            throw new Exception("ReceiptId is required to refresh journal entries");

        if (!await IsAccountingFeatureEnabledAsync(receipt.OrganizationId))
        {
            await DeleteJournalEntriesForSourceAsync(
                receipt.OrganizationId,
                receipt.OfficeId,
                (int)SourceType.Receipt,
                receipt.ReceiptId);
            return;
        }

        var existingEntries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = receipt.OrganizationId,
            OfficeIds = receipt.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.Receipt,
            SourceId = receipt.ReceiptId,
            IncludeVoided = true,
            IncludeUnposted = true
        })).Where(e => !e.IsVoided).ToList();

        foreach (var entry in existingEntries.Where(e => e.IsPosted))
            throw new Exception($"Cannot refresh journal entries because {entry.JournalEntryCode} is posted");

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(receipt.OrganizationId, receipt.OfficeId);
        var rebuiltJournalEntry = await BuildJournalEntryFromReceiptAsync(receipt, chartOfAccounts, accountingOffice, currentUser);

        while (existingEntries.Count > 1)
        {
            var duplicate = existingEntries[^1];
            await DeleteJournalEntryAsync(duplicate.JournalEntryId, receipt.OrganizationId);
            existingEntries.RemoveAt(existingEntries.Count - 1);
        }

        var existingEntry = existingEntries.FirstOrDefault();
        if (existingEntry != null)
        {
            rebuiltJournalEntry.JournalEntryId = existingEntry.JournalEntryId;
            rebuiltJournalEntry.OrganizationId = receipt.OrganizationId;
            rebuiltJournalEntry.OfficeId = receipt.OfficeId;
            rebuiltJournalEntry.CreatedBy = existingEntry.CreatedBy;
            rebuiltJournalEntry.ModifiedBy = currentUser;

            foreach (var line in rebuiltJournalEntry.JournalEntryLines)
            {
                line.JournalEntryId = existingEntry.JournalEntryId;
                line.JournalEntryLineId = Guid.Empty;
            }

            await UpdateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
            return;
        }

        await CreateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
    }

    async Task ReplaceJournalEntriesFromInvoiceAsync(Invoice invoice, IEnumerable<Guid> priorPaymentLedgerLineIds)
    {
        if (invoice.InvoiceId == Guid.Empty)
            throw new Exception("InvoiceId is required to refresh journal entries");

        var costCodes = await _accountingRepository.GetCostCodesByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);
        var costCodeById = costCodes.ToDictionary(c => c.CostCodeId);

        var paymentLedgerLineIds = priorPaymentLedgerLineIds
            .Concat(invoice.LedgerLines
                .Where(l => l.LedgerLineId != Guid.Empty)
                .Where(l => costCodeById.TryGetValue(l.CostCodeId, out var costCode) && IsPaymentLedgerLine(costCode))
                .Select(l => l.LedgerLineId))
            .Distinct()
            .ToList();

        await DeleteJournalEntriesForInvoiceChargesAsync(invoice);

        foreach (var ledgerLineId in paymentLedgerLineIds)
            await DeleteJournalEntriesForInvoicePaymentLedgerLineAsync(invoice.OrganizationId, invoice.OfficeId, ledgerLineId);

        if (await IsAccountingFeatureEnabledAsync(invoice.OrganizationId))
        {
            await CreateJournalEntryFromInvoiceAsync(invoice, invoice.ModifiedBy);

            foreach (var paymentLedgerLine in invoice.LedgerLines
                         .Where(l => l.Amount != 0)
                         .Where(l => costCodeById.TryGetValue(l.CostCodeId, out var costCode) && IsPaymentLedgerLine(costCode)))
            {
                await CreateJournalEntryFromPaymentAsync(invoice, paymentLedgerLine, invoice.ModifiedBy);
            }
        }
    }

    async Task ReplaceJournalEntriesFromBillAsync(Receipt bill, Guid currentUser)
    {
        EnsureReceiptIsBill(bill);

        if (bill.ReceiptId == Guid.Empty)
            throw new Exception("ReceiptId is required to refresh journal entries");

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(bill.OrganizationId, bill.OfficeId);
        var paymentOffsetAccountId = await DeleteBillPaymentJournalEntriesAsync(bill, chartOfAccounts, accountingOffice);

        await DeleteJournalEntriesForSourceAsync(
            bill.OrganizationId,
            bill.OfficeId,
            (int)SourceType.Bill,
            bill.ReceiptId);

        if (await IsAccountingFeatureEnabledAsync(bill.OrganizationId))
        {
            var billJournalEntry = await BuildJournalEntryFromBillAsync(bill, chartOfAccounts, accountingOffice, currentUser);
            await CreateAutoGeneratedJournalEntryAsync(billJournalEntry);
        }

        if (bill.PaidAmount == 0)
            return;

        if (!await IsAccountingFeatureEnabledAsync(bill.OrganizationId))
            return;

        var billLabel = !string.IsNullOrWhiteSpace(bill.BillNumber)
            ? bill.BillNumber.Trim()
            : bill.ReceiptCode.Trim();
        var paymentApplication = new BillPaymentApplication
        {
            Bill = bill,
            AmountApplied = bill.PaidAmount,
            PaymentDate = bill.PaidDate ?? bill.ReceiptDate,
            ChartOfAccountId = paymentOffsetAccountId ?? GetDefaultBankAccount(chartOfAccounts, bill.OfficeId, accountingOffice),
            Description = $"Bill Payment - {billLabel}",
            PaymentSequence = 0
        };

        await CreateJournalEntryFromBillPaymentAsync(paymentApplication, currentUser);
    }

    async Task DeleteJournalEntriesForSourceAsync(Guid organizationId, int officeId, int sourceTypeId, Guid sourceId)
    {
        var entries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = organizationId,
            OfficeIds = officeId.ToString(),
            SourceTypeId = sourceTypeId,
            SourceId = sourceId,
            IncludeVoided = true,
            IncludeUnposted = true
        })).ToList();

        foreach (var entry in entries.Where(e => !e.IsVoided))
        {
            if (entry.IsPosted)
                throw new Exception($"Cannot refresh journal entries because {entry.JournalEntryCode} is posted");

            await DeleteJournalEntryAsync(entry.JournalEntryId, organizationId);
        }
    }

    async Task<int?> DeleteBillPaymentJournalEntriesAsync(Receipt bill, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice)
    {
        var liabilityAccountId = GetBillReceiptLiabilityAccountId(bill, chartOfAccounts, accountingOffice);

        var existingEntries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = bill.OrganizationId,
            OfficeIds = bill.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.BillPayment,
            IncludeVoided = true,
            IncludeUnposted = true
        })).ToList();

        int? paymentOffsetAccountId = null;

        foreach (var entry in existingEntries.Where(e => !e.IsVoided && e.SourceId == bill.ReceiptId))
        {
            paymentOffsetAccountId ??= ResolveBillPaymentOffsetAccountId(entry, liabilityAccountId);

            if (entry.IsPosted)
                throw new Exception($"Cannot refresh journal entries because {entry.JournalEntryCode} is posted");

            await DeleteJournalEntryAsync(entry.JournalEntryId, bill.OrganizationId);
        }

        return paymentOffsetAccountId;
    }

    static int? ResolveBillPaymentOffsetAccountId(JournalEntry entry, int liabilityAccountId)
    {
        var offsetLine = entry.JournalEntryLines.FirstOrDefault(l =>
            l.ChartOfAccountId > 0 &&
            l.ChartOfAccountId != liabilityAccountId);

        return offsetLine?.ChartOfAccountId;
    }
}
