using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    private readonly struct TransferJournalEntryAccounts
    {
        public int EscrowDepositAccountId { get; init; }
        public int EscrowSecurityDepositAccountId { get; init; }
        public int EscrowSdwAccountId { get; init; }
        public int EscrowOwnersAccountId { get; init; }
        public int BankAccountId { get; init; }
    }

    #region Triggers
    public async Task<JournalEntry?> CreateJournalEntryFromTransferAsync(Transfer transfer, Guid currentUser)
        => (await CreateJournalEntryFromTransferWithResultAsync(transfer, currentUser)).JournalEntry;

    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromTransferWithResultAsync(Transfer transfer, Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(transfer.OrganizationId))
            return AccountingJournalEntryResult.Success();

        if (!ShouldCreateJournalEntryForTransfer(transfer))
            return AccountingJournalEntryResult.Success();

        try
        {
            ValidateTransferForJournalEntry(transfer);

            await EnrichTransferSplitsFromJournalEntryLinesAsync(transfer);
            ApplyTransferHeaderContextFromSplits(transfer);

            var journalEntry = await BuildJournalEntryFromTransferRecordAsync(transfer, currentUser);
            var created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);
            if (created == null)
                return AccountingJournalEntryResult.Success();

            await SyncTransferDocumentLinksAsync(transfer, currentUser);

            return AccountingJournalEntryResult.Success(created);
        }
        catch (Exception ex)
        {
            var transferLabel = string.IsNullOrWhiteSpace(transfer.TransferCode)
                ? transfer.TransferId.ToString()
                : transfer.TransferCode.Trim();

            await LogAccountingErrorAsync(
                trigger: "Transfer",
                organizationId: transfer.OrganizationId,
                officeId: transfer.OfficeId,
                sourceTypeId: (int)SourceType.Transfer,
                sourceId: transfer.TransferId,
                documentCode: transferLabel,
                accountingPeriod: transfer.AccountingPeriod == default ? null : transfer.AccountingPeriod,
                amount: transfer.Amount,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    #endregion

    #region Journal Entry
    private async Task TryReplaceJournalEntriesFromTransferAsync(Transfer transfer, Guid currentUser)
    {
        try
        {
            if (transfer.TransferId == Guid.Empty)
                return;

            if (!await IsAccountingFeatureEnabledAsync(transfer.OrganizationId) || !ShouldCreateJournalEntryForTransfer(transfer))
            {
                await ClearTransferDocumentLinksAsync(transfer.OrganizationId, transfer.TransferId, currentUser);
                await _accountingRepository.ClearDepositTransferIdsByTransferIdAsync(
                    transfer.OrganizationId,
                    transfer.TransferId,
                    currentUser);
                await DeleteJournalEntriesForSourceAsync(
                    transfer.OrganizationId,
                    transfer.OfficeId,
                    (int)SourceType.Transfer,
                    transfer.TransferId);

                return;
            }

            var existingEntries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
            {
                OrganizationId = transfer.OrganizationId,
                OfficeIds = transfer.OfficeId.ToString(),
                SourceTypeId = (int)SourceType.Transfer,
                SourceId = transfer.TransferId,
                StartDate = DateOnly.MinValue,
                IncludeUnposted = true
            })).ToList();

            var rebuiltJournalEntry = await BuildJournalEntryFromTransferRecordAsync(transfer, currentUser);

            while (existingEntries.Count > 1)
            {
                var duplicate = existingEntries[^1];
                await DeleteOpenJournalEntryAsync(duplicate.JournalEntryId, transfer.OrganizationId);
                existingEntries.RemoveAt(existingEntries.Count - 1);
            }

            var existingEntry = existingEntries.FirstOrDefault();
            if (existingEntry != null)
            {
                rebuiltJournalEntry.JournalEntryId = existingEntry.JournalEntryId;
                rebuiltJournalEntry.OrganizationId = transfer.OrganizationId;
                rebuiltJournalEntry.OfficeId = transfer.OfficeId;
                rebuiltJournalEntry.CreatedBy = existingEntry.CreatedBy;
                rebuiltJournalEntry.ModifiedBy = currentUser;

                foreach (var line in rebuiltJournalEntry.JournalEntryLines)
                {
                    line.JournalEntryId = existingEntry.JournalEntryId;
                    line.JournalEntryLineId = Guid.Empty;
                }

                await UpdateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);

                await SyncTransferDocumentLinksAsync(transfer, currentUser);
                return;
            }

            await CreateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
            await SyncTransferDocumentLinksAsync(transfer, currentUser);
        }
        catch (Exception ex)
        {
            var transferLabel = string.IsNullOrWhiteSpace(transfer.TransferCode)
                ? transfer.TransferId.ToString()
                : transfer.TransferCode.Trim();

            await LogAccountingErrorAsync(
                trigger: "Transfer",
                organizationId: transfer.OrganizationId,
                officeId: transfer.OfficeId,
                sourceTypeId: (int)SourceType.Transfer,
                sourceId: transfer.TransferId,
                documentCode: transferLabel,
                accountingPeriod: transfer.AccountingPeriod == default ? null : transfer.AccountingPeriod,
                amount: transfer.Amount,
                message: $"Transfer {transferLabel} journal entry refresh failed: {ex.Message}",
                currentUser: currentUser);
        }
    }

    private static void ValidateTransferForJournalEntry(Transfer transfer)
    {
        if (transfer.OfficeId <= 0)
            throw new Exception("OfficeId is required");

        if (transfer.Amount == 0)
            throw new Exception("Transfer amount cannot be zero");

        if (transfer.TransferDate == default)
            throw new Exception("Transfer date is required");

        if (transfer.Splits == null || transfer.Splits.Count == 0)
            throw new Exception("At least one split is required");

        foreach (var split in transfer.Splits)
        {
            if (split.ChartOfAccountId is null or <= 0)
                throw new Exception("Each split must have a chart of account");

            if (split.Amount == 0)
                throw new Exception("Split amounts must be non-zero");
        }

        var splitTotal = transfer.Splits.Sum(split => split.Amount);
        if (Math.Abs(splitTotal - transfer.Amount) > 0.005m)
            throw new Exception($"Transfer amount must equal split total ({splitTotal:0.00})");
    }

    private static bool ShouldCreateJournalEntryForTransfer(Transfer transfer)
        => transfer.IsActive
            && transfer.OfficeId > 0
            && transfer.Amount != 0
            && transfer.TransferDate != default
            && transfer.Splits is { Count: > 0 }
            && transfer.Splits.All(split => split.ChartOfAccountId is > 0 && split.Amount != 0)
            && Math.Abs(transfer.Splits.Sum(split => split.Amount) - transfer.Amount) <= 0.005m;

    private async Task<JournalEntry> BuildJournalEntryFromTransferRecordAsync(Transfer transfer, Guid currentUser)
    {
        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(transfer.OrganizationId, transfer.OfficeId);
        return BuildJournalEntryFromTransferRecord(transfer, chartOfAccounts, accountingOffice, currentUser);
    }

    private JournalEntry BuildJournalEntryFromTransferRecord(Transfer transfer, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // TRANSFER-JE-ACCOUNTS
        // Line 1 — Escrow deposit (transfer.BankAccountId or default escrow deposit):
        //   positive transfer: Debit 0 / Credit escrow deposit
        //   negative transfer: Debit escrow deposit / Credit 0
        // Lines 2+ — One JE line per transfer split (each linked to a source escrow JE line).
        //   positive split: Debit split / Credit 0
        //   negative split: Debit 0 / Credit split
        // END TRANSFER-JE-ACCOUNTS

        var accounts = ResolveTransferJournalEntryAccounts(chartOfAccounts, transfer.OfficeId, accountingOffice);
        var bankAccountId = transfer.BankAccountId is > 0
            ? transfer.BankAccountId.Value
            : accounts.EscrowDepositAccountId;
        var memo = BuildTransferMemo(transfer.TransferCode, transfer.TransferDate);
        var headerLineContext = FirstTransferSplitContext(transfer.Splits) with
        {
            PropertyId = transfer.PropertyId ?? FirstSplitContextId(transfer.Splits, split => split.PropertyId)
        };
        var bankLine = new JournalEntryLine
        {
            ChartOfAccountId = bankAccountId,
            Debit = transfer.Amount < 0 ? Math.Abs(transfer.Amount) : 0,
            Credit = transfer.Amount > 0 ? transfer.Amount : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(bankLine, headerLineContext);
        var journalEntryLines = new List<JournalEntryLine> { bankLine };

        var destinationSplits = (transfer.Splits ?? [])
            .Where(split => split.ChartOfAccountId is > 0 && split.Amount != 0)
            .OrderBy(split => GetTransferCreditAccountSortOrder(split.ChartOfAccountId!.Value, accounts))
            .ThenBy(split => split.JournalEntryLineId ?? Guid.Empty)
            .ThenBy(split => split.ChartOfAccountId!.Value)
            .ToList();

        foreach (var split in destinationSplits)
        {
            var splitMemo = string.IsNullOrWhiteSpace(split.Description) ? memo : split.Description.Trim();
            var splitLine = new JournalEntryLine
            {
                ChartOfAccountId = split.ChartOfAccountId!.Value,
                Debit = split.Amount > 0 ? split.Amount : 0,
                Credit = split.Amount < 0 ? Math.Abs(split.Amount) : 0,
                Memo = splitMemo,
                CreatedBy = currentUser
            };
            ApplyJournalEntryLineContext(splitLine, CreateJournalEntryLineContextFromTransferSplit(split));
            journalEntryLines.Add(splitLine);
        }

        return ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = transfer.OrganizationId,
            OfficeId = transfer.OfficeId,
            TransactionDate = transfer.TransferDate,
            AccountingPeriod = transfer.AccountingPeriod,
            SourceTypeId = (int)SourceType.Transfer,
            SourceId = transfer.TransferId,
            SourceCode = ResolveJournalEntrySourceCodeFromTransfer(transfer),
            Memo = memo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        }, JournalEntryKind.Transfer, Perspective.Company);
    }

    private TransferJournalEntryAccounts ResolveTransferJournalEntryAccounts(List<ChartOfAccount> chartOfAccounts, int officeId, AccountingOffice? accountingOffice)
    {
        return new TransferJournalEntryAccounts
        {
            EscrowDepositAccountId = GetDefaultEscrowDepositAccount(chartOfAccounts, officeId, accountingOffice),
            EscrowSecurityDepositAccountId = GetDefaultEscrowSecurityDepositAccount(chartOfAccounts, officeId, accountingOffice),
            EscrowSdwAccountId = GetDefaultEscrowSdwAccount(chartOfAccounts, officeId, accountingOffice),
            EscrowOwnersAccountId = GetDefaultEscrowOwnersAccount(chartOfAccounts, officeId, accountingOffice),
            BankAccountId = GetDefaultBankAccount(chartOfAccounts, officeId, accountingOffice)
        };
    }

    private static int GetTransferCreditAccountSortOrder(int chartOfAccountId, TransferJournalEntryAccounts accounts)
    {
        if (chartOfAccountId == accounts.EscrowSecurityDepositAccountId)
            return 0;
        if (chartOfAccountId == accounts.EscrowSdwAccountId)
            return 1;
        if (chartOfAccountId == accounts.EscrowOwnersAccountId)
            return 2;
        if (chartOfAccountId == accounts.BankAccountId)
            return 3;
        return 99;
    }
    #endregion

    #region Document Link
    private static void ApplyTransferDocumentLink(JournalEntry journalEntry, Transfer transfer)
    {
        if (transfer.TransferId == Guid.Empty)
            return;

        journalEntry.TransferId = transfer.TransferId;
        journalEntry.TransferCode = transfer.TransferCode.Trim();
    }

    private static void ClearTransferDocumentLink(JournalEntry journalEntry)
    {
        journalEntry.TransferId = null;
        journalEntry.TransferCode = null;
    }

    private async Task SyncTransferDocumentLinksAsync(Transfer transfer, Guid currentUser)
    {
        if (transfer.TransferId == Guid.Empty || !transfer.IsActive)
            return;

        if (!await IsAccountingFeatureEnabledAsync(transfer.OrganizationId))
            return;

        await ClearTransferDocumentLinksAsync(transfer.OrganizationId, transfer.TransferId, currentUser);

        var depositIds = await CollectDepositIdsFromTransferSplitsAsync(transfer);
        await SyncDepositTransferIdsForTransferAsync(transfer, depositIds, currentUser);
        foreach (var depositId in depositIds)
        {
            var depositJournalEntries = (await _journalEntryRepository.GetJournalEntriesByDepositIdAsync(new JournalEntryGetByDepositIdCriteria
            {
                OrganizationId = transfer.OrganizationId,
                DepositId = depositId
            })).ToList();

            foreach (var journalEntry in depositJournalEntries)
            {
                ApplyTransferDocumentLink(journalEntry, transfer);
                journalEntry.ModifiedBy = currentUser;
                await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(journalEntry, requireActiveLines: true);
            }
        }

        var transferJournalEntries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = transfer.OrganizationId,
            OfficeIds = transfer.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.Transfer,
            SourceId = transfer.TransferId,
            StartDate = DateOnly.MinValue,
            IncludeUnposted = true
        })).ToList();

        foreach (var transferJournalEntry in transferJournalEntries)
        {
            ApplyTransferDocumentLink(transferJournalEntry, transfer);
            transferJournalEntry.ModifiedBy = currentUser;
            await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(transferJournalEntry, requireActiveLines: true);
        }
    }

    private async Task ClearTransferDocumentLinksAsync(Guid organizationId, Guid transferId, Guid currentUser)
    {
        if (transferId == Guid.Empty)
            return;

        var linkedEntries = (await _journalEntryRepository.GetJournalEntriesByTransferIdAsync(new JournalEntryGetByTransferIdCriteria
        {
            OrganizationId = organizationId,
            TransferId = transferId
        })).ToList();

        foreach (var journalEntry in linkedEntries)
        {
            ClearTransferDocumentLink(journalEntry);
            journalEntry.ModifiedBy = currentUser;
            await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(journalEntry, requireActiveLines: true);
        }
    }

    private async Task<HashSet<Guid>> CollectDepositIdsFromTransferSplitsAsync(Transfer transfer)
    {
        var depositIds = new HashSet<Guid>();

        foreach (var split in transfer.Splits ?? [])
        {
            if (split.JournalEntryLineId is not { } journalEntryLineId || journalEntryLineId == Guid.Empty)
                continue;

            var sourceLine = await _journalEntryRepository.GetJournalEntryLineByIdAsync(journalEntryLineId);
            if (sourceLine == null || sourceLine.JournalEntryId == Guid.Empty)
                continue;

            var depositJournalEntry = await _journalEntryRepository.GetJournalEntryByIdAsync(
                sourceLine.JournalEntryId,
                transfer.OrganizationId);
            if (depositJournalEntry == null)
                continue;

            var depositId = NormalizeOptionalGuid(depositJournalEntry.DepositId);
            if (depositId == null
                && depositJournalEntry.SourceTypeId == (int)SourceType.Deposit)
            {
                depositId = NormalizeOptionalGuid(depositJournalEntry.SourceId);
            }

            if (depositId == null || depositId == Guid.Empty)
                throw new Exception("Transfer split journal entry line must belong to a journal entry with a deposit link.");

            depositIds.Add(depositId.Value);
        }

        return depositIds;
    }

    private async Task SyncDepositTransferIdsForTransferAsync(Transfer transfer, Guid currentUser)
    {
        if (transfer.TransferId == Guid.Empty)
            return;

        var depositIds = await CollectDepositIdsFromTransferSplitsAsync(transfer);
        await SyncDepositTransferIdsForTransferAsync(transfer, depositIds, currentUser);
    }

    private async Task SyncDepositTransferIdsForTransferAsync(Transfer transfer, IReadOnlyCollection<Guid> depositIds, Guid currentUser)
    {
        if (transfer.TransferId == Guid.Empty)
            return;

        await _accountingRepository.ClearDepositTransferIdsByTransferIdAsync(
            transfer.OrganizationId,
            transfer.TransferId,
            currentUser);

        foreach (var depositId in depositIds)
        {
            if (depositId == Guid.Empty)
                continue;

            await _accountingRepository.SetDepositTransferIdAsync(
                depositId,
                transfer.OrganizationId,
                transfer.TransferId,
                currentUser);
        }
    }
    #endregion
}
