using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Triggers
    public async Task<JournalEntry?> CreateJournalEntryFromDepositAsync(Deposit deposit, Guid currentUser)
        => (await CreateJournalEntryFromDepositWithResultAsync(deposit, currentUser)).JournalEntry;

    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromDepositWithResultAsync(Deposit deposit, Guid currentUser)
    {
        var trail = new AccountingSyncBailTrail();
        var result = await CreateJournalEntryFromDepositWithDiagnosticsAsync(deposit, currentUser, trail);
        if (result.HasWarning || result.JournalEntry == null)
        {
            // Day-to-day create: surface silent exits that Sync will also log as DepositSkip.
            if (result.JournalEntry == null && !result.HasWarning)
                return AccountingJournalEntryResult.WarningResult(trail.FormatBailTrail());
        }

        return result;
    }

    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromDepositWithDiagnosticsAsync(
        Deposit deposit,
        Guid currentUser,
        AccountingSyncBailTrail trail)
    {
        var depositLabel = string.IsNullOrWhiteSpace(deposit.DepositCode)
            ? deposit.DepositId.ToString()
            : deposit.DepositCode.Trim();
        trail.Note($"Deposit {depositLabel} IsActive={deposit.IsActive} Amount={deposit.Amount:0.00} Splits={deposit.Splits?.Count ?? 0} BankAccountId={deposit.BankAccountId}");

        if (!await IsAccountingFeatureEnabledAsync(deposit.OrganizationId))
        {
            trail.Bail("Exit: accounting feature is disabled for organization.");
            return AccountingJournalEntryResult.WarningResult("Accounting feature is disabled for organization.");
        }

        if (!ShouldCreateJournalEntryForDeposit(deposit))
        {
            AppendDepositShouldCreateBailReasons(deposit, trail);
            trail.Bail("Exit: ShouldCreateJournalEntryForDeposit=false.");
            return AccountingJournalEntryResult.WarningResult(trail.FormatBailTrail());
        }

        try
        {
            ValidateDepositForJournalEntry(deposit);

            await EnrichDepositSplitsFromJournalEntryLinesAsync(deposit);
            ApplyDepositHeaderContextFromSplits(deposit);
            trail.Note($"After enrich: splits={deposit.Splits?.Count ?? 0}");

            var journalEntry = BuildJournalEntryFromDepositRecord(deposit, currentUser);
            trail.Note($"Built deposit JE lines={journalEntry.JournalEntryLines?.Count ?? 0}");

            var created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);
            if (created == null)
            {
                trail.Bail("Exit: CreateAutoGeneratedJournalEntryAsync returned null (feature off or rejected).");
                return AccountingJournalEntryResult.WarningResult(trail.FormatBailTrail());
            }

            trail.Note($"Created {created.JournalEntryCode} kind={(int)created.JournalEntryKindId} DepositId={created.DepositId}");
            await SyncDepositDocumentLinksAsync(deposit, currentUser);
            trail.Note("SyncDepositDocumentLinksAsync completed.");

            return AccountingJournalEntryResult.Success(created);
        }
        catch (Exception ex)
        {
            trail.Bail($"Exception: {ex.Message}");
            await LogAccountingErrorAsync(
                trigger: "Deposit",
                organizationId: deposit.OrganizationId,
                officeId: deposit.OfficeId,
                sourceTypeId: (int)SourceType.Deposit,
                sourceId: deposit.DepositId,
                documentCode: depositLabel,
                accountingPeriod: deposit.AccountingPeriod == default ? null : deposit.AccountingPeriod,
                amount: deposit.Amount,
                message: ex.Message + Environment.NewLine + "Bail trail:" + Environment.NewLine + trail.FormatBailTrail(),
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    #endregion

    #region Journal Entry
    private async Task TryReplaceJournalEntriesFromDepositAsync(Deposit deposit, Guid currentUser)
        => await TryReplaceJournalEntriesFromDepositWithDiagnosticsAsync(deposit, currentUser, new AccountingSyncBailTrail());

    private async Task TryReplaceJournalEntriesFromDepositWithDiagnosticsAsync(
        Deposit deposit,
        Guid currentUser,
        AccountingSyncBailTrail trail)
    {
        var depositLabel = string.IsNullOrWhiteSpace(deposit.DepositCode)
            ? deposit.DepositId.ToString()
            : deposit.DepositCode.Trim();

        try
        {
            if (deposit.DepositId == Guid.Empty)
            {
                trail.Bail("Exit: DepositId is empty.");
                return;
            }

            trail.Note($"TryReplace deposit {depositLabel} IsActive={deposit.IsActive} Amount={deposit.Amount:0.00} Splits={deposit.Splits?.Count ?? 0}");

            if (!await IsAccountingFeatureEnabledAsync(deposit.OrganizationId))
            {
                trail.Bail("Exit: accounting feature disabled — clearing deposit links/JEs.");
                await ClearDepositDocumentLinksAsync(deposit.OrganizationId, deposit.DepositId, currentUser);
                await _accountingRepository.ClearPaymentDepositIdsByDepositIdAsync(
                    deposit.OrganizationId,
                    deposit.DepositId,
                    currentUser);
                await DeleteJournalEntriesForSourceAsync(
                    deposit.OrganizationId,
                    deposit.OfficeId,
                    (int)SourceType.Deposit,
                    deposit.DepositId);
                return;
            }

            if (!ShouldCreateJournalEntryForDeposit(deposit))
            {
                AppendDepositShouldCreateBailReasons(deposit, trail);
                trail.Bail("Exit: ShouldCreateJournalEntryForDeposit=false — clearing deposit links/JEs.");
                await ClearDepositDocumentLinksAsync(deposit.OrganizationId, deposit.DepositId, currentUser);
                await _accountingRepository.ClearPaymentDepositIdsByDepositIdAsync(
                    deposit.OrganizationId,
                    deposit.DepositId,
                    currentUser);
                await DeleteJournalEntriesForSourceAsync(
                    deposit.OrganizationId,
                    deposit.OfficeId,
                    (int)SourceType.Deposit,
                    deposit.DepositId);
                return;
            }

            var existingEntries = await GetDocumentJournalEntriesForSyncAsync(
                deposit.OrganizationId,
                deposit.OfficeId,
                SourceType.Deposit,
                deposit.DepositId);
            trail.Note($"Existing SourceType.Deposit JEs: {existingEntries.Count}");

            var rebuiltJournalEntry = BuildJournalEntryFromDepositRecord(deposit, currentUser);
            trail.Note($"Rebuilt JE lines={rebuiltJournalEntry.JournalEntryLines?.Count ?? 0}");

            var updated = await UpsertAutoGeneratedJournalEntryAsync(
                rebuiltJournalEntry,
                existingEntries,
                currentUser,
                deposit.OrganizationId);
            if (updated == null)
            {
                trail.Bail("Exit: UpsertAutoGeneratedJournalEntryAsync returned null on replace.");
                return;
            }

            trail.Note($"Upserted deposit JE {updated.JournalEntryCode}");
            await SyncDepositDocumentLinksAsync(deposit, currentUser);
            trail.Note("SyncDepositDocumentLinksAsync completed.");
        }
        catch (Exception ex)
        {
            trail.Bail($"Exception: {ex.Message}");
            await LogAccountingErrorAsync(
                trigger: "Deposit",
                organizationId: deposit.OrganizationId,
                officeId: deposit.OfficeId,
                sourceTypeId: (int)SourceType.Deposit,
                sourceId: deposit.DepositId,
                documentCode: depositLabel,
                accountingPeriod: deposit.AccountingPeriod == default ? null : deposit.AccountingPeriod,
                amount: deposit.Amount,
                message: $"Deposit {depositLabel} journal entry refresh failed: {ex.Message}"
                    + Environment.NewLine + "Bail trail:" + Environment.NewLine + trail.FormatBailTrail(),
                currentUser: currentUser);
        }
    }

    private static void AppendDepositShouldCreateBailReasons(Deposit deposit, AccountingSyncBailTrail trail)
    {
        if (!deposit.IsActive)
            trail.Bail("Reason: deposit IsActive=false.");
        if (deposit.OfficeId <= 0)
            trail.Bail("Reason: OfficeId missing.");
        if (deposit.BankAccountId is null or <= 0)
            trail.Bail("Reason: BankAccountId missing.");
        if (deposit.Amount == 0)
            trail.Bail("Reason: Amount is zero.");
        if (deposit.DepositDate == default)
            trail.Bail("Reason: DepositDate missing.");
        if (deposit.Splits == null || deposit.Splits.Count == 0)
            trail.Bail("Reason: no splits.");
        else
        {
            if (deposit.Splits.Any(split => split.ChartOfAccountId is null or <= 0))
                trail.Bail("Reason: one or more splits missing ChartOfAccountId.");
            if (deposit.Splits.Any(split => split.Amount == 0))
                trail.Bail("Reason: one or more splits have Amount=0.");
            var splitTotal = deposit.Splits.Sum(split => split.Amount);
            if (Math.Abs(splitTotal - deposit.Amount) > 0.005m)
                trail.Bail($"Reason: amount/split mismatch header={deposit.Amount:0.00} splits={splitTotal:0.00}.");
        }
    }

    private async Task<bool> DepositHasHealthJournalEntryAsync(Guid organizationId, int officeId, Guid depositId)
    {
        if (depositId == Guid.Empty)
            return false;

        var bySource = await GetJournalEntriesForSourceAsync(organizationId, officeId, SourceType.Deposit, depositId);
        if (bySource.Count > 0)
            return true;

        var byDepositId = await GetJournalEntriesByDepositIdCachedAsync(organizationId, depositId);
        return byDepositId.Any(entry =>
            entry.SourceTypeId == (int)SourceType.Deposit
            || entry.JournalEntryKindId == JournalEntryKind.Deposit);
    }

    private static void ValidateDepositForJournalEntry(Deposit deposit)
    {
        if (deposit.OfficeId <= 0)
            throw new Exception("OfficeId is required");

        if (deposit.BankAccountId is null or <= 0)
            throw new Exception("Bank account is required");

        if (deposit.Amount == 0)
            throw new Exception("Deposit amount cannot be zero");

        if (deposit.DepositDate == default)
            throw new Exception("Deposit date is required");

        if (deposit.Splits == null || deposit.Splits.Count == 0)
            throw new Exception("At least one split is required");

        foreach (var split in deposit.Splits)
        {
            if (split.ChartOfAccountId is null or <= 0)
                throw new Exception("Each split must have a chart of account");

            if (split.Amount == 0)
                throw new Exception("Split amounts must be non-zero");
        }

        var splitTotal = deposit.Splits.Sum(split => split.Amount);
        if (Math.Abs(splitTotal - deposit.Amount) > 0.005m)
            throw new Exception($"Deposit amount must equal split total ({splitTotal:0.00})");
    }

    private static bool ShouldCreateJournalEntryForDeposit(Deposit deposit)
        => deposit.IsActive
            && deposit.OfficeId > 0
            && deposit.BankAccountId is > 0
            && deposit.Amount != 0
            && deposit.DepositDate != default
            && deposit.Splits is { Count: > 0 }
            && deposit.Splits.All(split => split.ChartOfAccountId is > 0 && split.Amount != 0)
            && Math.Abs(deposit.Splits.Sum(split => split.Amount) - deposit.Amount) <= 0.005m;

    private JournalEntry BuildJournalEntryFromDepositRecord(Deposit deposit, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // DEPOSIT-JE-ACCOUNTS
        // Line 1 — Bank account (deposit.BankAccountId):
        //   positive deposit: Debit bank / Credit 0
        //   negative deposit: Debit 0 / Credit bank
        // Lines 2+ — Split chart-of-account lines:
        //   positive split: Debit 0 / Credit split
        //   negative split: Debit split / Credit 0
        // END DEPOSIT-JE-ACCOUNTS

        var memo = BuildDepositMemo(deposit.DepositCode, deposit.BankAccountDisplayName, deposit.DepositDate);
        var headerLineContext = FirstDepositSplitContext(deposit.Splits) with
        {
            PropertyId = deposit.PropertyId
                ?? FirstSplitContextId(deposit.Splits, split => split.PropertyId)
        };
        var bankLine = new JournalEntryLine
        {
            ChartOfAccountId = deposit.BankAccountId!.Value,
            Debit = deposit.Amount > 0 ? deposit.Amount : 0,
            Credit = deposit.Amount < 0 ? Math.Abs(deposit.Amount) : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(bankLine, headerLineContext);
        var journalEntryLines = new List<JournalEntryLine> { bankLine };

        foreach (var split in deposit.Splits)
        {
            var splitLine = new JournalEntryLine
            {
                ChartOfAccountId = split.ChartOfAccountId!.Value,
                Debit = split.Amount < 0 ? Math.Abs(split.Amount) : 0,
                Credit = split.Amount > 0 ? split.Amount : 0,
                Memo = string.IsNullOrWhiteSpace(split.Description) ? memo : split.Description.Trim(),
                CreatedBy = currentUser
            };
            ApplyJournalEntryLineContext(splitLine, CreateJournalEntryLineContextFromDepositSplit(split));
            journalEntryLines.Add(splitLine);
        }

        var journalEntry = ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = deposit.OrganizationId,
            OfficeId = deposit.OfficeId,
            TransactionDate = deposit.DepositDate,
            AccountingPeriod = deposit.AccountingPeriod,
            SourceTypeId = (int)SourceType.Deposit,
            SourceId = deposit.DepositId,
            SourceCode = ResolveJournalEntrySourceCodeFromDeposit(deposit),
            Memo = memo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        }, JournalEntryKind.Deposit, Perspective.Company);

        ApplyDepositDocumentLink(journalEntry, deposit);
        return journalEntry;
    }
    #endregion

    #region Document Link
    private static void ApplyDepositDocumentLink(JournalEntry journalEntry, Deposit deposit)
    {
        if (deposit.DepositId == Guid.Empty)
            return;

        journalEntry.DepositId = deposit.DepositId;
        journalEntry.DepositCode = deposit.DepositCode.Trim();
    }

    private static void ClearDepositDocumentLink(JournalEntry journalEntry)
    {
        journalEntry.DepositId = null;
        journalEntry.DepositCode = null;
    }

    private async Task SyncDepositDocumentLinksAsync(Deposit deposit, Guid currentUser)
    {
        if (deposit.DepositId == Guid.Empty || !deposit.IsActive)
            return;

        if (!await IsAccountingFeatureEnabledAsync(deposit.OrganizationId))
            return;

        await ClearDepositDocumentLinksAsync(deposit.OrganizationId, deposit.DepositId, currentUser);

        await ApplyDepositDocumentLinksFromDepositSplitsAsync(deposit, currentUser);

        var paymentIds = await CollectPaymentIdsFromDepositSplitsAsync(deposit);
        await SyncPaymentDepositIdsForDepositAsync(deposit, paymentIds, currentUser);
        foreach (var paymentId in paymentIds)
        {
            var paymentJournalEntries = await GetJournalEntriesByPaymentIdCachedAsync(deposit.OrganizationId, paymentId);

            foreach (var journalEntry in paymentJournalEntries)
            {
                ApplyDepositDocumentLink(journalEntry, deposit);
                journalEntry.ModifiedBy = currentUser;
                await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(journalEntry, requireActiveLines: true);
            }

            var invoiceChargeJournalEntries = await LoadDepositInvoiceChargeJournalEntriesForPaymentJournalEntriesAsync(deposit.OrganizationId, deposit.OfficeId, paymentJournalEntries);
            foreach (var invoiceChargeJournalEntry in invoiceChargeJournalEntries)
            {
                ApplyDepositDocumentLink(invoiceChargeJournalEntry, deposit);
                invoiceChargeJournalEntry.ModifiedBy = currentUser;
                await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(invoiceChargeJournalEntry, requireActiveLines: true);
            }
        }

        var depositJournalEntries = await GetDocumentJournalEntriesForSyncAsync(
            deposit.OrganizationId,
            deposit.OfficeId,
            SourceType.Deposit,
            deposit.DepositId);

        foreach (var depositJournalEntry in depositJournalEntries)
        {
            ApplyDepositDocumentLink(depositJournalEntry, deposit);
            depositJournalEntry.ModifiedBy = currentUser;
            await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(depositJournalEntry, requireActiveLines: true);
        }
    }

    private async Task ClearDepositDocumentLinksAsync(Guid organizationId, Guid depositId, Guid currentUser)
    {
        if (depositId == Guid.Empty)
            return;

        var linkedEntries = await GetJournalEntriesByDepositIdCachedAsync(organizationId, depositId);

        foreach (var journalEntry in linkedEntries)
        {
            ClearDepositDocumentLink(journalEntry);
            journalEntry.ModifiedBy = currentUser;
            await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(journalEntry, requireActiveLines: true);
        }
    }

    private async Task<HashSet<Guid>> CollectPaymentIdsFromDepositSplitsAsync(Deposit deposit)
    {
        var paymentIds = new HashSet<Guid>();

        foreach (var split in deposit.Splits ?? [])
        {
            if (split.JournalEntryLineId is not { } journalEntryLineId || journalEntryLineId == Guid.Empty)
                continue;

            if (_officeSyncCache != null && _officeSyncCache.TryGetPaymentIdForLine(journalEntryLineId, out var cachedPaymentId))
            {
                paymentIds.Add(cachedPaymentId);
                continue;
            }

            var sourceLine = await GetJournalEntryLineByIdCachedAsync(journalEntryLineId);
            if (sourceLine == null || sourceLine.JournalEntryId == Guid.Empty)
                continue;

            var undepositedFundsJournalEntry = await GetJournalEntryByIdCachedAsync(
                sourceLine.JournalEntryId,
                deposit.OrganizationId);
            if (undepositedFundsJournalEntry?.PaymentId is { } paymentId && paymentId != Guid.Empty)
                paymentIds.Add(paymentId);
        }

        return paymentIds;
    }

    private async Task SyncPaymentDepositIdsForDepositAsync(Deposit deposit, Guid currentUser)
    {
        if (deposit.DepositId == Guid.Empty)
            return;

        var paymentIds = await CollectPaymentIdsFromDepositSplitsAsync(deposit);
        await SyncPaymentDepositIdsForDepositAsync(deposit, paymentIds, currentUser);
    }

    private async Task SyncPaymentDepositIdsForDepositAsync(Deposit deposit, IReadOnlyCollection<Guid> paymentIds, Guid currentUser)
    {
        if (deposit.DepositId == Guid.Empty)
            return;

        await _accountingRepository.ClearPaymentDepositIdsByDepositIdAsync(
            deposit.OrganizationId,
            deposit.DepositId,
            currentUser);

        foreach (var paymentId in paymentIds)
        {
            if (paymentId == Guid.Empty)
                continue;

            await _accountingRepository.SetPaymentDepositIdAsync(
                paymentId,
                deposit.OrganizationId,
                deposit.DepositId,
                currentUser);
        }
    }

    private async Task ApplyDepositDocumentLinksFromDepositSplitsAsync(Deposit deposit, Guid currentUser)
    {
        var processedJournalEntryIds = new HashSet<Guid>();

        foreach (var split in deposit.Splits ?? [])
        {
            if (split.JournalEntryLineId is not { } journalEntryLineId || journalEntryLineId == Guid.Empty)
                continue;

            var sourceLine = await GetJournalEntryLineByIdCachedAsync(journalEntryLineId);
            if (sourceLine?.JournalEntryId is not { } journalEntryId || journalEntryId == Guid.Empty)
                continue;

            if (!processedJournalEntryIds.Add(journalEntryId))
                continue;

            var journalEntry = await GetJournalEntryByIdCachedAsync(journalEntryId, deposit.OrganizationId);
            if (journalEntry == null)
                continue;

            ApplyDepositDocumentLink(journalEntry, deposit);
            await TryApplyPaymentDocumentLinkFromDepositedJournalEntryAsync(journalEntry);
            journalEntry.ModifiedBy = currentUser;
            await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(journalEntry, requireActiveLines: true);
        }
    }

    private async Task TryApplyPaymentDocumentLinkFromDepositedJournalEntryAsync(JournalEntry journalEntry)
    {
        if (journalEntry.PaymentId is { } existingPaymentId && existingPaymentId != Guid.Empty)
            return;

        if (!string.IsNullOrWhiteSpace(journalEntry.PaymentCode))
            return;

        if (journalEntry.SourceTypeId != (int)SourceType.Invoice
            || journalEntry.SourceId is not { } invoiceId
            || invoiceId == Guid.Empty)
        {
            return;
        }

        var invoice = await _accountingRepository.GetInvoiceByIdAsync(invoiceId, journalEntry.OrganizationId);
        if (invoice == null)
            return;

        var costCodeById = await LoadCostCodeByOfficeIdAsync(journalEntry.OrganizationId, journalEntry.OfficeId);
        foreach (var ledgerLine in invoice.LedgerLines.Where(line => line.Amount != 0))
        {
            if (!costCodeById.TryGetValue(ledgerLine.CostCodeId, out var costCode) || !IsPaymentLedgerLine(costCode))
                continue;

            if (!MatchesInvoicePaymentLedgerLineMemo(journalEntry, invoice, ledgerLine))
                continue;

            if (ledgerLine.PaymentId is not { } paymentId || paymentId == Guid.Empty)
                continue;

            await ApplyPaymentDocumentLinkAsync(journalEntry, ledgerLine, journalEntry.OrganizationId);
            return;
        }
    }

    private async Task<List<JournalEntry>> LoadDepositInvoiceChargeJournalEntriesForPaymentJournalEntriesAsync(Guid organizationId, int officeId, IReadOnlyList<JournalEntry> paymentJournalEntries)
    {
        var chargeJournalEntries = new List<JournalEntry>();
        var processedJournalEntryIds = new HashSet<Guid>();

        foreach (var paymentJournalEntry in paymentJournalEntries)
        {
            if (paymentJournalEntry.SourceTypeId != (int)SourceType.Invoice
                || paymentJournalEntry.SourceId is not { } invoiceId
                || invoiceId == Guid.Empty
                || string.IsNullOrWhiteSpace(paymentJournalEntry.SourceCode))
            {
                continue;
            }

            var allocationScope = new TransferDepositAllocationScope
            {
                PaymentId = paymentJournalEntry.PaymentId ?? Guid.Empty,
                InvoiceId = invoiceId,
                SourceCode = paymentJournalEntry.SourceCode.Trim(),
                PaymentMemoSourceCode = ResolveTransferDepositPaymentMemoSourceCode(paymentJournalEntry)
            };

            foreach (var chargeEntry in await GetAllJournalEntriesForInvoiceAsync(organizationId, officeId, invoiceId))
            {
                if (!string.Equals(chargeEntry.SourceCode, allocationScope.SourceCode, StringComparison.OrdinalIgnoreCase))
                    continue;

                if (!MatchesTransferDepositInvoiceChargeJournalEntry(chargeEntry, allocationScope))
                    continue;

                if (processedJournalEntryIds.Add(chargeEntry.JournalEntryId))
                    chargeJournalEntries.Add(chargeEntry);
            }
        }

        return chargeJournalEntries;
    }
    #endregion
}
