using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    private async Task<Receipt> LoadReceiptSnapshotForRevertAsync(Guid receiptId, Guid organizationId)
    {
        var receipt = await _maintenanceRepository.GetReceiptByIdAsync(receiptId, organizationId)
            ?? throw new Exception("Receipt not found");
        return await LoadReceiptWithSplitsAsync(receipt);
    }

    private Task RestoreReceiptSnapshotAsync(Receipt snapshot)
        => _maintenanceRepository.UpdateReceiptAsync(snapshot);

    private async Task<Invoice> LoadInvoiceSnapshotForRevertAsync(Guid invoiceId, Guid organizationId)
    {
        return await _accountingRepository.GetInvoiceByIdAsync(invoiceId, organizationId)
            ?? throw new Exception("Invoice not found");
    }

    private Task RestoreInvoiceSnapshotAsync(Invoice snapshot)
        => _accountingRepository.UpdateByIdAsync(snapshot);

    private async Task<WorkOrder> LoadWorkOrderSnapshotForRevertAsync(Guid workOrderId, Guid organizationId)
    {
        return await _maintenanceRepository.GetWorkOrderByIdAsync(workOrderId, organizationId)
            ?? throw new Exception("Work order not found");
    }

    private Task RestoreWorkOrderSnapshotAsync(WorkOrder snapshot)
        => _maintenanceRepository.UpdateWorkOrderAsync(snapshot);

    private static bool IsHardClosedJournalEntry(JournalEntry entry)
        => entry.PostingStatusId == PostingStatus.HardClosed;

    private async Task RemoveAutoGeneratedJournalEntryForDocumentSyncAsync(
        JournalEntry entry,
        Guid organizationId,
        JournalEntry? rebuiltReplacement,
        Guid currentUser)
    {
        if (IsHardClosedJournalEntry(entry))
            throw new Exception($"Journal entry {entry.JournalEntryCode} is hard-closed and cannot be changed.");

        if (entry.PostingStatusId == PostingStatus.Open)
        {
            await DeleteOpenJournalEntryAsync(entry.JournalEntryId, organizationId);
            return;
        }

        if (rebuiltReplacement != null)
        {
            AssignRebuiltJournalEntryFromExisting(rebuiltReplacement, entry, currentUser);
            await UpdateAutoGeneratedJournalEntryAsync(rebuiltReplacement);
        }
    }

    private async Task PruneOpenDuplicateAutoGeneratedJournalEntriesAsync(List<JournalEntry> entries, Guid organizationId, Guid currentUser)
    {
        if (entries.Count <= 1)
            return;

        SortJournalEntriesForDuplicateRetention(entries);
        var retained = entries[0];

        while (entries.Count > 1)
        {
            var duplicate = entries[^1];
            if (duplicate.PostingStatusId == PostingStatus.Open)
            {
                if (currentUser != Guid.Empty)
                    await ReconnectDuplicateJournalEntryLinksAsync(retained, duplicate, organizationId, currentUser);

                await DeleteOpenJournalEntryAsync(duplicate.JournalEntryId, organizationId);
            }

            entries.RemoveAt(entries.Count - 1);
        }
    }

    private async Task RemoveOrphanOpenAutoGeneratedJournalEntriesAsync(
        IEnumerable<JournalEntry> entries,
        IReadOnlyCollection<Guid> retainJournalEntryIds,
        Guid organizationId,
        Guid currentUser)
    {
        var entryList = entries.ToList();
        var retainedEntries = entryList
            .Where(entry => retainJournalEntryIds.Contains(entry.JournalEntryId))
            .ToList();

        foreach (var entry in entryList)
        {
            if (retainJournalEntryIds.Contains(entry.JournalEntryId))
                continue;

            if (entry.PostingStatusId != PostingStatus.Open)
                continue;

            var retained = retainedEntries.FirstOrDefault(candidate => candidate.JournalEntryKindId == entry.JournalEntryKindId)
                ?? retainedEntries.FirstOrDefault();

            if (retained != null && currentUser != Guid.Empty)
                await ReconnectDuplicateJournalEntryLinksAsync(retained, entry, organizationId, currentUser);

            await DeleteOpenJournalEntryAsync(entry.JournalEntryId, organizationId);
        }
    }
}
