using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Triggers
    public async Task<List<JournalEntry>> CreateJournalEntriesFromOwnerPaymentAsync(OwnerPayment ownerPayment, Guid currentUser)
    {
        var journalEntries = new List<JournalEntry>();
        if (ownerPayment.PaymentApplications.Count == 0)
            return journalEntries;

        foreach (var paymentApplication in ownerPayment.PaymentApplications)
        {
            var journalEntry = await CreateJournalEntryFromOwnerPaymentAsync(paymentApplication, currentUser);
            if (journalEntry != null)
                journalEntries.Add(journalEntry);
        }

        return journalEntries;
    }

    private async Task<JournalEntry?> CreateJournalEntryFromOwnerPaymentAsync(OwnerPaymentApplication paymentApplication, Guid currentUser)
        => (await CreateJournalEntryFromOwnerPaymentWithResultAsync(paymentApplication, currentUser)).JournalEntry;

    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromOwnerPaymentWithResultAsync(OwnerPaymentApplication paymentApplication, Guid currentUser)
    {
        if (paymentApplication.AmountApplied == 0)
            return AccountingJournalEntryResult.WarningResult("Owner payment amount cannot be zero");

        if (paymentApplication.PaymentDate == default)
            return AccountingJournalEntryResult.WarningResult("Payment date is required to create an owner payment journal entry");

        if (paymentApplication.ChartOfAccountId <= 0)
            return AccountingJournalEntryResult.WarningResult("Chart of account is required for owner payment");

        try
        {
            if (!await IsAccountingFeatureEnabledAsync(paymentApplication.OrganizationId))
                return AccountingJournalEntryResult.Success();

            var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(paymentApplication.OrganizationId, paymentApplication.OfficeId);
            var journalEntry = BuildJournalEntryFromOwnerPayment(paymentApplication, chartOfAccounts, accountingOffice, currentUser);
            var created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);
            return AccountingJournalEntryResult.Success(created);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "OwnerPayment",
                organizationId: paymentApplication.OrganizationId,
                officeId: paymentApplication.OfficeId,
                sourceTypeId: (int)SourceType.OwnerDistribution,
                sourceId: paymentApplication.PropertyId,
                documentCode: paymentApplication.PropertyCode,
                accountingPeriod: paymentApplication.PaymentDate == default ? null : FirstDayOfMonth(paymentApplication.PaymentDate),
                amount: paymentApplication.AmountApplied,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }
    #endregion

    #region Journal Entry
    private JournalEntry BuildJournalEntryFromOwnerPayment(OwnerPaymentApplication paymentApplication, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // OWNER-PAYMENT-JE-ACCOUNTS
        // Line 1 — Debit: Owner Accounts Payable (GetDefaultOwnerAccountsPayable).
        // Line 2 — Credit: Bank account selected on the payment (paymentApplication.ChartOfAccountId).
        // END OWNER-PAYMENT-JE-ACCOUNTS

        var amount = paymentApplication.AmountApplied;
        var ownerAccountsPayableAccountId = GetDefaultOwnerAccountsPayable(chartOfAccounts, paymentApplication.OfficeId, accountingOffice);
        var paymentBankAccountId = paymentApplication.ChartOfAccountId;
        var memo = BuildOwnerStatementPaymentMemo(paymentApplication.PropertyCode, paymentApplication.Description);
        var lineContext = new JournalEntryLineContext(
            paymentApplication.PropertyId,
            paymentApplication.PropertyCode,
            null,
            null,
            paymentApplication.OwnerId,
            paymentApplication.OwnerName);
        var ownerPayableLine = new JournalEntryLine
        {
            ChartOfAccountId = ownerAccountsPayableAccountId,
            Debit = amount > 0 ? amount : 0,
            Credit = amount < 0 ? Math.Abs(amount) : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(ownerPayableLine, lineContext);
        var paymentLine = new JournalEntryLine
        {
            ChartOfAccountId = paymentBankAccountId,
            Debit = amount < 0 ? Math.Abs(amount) : 0,
            Credit = amount > 0 ? amount : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(paymentLine, lineContext);

        return ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = paymentApplication.OrganizationId,
            OfficeId = paymentApplication.OfficeId,
            TransactionDate = paymentApplication.PaymentDate,
            AccountingPeriod = FirstDayOfMonth(paymentApplication.PaymentDate),
            SourceTypeId = (int)SourceType.OwnerDistribution,
            SourceId = paymentApplication.PropertyId,
            SourceCode = paymentApplication.PropertyCode,
            Memo = memo,
            JournalEntryLines = new List<JournalEntryLine> { ownerPayableLine, paymentLine },
            CreatedBy = currentUser
        }, JournalEntryKind.BillPayment, Perspective.Owner);
    }

    private static string BuildOwnerStatementPaymentMemo(string propertyCode, string paymentReference)
    {
        if (string.IsNullOrWhiteSpace(propertyCode))
            throw new ArgumentException("Property code is required.", nameof(propertyCode));
        if (string.IsNullOrWhiteSpace(paymentReference))
            throw new ArgumentException("Payment reference is required.", nameof(paymentReference));

        return $"{propertyCode.Trim()}: Owner: Payment: {paymentReference.Trim()}";
    }
    #endregion
}
