using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    private async Task PersistReceiptJournalEntryIdIfChangedAsync(Receipt receipt, Guid? journalEntryId, Guid currentUser)
    {
        if (receipt.JournalEntryId == journalEntryId)
            return;

        receipt.JournalEntryId = journalEntryId;
        receipt.ModifiedBy = currentUser;
        await _maintenanceRepository.UpdateReceiptAsync(receipt);
    }

    private async Task PersistWorkOrderJournalEntryIdIfChangedAsync(WorkOrder workOrder, Guid? journalEntryId, Guid currentUser)
    {
        if (workOrder.JournalEntryId == journalEntryId)
            return;

        workOrder.JournalEntryId = journalEntryId;
        workOrder.ModifiedBy = currentUser;
        await _maintenanceRepository.UpdateWorkOrderAsync(workOrder);
    }

    private async Task PersistInvoiceJournalEntryIdIfChangedAsync(Invoice invoice, Guid? journalEntryId, Guid currentUser)
    {
        if (invoice.JournalEntryId == journalEntryId)
            return;

        invoice.JournalEntryId = journalEntryId;
        invoice.ModifiedBy = currentUser;
        await _accountingRepository.UpdateInvoiceJournalEntryIdAsync(invoice);
    }

    private async Task<List<JournalEntry>> GetJournalEntriesForSourceAsync(
        Guid organizationId,
        int officeId,
        SourceType sourceType,
        Guid sourceId)
    {
        return (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = organizationId,
            OfficeIds = officeId.ToString(),
            SourceTypeId = (int)sourceType,
            SourceId = sourceId,
            IncludeVoided = true,
            IncludeUnposted = true
        })).ToList();
    }

    private static void AssignRebuiltJournalEntryFromExisting(JournalEntry rebuilt, JournalEntry existing, Guid currentUser)
    {
        rebuilt.JournalEntryId = existing.JournalEntryId;
        rebuilt.OrganizationId = existing.OrganizationId;
        rebuilt.OfficeId = existing.OfficeId;
        rebuilt.CreatedBy = existing.CreatedBy;
        rebuilt.ModifiedBy = currentUser;

        foreach (var line in rebuilt.JournalEntryLines)
        {
            line.JournalEntryId = existing.JournalEntryId;
            line.JournalEntryLineId = Guid.Empty;
        }
    }

    private async Task<JournalEntry?> UpsertAutoGeneratedJournalEntryAsync(
        JournalEntry rebuiltJournalEntry,
        IReadOnlyList<JournalEntry> existingEntries,
        Guid currentUser,
        Guid organizationId)
    {
        var candidates = existingEntries.ToList();

        while (candidates.Count > 1)
        {
            await DeleteJournalEntryAsync(candidates[^1].JournalEntryId, organizationId);
            candidates.RemoveAt(candidates.Count - 1);
        }

        var existingEntry = candidates.FirstOrDefault();
        if (existingEntry != null)
        {
            AssignRebuiltJournalEntryFromExisting(rebuiltJournalEntry, existingEntry, currentUser);
            return await UpdateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
        }

        return await CreateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
    }

    private async Task DeleteJournalEntriesExceptAsync(
        IEnumerable<JournalEntry> entries,
        IReadOnlyCollection<Guid> retainJournalEntryIds,
        Guid organizationId)
    {
        foreach (var entry in entries)
        {
            if (!retainJournalEntryIds.Contains(entry.JournalEntryId))
                await DeleteJournalEntryAsync(entry.JournalEntryId, organizationId);
        }
    }

    private static (JournalEntry? Main, JournalEntry? OwnerUtility) ClassifyBillJournalEntries(
        IReadOnlyList<JournalEntry> entries,
        int ownerAccountsPayableAccountId,
        int pmUtilityIncomeAccountId)
    {
        JournalEntry? main = null;
        JournalEntry? ownerUtility = null;

        foreach (var entry in entries)
        {
            var accountIds = entry.JournalEntryLines
                .Select(line => line.ChartOfAccountId)
                .Where(accountId => accountId > 0)
                .ToHashSet();

            if (accountIds.Contains(ownerAccountsPayableAccountId) && accountIds.Contains(pmUtilityIncomeAccountId))
                ownerUtility = entry;
            else
                main ??= entry;
        }

        return (main, ownerUtility);
    }

    private static bool IsInvoiceChargeJournalEntry(JournalEntry entry, int accountsReceivableAccountId)
    {
        if (entry.SourceTypeId != (int)SourceType.Invoice)
            return false;

        if (IsInvoiceOwnerShareJournalEntry(entry))
            return false;

        return entry.JournalEntryLines.Any(line => line.ChartOfAccountId == accountsReceivableAccountId);
    }

    private static bool IsInvoiceOwnerShareJournalEntry(JournalEntry entry)
        => MatchOwnerExpectedRentMemo(entry.Memo).Category != JournalEntryMemoCategory.None;

    private static bool IsStandardInvoicePaymentJournalEntry(JournalEntry entry)
        => entry.SourceTypeId == (int)SourceType.InvoicePayment && !entry.IsCashOnly;

    private static bool IsInvoiceOwnerActualPaymentJournalEntry(JournalEntry entry)
        => entry.SourceTypeId == (int)SourceType.InvoicePayment && entry.IsCashOnly;

    private static bool IsInvoicePrePaymentReceivedJournalEntry(JournalEntry entry, int prePaymentAccountId)
        => entry.SourceTypeId == (int)SourceType.InvoicePayment
           && entry.JournalEntryLines.Any(line => line.ChartOfAccountId == prePaymentAccountId);

    private static bool IsInvoicePrePaymentApplyJournalEntry(JournalEntry entry, int prePaymentAccountId)
        => entry.SourceTypeId == (int)SourceType.Invoice
           && entry.JournalEntryLines.Any(line => line.ChartOfAccountId == prePaymentAccountId);
}
