using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Types

    private readonly struct PaymentWaterfallApplication
    {
        public PaymentWaterfallApplication(decimal securityDepositApplied, decimal rentApplied, decimal securityDepositWaiverApplied, decimal feesApplied)
        {
            SecurityDepositApplied = securityDepositApplied;
            RentApplied = rentApplied;
            SecurityDepositWaiverApplied = securityDepositWaiverApplied;
            FeesApplied = feesApplied;
        }

        public decimal SecurityDepositApplied { get; }
        public decimal RentApplied { get; }
        public decimal SecurityDepositWaiverApplied { get; }
        public decimal FeesApplied { get; }

        public static PaymentWaterfallApplication Zero { get; } = new(0m, 0m, 0m, 0m);
    }

    #endregion

    #region Upsert Payment Escrow Actual Journal Entries

    private async Task TryCreateInvoicePaymentEscrowActualJournalEntriesForPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, decimal paymentAmount, DateOnly transactionDate, Guid currentUser)
    {
        if (paymentAmount == 0 || paymentLedgerLine.LedgerLineId == Guid.Empty)
            return;

        await TryCreateSecurityDepositActualJournalEntryForPaymentAsync(invoice, paymentLedgerLine, paymentAmount, transactionDate, currentUser);
        await TryCreateSecurityDepositWaiverActualJournalEntryForPaymentAsync(invoice, paymentLedgerLine, paymentAmount, transactionDate, currentUser);
        await TryCreateFeesActualJournalEntryForPaymentAsync(invoice, paymentLedgerLine, paymentAmount, transactionDate, currentUser);
    }

    private async Task TryCreateSecurityDepositActualJournalEntryForPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, decimal paymentAmount, DateOnly transactionDate, Guid currentUser)
    {
        try
        {
            var journalEntry = await BuildJournalEntryFromPaymentForSecurityDepositActualAsync(invoice, paymentLedgerLine, paymentAmount, transactionDate, currentUser);
            if (journalEntry == null || !journalEntry.JournalEntryLines.Any(line => line.Debit != 0 || line.Credit != 0))
                return;

            await CreateAutoGeneratedJournalEntryAsync(journalEntry);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "InvoiceSecurityDepositActual",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.InvoicePayment,
                sourceId: paymentLedgerLine.LedgerLineId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: paymentAmount,
                message: ex.Message,
                currentUser: currentUser);
        }
    }

    private async Task TryCreateSecurityDepositWaiverActualJournalEntryForPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, decimal paymentAmount, DateOnly transactionDate, Guid currentUser)
    {
        try
        {
            var journalEntry = await BuildJournalEntryFromPaymentForSecurityDepositWaiverActualAsync(invoice, paymentLedgerLine, paymentAmount, transactionDate, currentUser);
            if (journalEntry == null || !journalEntry.JournalEntryLines.Any(line => line.Debit != 0 || line.Credit != 0))
                return;

            await CreateAutoGeneratedJournalEntryAsync(journalEntry);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "InvoiceSecurityDepositWaiverActual",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.InvoicePayment,
                sourceId: paymentLedgerLine.LedgerLineId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: paymentAmount,
                message: ex.Message,
                currentUser: currentUser);
        }
    }

    private async Task TryCreateFeesActualJournalEntryForPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, decimal paymentAmount, DateOnly transactionDate, Guid currentUser)
    {
        try
        {
            var journalEntry = await BuildJournalEntryFromPaymentForFeesActualAsync(invoice, paymentLedgerLine, transactionDate, workingEntries: null, currentUser);
            if (journalEntry == null || !journalEntry.JournalEntryLines.Any(line => line.Debit != 0 || line.Credit != 0))
                return;

            await CreateAutoGeneratedJournalEntryAsync(journalEntry);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "InvoiceFeesActual",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.InvoicePayment,
                sourceId: paymentLedgerLine.LedgerLineId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: paymentAmount,
                message: ex.Message,
                currentUser: currentUser);
        }
    }

    private async Task UpsertInvoicePaymentEscrowActualJournalEntriesForPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, decimal paymentAmount, DateOnly transactionDate, List<JournalEntry> workingEntries, ISet<Guid> retainedEntryIds, Guid currentUser, Invoice? paymentSourceInvoice = null)
    {
        await UpsertSecurityDepositActualJournalEntryForPaymentAsync(invoice, paymentLedgerLine, paymentAmount, transactionDate, workingEntries, retainedEntryIds, currentUser, paymentSourceInvoice);
        await UpsertSecurityDepositWaiverActualJournalEntryForPaymentAsync(invoice, paymentLedgerLine, paymentAmount, transactionDate, workingEntries, retainedEntryIds, currentUser, paymentSourceInvoice);
        await UpsertFeesActualJournalEntryForPaymentAsync(invoice, paymentLedgerLine, paymentAmount, transactionDate, workingEntries, retainedEntryIds, currentUser, paymentSourceInvoice);
    }

    private async Task UpsertSecurityDepositActualJournalEntryForPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, decimal paymentAmount, DateOnly transactionDate, List<JournalEntry> workingEntries, ISet<Guid> retainedEntryIds, Guid currentUser, Invoice? paymentSourceInvoice = null)
    {
        if (paymentAmount == 0 || paymentLedgerLine.LedgerLineId == Guid.Empty)
            return;

        try
        {
            var journalEntry = await BuildJournalEntryFromPaymentForSecurityDepositActualAsync(invoice, paymentLedgerLine, paymentAmount, transactionDate, currentUser, paymentSourceInvoice);
            if (journalEntry == null || !journalEntry.JournalEntryLines.Any(line => line.Debit != 0 || line.Credit != 0))
                return;

            await UpsertClaimedAutoGeneratedJournalEntryAsync(
                journalEntry,
                workingEntries,
                entry => IsInvoiceSecurityDepositActualPaymentJournalEntry(entry, invoice, paymentLedgerLine)
                    && MatchesJournalEntryAccountingPeriod(entry, invoice.AccountingPeriod),
                retainedEntryIds,
                currentUser,
                invoice.OrganizationId);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "InvoiceSecurityDepositActual",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.InvoicePayment,
                sourceId: paymentLedgerLine.LedgerLineId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: paymentAmount,
                message: ex.Message,
                currentUser: currentUser);
        }
    }

    private async Task UpsertSecurityDepositWaiverActualJournalEntryForPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, decimal paymentAmount, DateOnly transactionDate, List<JournalEntry> workingEntries, ISet<Guid> retainedEntryIds, Guid currentUser, Invoice? paymentSourceInvoice = null)
    {
        if (paymentAmount == 0 || paymentLedgerLine.LedgerLineId == Guid.Empty)
            return;

        try
        {
            var journalEntry = await BuildJournalEntryFromPaymentForSecurityDepositWaiverActualAsync(invoice, paymentLedgerLine, paymentAmount, transactionDate, currentUser, paymentSourceInvoice);
            if (journalEntry == null || !journalEntry.JournalEntryLines.Any(line => line.Debit != 0 || line.Credit != 0))
                return;

            await UpsertClaimedAutoGeneratedJournalEntryAsync(
                journalEntry,
                workingEntries,
                entry => IsInvoiceSecurityDepositWaiverActualPaymentJournalEntry(entry, invoice, paymentLedgerLine)
                    && MatchesJournalEntryAccountingPeriod(entry, invoice.AccountingPeriod),
                retainedEntryIds,
                currentUser,
                invoice.OrganizationId);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "InvoiceSecurityDepositWaiverActual",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.InvoicePayment,
                sourceId: paymentLedgerLine.LedgerLineId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: paymentAmount,
                message: ex.Message,
                currentUser: currentUser);
        }
    }

    private async Task UpsertFeesActualJournalEntryForPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, decimal paymentAmount, DateOnly transactionDate, List<JournalEntry> workingEntries, ISet<Guid> retainedEntryIds, Guid currentUser, Invoice? paymentSourceInvoice = null)
    {
        if (paymentAmount == 0 || paymentLedgerLine.LedgerLineId == Guid.Empty)
            return;

        try
        {
            var journalEntry = await BuildJournalEntryFromPaymentForFeesActualAsync(
                invoice,
                paymentLedgerLine,
                transactionDate,
                workingEntries,
                currentUser,
                paymentSourceInvoice);
            if (journalEntry == null || !journalEntry.JournalEntryLines.Any(line => line.Debit != 0 || line.Credit != 0))
                return;

            await UpsertClaimedAutoGeneratedJournalEntryAsync(
                journalEntry,
                workingEntries,
                entry => IsInvoiceFeesActualPaymentJournalEntry(entry, invoice, paymentLedgerLine),
                retainedEntryIds,
                currentUser,
                invoice.OrganizationId);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "InvoiceFeesActual",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.InvoicePayment,
                sourceId: paymentLedgerLine.LedgerLineId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: paymentAmount,
                message: ex.Message,
                currentUser: currentUser);
        }
    }

    #endregion

    #region Build Payment Escrow Actual Journal Entries

    private async Task<JournalEntry?> BuildJournalEntryFromPaymentForSecurityDepositActualAsync(Invoice invoice, LedgerLine paymentLedgerLine, decimal paymentAmount, DateOnly transactionDate, Guid currentUser, Invoice? paymentSourceInvoice = null)
    {
        var allocationInvoice = await ResolveInvoiceForOwnerShareAsync(invoice);
        var costCodeById = await LoadCostCodeByOfficeIdAsync(allocationInvoice.OrganizationId, allocationInvoice.OfficeId);
        if (!TryGetInvoiceLedgerLineByTransactionType(allocationInvoice, TransactionType.SecurityDeposit, costCodeById, out var securityDepositLine))
            return null;

        var appliedAmount = await CalculateSecurityDepositAppliedForInvoicePaymentAsync(allocationInvoice, paymentSourceInvoice ?? invoice, paymentLedgerLine, paymentAmount, costCodeById);
        if (!appliedAmount.HasValue || appliedAmount.Value == 0)
            return null;

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);
        var lineContext = await ResolveInvoiceJournalEntryLineContextAsync(invoice, securityDepositLine);
        var memo = BuildSecurityDepositActualMemo(invoice, securityDepositLine, paymentLedgerLine);
        var journalEntryLines = BuildJournalEntryLinesForSecurityDepositActual(
            invoice,
            securityDepositLine,
            appliedAmount.Value,
            chartOfAccounts,
            accountingOffice,
            costCodeById,
            lineContext,
            memo,
            currentUser);
        if (journalEntryLines.Count == 0)
            return null;

        var journalEntry = ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = transactionDate,
            AccountingPeriod = invoice.AccountingPeriod != default
                ? invoice.AccountingPeriod
                : FirstDayOfMonth(transactionDate),
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = invoice.InvoiceId,
            SourceCode = ResolveJournalEntrySourceCodeFromInvoice(invoice),
            Memo = memo,
            IsCashOnly = true,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        }, JournalEntryKind.SecurityDepositActual, Perspective.Company);

        await ApplyPaymentDocumentLinkAsync(journalEntry, paymentLedgerLine, invoice.OrganizationId);
        return journalEntry;
    }

    private async Task<JournalEntry?> BuildJournalEntryFromPaymentForSecurityDepositWaiverActualAsync(Invoice invoice, LedgerLine paymentLedgerLine, decimal paymentAmount, DateOnly transactionDate, Guid currentUser, Invoice? paymentSourceInvoice = null)
    {
        var allocationInvoice = await ResolveInvoiceForOwnerShareAsync(invoice);
        var costCodeById = await LoadCostCodeByOfficeIdAsync(allocationInvoice.OrganizationId, allocationInvoice.OfficeId);
        if (!TryGetInvoiceLedgerLineByTransactionType(allocationInvoice, TransactionType.SecurityDepositWaiver, costCodeById, out var securityDepositWaiverLine))
            return null;

        var appliedAmount = await CalculateSecurityDepositWaiverAppliedForInvoicePaymentAsync(allocationInvoice, paymentSourceInvoice ?? invoice, paymentLedgerLine, paymentAmount, costCodeById);
        if (!appliedAmount.HasValue || appliedAmount.Value == 0)
            return null;

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);
        var lineContext = await ResolveInvoiceJournalEntryLineContextAsync(invoice, securityDepositWaiverLine);
        var memo = BuildSecurityDepositWaiverActualMemo(invoice, securityDepositWaiverLine, paymentLedgerLine);
        var journalEntryLines = BuildJournalEntryLinesForSecurityDepositWaiverActual(
            invoice,
            securityDepositWaiverLine,
            appliedAmount.Value,
            chartOfAccounts,
            accountingOffice,
            costCodeById,
            lineContext,
            memo,
            currentUser);
        if (journalEntryLines.Count == 0)
            return null;

        var journalEntry = ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = transactionDate,
            AccountingPeriod = invoice.AccountingPeriod != default
                ? invoice.AccountingPeriod
                : FirstDayOfMonth(transactionDate),
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = invoice.InvoiceId,
            SourceCode = ResolveJournalEntrySourceCodeFromInvoice(invoice),
            Memo = memo,
            IsCashOnly = true,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        }, JournalEntryKind.SecurityDepositWaiverActual, Perspective.Company);

        await ApplyPaymentDocumentLinkAsync(journalEntry, paymentLedgerLine, invoice.OrganizationId);
        return journalEntry;
    }

    private async Task<JournalEntry?> BuildJournalEntryFromPaymentForFeesActualAsync(Invoice invoice, LedgerLine paymentLedgerLine, DateOnly transactionDate, IReadOnlyList<JournalEntry>? workingEntries, Guid currentUser, Invoice? paymentSourceInvoice = null)
    {
        var waterfallInvoice = paymentSourceInvoice ?? invoice;
        var costCodeById = await LoadCostCodeByOfficeIdAsync(waterfallInvoice.OrganizationId, waterfallInvoice.OfficeId);
        var appliedAmount = await CalculateFeesAppliedForInvoicePaymentAsync(waterfallInvoice, paymentLedgerLine, costCodeById, workingEntries);
        if (!appliedAmount.HasValue || appliedAmount.Value == 0)
            return null;

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);
        costCodeById.TryGetValue(paymentLedgerLine.CostCodeId, out var paymentCostCode);
        var lineContext = await ResolveInvoiceJournalEntryLineContextAsync(invoice, paymentLedgerLine);
        var memo = BuildFeesActualMemo(invoice, paymentLedgerLine);
        var journalEntryLines = BuildJournalEntryLinesForFeesActual(
            invoice,
            paymentLedgerLine,
            appliedAmount.Value,
            chartOfAccounts,
            accountingOffice,
            paymentCostCode,
            lineContext,
            memo,
            currentUser);
        if (journalEntryLines.Count == 0)
            return null;

        var journalEntry = ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = transactionDate,
            AccountingPeriod = invoice.AccountingPeriod != default
                ? invoice.AccountingPeriod
                : FirstDayOfMonth(transactionDate),
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = invoice.InvoiceId,
            SourceCode = ResolveJournalEntrySourceCodeFromInvoice(invoice),
            Memo = memo,
            IsCashOnly = true,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        }, JournalEntryKind.FeesActual, Perspective.Company);

        await ApplyPaymentDocumentLinkAsync(journalEntry, paymentLedgerLine, invoice.OrganizationId);
        return journalEntry;
    }

    private List<JournalEntryLine> BuildJournalEntryLinesForSecurityDepositActual(Invoice invoice, LedgerLine securityDepositLine, decimal actualAmount, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, IReadOnlyDictionary<int, CostCode> costCodeById, JournalEntryLineContext lineContext, string memo, Guid currentUser)
    {
        costCodeById.TryGetValue(securityDepositLine.CostCodeId, out var costCode);
        var tenantIncomeAccountId = GetDefaultTenantIncome(chartOfAccounts, invoice.OfficeId, accountingOffice, costCode);
        var escrowSecurityDepositAccountId = GetDefaultEscrowSecurityDepositAccount(chartOfAccounts, invoice.OfficeId, accountingOffice);
        if (tenantIncomeAccountId <= 0 || escrowSecurityDepositAccountId <= 0)
            return [];

        var tenantIncomeLine = new JournalEntryLine
        {
            ChartOfAccountId = tenantIncomeAccountId,
            CostCodeId = securityDepositLine.CostCodeId,
            Debit = actualAmount > 0 ? actualAmount : 0,
            Credit = actualAmount < 0 ? Math.Abs(actualAmount) : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(tenantIncomeLine, lineContext);

        var escrowLine = new JournalEntryLine
        {
            ChartOfAccountId = escrowSecurityDepositAccountId,
            CostCodeId = securityDepositLine.CostCodeId,
            Debit = actualAmount < 0 ? Math.Abs(actualAmount) : 0,
            Credit = actualAmount > 0 ? actualAmount : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(escrowLine, lineContext);

        return [tenantIncomeLine, escrowLine];
    }

    private List<JournalEntryLine> BuildJournalEntryLinesForSecurityDepositWaiverActual(Invoice invoice, LedgerLine securityDepositWaiverLine, decimal actualAmount, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, IReadOnlyDictionary<int, CostCode> costCodeById, JournalEntryLineContext lineContext, string memo, Guid currentUser)
    {
        costCodeById.TryGetValue(securityDepositWaiverLine.CostCodeId, out var costCode);
        var tenantIncomeAccountId = GetDefaultTenantIncome(chartOfAccounts, invoice.OfficeId, accountingOffice, costCode);
        var escrowSdwAccountId = GetDefaultEscrowSdwAccount(chartOfAccounts, invoice.OfficeId, accountingOffice);
        if (tenantIncomeAccountId <= 0 || escrowSdwAccountId <= 0)
            return [];

        var tenantIncomeLine = new JournalEntryLine
        {
            ChartOfAccountId = tenantIncomeAccountId,
            CostCodeId = securityDepositWaiverLine.CostCodeId,
            Debit = actualAmount > 0 ? actualAmount : 0,
            Credit = actualAmount < 0 ? Math.Abs(actualAmount) : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(tenantIncomeLine, lineContext);

        var escrowLine = new JournalEntryLine
        {
            ChartOfAccountId = escrowSdwAccountId,
            CostCodeId = securityDepositWaiverLine.CostCodeId,
            Debit = actualAmount < 0 ? Math.Abs(actualAmount) : 0,
            Credit = actualAmount > 0 ? actualAmount : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(escrowLine, lineContext);

        return [tenantIncomeLine, escrowLine];
    }

    private List<JournalEntryLine> BuildJournalEntryLinesForFeesActual(Invoice invoice, LedgerLine paymentLedgerLine, decimal actualAmount, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, CostCode? paymentCostCode, JournalEntryLineContext lineContext, string memo, Guid currentUser)
    {
        var tenantIncomeAccountId = GetDefaultTenantIncome(chartOfAccounts, invoice.OfficeId, accountingOffice, paymentCostCode);
        var escrowDepositAccountId = GetDefaultEscrowDepositAccount(chartOfAccounts, invoice.OfficeId, accountingOffice);
        if (tenantIncomeAccountId <= 0 || escrowDepositAccountId <= 0)
            return [];

        var tenantIncomeLine = new JournalEntryLine
        {
            ChartOfAccountId = tenantIncomeAccountId,
            CostCodeId = paymentLedgerLine.CostCodeId,
            Debit = actualAmount > 0 ? actualAmount : 0,
            Credit = actualAmount < 0 ? Math.Abs(actualAmount) : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(tenantIncomeLine, lineContext);

        var escrowLine = new JournalEntryLine
        {
            ChartOfAccountId = escrowDepositAccountId,
            CostCodeId = paymentLedgerLine.CostCodeId,
            Debit = actualAmount < 0 ? Math.Abs(actualAmount) : 0,
            Credit = actualAmount > 0 ? actualAmount : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(escrowLine, lineContext);

        return [tenantIncomeLine, escrowLine];
    }

    #endregion

    #region Payment Waterfall Application

    private async Task<decimal?> CalculateSecurityDepositAppliedForInvoicePaymentAsync(Invoice allocationInvoice, Invoice paymentSourceInvoice, LedgerLine paymentLedgerLine, decimal paymentAmount, IReadOnlyDictionary<int, CostCode> costCodeById)
    {
        var application = await CalculatePaymentWaterfallApplicationForInvoicePaymentAsync(allocationInvoice, paymentSourceInvoice, paymentLedgerLine, paymentAmount, costCodeById);
        return application.SecurityDepositApplied == 0 ? null : application.SecurityDepositApplied;
    }

    private async Task<decimal?> CalculateSecurityDepositWaiverAppliedForInvoicePaymentAsync(Invoice allocationInvoice, Invoice paymentSourceInvoice, LedgerLine paymentLedgerLine, decimal paymentAmount, IReadOnlyDictionary<int, CostCode> costCodeById)
    {
        var application = await CalculatePaymentWaterfallApplicationForInvoicePaymentAsync(allocationInvoice, paymentSourceInvoice, paymentLedgerLine, paymentAmount, costCodeById);
        return application.SecurityDepositWaiverApplied == 0 ? null : application.SecurityDepositWaiverApplied;
    }

    private async Task<decimal?> CalculateFeesAppliedForInvoicePaymentAsync(Invoice waterfallInvoice, LedgerLine paymentLedgerLine, IReadOnlyDictionary<int, CostCode> costCodeById, IReadOnlyList<JournalEntry>? workingEntries = null)
    {
        if (paymentLedgerLine.LedgerLineId == Guid.Empty)
            return null;

        var orderedPayments = GetOrderedInvoicePaymentLines(waterfallInvoice, costCodeById);
        if (orderedPayments.All(payment => payment.LedgerLineId != paymentLedgerLine.LedgerLineId))
            orderedPayments = [.. orderedPayments, paymentLedgerLine];

        if (orderedPayments.Count == 0)
            return null;

        var securityDepositDue = await GetInvoiceSecurityDepositBaseAsync(waterfallInvoice);
        var sdwDue = await GetInvoiceSecurityDepositWaiverBaseAsync(waterfallInvoice);
        var rentDue = await GetInvoiceRentPlus4000BaseAsync(waterfallInvoice);
        var feesDue = await GetInvoiceFeesBaseAsync(waterfallInvoice);
        if (feesDue == 0)
            return null;

        var cumulativeFeesApplied = CalculateCumulativeFeesPaidThroughWaterfall(
            securityDepositDue,
            rentDue,
            sdwDue,
            feesDue,
            orderedPayments,
            paymentLedgerLine.LedgerLineId);
        if (cumulativeFeesApplied <= 0)
            return null;

        var priorFeesActual = await SumPriorFeesActualAmountAsync(waterfallInvoice, paymentLedgerLine, workingEntries);
        var incrementalFeesActual = RoundCurrency(cumulativeFeesApplied - priorFeesActual);
        return incrementalFeesActual > 0 ? incrementalFeesActual : null;
    }

    private async Task<decimal> SumPriorFeesActualAmountAsync(Invoice invoice, LedgerLine currentPaymentLedgerLine, IReadOnlyList<JournalEntry>? workingEntries)
    {
        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);
        var escrowDepositAccountId = GetDefaultEscrowDepositAccount(chartOfAccounts, invoice.OfficeId, accountingOffice);

        var dbEntries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = invoice.OrganizationId,
            OfficeIds = invoice.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = invoice.InvoiceId,
            IncludeUnposted = true
        })).ToList();

        var entries = (workingEntries ?? [])
            .Where(entry => entry.JournalEntryKindId == JournalEntryKind.FeesActual && entry.SourceId == invoice.InvoiceId)
            .Concat(dbEntries.Where(entry => entry.JournalEntryKindId == JournalEntryKind.FeesActual))
            .GroupBy(entry => entry.JournalEntryId)
            .Select(group => group.First())
            .ToList();

        return entries.Sum(entry => entry.JournalEntryLines
            .Where(line => line.ChartOfAccountId == escrowDepositAccountId)
            .Sum(line => line.Credit - line.Debit));
    }

    private static decimal CalculateCumulativeFeesPaidThroughWaterfall(decimal securityDepositDue, decimal rentDue, decimal sdwDue, decimal feesDue, IReadOnlyList<LedgerLine> orderedPayments, Guid throughPaymentLedgerLineId)
    {
        var securityDepositRemaining = securityDepositDue;
        var rentRemaining = rentDue;
        var sdwRemaining = sdwDue;
        var feesRemaining = feesDue;
        var cumulativeFeesApplied = 0m;

        foreach (var payment in orderedPayments)
        {
            var paymentRemaining = payment.Amount;

            var applySecurityDeposit = Math.Min(Math.Max(paymentRemaining, 0m), securityDepositRemaining);
            securityDepositRemaining -= applySecurityDeposit;
            paymentRemaining -= applySecurityDeposit;

            var applyRent = Math.Min(Math.Max(paymentRemaining, 0m), rentRemaining);
            rentRemaining -= applyRent;
            paymentRemaining -= applyRent;

            var applySdw = Math.Min(Math.Max(paymentRemaining, 0m), sdwRemaining);
            sdwRemaining -= applySdw;
            paymentRemaining -= applySdw;

            var applyFees = Math.Min(Math.Max(paymentRemaining, 0m), feesRemaining);
            feesRemaining -= applyFees;
            cumulativeFeesApplied += applyFees;

            if (payment.LedgerLineId == throughPaymentLedgerLineId)
                break;
        }

        return RoundCurrency(cumulativeFeesApplied);
    }

    private async Task<PaymentWaterfallApplication> CalculatePaymentWaterfallApplicationForInvoicePaymentAsync(Invoice allocationInvoice, Invoice paymentSourceInvoice, LedgerLine paymentLedgerLine, decimal paymentAmount, IReadOnlyDictionary<int, CostCode> costCodeById)
    {
        if (paymentAmount == 0 || paymentLedgerLine.LedgerLineId == Guid.Empty)
            return PaymentWaterfallApplication.Zero;

        var securityDepositDue = await GetInvoiceSecurityDepositBaseAsync(allocationInvoice);
        var sdwDue = await GetInvoiceSecurityDepositWaiverBaseAsync(allocationInvoice);
        var rentDue = await GetInvoiceRentPlus4000BaseAsync(allocationInvoice);
        var feesDue = await GetInvoiceFeesBaseAsync(allocationInvoice);
        var orderedPayments = await ResolveOrderedPaymentsForOwnerActualAsync(
            allocationInvoice,
            paymentSourceInvoice,
            paymentLedgerLine,
            paymentAmount,
            costCodeById);
        if (orderedPayments.Count == 0)
            return PaymentWaterfallApplication.Zero;

        return CalculatePaymentWaterfallApplicationForLedgerLine(
            securityDepositDue,
            rentDue,
            sdwDue,
            feesDue,
            orderedPayments,
            paymentLedgerLine.LedgerLineId);
    }

    private static PaymentWaterfallApplication CalculatePaymentWaterfallApplicationForLedgerLine(decimal securityDepositDue, decimal rentDue, decimal sdwDue, decimal feesDue, IReadOnlyList<LedgerLine> orderedPayments, Guid paymentLedgerLineId)
    {
        var securityDepositRemaining = securityDepositDue;
        var rentRemaining = rentDue;
        var sdwRemaining = sdwDue;
        var feesRemaining = feesDue;

        foreach (var payment in orderedPayments)
        {
            var paymentRemaining = payment.Amount;

            var applySecurityDeposit = Math.Min(Math.Max(paymentRemaining, 0m), securityDepositRemaining);
            securityDepositRemaining -= applySecurityDeposit;
            paymentRemaining -= applySecurityDeposit;

            var applyRent = Math.Min(Math.Max(paymentRemaining, 0m), rentRemaining);
            rentRemaining -= applyRent;
            paymentRemaining -= applyRent;

            var applySdw = Math.Min(Math.Max(paymentRemaining, 0m), sdwRemaining);
            sdwRemaining -= applySdw;
            paymentRemaining -= applySdw;

            var applyFees = Math.Min(Math.Max(paymentRemaining, 0m), feesRemaining);
            feesRemaining -= applyFees;

            if (payment.LedgerLineId == paymentLedgerLineId)
            {
                return new PaymentWaterfallApplication(
                    RoundCurrency(applySecurityDeposit),
                    RoundCurrency(applyRent),
                    RoundCurrency(applySdw),
                    RoundCurrency(applyFees));
            }
        }

        return PaymentWaterfallApplication.Zero;
    }

    private static bool TryGetInvoiceLedgerLineByTransactionType(Invoice invoice, TransactionType transactionType, IReadOnlyDictionary<int, CostCode> costCodeById, out LedgerLine ledgerLine)
    {
        ledgerLine = null!;
        var match = invoice.LedgerLines
            .Where(line => line.Amount != 0)
            .FirstOrDefault(line =>
            {
                costCodeById.TryGetValue(line.CostCodeId, out var costCode);
                return costCode?.TransactionType == transactionType;
            });

        if (match == null)
            return false;

        ledgerLine = match;
        return true;
    }

    #endregion
}
