using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Triggers
    public async Task<JournalEntry?> CreateJournalEntryFromReceiptAsync(Receipt receipt, Guid currentUser)
        => (await CreateJournalEntryFromReceiptWithResultAsync(receipt, currentUser)).JournalEntry;

    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromReceiptWithResultAsync(Receipt receipt, Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(receipt.OrganizationId))
            return AccountingJournalEntryResult.Success();

        try
        {
            EnsureReceiptIsCardReceipt(receipt);
            receipt = await LoadReceiptWithSplitsAsync(receipt);

            var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(receipt.OrganizationId, receipt.OfficeId);
            var created = await CreateReceiptJournalEntriesAsync(receipt, chartOfAccounts, accountingOffice, currentUser);
            return AccountingJournalEntryResult.Success(created);
        }
        catch (Exception ex)
        {
            var receiptLabel = receipt.ReceiptCode.Trim();
            await LogAccountingErrorAsync(
                trigger: "Receipt",
                organizationId: receipt.OrganizationId,
                officeId: receipt.OfficeId,
                sourceTypeId: (int)SourceType.Receipt,
                sourceId: receipt.ReceiptId,
                documentCode: receiptLabel,
                accountingPeriod: receipt.AccountingPeriod == default ? null : receipt.AccountingPeriod,
                amount: receipt.Amount,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    private async Task<JournalEntry?> CreateReceiptJournalEntriesAsync(Receipt receipt, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        var bankCard = await ResolveReceiptBankCardAsync(receipt, accountingOffice);
        var receiptJournalEntry = await BuildJournalEntryFromReceiptAsync(receipt, chartOfAccounts, accountingOffice, currentUser);
        var created = await CreateAutoGeneratedJournalEntryAsync(receiptJournalEntry);

        // Sometimes people use the wrong office credit card, this uses JEs to correct that
        if (IsCrossOfficeBankCardReceipt(receipt, bankCard))
        {
            var (bankCardChartOfAccounts, bankCardAccountingOffice) = await LoadAccountContextAsync(receipt.OrganizationId, bankCard.OfficeId);
            var receiptOfficeVendorId = await ResolveInterOfficeVendorContactIdAsync(receipt.OrganizationId, bankCard.OfficeId, receipt.OfficeId);
            var receiptOfficeName = await GetOfficeNameAsync(receipt.OrganizationId, receipt.OfficeId);
            var defaultLineContext = await ResolveReceiptJournalEntryLineContextAsync(receipt);
            var companionEntry = BuildCrossOfficeBankCardLiabilityJournalEntryFromReceiptAsync(receipt, bankCard.OfficeId, bankCardChartOfAccounts, bankCardAccountingOffice, bankCard, receiptOfficeVendorId, receiptOfficeName, defaultLineContext, currentUser);
            await CreateAutoGeneratedJournalEntryAsync(companionEntry);
        }

        return created;
    }
    #endregion

    #region Journal Entry
    private async Task<JournalEntry> BuildJournalEntryFromReceiptAsync(Receipt receipt, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        EnsureReceiptIsCardReceipt(receipt);
        receipt = await LoadReceiptWithSplitsAsync(receipt);

        if (receipt.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required to create a journal entry for a receipt");

        if (receipt.ReceiptDate == default)
            throw new Exception("ReceiptDate is required to create a journal entry for a receipt");

        var bankCard = await ResolveReceiptBankCardAsync(receipt, accountingOffice);
        var defaultLineContext = await ResolveReceiptJournalEntryLineContextAsync(receipt);
        if (IsCrossOfficeBankCardReceipt(receipt, bankCard))
        {
            var bankCardOfficeVendorId = await ResolveInterOfficeVendorContactIdAsync(receipt.OrganizationId, receipt.OfficeId, bankCard.OfficeId);
            var bankCardOfficeName = await GetOfficeNameAsync(receipt.OrganizationId, bankCard.OfficeId);
            return BuildCrossOfficeBankCardJournalEntryFromReceiptAsync(receipt, chartOfAccounts, accountingOffice, bankCardOfficeVendorId, bankCardOfficeName, defaultLineContext, currentUser);
        }

        return BuildSameOfficeBankCardJournalEntryFromReceiptAsync(receipt, chartOfAccounts, accountingOffice, bankCard, defaultLineContext, currentUser);
    }

    private JournalEntry BuildSameOfficeBankCardJournalEntryFromReceiptAsync(Receipt receipt, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, BankCard bankCard, JournalEntryLineContext defaultLineContext, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // SAME-OFFICE-RECEIPT-JE-ACCOUNTS
        //   Line 1   — Credit: Credit card account on the bank card (BankCard.ChartOfAccountId).
        //   Lines 2+ — Debit: Expense account per split (GetDefaultTenantExpense, GetDefaultDepartureExpense,
        //               GetDefaultOwnerExpense, or GetDefaultCompanyExpense based on split receipt type).
        // END SAME-OFFICE-RECEIPT-JE-ACCOUNTS

        var splitLines = ResolveReceiptSplitLines(receipt);
        var creditCardAccountId = GetCreditCardAccountId(bankCard);
        var transactionDate = ResolveBillOrReceiptJournalEntryDate(receipt);
        var receiptCode = receipt.ReceiptCode.Trim();
        var bankCardDisplayName = receipt.BankCardDisplayName.Trim();
        var firstEligibleSplit = splitLines
            .Where(IsJournalEligibleReceiptSplit)
            .FirstOrDefault(split => !string.IsNullOrWhiteSpace(split.Description));
        var headerMemo = BuildReceiptHeaderMemo(receipt, firstEligibleSplit);
        var totalAmount = splitLines.Where(IsJournalEligibleReceiptSplit).Sum(s => s.Amount);
        var creditCardLine = new JournalEntryLine
        {
            ChartOfAccountId = creditCardAccountId,
            Debit = totalAmount < 0 ? Math.Abs(totalAmount) : 0,
            Credit = totalAmount > 0 ? totalAmount : 0,
            Memo = BuildReceiptBankCardMemo(receiptCode, bankCardDisplayName),
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(creditCardLine, defaultLineContext);
        var journalEntryLines = new List<JournalEntryLine> { creditCardLine };

        foreach (var split in splitLines)
        {
            if (!IsJournalEligibleReceiptSplit(split))
                continue;

            var expenseAccountId = GetBillReceiptExpenseAccountId(split, receipt.OfficeId, chartOfAccounts, accountingOffice);
            var splitMemo = BuildReceiptSplitLineMemo(receipt, split);
            var splitLine = new JournalEntryLine
            {
                ChartOfAccountId = expenseAccountId,
                Debit = split.Amount > 0 ? split.Amount : 0,
                Credit = split.Amount < 0 ? Math.Abs(split.Amount) : 0,
                Memo = splitMemo,
                CreatedBy = currentUser
            };
            ApplyJournalEntryLineContext(splitLine, CreateJournalEntryLineContextFromReceiptSplit(receipt, split) with
            {
                PropertyCode = defaultLineContext.PropertyCode,
                ContactName = defaultLineContext.ContactName
            });
            journalEntryLines.Add(splitLine);
        }

        return new JournalEntry
        {
            OrganizationId = receipt.OrganizationId,
            OfficeId = receipt.OfficeId,
            TransactionDate = transactionDate,
            SourceTypeId = (int)SourceType.Receipt,
            SourceId = receipt.ReceiptId,
            SourceCode = ResolveJournalEntrySourceCodeFromReceipt(receipt),
            Memo = headerMemo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };
    }

    private JournalEntry BuildCrossOfficeBankCardJournalEntryFromReceiptAsync(Receipt receipt, List<ChartOfAccount> receiptChartOfAccounts, AccountingOffice? receiptAccountingOffice, Guid? bankCardOfficeVendorId, string bankCardOfficeName, JournalEntryLineContext defaultLineContext, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // CROSS-OFFICE-RECEIPT-JE-ACCOUNTS (receipt office)
        //   Lines 1+ — Debit: Expense account per split (GetDefaultTenantExpense, GetDefaultDepartureExpense,
        //              GetDefaultOwnerExpense, or GetDefaultCompanyExpense based on split receipt type).
        //   Line 2 — Credit: Accounts Payable (GetDefaultAccountsPayable) to the bank card office.
        // END CROSS-OFFICE-RECEIPT-JE-ACCOUNTS

        var splitLines = ResolveReceiptSplitLines(receipt);
        var accountsPayableAccountId = GetDefaultAccountsPayable(receiptChartOfAccounts, receipt.OfficeId, receiptAccountingOffice);
        var transactionDate = ResolveBillOrReceiptJournalEntryDate(receipt);
        var receiptCode = receipt.ReceiptCode.Trim();
        var firstEligibleSplit = splitLines
            .Where(IsJournalEligibleReceiptSplit)
            .FirstOrDefault(split => !string.IsNullOrWhiteSpace(split.Description));
        var headerMemo = BuildReceiptHeaderMemo(receipt, firstEligibleSplit);
        var totalAmount = splitLines.Where(IsJournalEligibleReceiptSplit).Sum(s => s.Amount);
        var journalEntryLines = new List<JournalEntryLine>();
        var payableLineContext = defaultLineContext with { ContactId = bankCardOfficeVendorId };

        foreach (var split in splitLines)
        {
            if (!IsJournalEligibleReceiptSplit(split))
                continue;

            var expenseAccountId = GetBillReceiptExpenseAccountId(split, receipt.OfficeId, receiptChartOfAccounts, receiptAccountingOffice);
            var splitMemo = BuildReceiptSplitLineMemo(receipt, split);
            var splitLine = new JournalEntryLine
            {
                ChartOfAccountId = expenseAccountId,
                Debit = split.Amount > 0 ? split.Amount : 0,
                Credit = split.Amount < 0 ? Math.Abs(split.Amount) : 0,
                Memo = splitMemo,
                CreatedBy = currentUser
            };
            ApplyJournalEntryLineContext(splitLine, CreateJournalEntryLineContextFromReceiptSplit(receipt, split) with
            {
                PropertyCode = defaultLineContext.PropertyCode,
                ContactName = defaultLineContext.ContactName
            });
            journalEntryLines.Add(splitLine);
        }

        var accountsPayableLine = new JournalEntryLine
        {
            ChartOfAccountId = accountsPayableAccountId,
            Debit = totalAmount < 0 ? Math.Abs(totalAmount) : 0,
            Credit = totalAmount > 0 ? totalAmount : 0,
            Memo = BuildReceiptOfficeMemo(receiptCode, bankCardOfficeName),
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(accountsPayableLine, payableLineContext);
        journalEntryLines.Add(accountsPayableLine);

        return new JournalEntry
        {
            OrganizationId = receipt.OrganizationId,
            OfficeId = receipt.OfficeId,
            TransactionDate = transactionDate,
            SourceTypeId = (int)SourceType.Receipt,
            SourceId = receipt.ReceiptId,
            SourceCode = ResolveJournalEntrySourceCodeFromReceipt(receipt),
            Memo = headerMemo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };
    }

    private JournalEntry BuildCrossOfficeBankCardLiabilityJournalEntryFromReceiptAsync(Receipt receipt, int bankCardOfficeId, List<ChartOfAccount> bankCardOfficeChartOfAccounts, AccountingOffice? bankCardAccountingOffice, BankCard bankCard, Guid? receiptOfficeVendorId, string receiptOfficeName, JournalEntryLineContext defaultLineContext, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // CROSS-OFFICE-RECEIPT-LIABILITY-JE-ACCOUNTS (bank card office)
        // Line 1 — Debit: Accounts Payable (GetDefaultAccountsPayable) to the receipt office.
        // Line 2 — Credit: Credit card account on the bank card (BankCard.ChartOfAccountId).
        // END CROSS-OFFICE-RECEIPT-LIABILITY-JE-ACCOUNTS

        var splitLines = ResolveReceiptSplitLines(receipt);
        var accountsPayableAccountId = GetDefaultAccountsPayable(bankCardOfficeChartOfAccounts, bankCardOfficeId, bankCardAccountingOffice);
        var creditCardAccountId = GetCreditCardAccountId(bankCard);
        var transactionDate = ResolveBillOrReceiptJournalEntryDate(receipt);
        var receiptCode = receipt.ReceiptCode.Trim();
        var bankCardDisplayName = receipt.BankCardDisplayName.Trim();
        var firstEligibleSplit = splitLines
            .Where(IsJournalEligibleReceiptSplit)
            .FirstOrDefault(split => !string.IsNullOrWhiteSpace(split.Description));
        var headerMemo = BuildReceiptHeaderMemo(receipt, firstEligibleSplit);
        var totalAmount = splitLines.Where(IsJournalEligibleReceiptSplit).Sum(s => s.Amount);
        var officeVendorContext = defaultLineContext with { ContactId = receiptOfficeVendorId };
        var accountsPayableLine = new JournalEntryLine
        {
            ChartOfAccountId = accountsPayableAccountId,
            Debit = totalAmount > 0 ? totalAmount : 0,
            Credit = totalAmount < 0 ? Math.Abs(totalAmount) : 0,
            Memo = BuildReceiptOfficeMemo(receiptCode, receiptOfficeName),
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(accountsPayableLine, officeVendorContext);
        var creditCardLine = new JournalEntryLine
        {
            ChartOfAccountId = creditCardAccountId,
            Debit = totalAmount < 0 ? Math.Abs(totalAmount) : 0,
            Credit = totalAmount > 0 ? totalAmount : 0,
            Memo = BuildReceiptOfficeMemo(receiptCode, bankCardDisplayName),
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(creditCardLine, officeVendorContext);
        var journalEntryLines = new List<JournalEntryLine> { accountsPayableLine, creditCardLine };

        return new JournalEntry
        {
            OrganizationId = receipt.OrganizationId,
            OfficeId = bankCardOfficeId,
            TransactionDate = transactionDate,
            SourceTypeId = (int)SourceType.CreditCard,
            SourceId = receipt.ReceiptId,
            SourceCode = ResolveJournalEntrySourceCodeFromReceipt(receipt),
            Memo = headerMemo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };
    }

    private async Task SyncCrossOfficeReceiptCompanionJournalEntryAsync(Receipt receipt, AccountingOffice? receiptAccountingOffice, BankCard bankCard, Guid currentUser)
    {
        await DeleteAllCrossOfficeReceiptCompanionEntriesAsync(receipt);

        if (!IsCrossOfficeBankCardReceipt(receipt, bankCard))
            return;

        var (bankCardChartOfAccounts, bankCardAccountingOffice) = await LoadAccountContextAsync(receipt.OrganizationId, bankCard.OfficeId);
        var receiptOfficeVendorId = await ResolveInterOfficeVendorContactIdAsync(receipt.OrganizationId, bankCard.OfficeId, receipt.OfficeId);
        var receiptOfficeName = await GetOfficeNameAsync(receipt.OrganizationId, receipt.OfficeId);
        var defaultLineContext = await ResolveReceiptJournalEntryLineContextAsync(receipt);
        var companionEntry = BuildCrossOfficeBankCardLiabilityJournalEntryFromReceiptAsync(receipt, bankCard.OfficeId, bankCardChartOfAccounts, bankCardAccountingOffice, bankCard, receiptOfficeVendorId, receiptOfficeName, defaultLineContext, currentUser);
        await CreateAutoGeneratedJournalEntryAsync(companionEntry);
    }
    #endregion

    #region Receipt And Bill Helpers
    private async Task<Receipt> LoadReceiptWithSplitsAsync(Receipt receipt)
    {
        if (receipt.ReceiptId == Guid.Empty)
            return receipt;

        return await _maintenanceRepository.GetReceiptByIdAsync(receipt.ReceiptId, receipt.OrganizationId) ?? receipt;
    }

    private static List<ReceiptSplit> ResolveReceiptSplitLines(Receipt receipt)
    {
        var allSplits = (receipt.Splits ?? new List<ReceiptSplit>()).OrderBy(s => s.ReceiptSplitId).ToList();
        if (allSplits.Count == 0)
            throw new Exception("Splits are required to create a journal entry");

        var nonZeroSplits = allSplits.Where(split => split.Amount != 0).ToList();
        if (nonZeroSplits.Count > 0)
            return nonZeroSplits;

        return allSplits;
    }

    private static bool IsJournalEligibleReceiptSplit(ReceiptSplit split)
        => split.Amount != 0 && split.ReceiptType != ReceiptType.NonExpense;

    private static string BuildReceiptSplitLineMemo(Receipt receipt, ReceiptSplit split)
    {
        var receiptCode = receipt.ReceiptCode.Trim();
        if (string.IsNullOrWhiteSpace(split.Description))
            throw new Exception("Split description is required to create a receipt journal entry memo");

        return split.ReceiptType == ReceiptType.Owner
            ? BuildOwnerReceiptMemo(receiptCode, split.Description)
            : BuildReceiptMemo(receiptCode, split.Description);
    }

    private static string BuildReceiptHeaderMemo(Receipt receipt, ReceiptSplit? firstEligibleSplit)
    {
        if (firstEligibleSplit == null || string.IsNullOrWhiteSpace(firstEligibleSplit.Description))
            throw new Exception("Receipt split description is required to create a receipt journal entry memo");

        return BuildReceiptSplitLineMemo(receipt, firstEligibleSplit);
    }

    #endregion

    #region Bank Card Helpers
    private async Task<BankCard> ResolveReceiptBankCardAsync(Receipt receipt, AccountingOffice? receiptAccountingOffice)
    {
        if (receipt.BankCardId is not > 0)
            throw new Exception("BankCardId is required to resolve a bank card");

        var bankCard = receiptAccountingOffice?.BankCards
            .FirstOrDefault(card => card.BankCardId == receipt.BankCardId.Value);
        if (bankCard != null)
            return bankCard;

        var offices = await _organizationRepository.GetOfficesByOrganizationIdAsync(receipt.OrganizationId);
        var officeIds = string.Join(',', offices.Select(office => office.OfficeId));
        if (string.IsNullOrWhiteSpace(officeIds))
            throw new Exception("Bank card not found for organization");

        var organizationBankCards = await _accountingRepository.GetBankCardsByOfficeIdsAsync(receipt.OrganizationId, officeIds);
        bankCard = organizationBankCards.FirstOrDefault(card => card.BankCardId == receipt.BankCardId.Value);
        if (bankCard == null)
            throw new Exception("Bank card not found for organization");

        return bankCard;
    }

    private async Task<Guid?> ResolveInterOfficeVendorContactIdAsync(Guid organizationId, int accountingOfficeId, int representedOfficeId)
    {
        var representedOffice = await _organizationRepository.GetOfficeByIdAsync(representedOfficeId, organizationId);
        if (representedOffice == null)
            throw new Exception($"Office {representedOfficeId} was not found");

        var representedOfficeName = representedOffice.Name.Trim();
        if (string.IsNullOrWhiteSpace(representedOfficeName))
            throw new Exception($"Office {representedOfficeId} does not have a name configured");

        var officeContacts = await _contactRepository.GetContactsByOfficeIdAsync(organizationId, accountingOfficeId.ToString());
        var officeVendor = officeContacts
            .Where(contact => contact.EntityType == EntityType.Vendor && contact.IsActive)
            .FirstOrDefault(contact => ContactRepresentsOffice(contact, representedOfficeName));

        if (officeVendor == null)
            throw new Exception($"No vendor contact named {representedOfficeName} is configured in office {accountingOfficeId}");

        return officeVendor.ContactId;
    }

    private async Task<string> GetOfficeNameAsync(Guid organizationId, int officeId)
    {
        var office = await _organizationRepository.GetOfficeByIdAsync(officeId, organizationId);
        if (office == null)
            throw new Exception($"Office {officeId} was not found");

        var officeName = office.Name.Trim();
        if (string.IsNullOrWhiteSpace(officeName))
            throw new Exception($"Office {officeId} does not have a name configured");

        return officeName;
    }

    private async Task DeleteAllCrossOfficeReceiptCompanionEntriesAsync(Receipt receipt)
    {
        var offices = await _organizationRepository.GetOfficesByOrganizationIdAsync(receipt.OrganizationId);
        foreach (var office in offices)
        {
            await DeleteJournalEntriesForSourceAsync(
                receipt.OrganizationId,
                office.OfficeId,
                (int)SourceType.CreditCard,
                receipt.ReceiptId);
        }
    }

    private static bool IsCrossOfficeBankCardReceipt(Receipt receipt, BankCard bankCard)
        => bankCard.OfficeId != receipt.OfficeId;

    private static string GetReceiptOfficeLabel(Receipt receipt)
        => string.IsNullOrWhiteSpace(receipt.OfficeName) ? receipt.ReceiptCode.Trim() : receipt.OfficeName.Trim();

    private static bool ContactRepresentsOffice(Contact contact, string officeName)
    {
        var candidates = new[]
        {
            contact.CompanyName,
            contact.DisplayName,
            contact.FullName,
            $"{contact.FirstName} {contact.LastName}".Trim()
        };

        return candidates.Any(candidate =>
            !string.IsNullOrWhiteSpace(candidate) &&
            string.Equals(candidate.Trim(), officeName, StringComparison.OrdinalIgnoreCase));
    }

    private static int GetCreditCardAccountId(BankCard bankCard)
    {
        if (bankCard.ChartOfAccountId is not > 0)
            throw new Exception("Bank card must have a chart of account configured");

        return bankCard.ChartOfAccountId.Value;
    }

    private static void EnsureReceiptIsCardReceipt(Receipt receipt)
    {
        if (receipt.BankCardId is not > 0)
            throw new Exception("Receipt is not a card receipt");
    }
    #endregion
}
