using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    public async Task<Reservation> ApplySecurityDepositReturnAsync(
        Guid reservationId,
        Guid organizationId,
        string officeAccess,
        int chartOfAccountId,
        string description,
        decimal amount,
        DateOnly paymentDate,
        PaymentType paymentType,
        Guid currentUser)
    {
        _ = paymentType;
        var reservation = await _reservationRepository.GetReservationByIdAsync(reservationId, organizationId)
            ?? throw new Exception("Reservation not found");

        if (reservation.DepositReturned)
            throw new Exception("Security deposit has already been returned");

        if (reservation.DepositType != DepositType.Deposit)
            throw new Exception("Reservation does not have a security deposit");

        if (amount == 0)
            throw new Exception("Payment amount cannot be zero");

        if (chartOfAccountId <= 0)
            throw new Exception("Chart of account is required for security deposit return");

        if (paymentDate == default)
            throw new Exception("Payment date is required for security deposit return");

        var property = await _propertyRepository.GetPropertyByIdAsync(reservation.PropertyId, organizationId)
            ?? throw new Exception("Property not found");

        var departure = new ReservationDeparture
        {
            ReservationId = reservation.ReservationId,
            ReservationCode = reservation.ReservationCode,
            PropertyId = reservation.PropertyId,
            PropertyCode = property.PropertyCode,
            OfficeId = reservation.OfficeId,
            OfficeName = reservation.OfficeName,
            ContactId = reservation.ContactIds.FirstOrDefault(),
            ContactName = reservation.ContactName,
            CompanyId = reservation.CompanyId,
            CompanyName = reservation.CompanyName,
            TenantName = reservation.TenantName ?? string.Empty,
            Deposit = reservation.Deposit,
            DepositType = reservation.DepositType,
            DepositReturned = reservation.DepositReturned
        };

        if (!await IsAccountingFeatureEnabledAsync(organizationId))
        {
            reservation.DepositReturned = true;
            reservation.ModifiedBy = currentUser;
            return await _reservationRepository.UpdateByIdAsync(reservation);
        }

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(organizationId, reservation.OfficeId);
        var escrowSecurityDepositAccountId = GetDefaultEscrowSecurityDepositAccount(chartOfAccounts, reservation.OfficeId, accountingOffice);
        var lineContext = await ResolveReservationJournalEntryLineContextAsync(organizationId, departure, reservation);
        var memo = string.IsNullOrWhiteSpace(description)
            ? $"{reservation.ReservationCode}: Security Deposit Return"
            : description.Trim();

        var liabilityLine = new JournalEntryLine
        {
            ChartOfAccountId = escrowSecurityDepositAccountId,
            Debit = amount > 0 ? amount : 0,
            Credit = amount < 0 ? Math.Abs(amount) : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(liabilityLine, lineContext);

        var bankLine = new JournalEntryLine
        {
            ChartOfAccountId = chartOfAccountId,
            Debit = amount < 0 ? Math.Abs(amount) : 0,
            Credit = amount > 0 ? amount : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(bankLine, lineContext);

        var journalEntry = new JournalEntry
        {
            OrganizationId = organizationId,
            OfficeId = reservation.OfficeId,
            TransactionDate = paymentDate,
            SourceTypeId = (int)SourceType.SecurityDeposit,
            SourceId = reservation.ReservationId,
            SourceCode = reservation.ReservationCode,
            Memo = memo,
            JournalEntryLines = new List<JournalEntryLine> { liabilityLine, bankLine },
            CreatedBy = currentUser
        };

        await CreateAutoGeneratedJournalEntryAsync(journalEntry);

        reservation.DepositReturned = true;
        reservation.ModifiedBy = currentUser;
        return await _reservationRepository.UpdateByIdAsync(reservation);
    }
}
