using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Triggers
    public async Task<JournalEntry?> CreateJournalEntryFromWorkOrderAsync(WorkOrder workOrder, Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(workOrder.OrganizationId))
            return null;

        if (!ShouldCreateJournalEntryForWorkOrder(workOrder))
            return null;

        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = workOrder.OrganizationId,
            OfficeIds = workOrder.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.WorkOrder,
            SourceId = workOrder.WorkOrderId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        var existingEntry = existingEntries.FirstOrDefault(e => !e.IsVoided);
        if (existingEntry != null)
        {
            if (existingEntry.IsPosted)
                return existingEntry;

            await ReplaceJournalEntriesFromWorkOrderAsync(workOrder, currentUser);
            return (await _journalEntryRepository.GetJournalEntryByIdAsync(existingEntry.JournalEntryId, workOrder.OrganizationId))!;
        }

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(workOrder.OrganizationId, workOrder.OfficeId);
        var journalEntry = await BuildJournalEntryFromWorkOrderAsync(workOrder, chartOfAccounts, accountingOffice, currentUser);
        return await CreateAutoGeneratedJournalEntryAsync(journalEntry);
    }

    private async Task<JournalEntry?> CreateJournalEntryFromInvoiceOwnerShareAsync(Invoice invoice, decimal amount, Guid currentUser)
    {
        var propertyId = await ResolveInvoicePropertyIdAsync(invoice);
        if (propertyId == null || propertyId == Guid.Empty)
            return null;

        var property = await _propertyRepository.GetPropertyByIdAsync(propertyId.Value, invoice.OrganizationId);
        var propertyAgreement = await _propertyRepository.GetPropertyAgreementByPropertyIdAsync(propertyId.Value);
        if (property == null || propertyAgreement == null)
            return null;

        List<JournalEntryLine>? journalEntryLines = null;

        switch (property.PropertyLeaseType)
        {
            case PropertyLeaseType.PropertyManagement:
            {
                if (!TryGetInvoiceRentalLedgerLine(invoice, out var rentalLine))
                    return null;

                var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);
                var costCodes = await _accountingRepository.GetCostCodesByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);
                costCodes.ToDictionary(c => c.CostCodeId).TryGetValue(rentalLine.CostCodeId, out var rentalCostCode);
                var defaultIncomeAccountId = GetDefaultTenantIncome(chartOfAccounts, invoice.OfficeId, accountingOffice);
                var rentalIncomeAccountId = GetChartOfAccountIdByCostCode(chartOfAccounts, invoice.OfficeId, rentalCostCode, defaultIncomeAccountId);
                journalEntryLines = BuildJournalEntryLinesForPropertyManagement(invoice, amount, property, propertyAgreement, rentalIncomeAccountId, rentalLine.CostCodeId, chartOfAccounts, accountingOffice, propertyId.Value, currentUser);
                break;
            }

            case PropertyLeaseType.Direct:
            case PropertyLeaseType.ThirdParty:
            {
                return null;
            }

            default:
                return null;
        }

        if (journalEntryLines == null || journalEntryLines.Count == 0)
            return null;

        if (invoice.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required to create an owner share journal entry for an invoice");

        var ownerJournalEntry = new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = invoice.AccountingPeriod,
            PostingDate = invoice.AccountingPeriod,
            SourceTypeId = (int)SourceType.OwnerDistribution,
            SourceId = invoice.InvoiceId,
            Memo = $"Owner Share - {invoice.InvoiceCode}",
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };

        return await CreateAutoGeneratedJournalEntryAsync(ownerJournalEntry);
    }
    #endregion

    #region Journal Entry
    private List<JournalEntryLine> BuildJournalEntryLinesForPropertyManagement(Invoice invoice, decimal amount, Property property, PropertyAgreement propertyAgreement, int rentalIncomeAccountId, int rentalCostCodeId, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid propertyId, Guid currentUser)
    {
        decimal ownerAmount = 0m;
        var journalEntryLines = new List<JournalEntryLine>();

        switch (propertyAgreement.ManagementFeeType)
        {
            case ManagementFeeType.FlatRate:
                ownerAmount = propertyAgreement.FlatRateAmount;
                break;

            case ManagementFeeType.Percentage:
                ownerAmount = amount * propertyAgreement.RevenueSplitOwner / 100m;
                break;

            case ManagementFeeType.Minimum:
                ownerAmount = amount * propertyAgreement.RevenueSplitOwner / 100m;
                if (ownerAmount < propertyAgreement.FlatRateAmount)
                    ownerAmount = propertyAgreement.FlatRateAmount;
                break;

            default:
                return new List<JournalEntryLine>();
        }

        if (ownerAmount == 0)
            return journalEntryLines;

        var ownerAccountsPayableAccountId = GetDefaultOwnerAccountsPayable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var memo = $"Owner Share - {invoice.InvoiceCode}";
        var (incomeDebit, incomeCredit) = SignedAmountToDebitCredit(ownerAmount, positiveIsDebit: true);
        var (ownerApDebit, ownerApCredit) = SignedAmountToDebitCredit(ownerAmount, positiveIsDebit: false);

        journalEntryLines.Add(new JournalEntryLine
        {
            ChartOfAccountId = rentalIncomeAccountId,
            CostCodeId = rentalCostCodeId,
            PropertyId = propertyId,
            ReservationId = invoice.ReservationId,
            ContactId = invoice.ContactId,
            Debit = incomeDebit,
            Credit = incomeCredit,
            Memo = memo,
            CreatedBy = currentUser
        });
        journalEntryLines.Add(new JournalEntryLine
        {
            ChartOfAccountId = ownerAccountsPayableAccountId,
            PropertyId = propertyId,
            ReservationId = invoice.ReservationId,
            ContactId = invoice.ContactId,
            Debit = ownerApDebit,
            Credit = ownerApCredit,
            Memo = memo,
            CreatedBy = currentUser
        });

        return journalEntryLines;
    }

    private static bool ShouldCreateJournalEntryForWorkOrder(WorkOrder workOrder)
        => workOrder.WorkOrderType == WorkOrderType.Owner;

    private Task<JournalEntry> BuildJournalEntryFromWorkOrderAsync(WorkOrder workOrder, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // TODO: build journal entry lines from work order items and linked receipts.
        throw new NotImplementedException("Work order journal entry build logic is not yet implemented.");
    }
    #endregion
}
