using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    public async Task<Invoice> UpdateInvoiceAsync(Invoice invoice)
    {
        var existingInvoice = await _accountingRepository.GetInvoiceByIdAsync(invoice.InvoiceId, invoice.OrganizationId);
        if (existingInvoice == null)
            throw new Exception("Invoice not found");

        var priorPaymentLedgerLineIds = existingInvoice.LedgerLines
            .Where(l => l.LedgerLineId != Guid.Empty)
            .Select(l => l.LedgerLineId);

        var updatedInvoice = await _accountingRepository.UpdateByIdAsync(invoice);
        await TryReplaceJournalEntriesFromInvoiceAsync(updatedInvoice, priorPaymentLedgerLineIds);
        return updatedInvoice;
    }

    public async Task<Receipt> UpdateBillAsync(Receipt bill, Guid currentUser)
    {
        EnsureReceiptIsBill(bill);

        await _maintenanceRepository.UpdateReceiptAsync(bill);
        var freshBill = await _maintenanceRepository.GetReceiptByIdAsync(bill.ReceiptId, bill.OrganizationId)
            ?? throw new Exception("Bill not found after update");

        await ReplaceJournalEntriesFromBillAsync(freshBill, currentUser);
        return freshBill;
    }

    public async Task<Receipt> UpdateReceiptAsync(Receipt receipt, Guid currentUser)
    {
        EnsureReceiptIsCardReceipt(receipt);

        var updatedReceipt = await _maintenanceRepository.UpdateReceiptAsync(receipt);
        var freshReceipt = await _maintenanceRepository.GetReceiptByIdAsync(updatedReceipt.ReceiptId, updatedReceipt.OrganizationId)
            ?? throw new Exception("Receipt not found after update");

        await ReplaceJournalEntriesFromReceiptAsync(freshReceipt, currentUser);
        return freshReceipt;
    }

    public async Task<WorkOrder> UpdateWorkOrderAsync(WorkOrder workOrder, Guid currentUser)
    {
        var updatedWorkOrder = await _maintenanceRepository.UpdateWorkOrderAsync(workOrder);
        var freshWorkOrder = await _maintenanceRepository.GetWorkOrderByIdAsync(updatedWorkOrder.WorkOrderId, updatedWorkOrder.OrganizationId)
            ?? throw new Exception("Work order not found after update");

        await TryReplaceJournalEntriesFromWorkOrderAsync(freshWorkOrder, currentUser);
        return freshWorkOrder;
    }

    private async Task TryReplaceJournalEntriesFromWorkOrderAsync(WorkOrder workOrder, Guid currentUser)
    {
        try
        {
            if (workOrder.WorkOrderId == Guid.Empty)
                return;

            if (!await IsAccountingFeatureEnabledAsync(workOrder.OrganizationId) || !ShouldCreateJournalEntryForWorkOrder(workOrder))
            {
                await DeleteJournalEntriesForSourceAsync(
                    workOrder.OrganizationId,
                    workOrder.OfficeId,
                    (int)SourceType.WorkOrder,
                    workOrder.WorkOrderId);

                if (workOrder.JournalEntryId.HasValue && workOrder.JournalEntryId != Guid.Empty)
                    await PersistWorkOrderJournalEntryIdIfChangedAsync(workOrder, null, currentUser);

                return;
            }

            var existingEntries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
            {
                OrganizationId = workOrder.OrganizationId,
                OfficeIds = workOrder.OfficeId.ToString(),
                SourceTypeId = (int)SourceType.WorkOrder,
                SourceId = workOrder.WorkOrderId,
                IncludeVoided = true,
                IncludeUnposted = true
            })).ToList();

            var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(workOrder.OrganizationId, workOrder.OfficeId);
            var rebuiltJournalEntry = await BuildJournalEntryFromWorkOrderAsync(workOrder, chartOfAccounts, accountingOffice, currentUser);

            while (existingEntries.Count > 1)
            {
                var duplicate = existingEntries[^1];
                await DeleteJournalEntryAsync(duplicate.JournalEntryId, workOrder.OrganizationId);
                existingEntries.RemoveAt(existingEntries.Count - 1);
            }

            var existingEntry = existingEntries.FirstOrDefault();
            if (existingEntry != null)
            {
                rebuiltJournalEntry.JournalEntryId = existingEntry.JournalEntryId;
                rebuiltJournalEntry.OrganizationId = workOrder.OrganizationId;
                rebuiltJournalEntry.OfficeId = workOrder.OfficeId;
                rebuiltJournalEntry.CreatedBy = existingEntry.CreatedBy;
                rebuiltJournalEntry.ModifiedBy = currentUser;

                foreach (var line in rebuiltJournalEntry.JournalEntryLines)
                {
                    line.JournalEntryId = existingEntry.JournalEntryId;
                    line.JournalEntryLineId = Guid.Empty;
                }

                await UpdateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);

                await PersistWorkOrderJournalEntryIdIfChangedAsync(workOrder, existingEntry.JournalEntryId, currentUser);
                return;
            }

            var createdJournalEntry = await CreateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
            if (createdJournalEntry != null)
                await PersistWorkOrderJournalEntryIdIfChangedAsync(workOrder, createdJournalEntry.JournalEntryId, currentUser);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "WorkOrder",
                organizationId: workOrder.OrganizationId,
                officeId: workOrder.OfficeId,
                sourceTypeId: (int)SourceType.WorkOrder,
                sourceId: workOrder.WorkOrderId,
                documentCode: workOrder.WorkOrderCode,
                accountingPeriod: null,
                amount: null,
                message: $"Work order {workOrder.WorkOrderCode} journal entry refresh failed: {ex.Message}",
                currentUser: currentUser);
        }
    }

    private async Task ReplaceJournalEntriesFromReceiptAsync(Receipt receipt, Guid currentUser)
    {
        try
        {
            EnsureReceiptIsCardReceipt(receipt);
            receipt = await LoadReceiptWithSplitsAsync(receipt);

            if (receipt.ReceiptId == Guid.Empty)
                return;

            if (!await IsAccountingFeatureEnabledAsync(receipt.OrganizationId))
            {
                await DeleteJournalEntriesForSourceAsync(
                    receipt.OrganizationId,
                    receipt.OfficeId,
                    (int)SourceType.Receipt,
                    receipt.ReceiptId);
                await DeleteAllCrossOfficeReceiptCompanionEntriesAsync(receipt);

                if (receipt.JournalEntryId.HasValue && receipt.JournalEntryId != Guid.Empty)
                    await PersistReceiptJournalEntryIdIfChangedAsync(receipt, null, currentUser);

                return;
            }

            var existingEntries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
            {
                OrganizationId = receipt.OrganizationId,
                OfficeIds = receipt.OfficeId.ToString(),
                SourceTypeId = (int)SourceType.Receipt,
                SourceId = receipt.ReceiptId,
                IncludeVoided = true,
                IncludeUnposted = true
            })).ToList();

            var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(receipt.OrganizationId, receipt.OfficeId);
            var bankCard = await ResolveReceiptBankCardAsync(receipt, accountingOffice);
            var rebuiltJournalEntry = await BuildJournalEntryFromReceiptAsync(receipt, chartOfAccounts, accountingOffice, currentUser);

            while (existingEntries.Count > 1)
            {
                var duplicate = existingEntries[^1];
                await DeleteJournalEntryAsync(duplicate.JournalEntryId, receipt.OrganizationId);
                existingEntries.RemoveAt(existingEntries.Count - 1);
            }

            var existingEntry = existingEntries.FirstOrDefault();
            if (existingEntry != null)
            {
                rebuiltJournalEntry.JournalEntryId = existingEntry.JournalEntryId;
                rebuiltJournalEntry.OrganizationId = receipt.OrganizationId;
                rebuiltJournalEntry.OfficeId = receipt.OfficeId;
                rebuiltJournalEntry.CreatedBy = existingEntry.CreatedBy;
                rebuiltJournalEntry.ModifiedBy = currentUser;

                foreach (var line in rebuiltJournalEntry.JournalEntryLines)
                {
                    line.JournalEntryId = existingEntry.JournalEntryId;
                    line.JournalEntryLineId = Guid.Empty;
                }

                await UpdateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
                await SyncCrossOfficeReceiptCompanionJournalEntryAsync(receipt, accountingOffice, bankCard, currentUser);

                await PersistReceiptJournalEntryIdIfChangedAsync(receipt, existingEntry.JournalEntryId, currentUser);
                return;
            }

            var createdJournalEntry = await CreateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
            if (createdJournalEntry != null)
                await PersistReceiptJournalEntryIdIfChangedAsync(receipt, createdJournalEntry.JournalEntryId, currentUser);

            await SyncCrossOfficeReceiptCompanionJournalEntryAsync(receipt, accountingOffice, bankCard, currentUser);
        }
        catch (Exception ex)
        {
            var receiptLabel = receipt.ReceiptCode.Trim();
            await LogAccountingErrorAsync(
                trigger: "Receipt",
                organizationId: receipt.OrganizationId,
                officeId: receipt.OfficeId,
                sourceTypeId: (int)SourceType.Receipt,
                sourceId: receipt.ReceiptId,
                documentCode: receiptLabel,
                accountingPeriod: receipt.AccountingPeriod == default ? null : receipt.AccountingPeriod,
                amount: receipt.Amount,
                message: $"Receipt {receiptLabel} journal entry refresh failed: {ex.Message}",
                currentUser: currentUser);
            throw;
        }
    }

    private async Task TryReplaceJournalEntriesFromInvoiceAsync(Invoice invoice, IEnumerable<Guid> priorPaymentLedgerLineIds)
    {
        try
        {
            if (invoice.InvoiceId == Guid.Empty)
                return;

            var costCodeById = await LoadCostCodeByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);

            var currentPaymentLedgerLineIds = invoice.LedgerLines
                .Where(line => line.LedgerLineId != Guid.Empty && line.Amount != 0)
                .Where(line => costCodeById.TryGetValue(line.CostCodeId, out var costCode) && IsPaymentLedgerLine(costCode))
                .Select(line => line.LedgerLineId)
                .ToHashSet();

            var removedPaymentLedgerLineIds = priorPaymentLedgerLineIds
                .Where(ledgerLineId => ledgerLineId != Guid.Empty && !currentPaymentLedgerLineIds.Contains(ledgerLineId))
                .Distinct()
                .ToList();

            foreach (var ledgerLineId in removedPaymentLedgerLineIds)
                await DeleteJournalEntriesForInvoicePaymentLedgerLineAsync(invoice.OrganizationId, invoice.OfficeId, ledgerLineId);

            await RefreshInvoiceChargeJournalEntriesAsync(invoice, invoice.ModifiedBy);

            foreach (var paymentLedgerLine in invoice.LedgerLines
                         .Where(line => line.Amount != 0)
                         .Where(line => costCodeById.TryGetValue(line.CostCodeId, out var costCode) && IsPaymentLedgerLine(costCode)))
            {
                var existingPaymentEntries = await GetJournalEntriesForInvoicePaymentLedgerLineAsync(
                    invoice.OrganizationId,
                    invoice.OfficeId,
                    paymentLedgerLine.LedgerLineId);
                await UpsertJournalEntryFromPaymentAsync(invoice, paymentLedgerLine, existingPaymentEntries, invoice.ModifiedBy);
            }
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "Invoice",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.Invoice,
                sourceId: invoice.InvoiceId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: invoice.TotalAmount,
                message: $"Invoice {invoice.InvoiceCode} journal entry refresh failed: {ex.Message}",
                currentUser: invoice.ModifiedBy);
        }
    }

    private async Task ReplaceJournalEntriesFromBillAsync(Receipt bill, Guid currentUser)
    {
        try
        {
            EnsureReceiptIsBill(bill);
            bill = await LoadReceiptWithSplitsAsync(bill);

            if (bill.ReceiptId == Guid.Empty)
                return;

            if (!await IsAccountingFeatureEnabledAsync(bill.OrganizationId))
            {
                await DeleteAllBillJournalEntriesAsync(bill);
                await PersistReceiptJournalEntryIdIfChangedAsync(bill, null, currentUser);
                return;
            }

            var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(bill.OrganizationId, bill.OfficeId);
            var ownerAccountsPayableAccountId = GetDefaultOwnerAccountsPayable(chartOfAccounts, bill.OfficeId, accountingOffice);
            var pmUtilityIncomeAccountId = GetDefaultPmUtilityIncome(chartOfAccounts, bill.OfficeId, accountingOffice);
            var liabilityAccountId = GetBillReceiptLiabilityAccountId(bill, chartOfAccounts, accountingOffice);

            var existingBillEntries = await GetJournalEntriesForSourceAsync(
                bill.OrganizationId,
                bill.OfficeId,
                SourceType.Bill,
                bill.ReceiptId);
            var (mainExisting, ownerUtilityExisting) = ClassifyBillJournalEntries(
                existingBillEntries,
                ownerAccountsPayableAccountId,
                pmUtilityIncomeAccountId);

            var mainRebuilt = await BuildJournalEntryFromBillAsync(bill, chartOfAccounts, accountingOffice, currentUser);
            var updatedMain = await UpsertAutoGeneratedJournalEntryAsync(
                mainRebuilt,
                mainExisting != null ? [mainExisting] : [],
                currentUser,
                bill.OrganizationId);
            if (updatedMain != null)
                await PersistReceiptJournalEntryIdIfChangedAsync(bill, updatedMain.JournalEntryId, currentUser);

            JournalEntry? updatedOwnerUtility = null;
            var ownerUtilityRebuilt = await BuildJournalEntryFromBillForOwnerUtilityAsync(bill, chartOfAccounts, accountingOffice, currentUser);
            if (ownerUtilityRebuilt != null)
            {
                updatedOwnerUtility = await UpsertAutoGeneratedJournalEntryAsync(
                    ownerUtilityRebuilt,
                    ownerUtilityExisting != null ? [ownerUtilityExisting] : [],
                    currentUser,
                    bill.OrganizationId);
            }
            else if (ownerUtilityExisting != null)
            {
                await DeleteJournalEntryAsync(ownerUtilityExisting.JournalEntryId, bill.OrganizationId);
            }

            var retainedBillEntryIds = new HashSet<Guid>();
            if (updatedMain != null)
                retainedBillEntryIds.Add(updatedMain.JournalEntryId);
            if (updatedOwnerUtility != null)
                retainedBillEntryIds.Add(updatedOwnerUtility.JournalEntryId);
            await DeleteJournalEntriesExceptAsync(existingBillEntries, retainedBillEntryIds, bill.OrganizationId);

            var existingPayments = await GetJournalEntriesForSourceAsync(
                bill.OrganizationId,
                bill.OfficeId,
                SourceType.BillPayment,
                bill.ReceiptId);

            if (bill.PaidAmount == 0)
            {
                await DeleteJournalEntriesExceptAsync(existingPayments, Array.Empty<Guid>(), bill.OrganizationId);
                return;
            }

            var paymentOffsetAccountId = existingPayments
                .Select(entry => ResolveBillPaymentOffsetAccountId(entry, liabilityAccountId))
                .FirstOrDefault(accountId => accountId is > 0);

            var billLabel = !string.IsNullOrWhiteSpace(bill.BillNumber)
                ? bill.BillNumber.Trim()
                : bill.ReceiptCode.Trim();
            var paymentApplication = new BillPaymentApplication
            {
                Bill = bill,
                AmountApplied = bill.PaidAmount,
                PaymentDate = bill.PaidDate ?? bill.ReceiptDate,
                ChartOfAccountId = paymentOffsetAccountId ?? GetDefaultBankAccount(chartOfAccounts, bill.OfficeId, accountingOffice),
                Description = $"Bill Payment - {billLabel}",
                PaymentSequence = 0
            };

            var paymentRebuilt = await BuildJournalEntryFromBillPaymentAsync(paymentApplication, chartOfAccounts, accountingOffice, currentUser);
            var updatedPayment = await UpsertAutoGeneratedJournalEntryAsync(
                paymentRebuilt,
                existingPayments,
                currentUser,
                bill.OrganizationId);

            if (updatedPayment != null)
                await DeleteJournalEntriesExceptAsync(existingPayments, [updatedPayment.JournalEntryId], bill.OrganizationId);
        }
        catch (Exception ex)
        {
            var billLabel = !string.IsNullOrWhiteSpace(bill.BillNumber)
                ? bill.BillNumber.Trim()
                : bill.ReceiptCode.Trim();
            await LogAccountingErrorAsync(
                trigger: "Bill",
                organizationId: bill.OrganizationId,
                officeId: bill.OfficeId,
                sourceTypeId: (int)SourceType.Bill,
                sourceId: bill.ReceiptId,
                documentCode: billLabel,
                accountingPeriod: bill.AccountingPeriod == default ? null : bill.AccountingPeriod,
                amount: bill.Amount,
                message: $"Bill {billLabel} journal entry refresh failed: {ex.Message}",
                currentUser: currentUser);
            throw;
        }
    }

    private async Task DeleteAllBillJournalEntriesAsync(Receipt bill)
    {
        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(bill.OrganizationId, bill.OfficeId);
        await DeleteBillPaymentJournalEntriesAsync(bill, chartOfAccounts, accountingOffice);
        await DeleteJournalEntriesForSourceAsync(
            bill.OrganizationId,
            bill.OfficeId,
            (int)SourceType.Bill,
            bill.ReceiptId);
    }

    private async Task DeleteJournalEntriesForSourceAsync(Guid organizationId, int officeId, int sourceTypeId, Guid sourceId)
    {
        var entries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = organizationId,
            OfficeIds = officeId.ToString(),
            SourceTypeId = sourceTypeId,
            SourceId = sourceId,
            IncludeVoided = true,
            IncludeUnposted = true
        })).ToList();

        foreach (var entry in entries)
            await DeleteJournalEntryAsync(entry.JournalEntryId, organizationId);
    }

    private async Task<int?> DeleteBillPaymentJournalEntriesAsync(Receipt bill, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice)
    {
        var liabilityAccountId = GetBillReceiptLiabilityAccountId(bill, chartOfAccounts, accountingOffice);

        var existingEntries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = bill.OrganizationId,
            OfficeIds = bill.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.BillPayment,
            IncludeVoided = true,
            IncludeUnposted = true
        })).ToList();

        int? paymentOffsetAccountId = null;

        foreach (var entry in existingEntries.Where(e => e.SourceId == bill.ReceiptId))
        {
            paymentOffsetAccountId ??= ResolveBillPaymentOffsetAccountId(entry, liabilityAccountId);
            await DeleteJournalEntryAsync(entry.JournalEntryId, bill.OrganizationId);
        }

        return paymentOffsetAccountId;
    }

    private static int? ResolveBillPaymentOffsetAccountId(JournalEntry entry, int liabilityAccountId)
    {
        var offsetLine = entry.JournalEntryLines.FirstOrDefault(l =>
            l.ChartOfAccountId > 0 &&
            l.ChartOfAccountId != liabilityAccountId);

        return offsetLine?.ChartOfAccountId;
    }
}
