using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    private readonly struct TransferJournalEntryAccounts
    {
        public int EscrowDepositAccountId { get; init; }
        public int EscrowSecurityDepositAccountId { get; init; }
        public int EscrowSdwAccountId { get; init; }
        public int EscrowOwnersAccountId { get; init; }
        public int BankAccountId { get; init; }
    }

    #region Triggers
    public async Task<JournalEntry?> CreateJournalEntryFromTransferAsync(Transfer transfer, Guid currentUser)
        => (await CreateJournalEntryFromTransferWithResultAsync(transfer, currentUser)).JournalEntry;

    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromTransferWithResultAsync(Transfer transfer, Guid currentUser)
    {
        var trail = new AccountingSyncBailTrail();
        var result = await CreateJournalEntryFromTransferWithDiagnosticsAsync(transfer, currentUser, trail);
        if (result.JournalEntry == null && !result.HasWarning)
            return AccountingJournalEntryResult.WarningResult(trail.FormatBailTrail());
        return result;
    }

    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromTransferWithDiagnosticsAsync(
        Transfer transfer,
        Guid currentUser,
        AccountingSyncBailTrail trail)
    {
        var transferLabel = string.IsNullOrWhiteSpace(transfer.TransferCode)
            ? transfer.TransferId.ToString()
            : transfer.TransferCode.Trim();
        trail.Note($"Transfer {transferLabel} IsActive={transfer.IsActive} Amount={transfer.Amount:0.00} Splits={transfer.Splits?.Count ?? 0}");

        if (!await IsAccountingFeatureEnabledAsync(transfer.OrganizationId))
        {
            trail.Bail("Exit: accounting feature is disabled for organization.");
            return AccountingJournalEntryResult.WarningResult("Accounting feature is disabled for organization.");
        }

        if (!ShouldCreateJournalEntryForTransfer(transfer))
        {
            AppendTransferShouldCreateBailReasons(transfer, trail);
            trail.Bail("Exit: ShouldCreateJournalEntryForTransfer=false.");
            return AccountingJournalEntryResult.WarningResult(trail.FormatBailTrail());
        }

        try
        {
            ValidateTransferForJournalEntry(transfer);

            await EnrichTransferSplitsFromJournalEntryLinesAsync(transfer);
            ApplyTransferHeaderContextFromSplits(transfer);
            trail.Note($"After enrich: splits={transfer.Splits?.Count ?? 0}");

            var journalEntry = await BuildJournalEntryFromTransferRecordAsync(transfer, currentUser);
            trail.Note($"Built transfer JE lines={journalEntry.JournalEntryLines?.Count ?? 0}");

            var created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);
            if (created == null)
            {
                trail.Bail("Exit: CreateAutoGeneratedJournalEntryAsync returned null (feature off or rejected).");
                return AccountingJournalEntryResult.WarningResult(trail.FormatBailTrail());
            }

            trail.Note($"Created {created.JournalEntryCode} kind={(int)created.JournalEntryKindId} TransferId={created.TransferId}");
            await SyncTransferDocumentLinksAsync(transfer, currentUser);
            trail.Note("SyncTransferDocumentLinksAsync completed.");

            return AccountingJournalEntryResult.Success(created);
        }
        catch (Exception ex)
        {
            trail.Bail($"Exception: {ex.Message}");
            await LogAccountingErrorAsync(
                trigger: "Transfer",
                organizationId: transfer.OrganizationId,
                officeId: transfer.OfficeId,
                sourceTypeId: (int)SourceType.Transfer,
                sourceId: transfer.TransferId,
                documentCode: transferLabel,
                accountingPeriod: transfer.AccountingPeriod == default ? null : transfer.AccountingPeriod,
                amount: transfer.Amount,
                message: ex.Message + Environment.NewLine + "Bail trail:" + Environment.NewLine + trail.FormatBailTrail(),
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    #endregion

    #region Journal Entry
    private async Task TryReplaceJournalEntriesFromTransferAsync(Transfer transfer, Guid currentUser)
        => await TryReplaceJournalEntriesFromTransferWithDiagnosticsAsync(transfer, currentUser, new AccountingSyncBailTrail());

    private async Task TryReplaceJournalEntriesFromTransferWithDiagnosticsAsync(
        Transfer transfer,
        Guid currentUser,
        AccountingSyncBailTrail trail)
    {
        var transferLabel = string.IsNullOrWhiteSpace(transfer.TransferCode)
            ? transfer.TransferId.ToString()
            : transfer.TransferCode.Trim();

        try
        {
            if (transfer.TransferId == Guid.Empty)
            {
                trail.Bail("Exit: TransferId is empty.");
                return;
            }

            trail.Note($"TryReplace transfer {transferLabel} IsActive={transfer.IsActive} Amount={transfer.Amount:0.00} Splits={transfer.Splits?.Count ?? 0}");

            if (!await IsAccountingFeatureEnabledAsync(transfer.OrganizationId))
            {
                trail.Bail("Exit: accounting feature disabled — clearing transfer links/JEs.");
                await ClearTransferDocumentLinksAsync(transfer.OrganizationId, transfer.TransferId, currentUser);
                await _accountingRepository.ClearDepositTransferIdsByTransferIdAsync(
                    transfer.OrganizationId,
                    transfer.TransferId,
                    currentUser);
                await DeleteJournalEntriesForSourceAsync(
                    transfer.OrganizationId,
                    transfer.OfficeId,
                    (int)SourceType.Transfer,
                    transfer.TransferId);
                return;
            }

            if (!ShouldCreateJournalEntryForTransfer(transfer))
            {
                AppendTransferShouldCreateBailReasons(transfer, trail);
                trail.Bail("Exit: ShouldCreateJournalEntryForTransfer=false — clearing transfer links/JEs.");
                await ClearTransferDocumentLinksAsync(transfer.OrganizationId, transfer.TransferId, currentUser);
                await _accountingRepository.ClearDepositTransferIdsByTransferIdAsync(
                    transfer.OrganizationId,
                    transfer.TransferId,
                    currentUser);
                await DeleteJournalEntriesForSourceAsync(
                    transfer.OrganizationId,
                    transfer.OfficeId,
                    (int)SourceType.Transfer,
                    transfer.TransferId);
                return;
            }

            var existingEntries = (await GetJournalEntriesByCriteriaCachedAsync(new JournalEntryGetCriteria
            {
                OrganizationId = transfer.OrganizationId,
                OfficeIds = transfer.OfficeId.ToString(),
                SourceTypeId = (int)SourceType.Transfer,
                SourceId = transfer.TransferId,
                StartDate = DateOnly.MinValue,
                IncludeUnposted = true
            })).ToList();
            trail.Note($"Existing SourceType.Transfer JEs: {existingEntries.Count}");

            var rebuiltJournalEntry = await BuildJournalEntryFromTransferRecordAsync(transfer, currentUser);
            trail.Note($"Rebuilt JE lines={rebuiltJournalEntry.JournalEntryLines?.Count ?? 0}");

            while (existingEntries.Count > 1)
            {
                var duplicate = existingEntries[^1];
                trail.Note($"Deleting duplicate transfer JE {duplicate.JournalEntryCode}");
                await DeleteOpenJournalEntryAsync(duplicate.JournalEntryId, transfer.OrganizationId);
                existingEntries.RemoveAt(existingEntries.Count - 1);
            }

            var existingEntry = existingEntries.FirstOrDefault();
            if (existingEntry != null)
            {
                rebuiltJournalEntry.JournalEntryId = existingEntry.JournalEntryId;
                rebuiltJournalEntry.OrganizationId = transfer.OrganizationId;
                rebuiltJournalEntry.OfficeId = transfer.OfficeId;
                rebuiltJournalEntry.CreatedBy = existingEntry.CreatedBy;
                rebuiltJournalEntry.ModifiedBy = currentUser;

                foreach (var line in rebuiltJournalEntry.JournalEntryLines ?? [])
                {
                    line.JournalEntryId = existingEntry.JournalEntryId;
                    line.JournalEntryLineId = Guid.Empty;
                }

                await UpdateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
                trail.Note($"Updated existing transfer JE {existingEntry.JournalEntryCode}");
                await SyncTransferDocumentLinksAsync(transfer, currentUser);
                trail.Note("SyncTransferDocumentLinksAsync completed.");
                return;
            }

            var created = await CreateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
            if (created == null)
            {
                trail.Bail("Exit: CreateAutoGeneratedJournalEntryAsync returned null on replace-create.");
                return;
            }

            trail.Note($"Created transfer JE {created.JournalEntryCode}");
            await SyncTransferDocumentLinksAsync(transfer, currentUser);
            trail.Note("SyncTransferDocumentLinksAsync completed.");
        }
        catch (Exception ex)
        {
            trail.Bail($"Exception: {ex.Message}");
            await LogAccountingErrorAsync(
                trigger: "Transfer",
                organizationId: transfer.OrganizationId,
                officeId: transfer.OfficeId,
                sourceTypeId: (int)SourceType.Transfer,
                sourceId: transfer.TransferId,
                documentCode: transferLabel,
                accountingPeriod: transfer.AccountingPeriod == default ? null : transfer.AccountingPeriod,
                amount: transfer.Amount,
                message: $"Transfer {transferLabel} journal entry refresh failed: {ex.Message}"
                    + Environment.NewLine + "Bail trail:" + Environment.NewLine + trail.FormatBailTrail(),
                currentUser: currentUser);
        }
    }

    private static void AppendTransferShouldCreateBailReasons(Transfer transfer, AccountingSyncBailTrail trail)
    {
        if (!transfer.IsActive)
            trail.Bail("Reason: transfer IsActive=false.");
        if (transfer.OfficeId <= 0)
            trail.Bail("Reason: OfficeId missing.");
        if (transfer.Amount == 0)
            trail.Bail("Reason: Amount is zero.");
        if (transfer.TransferDate == default)
            trail.Bail("Reason: TransferDate missing.");
        if (transfer.Splits == null || transfer.Splits.Count == 0)
            trail.Bail("Reason: no splits.");
        else
        {
            if (transfer.Splits.Any(split => split.ChartOfAccountId is null or <= 0))
                trail.Bail("Reason: one or more splits missing ChartOfAccountId.");
            if (transfer.Splits.Any(split => split.Amount == 0))
                trail.Bail("Reason: one or more splits have Amount=0.");
            var splitTotal = transfer.Splits.Sum(split => split.Amount);
            if (Math.Abs(splitTotal - transfer.Amount) > 0.005m)
                trail.Bail($"Reason: amount/split mismatch header={transfer.Amount:0.00} splits={splitTotal:0.00}.");
        }
    }

    private async Task<bool> TransferHasHealthJournalEntryAsync(Guid organizationId, int officeId, Guid transferId)
    {
        if (transferId == Guid.Empty)
            return false;

        var bySource = await GetJournalEntriesForSourceAsync(organizationId, officeId, SourceType.Transfer, transferId);
        if (bySource.Count > 0)
            return true;

        var byTransferId = await GetJournalEntriesByTransferIdCachedAsync(organizationId, transferId);
        return byTransferId.Any(entry =>
            entry.SourceTypeId == (int)SourceType.Transfer
            || entry.JournalEntryKindId == JournalEntryKind.Transfer);
    }

    private static void ValidateTransferForJournalEntry(Transfer transfer)
    {
        if (transfer.OfficeId <= 0)
            throw new Exception("OfficeId is required");

        if (transfer.Amount == 0)
            throw new Exception("Transfer amount cannot be zero");

        if (transfer.TransferDate == default)
            throw new Exception("Transfer date is required");

        if (transfer.Splits == null || transfer.Splits.Count == 0)
            throw new Exception("At least one split is required");

        foreach (var split in transfer.Splits)
        {
            if (split.ChartOfAccountId is null or <= 0)
                throw new Exception("Each split must have a chart of account");

            if (split.Amount == 0)
                throw new Exception("Split amounts must be non-zero");
        }

        var splitTotal = transfer.Splits.Sum(split => split.Amount);
        if (Math.Abs(splitTotal - transfer.Amount) > 0.005m)
            throw new Exception($"Transfer amount must equal split total ({splitTotal:0.00})");
    }

    private static bool ShouldCreateJournalEntryForTransfer(Transfer transfer)
        => transfer.IsActive
            && transfer.OfficeId > 0
            && transfer.Amount != 0
            && transfer.TransferDate != default
            && transfer.Splits is { Count: > 0 }
            && transfer.Splits.All(split => split.ChartOfAccountId is > 0 && split.Amount != 0)
            && Math.Abs(transfer.Splits.Sum(split => split.Amount) - transfer.Amount) <= 0.005m;

    private async Task<JournalEntry> BuildJournalEntryFromTransferRecordAsync(Transfer transfer, Guid currentUser)
    {
        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(transfer.OrganizationId, transfer.OfficeId);
        return BuildJournalEntryFromTransferRecord(transfer, chartOfAccounts, accountingOffice, currentUser);
    }

    private JournalEntry BuildJournalEntryFromTransferRecord(Transfer transfer, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // TRANSFER-JE-ACCOUNTS
        // Line 1 — Escrow deposit (transfer.BankAccountId or default escrow deposit):
        //   positive transfer: Debit 0 / Credit escrow deposit
        //   negative transfer: Debit escrow deposit / Credit 0
        // Lines 2+ — One JE line per transfer split (each linked to a source escrow JE line).
        //   positive split: Debit split / Credit 0
        //   negative split: Debit 0 / Credit split
        // END TRANSFER-JE-ACCOUNTS

        var accounts = ResolveTransferJournalEntryAccounts(chartOfAccounts, transfer.OfficeId, accountingOffice);
        var bankAccountId = transfer.BankAccountId is > 0
            ? transfer.BankAccountId.Value
            : accounts.EscrowDepositAccountId;
        var memo = BuildTransferMemo(transfer.TransferCode, transfer.TransferDate);
        var headerLineContext = FirstTransferSplitContext(transfer.Splits) with
        {
            PropertyId = transfer.PropertyId ?? FirstSplitContextId(transfer.Splits, split => split.PropertyId)
        };
        var journalEntryLines = new List<JournalEntryLine>();

        // One debit + matching bank/escrow credit per destination account total (credits sum to transfer amount).
        var destinationAccountTotals = (transfer.Splits ?? [])
            .Where(split => split.ChartOfAccountId is > 0 && split.Amount != 0)
            .GroupBy(split => split.ChartOfAccountId!.Value)
            .Select(group =>
            {
                var amount = Math.Round(group.Sum(split => split.Amount), 2, MidpointRounding.AwayFromZero);
                var orderedSplits = group
                    .OrderBy(split => split.JournalEntryLineId ?? Guid.Empty)
                    .ToList();
                return new
                {
                    ChartOfAccountId = group.Key,
                    Amount = amount,
                    Splits = orderedSplits
                };
            })
            .Where(total => total.Amount != 0)
            .OrderBy(total => GetTransferCreditAccountSortOrder(total.ChartOfAccountId, accounts))
            .ThenBy(total => total.ChartOfAccountId)
            .ToList();

        foreach (var accountTotal in destinationAccountTotals)
        {
            var amount = Math.Abs(accountTotal.Amount);
            var sampleSplit = accountTotal.Splits[0];
            // Line Memo is VARCHAR(250). Aggregated transfers must not use long per-split descriptions
            // or JournalEntryLine_Add fails and the whole update rolls back (Posted JE stays old).
            var lineMemo = TruncateJournalEntryLineMemo(memo);

            var destinationContext = ResolveAggregatedTransferSplitLineContext(accountTotal.Splits, sampleSplit);
            var destinationIsDebit = accountTotal.Amount > 0;

            var destinationLine = new JournalEntryLine
            {
                ChartOfAccountId = accountTotal.ChartOfAccountId,
                Debit = destinationIsDebit ? amount : 0,
                Credit = destinationIsDebit ? 0 : amount,
                Memo = lineMemo,
                CreatedBy = currentUser
            };
            ApplyJournalEntryLineContext(destinationLine, destinationContext);

            var bankLine = new JournalEntryLine
            {
                ChartOfAccountId = bankAccountId,
                Debit = destinationIsDebit ? 0 : amount,
                Credit = destinationIsDebit ? amount : 0,
                Memo = lineMemo,
                CreatedBy = currentUser
            };
            ApplyJournalEntryLineContext(bankLine, headerLineContext);

            // Pair: destination first, then matching escrow/bank credit (display ORDER BY CreatedOn).
            journalEntryLines.Add(destinationLine);
            journalEntryLines.Add(bankLine);
        }

        return ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = transfer.OrganizationId,
            OfficeId = transfer.OfficeId,
            TransactionDate = transfer.TransferDate,
            AccountingPeriod = transfer.AccountingPeriod,
            SourceTypeId = (int)SourceType.Transfer,
            SourceId = transfer.TransferId,
            SourceCode = ResolveJournalEntrySourceCodeFromTransfer(transfer),
            Memo = memo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        }, JournalEntryKind.Transfer, Perspective.Company);
    }

    private TransferJournalEntryAccounts ResolveTransferJournalEntryAccounts(List<ChartOfAccount> chartOfAccounts, int officeId, AccountingOffice? accountingOffice)
    {
        return new TransferJournalEntryAccounts
        {
            EscrowDepositAccountId = GetDefaultEscrowDepositAccount(chartOfAccounts, officeId, accountingOffice),
            EscrowSecurityDepositAccountId = GetDefaultEscrowSecurityDepositAccount(chartOfAccounts, officeId, accountingOffice),
            EscrowSdwAccountId = GetDefaultEscrowSdwAccount(chartOfAccounts, officeId, accountingOffice),
            EscrowOwnersAccountId = GetDefaultEscrowOwnersAccount(chartOfAccounts, officeId, accountingOffice),
            BankAccountId = GetDefaultBankAccount(chartOfAccounts, officeId, accountingOffice)
        };
    }

    private static int GetTransferCreditAccountSortOrder(int chartOfAccountId, TransferJournalEntryAccounts accounts)
    {
        if (chartOfAccountId == accounts.EscrowSecurityDepositAccountId)
            return 0;
        if (chartOfAccountId == accounts.EscrowSdwAccountId)
            return 1;
        if (chartOfAccountId == accounts.EscrowOwnersAccountId)
            return 2;
        if (chartOfAccountId == accounts.BankAccountId)
            return 3;
        return 99;
    }

    private static JournalEntryLineContext ResolveAggregatedTransferSplitLineContext(
        IReadOnlyList<TransferSplit> splits,
        TransferSplit fallbackSplit)
    {
        if (splits.Count == 0)
            return CreateJournalEntryLineContextFromTransferSplit(fallbackSplit);

        if (splits.Count == 1)
            return CreateJournalEntryLineContextFromTransferSplit(splits[0]);

        var propertyIds = splits.Select(split => NormalizeOptionalGuid(split.PropertyId)).Distinct().ToList();
        var reservationIds = splits.Select(split => NormalizeOptionalGuid(split.ReservationId)).Distinct().ToList();
        var contactIds = splits.Select(split => NormalizeOptionalGuid(split.ContactId)).Distinct().ToList();

        // Shared context only when every split in the account total agrees; otherwise leave blank.
        if (propertyIds.Count == 1 && reservationIds.Count == 1 && contactIds.Count == 1)
            return CreateJournalEntryLineContextFromTransferSplit(splits[0]);

        return new JournalEntryLineContext(null, null, null, null, null, null);
    }

    private static string TruncateJournalEntryLineMemo(string? memo, int maxLength = 250)
    {
        var value = (memo ?? string.Empty).Trim();
        if (value.Length <= maxLength)
            return value;
        return value[..maxLength];
    }
    #endregion

    #region Document Link
    private static void ApplyTransferDocumentLink(JournalEntry journalEntry, Transfer transfer)
    {
        if (transfer.TransferId == Guid.Empty)
            return;

        journalEntry.TransferId = transfer.TransferId;
        journalEntry.TransferCode = transfer.TransferCode.Trim();
    }

    private static void ClearTransferDocumentLink(JournalEntry journalEntry)
    {
        journalEntry.TransferId = null;
        journalEntry.TransferCode = null;
    }

    private async Task SyncTransferDocumentLinksAsync(Transfer transfer, Guid currentUser)
    {
        if (transfer.TransferId == Guid.Empty || !transfer.IsActive)
            return;

        if (!await IsAccountingFeatureEnabledAsync(transfer.OrganizationId))
            return;

        await ClearTransferDocumentLinksAsync(transfer.OrganizationId, transfer.TransferId, currentUser);

        var depositIds = await CollectDepositIdsFromTransferSplitsAsync(transfer);
        await SyncDepositTransferIdsForTransferAsync(transfer, depositIds, currentUser);
        foreach (var depositId in depositIds)
        {
            var depositJournalEntries = await GetJournalEntriesByDepositIdCachedAsync(transfer.OrganizationId, depositId);

            foreach (var journalEntry in depositJournalEntries)
            {
                ApplyTransferDocumentLink(journalEntry, transfer);
                journalEntry.ModifiedBy = currentUser;
                await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(journalEntry, requireActiveLines: true);
            }
        }

        var transferJournalEntries = (await GetJournalEntriesByCriteriaCachedAsync(new JournalEntryGetCriteria
        {
            OrganizationId = transfer.OrganizationId,
            OfficeIds = transfer.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.Transfer,
            SourceId = transfer.TransferId,
            StartDate = DateOnly.MinValue,
            IncludeUnposted = true
        })).ToList();

        foreach (var transferJournalEntry in transferJournalEntries)
        {
            ApplyTransferDocumentLink(transferJournalEntry, transfer);
            transferJournalEntry.ModifiedBy = currentUser;
            await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(transferJournalEntry, requireActiveLines: true);
        }
    }

    private async Task ClearTransferDocumentLinksAsync(Guid organizationId, Guid transferId, Guid currentUser)
    {
        if (transferId == Guid.Empty)
            return;

        var linkedEntries = await GetJournalEntriesByTransferIdCachedAsync(organizationId, transferId);

        foreach (var journalEntry in linkedEntries)
        {
            ClearTransferDocumentLink(journalEntry);
            journalEntry.ModifiedBy = currentUser;
            await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(journalEntry, requireActiveLines: true);
        }
    }

    private async Task<HashSet<Guid>> CollectDepositIdsFromTransferSplitsAsync(Transfer transfer)
    {
        var depositIds = new HashSet<Guid>();

        foreach (var split in transfer.Splits ?? [])
        {
            if (split.JournalEntryLineId is not { } journalEntryLineId || journalEntryLineId == Guid.Empty)
                continue;

            if (_officeSyncCache != null && _officeSyncCache.TryGetDepositIdForLine(journalEntryLineId, out var cachedDepositId))
            {
                depositIds.Add(cachedDepositId);
                continue;
            }

            var sourceLine = await GetJournalEntryLineByIdCachedAsync(journalEntryLineId);
            if (sourceLine == null || sourceLine.JournalEntryId == Guid.Empty)
                continue;

            var depositJournalEntry = await GetJournalEntryByIdCachedAsync(
                sourceLine.JournalEntryId,
                transfer.OrganizationId);
            if (depositJournalEntry == null)
                continue;

            var depositId = NormalizeOptionalGuid(depositJournalEntry.DepositId);
            if (depositId == null
                && depositJournalEntry.SourceTypeId == (int)SourceType.Deposit)
            {
                depositId = NormalizeOptionalGuid(depositJournalEntry.SourceId);
            }

            if (depositId == null || depositId == Guid.Empty)
                throw new Exception("Transfer split journal entry line must belong to a journal entry with a deposit link.");

            depositIds.Add(depositId.Value);
        }

        return depositIds;
    }

    private async Task SyncDepositTransferIdsForTransferAsync(Transfer transfer, Guid currentUser)
    {
        if (transfer.TransferId == Guid.Empty)
            return;

        var depositIds = await CollectDepositIdsFromTransferSplitsAsync(transfer);
        await SyncDepositTransferIdsForTransferAsync(transfer, depositIds, currentUser);
    }

    private async Task SyncDepositTransferIdsForTransferAsync(Transfer transfer, IReadOnlyCollection<Guid> depositIds, Guid currentUser)
    {
        if (transfer.TransferId == Guid.Empty)
            return;

        await _accountingRepository.ClearDepositTransferIdsByTransferIdAsync(
            transfer.OrganizationId,
            transfer.TransferId,
            currentUser);

        foreach (var depositId in depositIds)
        {
            if (depositId == Guid.Empty)
                continue;

            await _accountingRepository.SetDepositTransferIdAsync(
                depositId,
                transfer.OrganizationId,
                transfer.TransferId,
                currentUser);
        }
    }
    #endregion
}
