using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Triggers
    public async Task<JournalEntry> CreateJournalEntryFromReceiptAsync(Receipt receipt, Guid currentUser)
    {
        EnsureReceiptIsCardReceipt(receipt);

        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = receipt.OrganizationId,
            OfficeIds = receipt.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.Receipt,
            SourceId = receipt.ReceiptId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        var existingEntry = existingEntries.FirstOrDefault(e => !e.IsVoided);
        if (existingEntry != null)
        {
            if (existingEntry.IsPosted)
                return existingEntry;

            await ReplaceJournalEntriesFromReceiptAsync(receipt, currentUser);
            return (await _journalEntryRepository.GetJournalEntryByIdAsync(existingEntry.JournalEntryId, receipt.OrganizationId))!;
        }

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(receipt.OrganizationId, receipt.OfficeId);
        return await CreateReceiptJournalEntriesAsync(receipt, chartOfAccounts, accountingOffice, currentUser);
    }
    #endregion

    #region Journal Entry
    private async Task<JournalEntry> CreateReceiptJournalEntriesAsync(Receipt receipt, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        var bankCard = await ResolveReceiptBankCardAsync(receipt, accountingOffice);
        var receiptJournalEntry = await BuildJournalEntryFromReceiptAsync(receipt, chartOfAccounts, accountingOffice, currentUser);
        var created = await CreateAutoGeneratedJournalEntryAsync(receiptJournalEntry);

        if (IsCrossOfficeBankCardReceipt(receipt, bankCard))
        {
            var (bankCardChartOfAccounts, bankCardAccountingOffice) = await LoadAccountContextAsync(receipt.OrganizationId, bankCard.OfficeId);
            var companionEntry = BuildCrossOfficeBankCardLiabilityJournalEntryFromReceiptAsync(receipt, bankCardChartOfAccounts, bankCardAccountingOffice, bankCard, currentUser);
            await CreateAutoGeneratedJournalEntryAsync(companionEntry);
        }

        return created;
    }

    private async Task SyncCrossOfficeReceiptCompanionJournalEntryAsync(Receipt receipt, AccountingOffice? receiptAccountingOffice, BankCard bankCard, Guid currentUser)
    {
        await DeleteAllCrossOfficeReceiptCompanionEntriesAsync(receipt);

        if (!IsCrossOfficeBankCardReceipt(receipt, bankCard))
            return;

        var (bankCardChartOfAccounts, bankCardAccountingOffice) = await LoadAccountContextAsync(receipt.OrganizationId, bankCard.OfficeId);
        var companionEntry = BuildCrossOfficeBankCardLiabilityJournalEntryFromReceiptAsync(receipt, bankCardChartOfAccounts, bankCardAccountingOffice, bankCard, currentUser);
        await CreateAutoGeneratedJournalEntryAsync(companionEntry);
    }

    private async Task<JournalEntry> BuildJournalEntryFromReceiptAsync(Receipt receipt, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        EnsureReceiptIsCardReceipt(receipt);
        receipt = await LoadReceiptWithSplitsAsync(receipt);

        if (receipt.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required to create a journal entry for a receipt");

        var bankCard = await ResolveReceiptBankCardAsync(receipt, accountingOffice);
        if (IsCrossOfficeBankCardReceipt(receipt, bankCard))
            return BuildCrossOfficeBankCardJournalEntryFromReceiptAsync(receipt, chartOfAccounts, accountingOffice, currentUser);

        return BuildSameOfficeBankCardJournalEntryFromReceiptAsync(receipt, chartOfAccounts, accountingOffice, bankCard, currentUser);
    }

    private JournalEntry BuildSameOfficeBankCardJournalEntryFromReceiptAsync(Receipt receipt, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, BankCard bankCard, Guid currentUser)
    {
        var splitLines = ResolveDocumentSplitLines(receipt);
        var creditCardAccountId = GetCreditCardAccountId(bankCard);
        var transactionDate = receipt.AccountingPeriod;
        var postingDate = receipt.AccountingPeriod;
        var receiptLabel = receipt.ReceiptCode.Trim();
        var memo = string.IsNullOrWhiteSpace(receipt.Description)
            ? $"Receipt {receiptLabel}"
            : receipt.Description.Trim();
        var propertyId = receipt.PropertyIds.FirstOrDefault(id => id != Guid.Empty);

        var totalAmount = splitLines.Sum(s => s.Amount);
        var journalEntryLines = new List<JournalEntryLine>();
        var (creditCardDebit, creditCardCredit) = SignedAmountToDebitCredit(totalAmount, positiveIsDebit: false);
        journalEntryLines.Add(new JournalEntryLine
        {
            ChartOfAccountId = creditCardAccountId,
            PropertyId = propertyId == Guid.Empty ? null : propertyId,
            ContactId = receipt.VendorId,
            Debit = creditCardDebit,
            Credit = creditCardCredit,
            Memo = $"Credit Card - {receipt.BankCardDisplayName}".Trim(),
            CreatedBy = currentUser
        });

        foreach (var split in splitLines)
        {
            var expenseAccountId = GetBillReceiptExpenseAccountId(split, receipt.OfficeId, chartOfAccounts, accountingOffice);
            var (expenseDebit, expenseCredit) = SignedAmountToDebitCredit(split.Amount, positiveIsDebit: true);

            journalEntryLines.Add(new JournalEntryLine
            {
                ChartOfAccountId = expenseAccountId,
                PropertyId = propertyId == Guid.Empty ? null : propertyId,
                ContactId = receipt.VendorId,
                Debit = expenseDebit,
                Credit = expenseCredit,
                Memo = split.Amount < 0 && string.IsNullOrWhiteSpace(split.Description)
                    ? $"Receipt Credit - {receiptLabel}"
                    : split.Description,
                CreatedBy = currentUser
            });
        }

        return new JournalEntry
        {
            OrganizationId = receipt.OrganizationId,
            OfficeId = receipt.OfficeId,
            TransactionDate = transactionDate,
            PostingDate = postingDate,
            SourceTypeId = (int)SourceType.Receipt,
            SourceId = receipt.ReceiptId,
            Memo = memo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };
    }

    private JournalEntry BuildCrossOfficeBankCardJournalEntryFromReceiptAsync(Receipt receipt, List<ChartOfAccount> receiptChartOfAccounts, AccountingOffice? receiptAccountingOffice, Guid currentUser)
    {
        var splitLines = ResolveDocumentSplitLines(receipt);
        var accountsReceivableAccountId = GetDefaultAccountsReceivable(receiptChartOfAccounts, receipt.OfficeId, receiptAccountingOffice);
        var transactionDate = receipt.AccountingPeriod;
        var postingDate = receipt.AccountingPeriod;
        var receiptLabel = receipt.ReceiptCode.Trim();
        var memo = string.IsNullOrWhiteSpace(receipt.Description)
            ? $"Receipt {receiptLabel}"
            : receipt.Description.Trim();
        var propertyId = receipt.PropertyIds.FirstOrDefault(id => id != Guid.Empty);
        var totalAmount = splitLines.Sum(s => s.Amount);
        var journalEntryLines = new List<JournalEntryLine>();

        foreach (var split in splitLines)
        {
            var expenseAccountId = GetBillReceiptExpenseAccountId(split, receipt.OfficeId, receiptChartOfAccounts, receiptAccountingOffice);
            var (expenseDebit, expenseCredit) = SignedAmountToDebitCredit(split.Amount, positiveIsDebit: true);

            journalEntryLines.Add(new JournalEntryLine
            {
                ChartOfAccountId = expenseAccountId,
                PropertyId = propertyId == Guid.Empty ? null : propertyId,
                ContactId = receipt.VendorId,
                Debit = expenseDebit,
                Credit = expenseCredit,
                Memo = split.Amount < 0 && string.IsNullOrWhiteSpace(split.Description)
                    ? $"Receipt Credit - {receiptLabel}"
                    : split.Description,
                CreatedBy = currentUser
            });
        }

        var (accountsReceivableDebit, accountsReceivableCredit) = SignedAmountToDebitCredit(totalAmount, positiveIsDebit: false);
        journalEntryLines.Add(new JournalEntryLine
        {
            ChartOfAccountId = accountsReceivableAccountId,
            PropertyId = propertyId == Guid.Empty ? null : propertyId,
            ContactId = receipt.VendorId,
            Debit = accountsReceivableDebit,
            Credit = accountsReceivableCredit,
            Memo = $"Accounts Receivable - {receiptLabel}",
            CreatedBy = currentUser
        });

        return new JournalEntry
        {
            OrganizationId = receipt.OrganizationId,
            OfficeId = receipt.OfficeId,
            TransactionDate = transactionDate,
            PostingDate = postingDate,
            SourceTypeId = (int)SourceType.Receipt,
            SourceId = receipt.ReceiptId,
            Memo = memo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };
    }

    private JournalEntry BuildCrossOfficeBankCardLiabilityJournalEntryFromReceiptAsync(Receipt receipt, List<ChartOfAccount> bankCardOfficeChartOfAccounts, AccountingOffice? bankCardAccountingOffice, BankCard bankCard, Guid currentUser)
    {
        var splitLines = ResolveDocumentSplitLines(receipt);
        var accountsReceivableAccountId = GetDefaultAccountsReceivable(bankCardOfficeChartOfAccounts, bankCard.OfficeId, bankCardAccountingOffice);
        var creditCardAccountId = GetCreditCardAccountId(bankCard);
        var transactionDate = receipt.AccountingPeriod;
        var postingDate = receipt.AccountingPeriod;
        var receiptLabel = receipt.ReceiptCode.Trim();
        var receiptOfficeLabel = GetReceiptOfficeLabel(receipt);
        var memo = string.IsNullOrWhiteSpace(receipt.Description)
            ? $"Receipt {receiptLabel}"
            : receipt.Description.Trim();
        var propertyId = receipt.PropertyIds.FirstOrDefault(id => id != Guid.Empty);
        var totalAmount = splitLines.Sum(s => s.Amount);
        var journalEntryLines = new List<JournalEntryLine>();

        var (accountsReceivableDebit, accountsReceivableCredit) = SignedAmountToDebitCredit(totalAmount, positiveIsDebit: true);
        journalEntryLines.Add(new JournalEntryLine
        {
            ChartOfAccountId = accountsReceivableAccountId,
            PropertyId = propertyId == Guid.Empty ? null : propertyId,
            ContactId = receipt.VendorId,
            Debit = accountsReceivableDebit,
            Credit = accountsReceivableCredit,
            Memo = $"Accounts Receivable - {receiptOfficeLabel}",
            CreatedBy = currentUser
        });

        var (creditCardDebit, creditCardCredit) = SignedAmountToDebitCredit(totalAmount, positiveIsDebit: false);
        journalEntryLines.Add(new JournalEntryLine
        {
            ChartOfAccountId = creditCardAccountId,
            PropertyId = propertyId == Guid.Empty ? null : propertyId,
            ContactId = receipt.VendorId,
            Debit = creditCardDebit,
            Credit = creditCardCredit,
            Memo = $"Credit Card - {receipt.BankCardDisplayName}".Trim(),
            CreatedBy = currentUser
        });

        return new JournalEntry
        {
            OrganizationId = receipt.OrganizationId,
            OfficeId = bankCard.OfficeId,
            TransactionDate = transactionDate,
            PostingDate = postingDate,
            SourceTypeId = (int)SourceType.CreditCard,
            SourceId = receipt.ReceiptId,
            Memo = memo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };
    }
    #endregion

    #region Bank Card Helpers
    private async Task<BankCard> ResolveReceiptBankCardAsync(Receipt receipt, AccountingOffice? receiptAccountingOffice)
    {
        if (receipt.BankCardId is not > 0)
            throw new Exception("BankCardId is required to resolve a bank card");

        var bankCard = receiptAccountingOffice?.BankCards
            .FirstOrDefault(card => card.BankCardId == receipt.BankCardId.Value);
        if (bankCard != null)
            return bankCard;

        var offices = await _organizationRepository.GetOfficesByOrganizationIdAsync(receipt.OrganizationId);
        var officeIds = string.Join(',', offices.Select(office => office.OfficeId));
        if (string.IsNullOrWhiteSpace(officeIds))
            throw new Exception("Bank card not found for organization");

        var organizationBankCards = await _accountingRepository.GetBankCardsByOfficeIdsAsync(receipt.OrganizationId, officeIds);
        bankCard = organizationBankCards.FirstOrDefault(card => card.BankCardId == receipt.BankCardId.Value);
        if (bankCard == null)
            throw new Exception("Bank card not found for organization");

        return bankCard;
    }

    private async Task DeleteAllCrossOfficeReceiptCompanionEntriesAsync(Receipt receipt)
    {
        var offices = await _organizationRepository.GetOfficesByOrganizationIdAsync(receipt.OrganizationId);
        foreach (var office in offices)
        {
            await DeleteJournalEntriesForSourceAsync(
                receipt.OrganizationId,
                office.OfficeId,
                (int)SourceType.CreditCard,
                receipt.ReceiptId);
        }
    }

    private static bool IsCrossOfficeBankCardReceipt(Receipt receipt, BankCard bankCard)
        => bankCard.OfficeId != receipt.OfficeId;

    private static string GetReceiptOfficeLabel(Receipt receipt)
        => string.IsNullOrWhiteSpace(receipt.OfficeName) ? receipt.ReceiptCode.Trim() : receipt.OfficeName.Trim();

    private static int GetCreditCardAccountId(BankCard bankCard)
    {
        if (bankCard.ChartOfAccountId is not > 0)
            throw new Exception("Bank card must have a chart of account configured");

        return bankCard.ChartOfAccountId.Value;
    }

    private static void EnsureReceiptIsCardReceipt(Receipt receipt)
    {
        if (receipt.BankCardId is not > 0)
            throw new Exception("Receipt is not a card receipt");
    }
    #endregion
}
