using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Triggers
    public async Task<JournalEntry> CreateJournalEntryFromReceiptAsync(Receipt receipt, Guid currentUser)
    {
        EnsureReceiptIsCardReceipt(receipt);

        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = receipt.OrganizationId,
            OfficeIds = receipt.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.Receipt,
            SourceId = receipt.ReceiptId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        var existingEntry = existingEntries.FirstOrDefault(e => !e.IsVoided);
        if (existingEntry != null)
        {
            if (existingEntry.IsPosted)
                return existingEntry;

            await ReplaceJournalEntriesFromReceiptAsync(receipt, currentUser);
            return (await _journalEntryRepository.GetJournalEntryByIdAsync(existingEntry.JournalEntryId, receipt.OrganizationId))!;
        }

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(receipt.OrganizationId, receipt.OfficeId);
        var journalEntry = await BuildJournalEntryFromReceiptAsync(receipt, chartOfAccounts, accountingOffice, currentUser);
        return await CreateAutoGeneratedJournalEntryAsync(journalEntry);
    }
    #endregion

    #region Journal Entry
    async Task<JournalEntry> BuildJournalEntryFromReceiptAsync(Receipt receipt, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        EnsureReceiptIsCardReceipt(receipt);
        receipt = await LoadReceiptWithSplitsAsync(receipt);

        var splitLines = ResolveDocumentSplitLines(receipt);

        if (receipt.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required to create a journal entry for a receipt");

        var creditCardAccountId = GetCreditCardAccountId(receipt, chartOfAccounts, accountingOffice);
        var defaultExpenseAccountId = GetCompanyExpenseAccountId(chartOfAccounts, receipt.OfficeId, accountingOffice);
        var defaultCostOfGoodsSoldAccountId = GetCostOfGoodsSoldAccountIdByNameOrType(chartOfAccounts, receipt.OfficeId);

        var transactionDate = receipt.ReceiptDate != default ? receipt.ReceiptDate : receipt.AccountingPeriod;
        var postingDate = receipt.AccountingPeriod;
        var receiptLabel = receipt.ReceiptCode.Trim();
        var memo = string.IsNullOrWhiteSpace(receipt.Description)
            ? $"Receipt {receiptLabel}"
            : receipt.Description.Trim();
        var propertyId = receipt.PropertyIds.FirstOrDefault(id => id != Guid.Empty);

        var totalAmount = splitLines.Sum(s => s.Amount);
        var journalEntryLines = new List<JournalEntryLine>();
        var (creditCardDebit, creditCardCredit) = SignedAmountToDebitCredit(totalAmount, positiveIsDebit: false);
        journalEntryLines.Add(new JournalEntryLine
        {
            ChartOfAccountId = creditCardAccountId,
            PropertyId = propertyId == Guid.Empty ? null : propertyId,
            ContactId = receipt.VendorId,
            Debit = creditCardDebit,
            Credit = creditCardCredit,
            Memo = $"Credit Card - {receipt.BankCardDisplayName}".Trim(),
            CreatedBy = currentUser
        });

        foreach (var split in splitLines)
        {
            var expenseAccountId = GetExpenseOrCogsAccountId(
                chartOfAccounts,
                receipt.OfficeId,
                split,
                defaultCostOfGoodsSoldAccountId,
                defaultExpenseAccountId);
            var (expenseDebit, expenseCredit) = SignedAmountToDebitCredit(split.Amount, positiveIsDebit: true);

            journalEntryLines.Add(new JournalEntryLine
            {
                ChartOfAccountId = expenseAccountId,
                PropertyId = propertyId == Guid.Empty ? null : propertyId,
                ContactId = receipt.VendorId,
                Debit = expenseDebit,
                Credit = expenseCredit,
                Memo = split.Amount < 0 && string.IsNullOrWhiteSpace(split.Description)
                    ? $"Receipt Credit - {receiptLabel}"
                    : split.Description,
                CreatedBy = currentUser
            });
        }

        return new JournalEntry
        {
            OrganizationId = receipt.OrganizationId,
            OfficeId = receipt.OfficeId,
            TransactionDate = transactionDate,
            PostingDate = postingDate,
            SourceTypeId = (int)SourceType.Receipt,
            SourceId = receipt.ReceiptId,
            Memo = memo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };
    }
    #endregion

    #region Static Helpers
    static void EnsureReceiptIsCardReceipt(Receipt receipt)
    {
        if (receipt.BankCardId is not > 0)
            throw new Exception("Receipt is not a card receipt");
    }
    #endregion
}
