using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Journal Entry
    public async Task<List<JournalEntry>> CreateJournalEntriesFromOwnerPaymentDocumentAsync(Guid paymentId, Guid organizationId, Guid currentUser)
    {
        var journalEntries = new List<JournalEntry>();

        if (paymentId == Guid.Empty)
            return journalEntries;

        if (!await IsAccountingFeatureEnabledAsync(organizationId))
            return journalEntries;

        Payment? payment = null;
        if (_officeSyncCache != null && _officeSyncCache.PaymentsById.TryGetValue(paymentId, out var cachedPayment))
            payment = cachedPayment;
        else
            payment = await _accountingRepository.GetPaymentByIdAsync(paymentId, organizationId);

        if (payment == null)
            throw new Exception("Payment record not found");

        if (payment.OwnerAllocations.Count == 0)
            payment = await _accountingRepository.GetPaymentByIdAsync(paymentId, organizationId)
                ?? throw new Exception("Payment record not found");

        if (payment.PaymentKindId != (int)PaymentKind.Owner)
            throw new Exception("Payment is not an owner payment.");

        if (payment.OwnerAllocations.Count == 0)
            return journalEntries;

        if (payment.ChartOfAccountId is not > 0)
            throw new Exception("ChartOfAccountId is required for owner payment journal entries.");

        var applications = new List<OwnerPaymentApplication>();
        foreach (var allocation in payment.OwnerAllocations.OrderBy(item => item.LineNumber))
        {
            applications.Add(new OwnerPaymentApplication
            {
                OrganizationId = payment.OrganizationId,
                OfficeId = payment.OfficeId,
                OwnerId = allocation.OwnerId,
                PropertyId = allocation.PropertyId,
                PropertyCode = allocation.PropertyCode,
                OwnerName = NormalizeOptionalString(allocation.OwnerName),
                AmountApplied = allocation.Amount,
                PaymentDate = payment.PaymentDate,
                ChartOfAccountId = payment.ChartOfAccountId.Value,
                Description = string.IsNullOrWhiteSpace(allocation.Description) ? payment.Description : allocation.Description.Trim(),
                PaymentType = payment.PaymentTypeId is > 0 ? (PaymentType)payment.PaymentTypeId.Value : PaymentType.Ach,
                PaymentId = payment.PaymentId,
                PaymentCode = payment.PaymentCode
            });
        }

        await DeleteOwnerPaymentJournalEntriesAsync(payment);

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(payment.OrganizationId, payment.OfficeId);
        var journalEntry = BuildConsolidatedOwnerPaymentJournalEntry(payment, applications, chartOfAccounts, accountingOffice, currentUser);

        var created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);
        if (created != null)
        {
            ApplyPaymentDocumentLink(created, payment);
            created.ModifiedBy = currentUser;
            await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(created, requireActiveLines: true);
            journalEntries.Add(created);
        }

        return journalEntries;
    }

    public async Task<List<JournalEntry>> CreateJournalEntriesFromOwnerPaymentAsync(OwnerPaymentBatch ownerPaymentBatch, Guid currentUser)
    {
        var journalEntries = new List<JournalEntry>();
        if (ownerPaymentBatch.PaymentApplications.Count == 0)
            return journalEntries;

        foreach (var paymentApplication in ownerPaymentBatch.PaymentApplications)
        {
            var journalEntry = await CreateJournalEntryFromOwnerPaymentAsync(paymentApplication, currentUser);
            if (journalEntry != null)
                journalEntries.Add(journalEntry);
        }

        return journalEntries;
    }

    private async Task<bool> PaymentHasHealthOwnerPaymentJournalEntryAsync(Guid paymentId, Guid organizationId)
    {
        if (paymentId == Guid.Empty)
            return false;

        var linkedEntries = await GetJournalEntriesByPaymentIdCachedAsync(organizationId, paymentId);
        if (linkedEntries.Any(entry =>
                entry.JournalEntryKindId == JournalEntryKind.BillPayment
                && entry.PaymentId is { } linkedPaymentId
                && linkedPaymentId == paymentId))
            return true;

        Payment? payment = null;
        if (_officeSyncCache != null && _officeSyncCache.PaymentsById.TryGetValue(paymentId, out var cachedPayment))
            payment = cachedPayment;
        else
            payment = await _accountingRepository.GetPaymentByIdAsync(paymentId, organizationId);

        if (payment == null)
            return false;

        var documentEntries = await GetJournalEntriesForSourceAsync(
            payment.OrganizationId,
            payment.OfficeId,
            SourceType.OwnerDistribution,
            paymentId);

        return documentEntries.Any(entry => entry.JournalEntryKindId == JournalEntryKind.BillPayment);
    }

    private async Task SyncOwnerPaymentJournalEntryAsync(Payment paymentSummary, Guid organizationId, Guid currentUser, JournalEntrySyncResult result)
    {
        if (paymentSummary.OwnerAllocations.Count == 0)
        {
            result.JournalEntriesSkipped++;
            return;
        }

        await CreateJournalEntriesFromOwnerPaymentDocumentAsync(paymentSummary.PaymentId, organizationId, currentUser);

        if (await PaymentHasHealthOwnerPaymentJournalEntryAsync(paymentSummary.PaymentId, organizationId))
        {
            result.JournalEntriesCreated++;
            return;
        }

        result.JournalEntriesSkipped++;

        Payment? payment = null;
        if (_officeSyncCache != null && _officeSyncCache.PaymentsById.TryGetValue(paymentSummary.PaymentId, out var cachedPayment))
            payment = cachedPayment;
        else
            payment = await _accountingRepository.GetPaymentByIdAsync(paymentSummary.PaymentId, organizationId);

        var message = $"Owner payment {ResolvePaymentDocumentCode(payment, paymentSummary)}: no OwnerDistribution JE with PaymentId after sync.";
        await LogAccountingErrorAsync(
            trigger: "OwnerPaymentSkip",
            organizationId: organizationId,
            officeId: paymentSummary.OfficeId,
            sourceTypeId: (int)SourceType.OwnerDistribution,
            sourceId: paymentSummary.PaymentId,
            documentCode: ResolvePaymentDocumentCode(payment, paymentSummary),
            accountingPeriod: null,
            amount: paymentSummary.Amount,
            message: message,
            currentUser: currentUser);
        result.Errors.Add(message);
    }

    private async Task<JournalEntry?> CreateJournalEntryFromOwnerPaymentAsync(OwnerPaymentApplication paymentApplication, Guid currentUser)
        => (await CreateJournalEntryFromOwnerPaymentWithResultAsync(paymentApplication, currentUser)).JournalEntry;

    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromOwnerPaymentWithResultAsync(OwnerPaymentApplication paymentApplication, Guid currentUser)
    {
        if (paymentApplication.AmountApplied == 0)
            return AccountingJournalEntryResult.WarningResult("Owner payment amount cannot be zero");

        if (paymentApplication.PaymentDate == default)
            return AccountingJournalEntryResult.WarningResult("Payment date is required to create an owner payment journal entry");

        if (paymentApplication.ChartOfAccountId <= 0)
            return AccountingJournalEntryResult.WarningResult("Chart of account is required for owner payment");

        try
        {
            if (!await IsAccountingFeatureEnabledAsync(paymentApplication.OrganizationId))
                return AccountingJournalEntryResult.Success();

            var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(paymentApplication.OrganizationId, paymentApplication.OfficeId);
            var journalEntry = BuildJournalEntryFromOwnerPayment(paymentApplication, chartOfAccounts, accountingOffice, currentUser);
            var created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);
            return AccountingJournalEntryResult.Success(created);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "OwnerPayment",
                organizationId: paymentApplication.OrganizationId,
                officeId: paymentApplication.OfficeId,
                sourceTypeId: (int)SourceType.OwnerDistribution,
                sourceId: paymentApplication.PropertyId,
                documentCode: paymentApplication.PropertyCode,
                accountingPeriod: paymentApplication.PaymentDate == default ? null : FirstDayOfMonth(paymentApplication.PaymentDate),
                amount: paymentApplication.AmountApplied,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    private JournalEntry BuildJournalEntryFromOwnerPayment(OwnerPaymentApplication paymentApplication, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // OWNER-PAYMENT-JE-ACCOUNTS
        // Line 1 — Debit: Owner Accounts Payable (GetDefaultOwnerAccountsPayable).
        // Line 2 — Credit: Bank account selected on the payment (paymentApplication.ChartOfAccountId).
        // END OWNER-PAYMENT-JE-ACCOUNTS

        var amount = paymentApplication.AmountApplied;
        var ownerAccountsPayableAccountId = GetDefaultOwnerAccountsPayable(chartOfAccounts, paymentApplication.OfficeId, accountingOffice);
        var paymentBankAccountId = paymentApplication.ChartOfAccountId;
        var memo = BuildOwnerStatementPaymentMemo(paymentApplication.PropertyCode, paymentApplication.Description);
        var lineContext = new JournalEntryLineContext(
            paymentApplication.PropertyId,
            paymentApplication.PropertyCode,
            null,
            null,
            paymentApplication.OwnerId,
            paymentApplication.OwnerName);
        var ownerPayableLine = new JournalEntryLine
        {
            ChartOfAccountId = ownerAccountsPayableAccountId,
            Debit = amount > 0 ? amount : 0,
            Credit = amount < 0 ? Math.Abs(amount) : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(ownerPayableLine, lineContext);
        var paymentLine = new JournalEntryLine
        {
            ChartOfAccountId = paymentBankAccountId,
            Debit = amount < 0 ? Math.Abs(amount) : 0,
            Credit = amount > 0 ? amount : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(paymentLine, lineContext);

        return ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = paymentApplication.OrganizationId,
            OfficeId = paymentApplication.OfficeId,
            TransactionDate = paymentApplication.PaymentDate,
            AccountingPeriod = FirstDayOfMonth(paymentApplication.PaymentDate),
            SourceTypeId = (int)SourceType.OwnerDistribution,
            SourceId = paymentApplication.PropertyId,
            SourceCode = paymentApplication.PropertyCode,
            Memo = memo,
            JournalEntryLines = new List<JournalEntryLine> { ownerPayableLine, paymentLine },
            CreatedBy = currentUser
        }, JournalEntryKind.BillPayment, Perspective.Owner);
    }

    private JournalEntry BuildConsolidatedOwnerPaymentJournalEntry(Payment payment, IReadOnlyList<OwnerPaymentApplication> applications, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        if (payment.Amount == 0)
            throw new Exception("Payment amount cannot be zero");

        if (applications.Count == 0)
            throw new Exception("At least one owner allocation is required.");

        var bankAccountId = payment.ChartOfAccountId ?? 0;
        if (bankAccountId <= 0)
            throw new Exception("Chart of account is required for owner payment");

        var ownerAccountsPayableAccountId = GetDefaultOwnerAccountsPayable(chartOfAccounts, payment.OfficeId, accountingOffice);
        var journalEntryLines = new List<JournalEntryLine>();
        var applicationMemos = new List<string>();
        JournalEntryLineContext? bankLineContext = null;

        foreach (var application in applications)
        {
            if (application.AmountApplied == 0)
                continue;

            var memo = BuildOwnerStatementPaymentMemo(application.PropertyCode, application.Description);
            applicationMemos.Add(memo);
            var lineContext = new JournalEntryLineContext(
                application.PropertyId,
                application.PropertyCode,
                null,
                null,
                application.OwnerId,
                application.OwnerName);
            bankLineContext ??= lineContext;

            var ownerPayableLine = new JournalEntryLine
            {
                ChartOfAccountId = ownerAccountsPayableAccountId,
                Debit = application.AmountApplied > 0 ? application.AmountApplied : 0,
                Credit = application.AmountApplied < 0 ? Math.Abs(application.AmountApplied) : 0,
                Memo = memo,
                CreatedBy = currentUser
            };
            ApplyJournalEntryLineContext(ownerPayableLine, lineContext);
            journalEntryLines.Add(ownerPayableLine);
        }

        var bankLineMemo = applicationMemos.Count == 1
            ? applicationMemos[0]
            : string.Join(" | ", applicationMemos.Where(memo => !string.IsNullOrWhiteSpace(memo)));
        if (string.IsNullOrWhiteSpace(bankLineMemo))
            bankLineMemo = payment.Description?.Trim() ?? string.Empty;

        var bankLine = new JournalEntryLine
        {
            ChartOfAccountId = bankAccountId,
            Debit = payment.Amount < 0 ? Math.Abs(payment.Amount) : 0,
            Credit = payment.Amount > 0 ? payment.Amount : 0,
            Memo = bankLineMemo,
            CreatedBy = currentUser
        };
        if (bankLineContext is { } resolvedBankLineContext)
            ApplyJournalEntryLineContext(bankLine, resolvedBankLineContext);

        journalEntryLines.Add(bankLine);

        return ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = payment.OrganizationId,
            OfficeId = payment.OfficeId,
            TransactionDate = payment.PaymentDate,
            AccountingPeriod = FirstDayOfMonth(payment.PaymentDate),
            SourceTypeId = (int)SourceType.OwnerDistribution,
            SourceId = payment.PaymentId,
            SourceCode = payment.PaymentCode,
            Memo = bankLineMemo,
            PaymentId = payment.PaymentId,
            PaymentCode = payment.PaymentCode,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        }, JournalEntryKind.BillPayment, Perspective.Owner);
    }

    private async Task DeleteOwnerPaymentJournalEntriesAsync(Payment payment)
    {
        var linkedEntries = await GetJournalEntriesByPaymentIdCachedAsync(payment.OrganizationId, payment.PaymentId);
        foreach (var journalEntry in linkedEntries)
            await DeleteOpenJournalEntryAsync(journalEntry.JournalEntryId, payment.OrganizationId);

        var documentEntries = await GetJournalEntriesForSourceAsync(payment.OrganizationId, payment.OfficeId, SourceType.OwnerDistribution, payment.PaymentId);

        foreach (var journalEntry in documentEntries)
            await DeleteOpenJournalEntryAsync(journalEntry.JournalEntryId, payment.OrganizationId);
    }

    private static string BuildOwnerStatementPaymentMemo(string propertyCode, string paymentReference)
    {
        if (string.IsNullOrWhiteSpace(propertyCode))
            throw new ArgumentException("Property code is required.", nameof(propertyCode));
        if (string.IsNullOrWhiteSpace(paymentReference))
            throw new ArgumentException("Payment reference is required.", nameof(paymentReference));

        return $"{propertyCode.Trim()}: Owner: Payment: {paymentReference.Trim()}";
    }
    #endregion
}
