using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    private static JournalEntry ClassifyJournalEntry(JournalEntry journalEntry, JournalEntryKind kind, Perspective linePerspective)
    {
        journalEntry.JournalEntryKindId = kind;
        ApplyUniformLinePerspective(journalEntry, linePerspective);
        return journalEntry;
    }

    private static JournalEntry ClassifyJournalEntryKind(JournalEntry journalEntry, JournalEntryKind kind)
    {
        journalEntry.JournalEntryKindId = kind;
        return journalEntry;
    }

    private static void ApplyUniformLinePerspective(JournalEntry journalEntry, Perspective perspective)
    {
        foreach (var line in journalEntry.JournalEntryLines)
            line.PerspectiveId = perspective;
    }

    private static void ApplyReceiptSplitLinePerspective(JournalEntryLine line, ReceiptSplit split)
        => line.PerspectiveId = PerspectiveFromReceiptType(split.ReceiptType);

    private static Perspective PerspectiveFromReceiptType(ReceiptType receiptType)
        => receiptType is ReceiptType.Tenant or ReceiptType.Owner or ReceiptType.Company
            ? (Perspective)(int)receiptType
            : Perspective.Company;

    private static void ApplyManualJournalEntryClassification(JournalEntry journalEntry)
    {
        if (journalEntry.JournalEntryKindId == JournalEntryKind.OwnerStartingBalance)
        {
            journalEntry.SourceTypeId = (int)SourceType.Journal;
            ApplyUniformLinePerspective(journalEntry, Perspective.Owner);
            return;
        }

        if (MatchOwnerStartingBalanceMemo(journalEntry.Memo).IsMatch)
        {
            journalEntry.SourceTypeId = (int)SourceType.Journal;
            journalEntry.JournalEntryKindId = JournalEntryKind.OwnerStartingBalance;
            ApplyUniformLinePerspective(journalEntry, Perspective.Owner);
            return;
        }

        journalEntry.SourceTypeId = (int)SourceType.Journal;
        journalEntry.JournalEntryKindId = JournalEntryKind.Manual;
    }

    private static void EnsureAutoGeneratedJournalEntryClassification(JournalEntry journalEntry)
    {
        if (journalEntry.SourceTypeId == (int)SourceType.Journal)
            return;

        if (journalEntry.JournalEntryKindId != JournalEntryKind.Manual)
            return;

        throw new Exception("Auto-generated journal entries must set JournalEntryKindId before save.");
    }
}
