using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Journal Entry
    public async Task<List<JournalEntry>> CreateJournalEntriesFromBillPaymentDocumentAsync(Guid paymentId, Guid organizationId, Guid currentUser)
    {
        var journalEntries = new List<JournalEntry>();

        if (paymentId == Guid.Empty)
            return journalEntries;

        if (!await IsAccountingFeatureEnabledAsync(organizationId))
            return journalEntries;

        var payment = await _accountingRepository.GetPaymentByIdAsync(paymentId, organizationId);
        if (payment == null)
            throw new Exception("Payment record not found");

        if (payment.PaymentDirectionId != (int)PaymentDirection.Outbound)
            throw new Exception("Payment is not a bill payment.");

        if (payment.BillAllocations.Count == 0)
            return journalEntries;

        if (payment.ChartOfAccountId is not > 0)
            throw new Exception("ChartOfAccountId is required for bill payment journal entries.");

        var applications = new List<BillPaymentApplication>();
        foreach (var allocation in payment.BillAllocations.OrderBy(item => item.LineNumber))
        {
            var bill = await _maintenanceRepository.GetReceiptByIdAsync(allocation.ReceiptId, organizationId)
                ?? throw new Exception($"Bill not found: {allocation.ReceiptCode}");

            bill = await LoadReceiptWithSplitsAsync(bill);
            applications.Add(new BillPaymentApplication
            {
                Bill = bill,
                AmountApplied = allocation.Amount,
                PaymentDate = payment.PaymentDate,
                ChartOfAccountId = payment.ChartOfAccountId.Value,
                Description = string.IsNullOrWhiteSpace(allocation.Description) ? payment.Description : allocation.Description,
                PaymentSequence = 0,
                CostCodeId = allocation.CostCodeId
            });
        }

        await DeleteBillPaymentJournalEntriesAsync(payment);

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(payment.OrganizationId, payment.OfficeId);
        var journalEntry = await BuildConsolidatedBillPaymentJournalEntryAsync(payment, applications, chartOfAccounts, accountingOffice, currentUser);

        var created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);
        if (created != null)
        {
            ApplyPaymentDocumentLink(created, payment);
            created.ModifiedBy = currentUser;
            await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(created, requireActiveLines: true);
            journalEntries.Add(created);
        }

        return journalEntries;
    }
    #endregion

    #region Helpers
    private async Task DeleteBillPaymentJournalEntriesAsync(Payment payment)
    {
        var linkedEntries = await GetJournalEntriesByPaymentIdCachedAsync(payment.OrganizationId, payment.PaymentId);
        foreach (var journalEntry in linkedEntries)
            await DeleteOpenJournalEntryAsync(journalEntry.JournalEntryId, payment.OrganizationId);

        var documentEntries = await GetJournalEntriesForSourceAsync(payment.OrganizationId, payment.OfficeId, SourceType.BillPayment, payment.PaymentId);

        foreach (var journalEntry in documentEntries)
            await DeleteOpenJournalEntryAsync(journalEntry.JournalEntryId, payment.OrganizationId);
    }

    private async Task<JournalEntry> BuildConsolidatedBillPaymentJournalEntryAsync(Payment payment, IReadOnlyList<BillPaymentApplication> applications, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        if (payment.Amount == 0)
            throw new Exception("Payment amount cannot be zero");

        if (applications.Count == 0)
            throw new Exception("At least one bill allocation is required.");

        var bankAccountId = payment.ChartOfAccountId ?? 0;
        if (bankAccountId <= 0)
            throw new Exception("Chart of account is required for bill payment");

        var paymentMemo = payment.Description?.Trim() ?? string.Empty;
        var journalEntryLines = new List<JournalEntryLine>();
        var totalAmount = payment.Amount;

        var bankLine = new JournalEntryLine
        {
            ChartOfAccountId = bankAccountId,
            Debit = totalAmount < 0 ? Math.Abs(totalAmount) : 0,
            Credit = totalAmount > 0 ? totalAmount : 0,
            Memo = paymentMemo,
            CreatedBy = currentUser
        };
        journalEntryLines.Add(bankLine);

        foreach (var application in applications)
        {
            var bill = application.Bill
                ?? throw new Exception("Bill is required to create a bill payment journal entry.");

            if (application.AmountApplied == 0)
                continue;

            var payableOrCardAccountId = bill.BankCardId is > 0
                ? GetCreditCardAccountId(bill, chartOfAccounts, accountingOffice)
                : GetDefaultAccountsPayable(chartOfAccounts, bill.OfficeId, accountingOffice);

            var amount = application.AmountApplied;
            var lineContext = await ResolveReceiptJournalEntryLineContextAsync(bill);
            var payableLine = new JournalEntryLine
            {
                ChartOfAccountId = payableOrCardAccountId,
                Debit = amount > 0 ? amount : 0,
                Credit = amount < 0 ? Math.Abs(amount) : 0,
                Memo = string.IsNullOrWhiteSpace(application.Description) ? paymentMemo : application.Description.Trim(),
                CreatedBy = currentUser
            };
            ApplyJournalEntryLineContext(payableLine, lineContext);

            if (application.CostCodeId is > 0)
                payableLine.CostCodeId = application.CostCodeId;

            journalEntryLines.Add(payableLine);
        }

        return ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = payment.OrganizationId,
            OfficeId = payment.OfficeId,
            TransactionDate = payment.PaymentDate,
            SourceTypeId = (int)SourceType.BillPayment,
            SourceId = payment.PaymentId,
            SourceCode = payment.PaymentCode,
            Memo = paymentMemo,
            PaymentId = payment.PaymentId,
            PaymentCode = payment.PaymentCode,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        }, JournalEntryKind.BillPayment, Perspective.Company);
    }
    #endregion
}
