using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    public async Task<JournalEntry?> CreateJournalEntryAsync(JournalEntry journalEntry)
    {
        if (!await IsAccountingFeatureEnabledAsync(journalEntry.OrganizationId))
            return null;

        ApplyManualJournalEntryClassification(journalEntry);

        if (!IsUserEditableJournalEntry(journalEntry))
            throw new Exception("Journal entry kind must be Manual, Opening Balance Sheet, or Retained Earnings.");

        return await CreateJournalEntryAsync(journalEntry, requireActiveLines: true);
    }

    private async Task<JournalEntry?> CreateAutoGeneratedJournalEntryAsync(JournalEntry journalEntry, bool postImmediately = false)
    {
        if (!await IsAccountingFeatureEnabledAsync(journalEntry.OrganizationId))
            return null;

        if (HasInvalidActiveJournalEntryAccountIds(journalEntry))
            return null;

        EnsureAutoGeneratedJournalEntryClassification(journalEntry);

        var requireActiveLines = HasActiveJournalEntryLines(journalEntry);
        if (postImmediately)
        {
            journalEntry.PostingStatusId = PostingStatus.Posted;
            if (journalEntry.AccountingPeriod == default)
                journalEntry.AccountingPeriod = FirstDayOfMonth(journalEntry.TransactionDate);

            ValidateJournalEntryForSave(journalEntry, requireActiveLines);
            return await CreateJournalEntryAsync(journalEntry, requireActiveLines, preservePostingStatus: true);
        }

        return await CreateJournalEntryAsync(journalEntry, requireActiveLines);
    }

    private async Task<JournalEntry?> CreateJournalEntryAsync(JournalEntry journalEntry, bool requireActiveLines, bool preservePostingStatus = false)
    {
        if (!preservePostingStatus)
            journalEntry.PostingStatusId = PostingStatus.Open;
        if (journalEntry.AccountingPeriod == default)
            journalEntry.AccountingPeriod = FirstDayOfMonth(journalEntry.TransactionDate);

        if (string.IsNullOrWhiteSpace(journalEntry.JournalEntryCode))
        {
            journalEntry.JournalEntryCode = await _organizationManager.GenerateEntityCodeAsync(
                journalEntry.OrganizationId,
                EntityType.JournalEntry);
        }

        ValidateJournalEntryForSave(journalEntry, requireActiveLines);
        var created = await _journalEntryRepository.CreateJournalEntryAsync(journalEntry);
        await TryRefreshRetainedEarningsAfterJournalEntryChangeAsync(created, logDecisions: false);
        return created;
    }

    public async Task<JournalEntry> UpdateJournalEntryAsync(JournalEntry journalEntry)
    {
        var existing = await _journalEntryRepository.GetJournalEntryByIdAsync(journalEntry.JournalEntryId, journalEntry.OrganizationId);
        if (existing == null)
            throw new Exception("Journal entry not found");

        if (!IsUserEditableJournalEntry(existing))
            throw new Exception("Only Manual, Opening Balance Sheet, and Retained Earnings journal entries can be updated.");

        if (!IsUserEditableJournalEntry(journalEntry))
            throw new Exception("Journal entry kind must be Manual, Opening Balance Sheet, or Retained Earnings.");

        return await UpdateJournalEntryAsync(journalEntry, requireActiveLines: true);
    }

    private async Task<JournalEntry> UpdateAutoGeneratedJournalEntryAsync(JournalEntry journalEntry, bool postImmediately = false)
        => await UpdateJournalEntryAsync(journalEntry, requireActiveLines: HasActiveJournalEntryLines(journalEntry), postImmediately: postImmediately);

    private async Task<JournalEntry> UpdateJournalEntryAsync(JournalEntry journalEntry, bool requireActiveLines)
        => await UpdateJournalEntryAsync(journalEntry, requireActiveLines, postImmediately: false);

    private async Task<JournalEntry> UpdateJournalEntryAsync(JournalEntry journalEntry, bool requireActiveLines, bool postImmediately)
    {
        var existing = await _journalEntryRepository.GetJournalEntryByIdAsync(journalEntry.JournalEntryId, journalEntry.OrganizationId);
        if (existing == null)
            throw new Exception("Journal entry not found");

        journalEntry.JournalEntryCode = existing.JournalEntryCode;
        // SourceTypeId/SourceId are insert-only in SQL; keep rebuilt Kind/SourceCode/IsCashOnly.
        journalEntry.SourceCode = string.IsNullOrWhiteSpace(journalEntry.SourceCode) ? existing.SourceCode : journalEntry.SourceCode;
        journalEntry.PostingStatusId = postImmediately ? PostingStatus.Posted : existing.PostingStatusId;
        journalEntry.CreatedBy = existing.CreatedBy;

        if (journalEntry.AccountingPeriod == default)
            journalEntry.AccountingPeriod = existing.AccountingPeriod;

        ValidateJournalEntryForSave(journalEntry, requireActiveLines);
        var updated = await _journalEntryRepository.UpdateJournalEntryByIdAsync(journalEntry);
        if (!IsRetainedEarningsCloseJournalEntry(existing) && !IsRetainedEarningsCloseJournalEntry(updated))
            await TryRefreshRetainedEarningsAfterJournalEntryChangeAsync(updated, existing, logDecisions: false);

        return updated;
    }

    private async Task<JournalEntry> UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(JournalEntry journalEntry, bool requireActiveLines)
    {
        var existing = await _journalEntryRepository.GetJournalEntryByIdAsync(journalEntry.JournalEntryId, journalEntry.OrganizationId);
        if (existing == null)
            throw new Exception("Journal entry not found");

        journalEntry.JournalEntryCode = existing.JournalEntryCode;
        journalEntry.SourceCode = string.IsNullOrWhiteSpace(journalEntry.SourceCode) ? existing.SourceCode : journalEntry.SourceCode;
        journalEntry.PostingStatusId = existing.PostingStatusId;
        journalEntry.CreatedBy = existing.CreatedBy;

        if (journalEntry.AccountingPeriod == default)
            journalEntry.AccountingPeriod = existing.AccountingPeriod;

        ValidateJournalEntryForSave(journalEntry, requireActiveLines);
        return await _journalEntryRepository.UpdateJournalEntryByIdAsync(journalEntry);
    }

    public async Task<JournalEntry> PostJournalEntryAsync(Guid journalEntryId, Guid organizationId, Guid currentUser, DateOnly? accountingPeriod = null)
    {
        var journalEntry = await _journalEntryRepository.GetJournalEntryByIdAsync(journalEntryId, organizationId);
        if (journalEntry == null)
            throw new Exception("Journal entry not found");

        if (journalEntry.PostingStatusId is PostingStatus.SoftClosed or PostingStatus.HardClosed)
            throw new Exception("A voided journal entry cannot be posted");

        if (journalEntry.PostingStatusId == PostingStatus.Posted)
            throw new Exception("Journal entry is already posted");

        ValidateJournalEntryForSave(journalEntry, requireActiveLines: true);

        if (accountingPeriod != null && accountingPeriod != default)
            journalEntry.AccountingPeriod = accountingPeriod.Value;
        else if (journalEntry.AccountingPeriod == default)
            journalEntry.AccountingPeriod = FirstDayOfMonth(journalEntry.TransactionDate);

        journalEntry.PostingStatusId = PostingStatus.Posted;
        journalEntry.ModifiedBy = currentUser;
        return await _journalEntryRepository.UpdateJournalEntryByIdAsync(journalEntry);
    }

    public async Task<JournalEntry> VoidJournalEntryAsync(Guid journalEntryId, Guid organizationId, Guid currentUser)
    {
        var journalEntry = await _journalEntryRepository.GetJournalEntryByIdAsync(journalEntryId, organizationId);
        if (journalEntry == null)
            throw new Exception("Journal entry not found");

        if (journalEntry.PostingStatusId is PostingStatus.SoftClosed or PostingStatus.HardClosed)
            throw new Exception("Journal entry is already voided");

        if (journalEntry.PostingStatusId != PostingStatus.Posted)
            throw new Exception("Only posted journal entries can be voided");

        journalEntry.PostingStatusId = PostingStatus.SoftClosed;
        journalEntry.ModifiedBy = currentUser;
        return await _journalEntryRepository.UpdateJournalEntryByIdAsync(journalEntry);
    }

    public async Task<JournalEntry> SoftCloseJournalEntryAsync(Guid journalEntryId, Guid organizationId, Guid currentUser)
    {
        var journalEntry = await _journalEntryRepository.GetJournalEntryByIdAsync(journalEntryId, organizationId);
        if (journalEntry == null)
            throw new Exception("Journal entry not found");

        if (journalEntry.PostingStatusId is PostingStatus.SoftClosed or PostingStatus.HardClosed)
            throw new Exception("Journal entry is already closed");

        journalEntry.PostingStatusId = PostingStatus.SoftClosed;
        journalEntry.ModifiedBy = currentUser;
        return await _journalEntryRepository.UpdateJournalEntryByIdAsync(journalEntry);
    }

    public async Task<JournalEntry> HardCloseJournalEntryAsync(Guid journalEntryId, Guid organizationId, Guid currentUser)
    {
        var journalEntry = await _journalEntryRepository.GetJournalEntryByIdAsync(journalEntryId, organizationId);
        if (journalEntry == null)
            throw new Exception("Journal entry not found");

        if (journalEntry.PostingStatusId == PostingStatus.HardClosed)
            throw new Exception("Journal entry is already hard closed");

        journalEntry.PostingStatusId = PostingStatus.HardClosed;
        journalEntry.ModifiedBy = currentUser;
        return await _journalEntryRepository.UpdateJournalEntryByIdAsync(journalEntry);
    }

    public async Task<CloseAccountingPeriodResult> CloseAccountingPeriodAsync(
        Guid organizationId,
        int officeId,
        DateOnly startDate,
        DateOnly endDate,
        PostingStatus closeStatus,
        IEnumerable<Guid> journalEntryIds,
        Guid currentUser)
    {
        if (closeStatus is not (PostingStatus.SoftClosed or PostingStatus.HardClosed))
            throw new ArgumentException("Close status must be SoftClosed or HardClosed", nameof(closeStatus));

        var result = new CloseAccountingPeriodResult();
        foreach (var journalEntryId in (journalEntryIds ?? Enumerable.Empty<Guid>()).Where(id => id != Guid.Empty).Distinct())
        {
            try
            {
                if (closeStatus == PostingStatus.SoftClosed)
                    await SoftCloseJournalEntryAsync(journalEntryId, organizationId, currentUser);
                else
                    await HardCloseJournalEntryAsync(journalEntryId, organizationId, currentUser);

                result.SuccessCount++;
            }
            catch (Exception ex)
            {
                result.FailedCount++;
                result.Errors.Add(ex.Message);
            }
        }

        var closedDate = await _accountingRepository.CreateClosedDateAsync(new ClosedDate
        {
            OrganizationId = organizationId,
            OfficeId = officeId,
            StartDate = startDate,
            EndDate = endDate,
            PostingStatusId = closeStatus
        });
        result.ClosedDateId = closedDate.ClosedDateId;

        return result;
    }

    public async Task DeleteJournalEntryAsync(Guid journalEntryId, Guid organizationId)
    {
        var journalEntry = await _journalEntryRepository.GetJournalEntryByIdAsync(journalEntryId, organizationId);
        if (journalEntry == null)
            throw new Exception("Journal entry not found");

        if (!IsDeletableManualJournalEntry(journalEntry))
            throw new Exception("Only open manual journal entries can be deleted.");

        await _journalEntryRepository.DeleteJournalEntryByIdAsync(journalEntryId, organizationId);
        await TryRefreshRetainedEarningsAfterJournalEntryChangeAsync(journalEntry, logDecisions: false);
    }

    private async Task DeleteOpenJournalEntryAsync(Guid journalEntryId, Guid organizationId)
    {
        var journalEntry = await _journalEntryRepository.GetJournalEntryByIdAsync(journalEntryId, organizationId);
        await _journalEntryRepository.DeleteOpenJournalEntryByIdAsync(journalEntryId, organizationId);
        if (journalEntry != null)
            await TryRefreshRetainedEarningsAfterJournalEntryChangeAsync(journalEntry, logDecisions: false);
    }

    public async Task DeleteJournalEntriesForInvoiceAsync(Invoice invoice)
    {
        await _journalEntryRepository.DeleteJournalEntriesBySourceIdAsync(invoice.OrganizationId, (int)SourceType.Invoice, invoice.InvoiceId);
    }

    public async Task DeleteJournalEntriesForReceiptAsync(Receipt receipt)
    {
        await _journalEntryRepository.DeleteJournalEntriesBySourceIdAsync(receipt.OrganizationId, (int)SourceType.Receipt, receipt.ReceiptId);
    }

    public async Task DeleteJournalEntriesForDepositAsync(Deposit deposit)
    {
        if (deposit.DepositId == Guid.Empty)
            return;

        await DeleteJournalEntriesForSourceAsync(deposit.OrganizationId, deposit.OfficeId, (int)SourceType.Deposit, deposit.DepositId);
    }

    public async Task DeleteJournalEntriesForTransferAsync(Transfer transfer)
    {
        if (transfer.TransferId == Guid.Empty)
            return;

        await DeleteJournalEntriesForSourceAsync(transfer.OrganizationId, transfer.OfficeId, (int)SourceType.Transfer, transfer.TransferId);
    }

    private async Task DeleteJournalEntriesForPaymentAsync(Payment payment)
    {
        if (payment.PaymentId == Guid.Empty)
            return;

        var entries = await GetJournalEntriesForSourceAsync(
            payment.OrganizationId,
            payment.OfficeId,
            SourceType.InvoicePayment,
            payment.PaymentId);

        foreach (var entry in entries)
            await DeleteOpenJournalEntryAsync(entry.JournalEntryId, payment.OrganizationId);
    }

    public async Task<JournalEntry> UnpostJournalEntryAsync(Guid journalEntryId, Guid organizationId, Guid currentUser)
    {
        var journalEntry = await _journalEntryRepository.GetJournalEntryByIdAsync(journalEntryId, organizationId);
        if (journalEntry == null)
            throw new Exception("Journal entry not found");

        if (journalEntry.PostingStatusId is PostingStatus.SoftClosed or PostingStatus.HardClosed)
            throw new Exception("A voided journal entry cannot be unposted");

        if (journalEntry.PostingStatusId != PostingStatus.Posted)
            throw new Exception("Journal entry is not posted");

        journalEntry.PostingStatusId = PostingStatus.Open;
        journalEntry.ModifiedBy = currentUser;
        return await _journalEntryRepository.UpdateJournalEntryByIdAsync(journalEntry);
    }

    private static bool HasActiveJournalEntryLines(JournalEntry journalEntry)
        => journalEntry.JournalEntryLines.Any(l => l.Debit != 0 || l.Credit != 0);

    private static bool HasInvalidActiveJournalEntryAccountIds(JournalEntry journalEntry)
        => journalEntry.JournalEntryLines.Any(l => (l.Debit != 0 || l.Credit != 0) && l.ChartOfAccountId <= 0);

    private static void ValidateJournalEntryForSave(JournalEntry journalEntry, bool requireActiveLines)
    {
        if (journalEntry.OfficeId <= 0)
            throw new Exception("OfficeId is required");

        if (journalEntry.TransactionDate == default)
            throw new Exception("TransactionDate is required");

        if (journalEntry.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required");

        var activeLines = journalEntry.JournalEntryLines
            .Where(l => l.Debit != 0 || l.Credit != 0)
            .ToList();

        if (requireActiveLines && activeLines.Count == 0)
            throw new Exception("At least one journal entry line is required");

        foreach (var line in activeLines)
        {
            if (line.ChartOfAccountId <= 0)
                throw new Exception("ChartOfAccountId is required on each journal entry line");

            if (line.Debit < 0 || line.Credit < 0)
                throw new Exception("Debit and Credit must be zero or greater");

            if (line.Debit != 0 && line.Credit != 0)
                throw new Exception("A journal entry line cannot have both debit and credit amounts");
        }

        var totalDebit = activeLines.Sum(l => l.Debit);
        var totalCredit = activeLines.Sum(l => l.Credit);

        if (Math.Abs(totalDebit - totalCredit) > 0.005m)
            throw new Exception("Journal entry debits and credits must balance");
    }

    private static bool IsManualJournalEntry(JournalEntry journalEntry)
        => journalEntry.SourceTypeId == (int)SourceType.Journal
            && journalEntry.JournalEntryKindId == JournalEntryKind.Manual;

    private static bool IsUserEditableJournalEntry(JournalEntry journalEntry)
        => journalEntry.SourceTypeId == (int)SourceType.Journal
            && journalEntry.JournalEntryKindId is JournalEntryKind.Manual
                or JournalEntryKind.OpeningBalanceSheet
                or JournalEntryKind.RetainedEarnings;

    private static bool IsDeletableManualJournalEntry(JournalEntry journalEntry)
        => IsManualJournalEntry(journalEntry)
            && journalEntry.PostingStatusId is PostingStatus.Open or PostingStatus.SoftClosed;
}
