using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Triggers
    public async Task<JournalEntry?> CreateJournalEntryFromInvoiceAsync(Invoice invoice, Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(invoice.OrganizationId))
            return null;

        if (CanUseCrossPeriodInvoiceJournalEntryPath(invoice))
        {
            var crossPeriodEntry = await CreateJournalEntriesFromCrossPeriodInvoiceAsync(invoice, currentUser);
            if (crossPeriodEntry != null)
                return crossPeriodEntry;
        }

        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = invoice.OrganizationId,
            OfficeIds = invoice.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = invoice.InvoiceId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        var existingEntry = existingEntries.FirstOrDefault(e => !e.IsVoided && !IsInvoiceOwnerShareJournalEntry(e));
        if (existingEntry != null)
        {
            if (TryGetInvoiceRentalLineAmount(invoice, out var existingOwnerShareAmount))
                await CreateJournalEntryFromInvoiceOwnerShareAsync(invoice, existingOwnerShareAmount, currentUser);
            return existingEntry;
        }

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);
        var journalEntry = await BuildJournalEntryFromInvoiceAsync(invoice, chartOfAccounts, accountingOffice, currentUser);
        var createdJournalEntry = await CreateAutoGeneratedJournalEntryAsync(journalEntry);
        if (TryGetInvoiceRentalLineAmount(invoice, out var rentalAmount))
            await CreateJournalEntryFromInvoiceOwnerShareAsync(invoice, rentalAmount, currentUser);
        return createdJournalEntry;
    }

    public async Task<JournalEntry?> CreateJournalEntryFromPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(invoice.OrganizationId))
            return null;

        if (paymentLedgerLine.LedgerLineId == Guid.Empty)
            throw new Exception("LedgerLineId is required to create a payment journal entry");

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);

        if (IsInvoicePrePayment(invoice, paymentLedgerLine))
            return await CreateJournalEntriesFromPrePaymentAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);

        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = invoice.OrganizationId,
            OfficeIds = invoice.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.InvoicePayment,
            SourceId = paymentLedgerLine.LedgerLineId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        var existingEntry = existingEntries.FirstOrDefault(e => !e.IsVoided);
        if (existingEntry != null)
            return existingEntry;

        var journalEntry = await BuildJournalEntryFromPaymentAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
        return await CreateAutoGeneratedJournalEntryAsync(journalEntry);
    }

    public async Task<JournalEntry?> CreateJournalEntriesFromPrePaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        var receivedEntry = await GetOrCreatePrePaymentReceivedJournalEntryAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
        if (receivedEntry == null)
            return null;

        var applyEntry = await GetOrCreatePrePaymentApplyJournalEntryAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
        if (applyEntry == null)
            return null;

        return receivedEntry;
    }

    public async Task<JournalEntry?> GetOrCreatePrePaymentReceivedJournalEntryAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = invoice.OrganizationId,
            OfficeIds = invoice.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.InvoicePayment,
            SourceId = paymentLedgerLine.LedgerLineId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        var existingEntry = existingEntries.FirstOrDefault(e => !e.IsVoided);
        if (existingEntry != null)
            return existingEntry;

        var journalEntry = await BuildJournalEntryFromPrePaymentReceivedAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
        return await CreateAutoGeneratedJournalEntryAsync(journalEntry);
    }

    public async Task<JournalEntry?> GetOrCreatePrePaymentApplyJournalEntryAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = invoice.OrganizationId,
            OfficeIds = invoice.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = paymentLedgerLine.LedgerLineId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        var existingEntry = existingEntries.FirstOrDefault(e => !e.IsVoided);
        if (existingEntry != null)
            return existingEntry;

        var journalEntry = await BuildJournalEntryFromPrePaymentApplyAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
        return await CreateAutoGeneratedJournalEntryAsync(journalEntry);
    }

    public async Task<List<JournalEntry>> CreateJournalEntriesFromInvoicePaymentAsync(InvoicePayment invoicePayment, Guid currentUser)
    {
        var journalEntries = new List<JournalEntry>();

        if (invoicePayment.PaymentApplications.Count == 0)
            return journalEntries;

        foreach (var paymentApplication in invoicePayment.PaymentApplications)
        {
            var journalEntry = await CreateJournalEntryFromPaymentAsync(paymentApplication.Invoice, paymentApplication.PaymentLedgerLine, currentUser);
            if (journalEntry != null)
                journalEntries.Add(journalEntry);
        }

        return journalEntries;
    }
    #endregion

    #region Journal Entry
    private async Task<JournalEntry> BuildJournalEntryFromInvoiceAsync(Invoice invoice, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser, Guid? sourceIdOverride = null, string? memoSuffix = null)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // INVOICE-JE-ACCOUNTS
        // Line 1 — Debit: Accounts Receivable (GetDefaultAccountsReceivable) for the invoice total.
        // Lines 2+ — Credit: Tenant Income (GetDefaultTenantIncome) for each non-payment charge line.
        // END INVOICE-JE-ACCOUNTS

        var costCodes = await _accountingRepository.GetCostCodesByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);
        var costCodeById = costCodes.ToDictionary(c => c.CostCodeId);
        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var propertyId = await ResolveInvoicePropertyIdAsync(invoice);

        var chargeLines = invoice.LedgerLines
            .Where(l => l.Amount != 0)
            .Where(l =>
            {
                costCodeById.TryGetValue(l.CostCodeId, out var costCode);
                return !IsPaymentLedgerLine(costCode);
            })
            .OrderBy(l => l.LineNumber)
            .ToList();

        var totalAmount = chargeLines.Sum(l => l.Amount);

        if (invoice.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required to create a journal entry for an invoice");

        var transactionDate = invoice.AccountingPeriod;
        var postingDate = invoice.AccountingPeriod;
        var memo = string.IsNullOrWhiteSpace(invoice.Notes)
            ? $"Invoice {invoice.InvoiceCode}"
            : invoice.Notes.Trim();
        if (!string.IsNullOrWhiteSpace(memoSuffix))
            memo = $"{memo} ({memoSuffix.Trim()})";

        var journalEntryLines = new List<JournalEntryLine>();
        journalEntryLines.Add(new JournalEntryLine
        {
            ChartOfAccountId = accountsReceivableAccountId,
            ReservationId = invoice.ReservationId,
            PropertyId = propertyId,
            ContactId = invoice.ContactId,
            Debit = totalAmount,
            Credit = 0,
            Memo = $"Accounts Receivable - {invoice.InvoiceCode}",
            CreatedBy = currentUser
        });

        foreach (var line in chargeLines)
        {
            journalEntryLines.Add(new JournalEntryLine
            {
                ChartOfAccountId = GetDefaultTenantIncomeByCostCodeId(chartOfAccounts, invoice.OfficeId, line.CostCodeId, costCodeById, accountingOffice),
                CostCodeId = line.CostCodeId,
                ReservationId = line.ReservationId ?? invoice.ReservationId,
                PropertyId = propertyId,
                ContactId = invoice.ContactId,
                Debit = 0,
                Credit = line.Amount,
                Memo = line.Description,
                CreatedBy = currentUser
            });
        }

        return new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = transactionDate,
            PostingDate = postingDate,
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = sourceIdOverride ?? invoice.InvoiceId,
            Memo = memo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };
    }

    private async Task<JournalEntry> BuildJournalEntryFromPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // PAYMENT-JE-ACCOUNTS
        // Line 1 — Debit: Undeposited Funds (GetDefaultUndepositedFunds).
        // Line 2 — Credit: Accounts Receivable (GetDefaultAccountsReceivable).
        // END PAYMENT-JE-ACCOUNTS

        if (paymentLedgerLine.Amount == 0)
            throw new Exception("Payment amount cannot be zero");

        if (paymentLedgerLine.LedgerLineDate == default)
            throw new Exception("Payment date is required to create a payment journal entry");

        var costCodes = await _accountingRepository.GetCostCodesByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);
        var costCodeById = costCodes.ToDictionary(c => c.CostCodeId);
        if (!costCodeById.TryGetValue(paymentLedgerLine.CostCodeId, out var paymentCostCode) || !IsPaymentLedgerLine(paymentCostCode))
            throw new Exception("Payment ledger line must use a payment cost code");

        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var undepositedFundsAccountId = GetDefaultUndepositedFunds(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var propertyId = await ResolveInvoicePropertyIdAsync(invoice);
        var reservationId = paymentLedgerLine.ReservationId ?? invoice.ReservationId;

        var amount = paymentLedgerLine.Amount;
        var transactionDate = paymentLedgerLine.LedgerLineDate;
        var postingDate = paymentLedgerLine.LedgerLineDate;
        var memo = string.IsNullOrWhiteSpace(paymentLedgerLine.Description)
            ? $"Invoice Payment - {invoice.InvoiceCode}"
            : paymentLedgerLine.Description.Trim();

        var undepositedFundsLine = new JournalEntryLine
        {
            ChartOfAccountId = undepositedFundsAccountId,
            CostCodeId = paymentLedgerLine.CostCodeId,
            ReservationId = reservationId,
            PropertyId = propertyId,
            ContactId = invoice.ContactId,
            Debit = amount,
            Credit = 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        var accountsReceivableLine = new JournalEntryLine
        {
            ChartOfAccountId = accountsReceivableAccountId,
            ReservationId = reservationId,
            PropertyId = propertyId,
            ContactId = invoice.ContactId,
            Debit = 0,
            Credit = amount,
            Memo = $"Accounts Receivable - {invoice.InvoiceCode}",
            CreatedBy = currentUser
        };

        return new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = transactionDate,
            PostingDate = postingDate,
            SourceTypeId = (int)SourceType.InvoicePayment,
            SourceId = paymentLedgerLine.LedgerLineId,
            Memo = memo,
            JournalEntryLines = new List<JournalEntryLine> { undepositedFundsLine, accountsReceivableLine },
            CreatedBy = currentUser
        };
    }

    private async Task<JournalEntry> BuildJournalEntryFromPrePaymentReceivedAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // PRE-PAYMENT-RECEIVED-JE-ACCOUNTS
        // Line 1 — Debit: Accounts Receivable (GetDefaultAccountsReceivable).
        // Line 2 — Credit: Pre-Payment liability (GetDefaultPrePayment).
        // END PRE-PAYMENT-RECEIVED-JE-ACCOUNTS

        await ValidatePrePaymentLedgerLineForJournalEntry(invoice, paymentLedgerLine);

        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var prePaymentAccountId = GetDefaultPrePayment(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var propertyId = await ResolveInvoicePropertyIdAsync(invoice);
        var reservationId = paymentLedgerLine.ReservationId ?? invoice.ReservationId;
        var amount = paymentLedgerLine.Amount;
        var transactionDate = paymentLedgerLine.LedgerLineDate;
        var memo = string.IsNullOrWhiteSpace(paymentLedgerLine.Description)
            ? $"Invoice Pre-Payment - {invoice.InvoiceCode}"
            : paymentLedgerLine.Description.Trim();

        return new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = transactionDate,
            PostingDate = transactionDate,
            SourceTypeId = (int)SourceType.InvoicePayment,
            SourceId = paymentLedgerLine.LedgerLineId,
            Memo = memo,
            JournalEntryLines = new List<JournalEntryLine>
            {
                new()
                {
                    ChartOfAccountId = accountsReceivableAccountId,
                    ReservationId = reservationId,
                    PropertyId = propertyId,
                    ContactId = invoice.ContactId,
                    Debit = amount,
                    Credit = 0,
                    Memo = $"Accounts Receivable - {invoice.InvoiceCode}",
                    CreatedBy = currentUser
                },
                new()
                {
                    ChartOfAccountId = prePaymentAccountId,
                    CostCodeId = paymentLedgerLine.CostCodeId,
                    ReservationId = reservationId,
                    PropertyId = propertyId,
                    ContactId = invoice.ContactId,
                    Debit = 0,
                    Credit = amount,
                    Memo = memo,
                    CreatedBy = currentUser
                }
            },
            CreatedBy = currentUser
        };
    }

    private async Task<JournalEntry> BuildJournalEntryFromPrePaymentApplyAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // PRE-PAYMENT-APPLY-JE-ACCOUNTS (on the date of the payment)
        // Line 1 — Debit: Pre-Payment liability (GetDefaultPrePayment).
        // Line 2 — Credit: Accounts Receivable (GetDefaultAccountsReceivable).
        // END PRE-PAYMENT-APPLY-JE-ACCOUNTS (on date of accounting period)

        await ValidatePrePaymentLedgerLineForJournalEntry(invoice, paymentLedgerLine);

        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var prePaymentAccountId = GetDefaultPrePayment(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var propertyId = await ResolveInvoicePropertyIdAsync(invoice);
        var reservationId = paymentLedgerLine.ReservationId ?? invoice.ReservationId;
        var amount = paymentLedgerLine.Amount;
        var postingDate = invoice.AccountingPeriod;
        var memo = $"Invoice Pre-Payment Apply - {invoice.InvoiceCode}";

        return new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = postingDate,
            PostingDate = postingDate,
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = paymentLedgerLine.LedgerLineId,
            Memo = memo,
            JournalEntryLines = new List<JournalEntryLine>
            {
                new()
                {
                    ChartOfAccountId = prePaymentAccountId,
                    CostCodeId = paymentLedgerLine.CostCodeId,
                    ReservationId = reservationId,
                    PropertyId = propertyId,
                    ContactId = invoice.ContactId,
                    Debit = amount,
                    Credit = 0,
                    Memo = memo,
                    CreatedBy = currentUser
                },
                new()
                {
                    ChartOfAccountId = accountsReceivableAccountId,
                    ReservationId = reservationId,
                    PropertyId = propertyId,
                    ContactId = invoice.ContactId,
                    Debit = 0,
                    Credit = amount,
                    Memo = $"Accounts Receivable - {invoice.InvoiceCode}",
                    CreatedBy = currentUser
                }
            },
            CreatedBy = currentUser
        };
    }

    private async Task ValidatePrePaymentLedgerLineForJournalEntry(Invoice invoice, LedgerLine paymentLedgerLine)
    {
        if (paymentLedgerLine.Amount == 0)
            throw new Exception("Payment amount cannot be zero");

        if (paymentLedgerLine.LedgerLineDate == default)
            throw new Exception("Payment date is required to create a payment journal entry");

        if (invoice.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required to create pre-payment journal entries");

        var costCodes = await _accountingRepository.GetCostCodesByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);
        var costCodeById = costCodes.ToDictionary(c => c.CostCodeId);
        if (!costCodeById.TryGetValue(paymentLedgerLine.CostCodeId, out var paymentCostCode) || !IsPaymentLedgerLine(paymentCostCode))
            throw new Exception("Payment ledger line must use a payment cost code");
    }

    private async Task DeleteJournalEntriesForInvoicePaymentLedgerLineAsync(Guid organizationId, int officeId, Guid ledgerLineId)
    {
        await DeleteJournalEntriesForSourceAsync(organizationId, officeId, (int)SourceType.InvoicePayment, ledgerLineId);
        await DeleteJournalEntriesForSourceAsync(organizationId, officeId, (int)SourceType.Invoice, ledgerLineId);
    }

    private async Task<Guid?> ResolveInvoicePropertyIdAsync(Invoice invoice)
    {
        if (invoice.PropertyId.HasValue && invoice.PropertyId != Guid.Empty)
            return invoice.PropertyId;

        if (!invoice.ReservationId.HasValue || invoice.ReservationId == Guid.Empty)
            return null;

        if (invoice.ReservationId == SystemOrganization)
            return null;

        var reservation = await _reservationRepository.GetReservationByIdAsync(invoice.ReservationId.Value, invoice.OrganizationId);
        if (reservation == null || reservation.PropertyId == Guid.Empty)
            return null;

        return reservation.PropertyId;
    }
    #endregion

    #region Invoice Journal Entry Static Helpers
    private static bool IsInvoicePrePayment(Invoice invoice, LedgerLine paymentLedgerLine)
    {
        if (invoice.AccountingPeriod == default || paymentLedgerLine.LedgerLineDate == default)
            return false;

        return paymentLedgerLine.LedgerLineDate < invoice.AccountingPeriod;
    }

    private static bool IsPaymentLedgerLine(CostCode? costCode)
    {
        return costCode?.TransactionType == TransactionType.Payment;
    }
    #endregion
}
