using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    private async Task<List<JournalEntry>> GetJournalEntriesForSourceAsync(
        Guid organizationId,
        int officeId,
        SourceType sourceType,
        Guid sourceId)
    {
        return (await _journalEntryRepository.GetJournalEntriesBySourceIdAsync(new JournalEntryGetBySourceIdCriteria
        {
            OrganizationId = organizationId,
            SourceTypeId = (int)sourceType,
            SourceId = sourceId,
            OfficeIds = officeId.ToString(),
            IncludeUnposted = true,
            IncludeCashOnly = true
        })).ToList();
    }

    private async Task<List<JournalEntry>> GetAllJournalEntriesForInvoiceAsync(
        Guid organizationId,
        int officeId,
        Guid invoiceId)
        => await GetJournalEntriesForSourceAsync(organizationId, officeId, SourceType.Invoice, invoiceId);

    private static bool MatchesJournalEntryAccountingPeriod(JournalEntry entry, DateOnly accountingPeriod)
    {
        if (entry.AccountingPeriod != default)
            return entry.AccountingPeriod == accountingPeriod;

        return entry.TransactionDate == accountingPeriod;
    }

    private static List<JournalEntry> FilterInvoiceJournalEntriesForAccountingPeriod(
        IEnumerable<JournalEntry> entries,
        DateOnly accountingPeriod)
        => entries.Where(entry => MatchesJournalEntryAccountingPeriod(entry, accountingPeriod)).ToList();

    private static bool IsInvoicePaymentLedgerLineJournalEntry(JournalEntry entry, Invoice invoice, LedgerLine paymentLedgerLine)
        => MatchesInvoicePaymentLedgerLineMemo(entry, invoice, paymentLedgerLine);

    private static bool MatchesInvoicePaymentLedgerLineMemo(JournalEntry entry, Invoice invoice, LedgerLine paymentLedgerLine)
    {
        if (entry.SourceId != invoice.InvoiceId || entry.SourceTypeId != (int)SourceType.Invoice)
            return false;

        return entry.JournalEntryKindId switch
        {
            JournalEntryKind.Payment => string.Equals(
                entry.Memo,
                BuildInvoicePaymentMemo(invoice.InvoiceCode, paymentLedgerLine.Description),
                StringComparison.Ordinal),
            JournalEntryKind.PrePaymentReceive or JournalEntryKind.PrePaymentApply => string.Equals(
                entry.Memo,
                BuildInvoicePrePaymentMemo(invoice.InvoiceCode, paymentLedgerLine.Description),
                StringComparison.Ordinal),
            JournalEntryKind.OwnerActual => MatchesOwnerActualPaymentJournalEntryMemo(entry, invoice, paymentLedgerLine),
            _ => false
        };
    }

    private static bool MatchesOwnerActualPaymentJournalEntryMemo(JournalEntry entry, Invoice invoice, LedgerLine paymentLedgerLine)
    {
        var paymentMemo = BuildOwnerActualRentMemo(invoice, paymentLedgerLine);
        if (string.Equals(entry.Memo, paymentMemo, StringComparison.Ordinal))
            return true;

        var legacyMemo = BuildOwnerActualRentMemo(invoice);
        return string.Equals(entry.Memo, legacyMemo, StringComparison.Ordinal);
    }

    private static void AssignRebuiltJournalEntryFromExisting(JournalEntry rebuilt, JournalEntry existing, Guid currentUser)
    {
        rebuilt.JournalEntryId = existing.JournalEntryId;
        rebuilt.OrganizationId = existing.OrganizationId;
        rebuilt.OfficeId = existing.OfficeId;
        rebuilt.CreatedBy = existing.CreatedBy;
        rebuilt.ModifiedBy = currentUser;

        foreach (var line in rebuilt.JournalEntryLines)
        {
            line.JournalEntryId = existing.JournalEntryId;
            line.JournalEntryLineId = Guid.Empty;
        }
    }

    private async Task<JournalEntry?> UpsertAutoGeneratedJournalEntryAsync(
        JournalEntry rebuiltJournalEntry,
        IReadOnlyList<JournalEntry> existingEntries,
        Guid currentUser,
        Guid organizationId)
    {
        var candidates = existingEntries.ToList();

        while (candidates.Count > 1)
        {
            await DeleteOpenJournalEntryAsync(candidates[^1].JournalEntryId, organizationId);
            candidates.RemoveAt(candidates.Count - 1);
        }

        var existingEntry = candidates.FirstOrDefault();
        if (existingEntry != null)
        {
            AssignRebuiltJournalEntryFromExisting(rebuiltJournalEntry, existingEntry, currentUser);
            return await UpdateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
        }

        return await CreateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
    }

    /// <summary>
    /// Removes all matching entries from <paramref name="workingEntries"/> so later upserts cannot
    /// update/delete the same JE (avoids stale-id "Journal entry not found" after prune).
    /// </summary>
    private static List<JournalEntry> ClaimAllMatchingEntries(List<JournalEntry> workingEntries, Func<JournalEntry, bool> predicate)
    {
        var claimed = workingEntries.Where(predicate).ToList();
        foreach (var entry in claimed)
            workingEntries.Remove(entry);
        return claimed;
    }

    private static JournalEntry? ClaimFirstMatchingEntry(List<JournalEntry> workingEntries, Func<JournalEntry, bool> predicate)
    {
        var match = workingEntries.FirstOrDefault(predicate);
        if (match != null)
            workingEntries.Remove(match);
        return match;
    }

    private async Task<JournalEntry?> UpsertClaimedAutoGeneratedJournalEntryAsync(
        JournalEntry rebuiltJournalEntry,
        List<JournalEntry> workingEntries,
        Func<JournalEntry, bool> predicate,
        ISet<Guid> retainedEntryIds,
        Guid currentUser,
        Guid organizationId)
    {
        var claimed = ClaimAllMatchingEntries(workingEntries, predicate);
        var updated = await UpsertAutoGeneratedJournalEntryAsync(
            rebuiltJournalEntry,
            claimed,
            currentUser,
            organizationId);
        if (updated != null)
            retainedEntryIds.Add(updated.JournalEntryId);
        return updated;
    }

    private async Task DeleteJournalEntriesExceptAsync(
        IEnumerable<JournalEntry> entries,
        IReadOnlyCollection<Guid> retainJournalEntryIds,
        Guid organizationId)
    {
        foreach (var entry in entries)
        {
            if (!retainJournalEntryIds.Contains(entry.JournalEntryId))
                await DeleteOpenJournalEntryAsync(entry.JournalEntryId, organizationId);
        }
    }

    private async Task DeleteClaimedOrphanJournalEntriesAsync(
        IEnumerable<JournalEntry> orphanEntries,
        Guid organizationId)
    {
        foreach (var entry in orphanEntries.Where(IsInvoicePaymentFlowOrphanCandidate))
            await DeleteOpenJournalEntryAsync(entry.JournalEntryId, organizationId);
    }

    private static bool IsInvoicePaymentFlowOrphanCandidate(JournalEntry entry)
        => entry.JournalEntryKindId is JournalEntryKind.Payment
            or JournalEntryKind.PrePaymentReceive
            or JournalEntryKind.PrePaymentApply
            or JournalEntryKind.OwnerActual;

    private static (JournalEntry? Main, JournalEntry? OwnerUtility) ClassifyBillJournalEntries(
        IReadOnlyList<JournalEntry> entries,
        int ownerAccountsPayableAccountId,
        int pmUtilityIncomeAccountId)
    {
        JournalEntry? main = null;
        JournalEntry? ownerUtility = null;

        foreach (var entry in entries)
        {
            var accountIds = entry.JournalEntryLines
                .Select(line => line.ChartOfAccountId)
                .Where(accountId => accountId > 0)
                .ToHashSet();

            if (accountIds.Contains(ownerAccountsPayableAccountId) && accountIds.Contains(pmUtilityIncomeAccountId))
                ownerUtility = entry;
            else
                main ??= entry;
        }

        return (main, ownerUtility);
    }

    private static bool IsInvoiceChargeJournalEntry(JournalEntry entry, int accountsReceivableAccountId)
        => entry.JournalEntryKindId == JournalEntryKind.Charge
            && entry.SourceTypeId == (int)SourceType.Invoice
            && entry.JournalEntryLines.Any(line => line.ChartOfAccountId == accountsReceivableAccountId);

    private static bool IsInvoiceOwnerShareJournalEntry(JournalEntry entry)
        => entry.JournalEntryKindId == JournalEntryKind.OwnerExpected
            && entry.SourceTypeId == (int)SourceType.Invoice;

    private static bool IsInvoiceChargeOrOwnerExpectedJournalEntry(JournalEntry entry)
        => entry.SourceTypeId == (int)SourceType.Invoice
            && entry.JournalEntryKindId is JournalEntryKind.Charge or JournalEntryKind.OwnerExpected;

    private static bool IsStandardInvoicePaymentJournalEntry(JournalEntry entry)
        => entry.JournalEntryKindId == JournalEntryKind.Payment
           && entry.SourceTypeId == (int)SourceType.Invoice
           && !entry.IsCashOnly;

    private static bool IsStandardInvoicePaymentJournalEntry(JournalEntry entry, int prePaymentAccountId)
        => IsStandardInvoicePaymentJournalEntry(entry);

    private static bool IsInvoiceOwnerActualPaymentJournalEntry(JournalEntry entry)
        => entry.JournalEntryKindId == JournalEntryKind.OwnerActual
           && entry.SourceTypeId == (int)SourceType.Invoice
           && entry.IsCashOnly;

    private static bool IsInvoiceOwnerActualPaymentJournalEntry(JournalEntry entry, Invoice invoice, LedgerLine paymentLedgerLine)
        => IsInvoiceOwnerActualPaymentJournalEntry(entry)
           && MatchesInvoicePaymentLedgerLineMemo(entry, invoice, paymentLedgerLine);

    private static bool IsInvoicePrePaymentReceivedJournalEntry(JournalEntry entry, int prePaymentAccountId)
        => entry.JournalEntryKindId == JournalEntryKind.PrePaymentReceive
           && entry.SourceTypeId == (int)SourceType.Invoice;

    private static bool IsInvoicePrePaymentApplyJournalEntry(JournalEntry entry, int prePaymentAccountId)
        => entry.JournalEntryKindId == JournalEntryKind.PrePaymentApply
           && entry.SourceTypeId == (int)SourceType.Invoice;
}
