using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Triggers
    // Main outside trigger 
    public async Task<JournalEntry?> CreateJournalEntryFromBillAsync(Receipt bill, Guid currentUser)
        => (await CreateJournalEntryFromBillWithResultAsync(bill, currentUser)).JournalEntry;

    // Inside function that returns loggable errors
    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromBillWithResultAsync(Receipt bill, Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(bill.OrganizationId))
            return AccountingJournalEntryResult.Success();

        try
        {
            // Only bills come here, receipts go another route
            EnsureReceiptIsBill(bill);
            bill = await LoadReceiptWithSplitsAsync(bill);

            // Create the main bill JE
            var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(bill.OrganizationId, bill.OfficeId);
            var journalEntry = await BuildJournalEntryFromBillAsync(bill, chartOfAccounts, accountingOffice, currentUser);
            JournalEntry? created = null;
            if (HasActiveJournalEntryLines(journalEntry))
                created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);

            try
            {
                // If that bill is a Utility, create a second JE for owner accountability
                var ownerUtilityJournalEntry = await BuildJournalEntryFromBillForOwnerUtilityAsync(bill, chartOfAccounts, accountingOffice, currentUser);
                if (ownerUtilityJournalEntry != null)
                {
                    await CreateAutoGeneratedJournalEntryAsync(ownerUtilityJournalEntry);
                }
            }
            catch (Exception ownerUtilityEx)
            {
                var ownerUtilityMessage = $"Owner utility journal entry failed for bill {(string.IsNullOrWhiteSpace(bill.BillNumber) ? bill.ReceiptCode.Trim() : bill.BillNumber.Trim())}: {ownerUtilityEx.Message}";
                await LogAccountingErrorAsync(
                    trigger: "BillOwnerUtility",
                    organizationId: bill.OrganizationId,
                    officeId: bill.OfficeId,
                    sourceTypeId: (int)SourceType.Bill,
                    sourceId: bill.ReceiptId,
                    documentCode: string.IsNullOrWhiteSpace(bill.BillNumber) ? bill.ReceiptCode.Trim() : bill.BillNumber.Trim(),
                    accountingPeriod: bill.AccountingPeriod == default ? null : bill.AccountingPeriod,
                    amount: bill.Amount,
                    message: ownerUtilityMessage,
                    currentUser: currentUser);
                return AccountingJournalEntryResult.WarningResult(ownerUtilityMessage, created);
            }

            return AccountingJournalEntryResult.Success(created);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "Bill",
                organizationId: bill.OrganizationId,
                officeId: bill.OfficeId,
                sourceTypeId: (int)SourceType.Bill,
                sourceId: bill.ReceiptId,
                documentCode: string.IsNullOrWhiteSpace(bill.BillNumber) ? bill.ReceiptCode.Trim() : bill.BillNumber.Trim(),
                accountingPeriod: bill.AccountingPeriod == default ? null : bill.AccountingPeriod,
                amount: bill.Amount,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    #endregion

    #region Journal Entry
    private async Task<JournalEntry> BuildJournalEntryFromBillAsync(Receipt bill, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // BILL-JE-ACCOUNTS
        // Positive splits:
        //   Credit - Accounts Payable (GetDefaultAccountsPayable) for the split total.
        //   Debit  - Expense account per split as defined by the user they default to the following
        //   (GetDefaultTenantExpense, GetDefaultDepartureExpense, GetDefaultOwnerExpense, or GetDefaultCompanyExpense).
        // Negative splits (bill credits):
        //   Exact opposite
        // END BILL-JE-ACCOUNTS

        EnsureReceiptIsBill(bill);
        bill = await LoadReceiptWithSplitsAsync(bill);

        var splitLines = (bill.Splits ?? new List<ReceiptSplit>())
            .OrderBy(s => s.ReceiptSplitId)
            .ToList();
        if (splitLines.Count == 0)
            throw new Exception("Splits are required to create a journal entry");

        var nonZeroSplits = splitLines.Where(split => split.Amount != 0).ToList();
        if (nonZeroSplits.Count > 0)
            splitLines = nonZeroSplits;

        if (bill.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required to create a journal entry for a bill");

        if (bill.ReceiptDate == default)
            throw new Exception("ReceiptDate is required to create a journal entry for a bill");

        var accountsPayableAccountId = GetDefaultAccountsPayable(chartOfAccounts, bill.OfficeId, accountingOffice);
        var transactionDate = ResolveBillOrReceiptJournalEntryDate(bill);
        var receiptCode = bill.ReceiptCode.Trim();
        var defaultLineContext = await ResolveReceiptJournalEntryLineContextAsync(bill);
        var eligibleSplits = splitLines
            .Where(split => split.ReceiptType != ReceiptType.NonExpense)
            .Where(split => split.Amount != 0)
            .ToList();
        var billMemo = BuildBillJournalMemo(bill, eligibleSplits);
        var positiveSplits = eligibleSplits.Where(s => s.Amount > 0).ToList();
        var negativeSplits = eligibleSplits.Where(s => s.Amount < 0).ToList();
        var journalEntryLines = new List<JournalEntryLine>();

        var positiveTotal = positiveSplits.Sum(s => s.Amount);
        if (positiveTotal > 0)
        {
            var accountsPayableLine = new JournalEntryLine
            {
                // Credit Accounts Payable
                ChartOfAccountId = accountsPayableAccountId,
                Debit = 0,
                Credit = positiveTotal,
                Memo = billMemo,
                CreatedBy = currentUser
            };
            ApplyJournalEntryLineContext(accountsPayableLine, defaultLineContext);
            journalEntryLines.Add(accountsPayableLine);

            foreach (var split in positiveSplits)
            {
                var expenseAccountId = GetBillReceiptExpenseAccountId(split, bill.OfficeId, chartOfAccounts, accountingOffice);
                var splitMemo = BuildBillSplitLineMemo(bill, split);

                var expenseLine = new JournalEntryLine
                {
                    // Debit Expense
                    ChartOfAccountId = expenseAccountId,
                    Debit = split.Amount,
                    Credit = 0,
                    Memo = splitMemo,
                    CreatedBy = currentUser
                };
                var splitContext = await ResolveReceiptSplitJournalEntryLineContextAsync(bill, split);
                ApplyJournalEntryLineContext(expenseLine, splitContext with { ContactName = defaultLineContext.ContactName });
                ApplyReceiptSplitLinePerspective(expenseLine, split);
                journalEntryLines.Add(expenseLine);
            }
        }

        var negativeTotal = negativeSplits.Sum(s => s.Amount);
        if (negativeTotal < 0)
        {
            var accountsPayableLine = new JournalEntryLine
            {
                // Debit Accounts Payable
                ChartOfAccountId = accountsPayableAccountId,
                Debit = Math.Abs(negativeTotal),
                Credit = 0,
                Memo = billMemo,
                CreatedBy = currentUser
            };
            ApplyJournalEntryLineContext(accountsPayableLine, defaultLineContext);
            journalEntryLines.Add(accountsPayableLine);

            foreach (var split in negativeSplits)
            {
                var expenseAccountId = GetBillReceiptExpenseAccountId(split, bill.OfficeId, chartOfAccounts, accountingOffice);
                var splitMemo = BuildBillSplitLineMemo(bill, split);
                var expenseLine = new JournalEntryLine
                {
                    // Credit ExpenseAccountId
                    ChartOfAccountId = expenseAccountId,
                    Debit = 0,
                    Credit = Math.Abs(split.Amount),
                    Memo = splitMemo,
                    CreatedBy = currentUser
                };
                var splitContext = await ResolveReceiptSplitJournalEntryLineContextAsync(bill, split);
                ApplyJournalEntryLineContext(expenseLine, splitContext with { ContactName = defaultLineContext.ContactName });
                ApplyReceiptSplitLinePerspective(expenseLine, split);
                journalEntryLines.Add(expenseLine);
            }
        }

        return ClassifyJournalEntryKind(new JournalEntry
        {
            OrganizationId = bill.OrganizationId,
            OfficeId = bill.OfficeId,
            TransactionDate = transactionDate,
            SourceTypeId = (int)SourceType.Bill,
            SourceId = bill.ReceiptId,
            SourceCode = ResolveJournalEntrySourceCodeFromReceipt(bill),
            Memo = billMemo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        }, JournalEntryKind.Bill);
    }

    private async Task<JournalEntry> BuildJournalEntryFromBillPaymentAsync(BillPaymentApplication paymentApplication, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // BILL-PAYMENT-JE-ACCOUNTS
        // Line 1 — Debit: Accounts Payable (GetDefaultAccountsPayable) or the credit card account on the bill's bank card.
        // Line 2 — Credit: Bank account selected on the payment (paymentApplication.ChartOfAccountId).
        // END BILL-PAYMENT-JE-ACCOUNTS

        var bill = paymentApplication.Bill;
        if (paymentApplication.AmountApplied == 0)
            throw new Exception("Bill payment amount cannot be zero");

        if (paymentApplication.PaymentDate == default)
            throw new Exception("Payment date is required to create a bill payment journal entry");

        if (paymentApplication.ChartOfAccountId <= 0)
            throw new Exception("Chart of account is required for bill payment");

        var payableOrCardAccountId = bill.BankCardId is > 0
            ? GetCreditCardAccountId(bill, chartOfAccounts, accountingOffice)
            : GetDefaultAccountsPayable(chartOfAccounts, bill.OfficeId, accountingOffice);
        var paymentBankAccountId = paymentApplication.ChartOfAccountId;

        var amount = paymentApplication.AmountApplied;
        var transactionDate = paymentApplication.PaymentDate;
        var paymentMemo = BuildBillPaymentApplicationMemo(bill, paymentApplication.Description);
        var lineContext = await ResolveReceiptJournalEntryLineContextAsync(bill);
        var payableLine = new JournalEntryLine
        {
            // Debit Accounts Payable or Credit Card
            ChartOfAccountId = payableOrCardAccountId,
            Debit = amount > 0 ? amount : 0,
            Credit = amount < 0 ? Math.Abs(amount) : 0,
            Memo = paymentMemo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(payableLine, lineContext);
        var paymentLine = new JournalEntryLine
        {
            // Credit Payment Bank Account
            ChartOfAccountId = paymentBankAccountId,
            Debit = amount < 0 ? Math.Abs(amount) : 0,
            Credit = amount > 0 ? amount : 0,
            Memo = paymentMemo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(paymentLine, lineContext);
        if (paymentApplication.CostCodeId is > 0)
        {
            payableLine.CostCodeId = paymentApplication.CostCodeId;
            paymentLine.CostCodeId = paymentApplication.CostCodeId;
        }
        var journalEntryLines = new List<JournalEntryLine> { payableLine, paymentLine };

        return ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = bill.OrganizationId,
            OfficeId = bill.OfficeId,
            TransactionDate = transactionDate,
            SourceTypeId = (int)SourceType.BillPayment,
            SourceId = bill.ReceiptId,
            SourceCode = ResolveJournalEntrySourceCodeFromReceipt(bill),
            Memo = paymentMemo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        }, JournalEntryKind.BillPayment, Perspective.Company);
    }
    #endregion

    #region Helpers
    private static void EnsureReceiptIsBill(Receipt bill)
    {
        if (bill.BankCardId != null)
            throw new Exception("Receipt is not a bill");
    }

    private static void EnsureBillIsUtility(Receipt bill)
    {
        if (bill.BankCardId != null || !bill.IsUtility)
            throw new Exception("Receipt is not a utility");
    }

    private static string BuildBillSplitLineMemo(Receipt bill, ReceiptSplit split)
    {
        var receiptCode = bill.ReceiptCode.Trim();
        if (string.IsNullOrWhiteSpace(split.Description))
            throw new Exception("Split description is required to create a bill journal entry memo");

        if (split.ReceiptType != ReceiptType.Owner)
            return BuildBillMemo(receiptCode, split.Description);

        return bill.IsUtility
            ? BuildOwnerUtilityBillMemo(receiptCode, split.Description)
            : BuildOwnerBillMemo(receiptCode, split.Description);
    }

    private static string BuildBillPaymentApplicationMemo(Receipt bill, string? fallbackDescription = null)
    {
        var receiptCode = bill.ReceiptCode.Trim();
        var eligibleSplits = (bill.Splits ?? [])
            .Where(split => split.ReceiptType != ReceiptType.NonExpense && split.Amount != 0)
            .OrderBy(split => split.ReceiptSplitId)
            .ToList();

        var splitDetail = string.Join(" — ", eligibleSplits
            .Select(split => (split.Description ?? string.Empty).Trim())
            .Where(description => description.Length > 0));

        var detail = !string.IsNullOrWhiteSpace(splitDetail)
            ? splitDetail
            : (fallbackDescription ?? string.Empty).Trim();

        if (string.IsNullOrWhiteSpace(detail))
            detail = (bill.PaymentDescription ?? bill.Description ?? string.Empty).Trim();

        if (string.IsNullOrWhiteSpace(detail))
            throw new Exception($"Bill {receiptCode} requires a description to create a bill payment journal entry memo.");

        if (bill.IsUtility)
            return BuildOwnerUtilityBillMemo(receiptCode, detail);

        if (eligibleSplits.Count > 0 && eligibleSplits.All(split => split.ReceiptType == ReceiptType.Owner))
            return BuildOwnerBillMemo(receiptCode, detail);

        return BuildBillMemo(receiptCode, detail);
    }

    private static string BuildConsolidatedBillPaymentBankLineMemo(IReadOnlyList<BillPaymentApplication> applications)
    {
        var memos = applications
            .Where(application => application.AmountApplied != 0)
            .Select(application => BuildBillPaymentApplicationMemo(application.Bill!, application.Description))
            .Where(memo => !string.IsNullOrWhiteSpace(memo))
            .ToList();

        return memos.Count switch
        {
            0 => string.Empty,
            1 => memos[0],
            _ => string.Join("; ", memos)
        };
    }

    private static string BuildBillJournalMemo(Receipt bill, IEnumerable<ReceiptSplit>? eligibleSplits = null)
    {
        var receiptCode = bill.ReceiptCode.Trim();
        if (string.IsNullOrWhiteSpace(bill.Description))
            throw new Exception("Bill description is required to create a bill journal entry memo");

        if (bill.IsUtility)
            return BuildOwnerUtilityBillMemo(receiptCode, bill.Description);

        var splits = eligibleSplits?
            .Where(split => split.ReceiptType != ReceiptType.NonExpense)
            .Where(split => split.Amount != 0)
            .ToList();
        if (splits is { Count: > 0 } && splits.All(split => split.ReceiptType == ReceiptType.Owner))
            return BuildOwnerBillMemo(receiptCode, bill.Description);

        return BuildBillMemo(receiptCode, bill.Description);
    }

    #endregion
}
