using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Triggers
    public async Task<JournalEntry?> CreateJournalEntryFromDepositAsync(Deposit deposit, Guid currentUser)
        => (await CreateJournalEntryFromDepositWithResultAsync(deposit, currentUser)).JournalEntry;

    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromDepositWithResultAsync(Deposit deposit, Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(deposit.OrganizationId))
            return AccountingJournalEntryResult.Success();

        if (!ShouldCreateJournalEntryForDeposit(deposit))
            return AccountingJournalEntryResult.Success();

        try
        {
            ValidateDepositForJournalEntry(deposit);

            await EnrichDepositSplitsFromJournalEntryLinesAsync(deposit);
            ApplyDepositHeaderContextFromSplits(deposit);

            var journalEntry = BuildJournalEntryFromDepositRecord(deposit, currentUser);
            var created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);
            if (created == null)
                return AccountingJournalEntryResult.Success();

            if (deposit.JournalEntryId != created.JournalEntryId)
            {
                deposit.JournalEntryId = created.JournalEntryId;
                deposit.ModifiedBy = currentUser;
                await _accountingRepository.UpdateDepositAsync(deposit);
            }

            return AccountingJournalEntryResult.Success(created);
        }
        catch (Exception ex)
        {
            var depositLabel = string.IsNullOrWhiteSpace(deposit.DepositCode)
                ? deposit.DepositId.ToString()
                : deposit.DepositCode.Trim();

            await LogAccountingErrorAsync(
                trigger: "Deposit",
                organizationId: deposit.OrganizationId,
                officeId: deposit.OfficeId,
                sourceTypeId: (int)SourceType.Deposit,
                sourceId: deposit.DepositId,
                documentCode: depositLabel,
                accountingPeriod: deposit.AccountingPeriod == default ? null : deposit.AccountingPeriod,
                amount: deposit.Amount,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    public async Task<Deposit> UpdateDepositAsync(Deposit deposit, Guid currentUser)
    {
        var existing = await _accountingRepository.GetDepositByIdAsync(deposit.DepositId, deposit.OrganizationId)
            ?? throw new Exception("Deposit not found");

        deposit.CreatedBy = existing.CreatedBy;
        deposit.JournalEntryId = existing.JournalEntryId;
        deposit.DepositCode = existing.DepositCode;

        await PrepareDepositForSaveAsync(deposit);
        await _accountingRepository.UpdateDepositAsync(deposit);

        var freshDeposit = await _accountingRepository.GetDepositByIdAsync(deposit.DepositId, deposit.OrganizationId)
            ?? throw new Exception("Deposit not found after update");

        await TryReplaceJournalEntriesFromDepositAsync(freshDeposit, currentUser);

        return await _accountingRepository.GetDepositByIdAsync(freshDeposit.DepositId, freshDeposit.OrganizationId)
            ?? freshDeposit;
    }
    #endregion

    #region Journal Entry
    private async Task TryReplaceJournalEntriesFromDepositAsync(Deposit deposit, Guid currentUser)
    {
        try
        {
            if (deposit.DepositId == Guid.Empty)
                return;

            if (!await IsAccountingFeatureEnabledAsync(deposit.OrganizationId) || !ShouldCreateJournalEntryForDeposit(deposit))
            {
                await DeleteJournalEntriesForSourceAsync(
                    deposit.OrganizationId,
                    deposit.OfficeId,
                    (int)SourceType.Deposit,
                    deposit.DepositId);

                if (deposit.JournalEntryId.HasValue && deposit.JournalEntryId != Guid.Empty)
                {
                    deposit.JournalEntryId = null;
                    deposit.ModifiedBy = currentUser;
                    await _accountingRepository.UpdateDepositAsync(deposit);
                }

                return;
            }

            var existingEntries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
            {
                OrganizationId = deposit.OrganizationId,
                OfficeIds = deposit.OfficeId.ToString(),
                SourceTypeId = (int)SourceType.Deposit,
                SourceId = deposit.DepositId,
                IncludeVoided = true,
                IncludeUnposted = true
            })).ToList();

            var rebuiltJournalEntry = BuildJournalEntryFromDepositRecord(deposit, currentUser);

            while (existingEntries.Count > 1)
            {
                var duplicate = existingEntries[^1];
                await DeleteJournalEntryAsync(duplicate.JournalEntryId, deposit.OrganizationId);
                existingEntries.RemoveAt(existingEntries.Count - 1);
            }

            var existingEntry = existingEntries.FirstOrDefault();
            if (existingEntry != null)
            {
                rebuiltJournalEntry.JournalEntryId = existingEntry.JournalEntryId;
                rebuiltJournalEntry.OrganizationId = deposit.OrganizationId;
                rebuiltJournalEntry.OfficeId = deposit.OfficeId;
                rebuiltJournalEntry.CreatedBy = existingEntry.CreatedBy;
                rebuiltJournalEntry.ModifiedBy = currentUser;

                foreach (var line in rebuiltJournalEntry.JournalEntryLines)
                {
                    line.JournalEntryId = existingEntry.JournalEntryId;
                    line.JournalEntryLineId = Guid.Empty;
                }

                await UpdateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);

                if (deposit.JournalEntryId != existingEntry.JournalEntryId)
                {
                    deposit.JournalEntryId = existingEntry.JournalEntryId;
                    deposit.ModifiedBy = currentUser;
                    await _accountingRepository.UpdateDepositAsync(deposit);
                }

                return;
            }

            var createdJournalEntry = await CreateAutoGeneratedJournalEntryAsync(rebuiltJournalEntry);
            if (createdJournalEntry == null)
                return;

            if (deposit.JournalEntryId != createdJournalEntry.JournalEntryId)
            {
                deposit.JournalEntryId = createdJournalEntry.JournalEntryId;
                deposit.ModifiedBy = currentUser;
                await _accountingRepository.UpdateDepositAsync(deposit);
            }
        }
        catch (Exception ex)
        {
            var depositLabel = string.IsNullOrWhiteSpace(deposit.DepositCode)
                ? deposit.DepositId.ToString()
                : deposit.DepositCode.Trim();

            await LogAccountingErrorAsync(
                trigger: "Deposit",
                organizationId: deposit.OrganizationId,
                officeId: deposit.OfficeId,
                sourceTypeId: (int)SourceType.Deposit,
                sourceId: deposit.DepositId,
                documentCode: depositLabel,
                accountingPeriod: deposit.AccountingPeriod == default ? null : deposit.AccountingPeriod,
                amount: deposit.Amount,
                message: $"Deposit {depositLabel} journal entry refresh failed: {ex.Message}",
                currentUser: currentUser);
        }
    }

    private static void ValidateDepositForJournalEntry(Deposit deposit)
    {
        if (deposit.OfficeId <= 0)
            throw new Exception("OfficeId is required");

        if (deposit.BankAccountId is null or <= 0)
            throw new Exception("Bank account is required");

        if (deposit.Amount == 0)
            throw new Exception("Deposit amount cannot be zero");

        if (deposit.DepositDate == default)
            throw new Exception("Deposit date is required");

        if (deposit.Splits == null || deposit.Splits.Count == 0)
            throw new Exception("At least one split is required");

        foreach (var split in deposit.Splits)
        {
            if (split.ChartOfAccountId is null or <= 0)
                throw new Exception("Each split must have a chart of account");

            if (split.Amount == 0)
                throw new Exception("Split amounts must be non-zero");
        }

        var splitTotal = deposit.Splits.Sum(split => split.Amount);
        if (Math.Abs(splitTotal - deposit.Amount) > 0.005m)
            throw new Exception($"Deposit amount must equal split total ({splitTotal:0.00})");
    }

    private static bool ShouldCreateJournalEntryForDeposit(Deposit deposit)
        => deposit.IsActive
            && deposit.OfficeId > 0
            && deposit.BankAccountId is > 0
            && deposit.Amount != 0
            && deposit.DepositDate != default
            && deposit.Splits is { Count: > 0 }
            && deposit.Splits.All(split => split.ChartOfAccountId is > 0 && split.Amount != 0)
            && Math.Abs(deposit.Splits.Sum(split => split.Amount) - deposit.Amount) <= 0.005m;

    private JournalEntry BuildJournalEntryFromDepositRecord(Deposit deposit, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // DEPOSIT-JE-ACCOUNTS
        // Line 1 — Bank account (deposit.BankAccountId):
        //   positive deposit: Debit bank / Credit 0
        //   negative deposit: Debit 0 / Credit bank
        // Lines 2+ — Split chart-of-account lines:
        //   positive split: Debit 0 / Credit split
        //   negative split: Debit split / Credit 0
        // END DEPOSIT-JE-ACCOUNTS

        var memo = string.IsNullOrWhiteSpace(deposit.Description) ? "Deposit" : "Deposit: " + deposit.Description.Trim();
        var depositPropertyId = deposit.PropertyId
            ?? deposit.Splits.FirstOrDefault(split => split.PropertyId.HasValue && split.PropertyId != Guid.Empty)?.PropertyId;
        var depositReservationId = deposit.Splits.FirstOrDefault(split => split.ReservationId.HasValue && split.ReservationId != Guid.Empty)?.ReservationId;
        var depositContactId = deposit.Splits.FirstOrDefault(split => split.ContactId.HasValue && split.ContactId != Guid.Empty)?.ContactId;
        var journalEntryLines = new List<JournalEntryLine>
        {
            new()
            {
                ChartOfAccountId = deposit.BankAccountId!.Value,
                PropertyId = depositPropertyId,
                ReservationId = depositReservationId,
                ContactId = depositContactId,
                Debit = deposit.Amount > 0 ? deposit.Amount : 0,
                Credit = deposit.Amount < 0 ? Math.Abs(deposit.Amount) : 0,
                Memo = memo,
                CreatedBy = currentUser
            }
        };

        foreach (var split in deposit.Splits)
        {
            journalEntryLines.Add(new JournalEntryLine
            {
                ChartOfAccountId = split.ChartOfAccountId!.Value,
                PropertyId = split.PropertyId,
                ReservationId = split.ReservationId,
                ContactId = split.ContactId,
                Debit = split.Amount < 0 ? Math.Abs(split.Amount) : 0,
                Credit = split.Amount > 0 ? split.Amount : 0,
                Memo = string.IsNullOrWhiteSpace(split.Description) ? memo : split.Description.Trim(),
                CreatedBy = currentUser
            });
        }

        return new JournalEntry
        {
            OrganizationId = deposit.OrganizationId,
            OfficeId = deposit.OfficeId,
            TransactionDate = deposit.DepositDate,
            PostingDate = deposit.AccountingPeriod,
            SourceTypeId = (int)SourceType.Deposit,
            SourceId = deposit.DepositId,
            Memo = memo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };
    }
    #endregion
}
