using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    private sealed class InvoicePaymentSplitAllocation
    {
        public DateOnly AccountingPeriod { get; set; }
        public decimal Amount { get; set; }
    }

    #region Triggers
    public async Task<JournalEntry?> CreateJournalEntryFromInvoiceAsync(Invoice invoice, Guid currentUser)
        => (await CreateJournalEntryFromInvoiceWithResultAsync(invoice, currentUser)).JournalEntry;

    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromInvoiceWithResultAsync(Invoice invoice, Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(invoice.OrganizationId))
            return AccountingJournalEntryResult.Success();

        try
        {
            return await CreateJournalEntryFromInvoiceCoreAsync(invoice, currentUser);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "Invoice",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.Invoice,
                sourceId: invoice.InvoiceId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: invoice.TotalAmount,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromInvoiceCoreAsync(Invoice invoice, Guid currentUser)
    {
        if (await TryUseCrossPeriodInvoiceJournalEntryPathAsync(invoice))
        {
            var (crossPeriodEntry, decisionMessage, postAsStandardInvoice) = await CreateJournalEntriesFromCrossPeriodInvoiceAsync(invoice, currentUser);
            if (crossPeriodEntry != null)
            {
                return AccountingJournalEntryResult.Success(crossPeriodEntry);
            }

            await LogInvoiceSplitDecisionAsync(invoice, split: false, message: decisionMessage);

            if (!postAsStandardInvoice)
            {
                var message = $"Invoice {invoice.InvoiceCode} spans two accounting periods but the split failed: {decisionMessage}";
                await LogAccountingErrorAsync(
                    trigger: "Invoice",
                    organizationId: invoice.OrganizationId,
                    officeId: invoice.OfficeId,
                    sourceTypeId: (int)SourceType.Invoice,
                    sourceId: invoice.InvoiceId,
                    documentCode: invoice.InvoiceCode,
                    accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                    amount: invoice.TotalAmount,
                    message: message,
                    currentUser: currentUser);
                return AccountingJournalEntryResult.WarningResult(message);
            }
        }

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);
        var journalEntry = await CreateJournalEntryFromInvoiceAsync(invoice, chartOfAccounts, accountingOffice, currentUser);
        var createdJournalEntry = await CreateAutoGeneratedJournalEntryAsync(journalEntry);

        if (TryGetInvoiceRentalLineAmount(invoice, out _))
        {
            try
            {
                var rentPlus4000Base = await GetInvoiceRentPlus4000BaseAsync(invoice);
                await CreateJournalEntryFromInvoiceForOwnerShareAsync(invoice, rentPlus4000Base, currentUser);
            }
            catch (Exception ex)
            {
                var ownerMessage = $"Owner share journal entry failed for invoice {invoice.InvoiceCode}: {ex.Message}";
                await LogAccountingErrorAsync(
                    trigger: "InvoiceOwnerShare",
                    organizationId: invoice.OrganizationId,
                    officeId: invoice.OfficeId,
                    sourceTypeId: (int)SourceType.Invoice,
                    sourceId: invoice.InvoiceId,
                    documentCode: invoice.InvoiceCode,
                    accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                    amount: invoice.TotalAmount,
                    message: ownerMessage,
                    currentUser: currentUser);
                return AccountingJournalEntryResult.WarningResult(ownerMessage, createdJournalEntry);
            }
        }

        return AccountingJournalEntryResult.Success(createdJournalEntry);
    }

    public async Task<JournalEntry?> CreateJournalEntryFromPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, Guid currentUser)
        => (await CreateJournalEntryFromPaymentWithResultAsync(invoice, paymentLedgerLine, currentUser)).JournalEntry;

    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromPaymentWithResultAsync(Invoice invoice, LedgerLine paymentLedgerLine, Guid currentUser)
    {
        var existingPaymentEntries = await GetJournalEntriesForInvoicePaymentLedgerLineAsync(
            invoice.OrganizationId,
            invoice.OfficeId,
            invoice,
            paymentLedgerLine);
        return await UpsertJournalEntryFromPaymentAsync(invoice, paymentLedgerLine, existingPaymentEntries, currentUser);
    }

    private async Task<AccountingJournalEntryResult> UpsertJournalEntryFromPaymentAsync(
        Invoice invoice,
        LedgerLine paymentLedgerLine,
        IReadOnlyList<JournalEntry> existingPaymentEntries,
        Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(invoice.OrganizationId))
            return AccountingJournalEntryResult.Success();

        var retainedEntryIds = new HashSet<Guid>();
        var workingEntries = existingPaymentEntries.ToList();

        try
        {
            if (paymentLedgerLine.LedgerLineId == Guid.Empty)
                return AccountingJournalEntryResult.WarningResult("LedgerLineId is required to create a payment journal entry");

            var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);
            var prePaymentAccountId = GetDefaultPrePayment(chartOfAccounts, invoice.OfficeId, accountingOffice);
            var splitAllocations = await GetInvoicePaymentSplitAllocationsAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice);

            if (splitAllocations.Count > 0)
            {
                // Cross-period payment: recognize cash OwnAct (first split) and PrePay receive (second split) together.
                // PrePay apply + second OwnAct happen in the apply step below.
                var paymentJournalEntry = await CreateJournalEntryFromPaymentAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
                var updatedPayment = await UpsertClaimedAutoGeneratedJournalEntryAsync(
                    paymentJournalEntry,
                    workingEntries,
                    entry => IsStandardInvoicePaymentJournalEntry(entry),
                    retainedEntryIds,
                    currentUser,
                    invoice.OrganizationId);

                foreach (var splitAllocation in splitAllocations)
                {
                    var splitInvoice = CloneInvoiceForPaymentAccountingPeriod(invoice, splitAllocation.AccountingPeriod);
                    var splitPaymentLedgerLine = ClonePaymentLedgerLineWithAmount(paymentLedgerLine, splitAllocation.Amount);
                    if (IsInvoicePrePayment(splitInvoice, splitPaymentLedgerLine))
                    {
                        var receivedResult = await UpsertPrePaymentReceivedJournalEntryAsync(
                            splitInvoice,
                            splitPaymentLedgerLine,
                            chartOfAccounts,
                            accountingOffice,
                            workingEntries,
                            prePaymentAccountId,
                            retainedEntryIds,
                            currentUser);
                        if (receivedResult.HasWarning)
                            return AccountingJournalEntryResult.WarningResult(receivedResult.Warning!, updatedPayment);
                    }
                    else
                    {
                        await UpsertOwnerActualJournalEntryForPaymentAsync(
                            splitInvoice,
                            splitPaymentLedgerLine,
                            splitAllocation.Amount,
                            ResolveInvoicePaymentJournalEntryDate(splitPaymentLedgerLine),
                            workingEntries,
                            retainedEntryIds,
                            currentUser);
                    }
                }

                var allocatedAmount = splitAllocations.Sum(allocation => allocation.Amount);
                var unappliedAmount = paymentLedgerLine.Amount - allocatedAmount;
                if (unappliedAmount > 0)
                {
                    var unappliedLedgerLine = ClonePaymentLedgerLineWithAmount(paymentLedgerLine, unappliedAmount);
                    var unappliedPrePaymentResult = await UpsertPrePaymentReceivedJournalEntryAsync(
                        invoice,
                        unappliedLedgerLine,
                        chartOfAccounts,
                        accountingOffice,
                        workingEntries,
                        prePaymentAccountId,
                        retainedEntryIds,
                        currentUser);
                    if (unappliedPrePaymentResult.HasWarning)
                        return AccountingJournalEntryResult.WarningResult(unappliedPrePaymentResult.Warning!, updatedPayment);
                }

                await LogInvoicePaymentSplitDecisionAsync(invoice, paymentLedgerLine, splitAllocations, "Cross-period payment split applied.");

                foreach (var splitAllocation in splitAllocations)
                {
                    var splitInvoice = CloneInvoiceForPaymentAccountingPeriod(invoice, splitAllocation.AccountingPeriod);
                    var splitPaymentLedgerLine = ClonePaymentLedgerLineWithAmount(paymentLedgerLine, splitAllocation.Amount);
                    if (!IsInvoicePrePayment(splitInvoice, splitPaymentLedgerLine))
                        continue;

                    // Apply PrePay for the second split, then post OwnAct for that period.
                    var applyResult = await UpsertPrePaymentApplyJournalEntryAsync(
                        splitInvoice,
                        splitPaymentLedgerLine,
                        chartOfAccounts,
                        accountingOffice,
                        workingEntries,
                        prePaymentAccountId,
                        retainedEntryIds,
                        currentUser);
                    if (applyResult.HasWarning)
                        return AccountingJournalEntryResult.WarningResult(applyResult.Warning!, updatedPayment);
                }

                await DeleteClaimedOrphanJournalEntriesAsync(workingEntries, invoice.OrganizationId);
                return AccountingJournalEntryResult.Success(updatedPayment);
            }

            var journalEntry = await CreateJournalEntryFromPaymentAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
            var updatedJournalEntry = await UpsertClaimedAutoGeneratedJournalEntryAsync(
                journalEntry,
                workingEntries,
                entry => IsStandardInvoicePaymentJournalEntry(entry),
                retainedEntryIds,
                currentUser,
                invoice.OrganizationId);

            if (IsInvoicePrePayment(invoice, paymentLedgerLine))
            {
                var prePaymentResult = await UpsertJournalEntriesFromPrePaymentAsync(
                    invoice,
                    paymentLedgerLine,
                    chartOfAccounts,
                    accountingOffice,
                    workingEntries,
                    retainedEntryIds,
                    currentUser);
                await DeleteClaimedOrphanJournalEntriesAsync(workingEntries, invoice.OrganizationId);
                if (prePaymentResult.HasWarning)
                    return prePaymentResult;

                return AccountingJournalEntryResult.Success(prePaymentResult.JournalEntry ?? updatedJournalEntry);
            }

            await UpsertOwnerActualJournalEntryForPaymentAsync(
                invoice,
                paymentLedgerLine,
                paymentLedgerLine.Amount,
                ResolveInvoicePaymentJournalEntryDate(paymentLedgerLine),
                workingEntries,
                retainedEntryIds,
                currentUser);

            await DeleteClaimedOrphanJournalEntriesAsync(workingEntries, invoice.OrganizationId);
            return AccountingJournalEntryResult.Success(updatedJournalEntry);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "InvoicePayment",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.InvoicePayment,
                sourceId: paymentLedgerLine.LedgerLineId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: paymentLedgerLine.Amount,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    private async Task<AccountingJournalEntryResult> UpsertJournalEntriesFromPrePaymentAsync(
        Invoice invoice,
        LedgerLine paymentLedgerLine,
        List<ChartOfAccount> chartOfAccounts,
        AccountingOffice? accountingOffice,
        List<JournalEntry> workingEntries,
        ISet<Guid> retainedEntryIds,
        Guid currentUser)
    {
        var receivedResult = await UpsertPrePaymentReceivedJournalEntryAsync(
            invoice,
            paymentLedgerLine,
            chartOfAccounts,
            accountingOffice,
            workingEntries,
            GetDefaultPrePayment(chartOfAccounts, invoice.OfficeId, accountingOffice),
            retainedEntryIds,
            currentUser);
        if (receivedResult.HasWarning)
            return receivedResult;

        if (receivedResult.JournalEntry == null)
            return AccountingJournalEntryResult.Success();

        var applyResult = await UpsertPrePaymentApplyJournalEntryAsync(
            invoice,
            paymentLedgerLine,
            chartOfAccounts,
            accountingOffice,
            workingEntries,
            GetDefaultPrePayment(chartOfAccounts, invoice.OfficeId, accountingOffice),
            retainedEntryIds,
            currentUser);
        if (applyResult.HasWarning)
            return applyResult;

        return AccountingJournalEntryResult.Success(receivedResult.JournalEntry);
    }

    private async Task<AccountingJournalEntryResult> UpsertPrePaymentReceivedJournalEntryAsync(
        Invoice invoice,
        LedgerLine paymentLedgerLine,
        List<ChartOfAccount> chartOfAccounts,
        AccountingOffice? accountingOffice,
        List<JournalEntry> workingEntries,
        int prePaymentAccountId,
        ISet<Guid> retainedEntryIds,
        Guid currentUser)
    {
        try
        {
            var journalEntry = await CreateJournalEntryFromPrePaymentReceivedAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
            var updated = await UpsertClaimedAutoGeneratedJournalEntryAsync(
                journalEntry,
                workingEntries,
                entry => IsInvoicePrePaymentReceivedJournalEntry(entry, prePaymentAccountId),
                retainedEntryIds,
                currentUser,
                invoice.OrganizationId);
            return AccountingJournalEntryResult.Success(updated);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "InvoicePrePaymentReceived",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.InvoicePayment,
                sourceId: paymentLedgerLine.LedgerLineId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: paymentLedgerLine.Amount,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    private async Task<AccountingJournalEntryResult> UpsertPrePaymentApplyJournalEntryAsync(
        Invoice invoice,
        LedgerLine paymentLedgerLine,
        List<ChartOfAccount> chartOfAccounts,
        AccountingOffice? accountingOffice,
        List<JournalEntry> workingEntries,
        int prePaymentAccountId,
        ISet<Guid> retainedEntryIds,
        Guid currentUser)
    {
        try
        {
            var journalEntry = await CreateJournalEntryFromPrePaymentApplyAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
            var updated = await UpsertClaimedAutoGeneratedJournalEntryAsync(
                journalEntry,
                workingEntries,
                entry => IsInvoicePrePaymentApplyJournalEntry(entry, prePaymentAccountId)
                    && MatchesJournalEntryAccountingPeriod(entry, invoice.AccountingPeriod),
                retainedEntryIds,
                currentUser,
                invoice.OrganizationId);

            await UpsertOwnerActualJournalEntryForPaymentAsync(
                invoice,
                paymentLedgerLine,
                paymentLedgerLine.Amount,
                invoice.AccountingPeriod,
                workingEntries,
                retainedEntryIds,
                currentUser);
            return AccountingJournalEntryResult.Success(updated);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "InvoicePrePaymentApply",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.Invoice,
                sourceId: paymentLedgerLine.LedgerLineId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: paymentLedgerLine.Amount,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    private async Task UpsertOwnerActualJournalEntryForPaymentAsync(
        Invoice invoice,
        LedgerLine paymentLedgerLine,
        decimal paymentAmount,
        DateOnly transactionDate,
        List<JournalEntry> workingEntries,
        ISet<Guid> retainedEntryIds,
        Guid currentUser)
    {
        if (paymentAmount == 0 || paymentLedgerLine.LedgerLineId == Guid.Empty)
            return;

        try
        {
            // Amount context: Owner Expected lives on SourceType Invoice (Kind OwnerExpected).
            IReadOnlyList<JournalEntry> amountContextEntries = workingEntries;
            if (InvoiceCrossesAccountingPeriodBoundary(invoice))
            {
                var invoiceEntries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
                {
                    OrganizationId = invoice.OrganizationId,
                    OfficeIds = invoice.OfficeId.ToString(),
                    SourceTypeId = (int)SourceType.Invoice,
                    SourceId = invoice.InvoiceId,
                    IncludeVoided = false,
                    IncludeUnposted = true
                })).ToList();
                amountContextEntries = invoiceEntries
                    .Concat(workingEntries)
                    .GroupBy(entry => entry.JournalEntryId)
                    .Select(group => group.First())
                    .ToList();
            }

            var journalEntry = await BuildJournalEntryFromPaymentForOwnerActualAsync(
                invoice,
                paymentLedgerLine,
                paymentAmount,
                transactionDate,
                currentUser,
                amountContextEntries);
            var existingOwnerActual = ClaimFirstMatchingEntry(
                workingEntries,
                entry => IsInvoiceOwnerActualPaymentJournalEntry(entry)
                    && MatchesJournalEntryAccountingPeriod(entry, invoice.AccountingPeriod));

            if (journalEntry == null || !journalEntry.JournalEntryLines.Any(line => line.Debit != 0 || line.Credit != 0))
                return;

            var updated = await UpsertAutoGeneratedJournalEntryAsync(
                journalEntry,
                existingOwnerActual != null ? [existingOwnerActual] : [],
                currentUser,
                invoice.OrganizationId);
            if (updated != null)
                retainedEntryIds.Add(updated.JournalEntryId);
            // Do not re-add to workingEntries: DeleteClaimedOrphanJournalEntriesAsync removes payment-flow
            // orphans (including OwnerActual) still listed there after upsert.
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "InvoiceOwnerActual",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.InvoicePayment,
                sourceId: paymentLedgerLine.LedgerLineId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: paymentAmount,
                message: ex.Message,
                currentUser: currentUser);
        }
    }

    public async Task<JournalEntry?> CreateJournalEntriesFromPrePaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
        => (await CreateJournalEntriesFromPrePaymentWithResultAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser)).JournalEntry;

    private async Task<AccountingJournalEntryResult> CreateJournalEntriesFromPrePaymentWithResultAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        try
        {
            var receivedEntry = await CreatePrePaymentReceivedJournalEntryWithResultAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
            if (receivedEntry.HasWarning)
                return receivedEntry;

            if (receivedEntry.JournalEntry == null)
                return AccountingJournalEntryResult.Success();

            var applyResult = await CreatePrePaymentApplyJournalEntryWithResultAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
            if (applyResult.HasWarning)
                return applyResult;

            return AccountingJournalEntryResult.Success(receivedEntry.JournalEntry);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "InvoicePrePayment",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.InvoicePayment,
                sourceId: paymentLedgerLine.LedgerLineId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: paymentLedgerLine.Amount,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    public async Task<JournalEntry?> CreatePrePaymentReceivedJournalEntryAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
        => (await CreatePrePaymentReceivedJournalEntryWithResultAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser)).JournalEntry;

    private async Task<AccountingJournalEntryResult> CreatePrePaymentReceivedJournalEntryWithResultAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        try
        {
            var journalEntry = await CreateJournalEntryFromPrePaymentReceivedAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
            var created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);
            return AccountingJournalEntryResult.Success(created);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "InvoicePrePaymentReceived",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.InvoicePayment,
                sourceId: paymentLedgerLine.LedgerLineId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: paymentLedgerLine.Amount,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    public async Task<JournalEntry?> CreatePrePaymentApplyJournalEntryAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
        => (await CreatePrePaymentApplyJournalEntryWithResultAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser)).JournalEntry;

    private async Task<AccountingJournalEntryResult> CreatePrePaymentApplyJournalEntryWithResultAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        try
        {
            var journalEntry = await CreateJournalEntryFromPrePaymentApplyAsync(invoice, paymentLedgerLine, chartOfAccounts, accountingOffice, currentUser);
            var created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);
            await TryCreateOwnerActualJournalEntryForPaymentAsync(invoice, paymentLedgerLine, paymentLedgerLine.Amount, invoice.AccountingPeriod, currentUser);
            return AccountingJournalEntryResult.Success(created);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "InvoicePrePaymentApply",
                organizationId: invoice.OrganizationId,
                officeId: invoice.OfficeId,
                sourceTypeId: (int)SourceType.Invoice,
                sourceId: paymentLedgerLine.LedgerLineId,
                documentCode: invoice.InvoiceCode,
                accountingPeriod: invoice.AccountingPeriod == default ? null : invoice.AccountingPeriod,
                amount: paymentLedgerLine.Amount,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    public async Task<List<JournalEntry>> CreateJournalEntriesFromInvoicePaymentAsync(InvoicePayment invoicePayment, Guid currentUser)
    {
        var journalEntries = new List<JournalEntry>();

        if (invoicePayment.PaymentApplications.Count == 0)
            return journalEntries;

        foreach (var paymentApplication in invoicePayment.PaymentApplications)
        {
            var journalEntry = await CreateJournalEntryFromPaymentAsync(paymentApplication.Invoice, paymentApplication.PaymentLedgerLine, currentUser);
            if (journalEntry != null)
                journalEntries.Add(journalEntry);
        }

        return journalEntries;
    }
    #endregion

    #region Journal Entry
    private async Task<JournalEntry> CreateJournalEntryFromInvoiceAsync(Invoice invoice, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser, Guid? sourceIdOverride = null)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // INVOICE-JE-ACCOUNTS
        //   Line 1   — Debit: Accounts Receivable (GetDefaultAccountsReceivable) for the invoice total.
        //   Lines 2+ — Credit: Tenant Income (GetDefaultTenantIncome) for each non-payment charge line.
        // END INVOICE-JE-ACCOUNTS

        var costCodeById = await LoadCostCodeByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);
        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var lineContext = await ResolveInvoiceJournalEntryLineContextAsync(invoice);

        var chargeLines = invoice.LedgerLines.Where(l => l.Amount != 0).Where(l =>
        {
            costCodeById.TryGetValue(l.CostCodeId, out var costCode);
            return !IsPaymentLedgerLine(costCode);
        }).OrderBy(l => l.LineNumber).ToList();

        var totalAmount = chargeLines.Sum(l => l.Amount);
        if (invoice.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required to create a journal entry for an invoice");

        var transactionDate = invoice.AccountingPeriod;
        var invoiceMemo = BuildInvoiceJournalEntryMemo(invoice, chargeLines);
        var accountsReceivableLine = new JournalEntryLine
        {
            // Debit Accounts Recievable
            ChartOfAccountId = accountsReceivableAccountId,
            Debit = totalAmount > 0 ? totalAmount : 0,
            Credit = totalAmount < 0 ? Math.Abs(totalAmount) : 0,
            Memo = BuildAccountsReceivableMemo(invoice.InvoiceCode),
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(accountsReceivableLine, lineContext);
        var journalEntryLines = new List<JournalEntryLine> { accountsReceivableLine };

        foreach (var line in chargeLines)
        {
            costCodeById.TryGetValue(line.CostCodeId, out var costCode);
            var chargeLine = new JournalEntryLine
            {
                // Debit Tenant Income
                ChartOfAccountId = GetDefaultTenantIncome(chartOfAccounts, invoice.OfficeId, accountingOffice, costCode),
                CostCodeId = line.CostCodeId,
                Debit = line.Amount < 0 ? Math.Abs(line.Amount) : 0,
                Credit = line.Amount > 0 ? line.Amount : 0,
                Memo = BuildInvoiceChargeLineMemo(invoice, line),
                CreatedBy = currentUser
            };
            var chargeLineContext = lineContext with
            {
                ReservationId = NormalizeOptionalGuid(line.ReservationId) ?? lineContext.ReservationId
            };
            ApplyJournalEntryLineContext(chargeLine, chargeLineContext);
            journalEntryLines.Add(chargeLine);
        }

        return ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = transactionDate,
            AccountingPeriod = invoice.AccountingPeriod,
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = sourceIdOverride ?? invoice.InvoiceId,
            SourceCode = ResolveJournalEntrySourceCodeFromInvoice(invoice),
            Memo = invoiceMemo,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        }, JournalEntryKind.Charge, Perspective.Company);
    }

    private async Task<JournalEntry> CreateJournalEntryFromPaymentAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // PAYMENT-JE-ACCOUNTS
        // Line 1 — Debit: Undeposited Funds (GetDefaultUndepositedFunds).
        // Line 2 — Credit: Accounts Receivable (GetDefaultAccountsReceivable).
        // END PAYMENT-JE-ACCOUNTS

        if (paymentLedgerLine.Amount == 0)
            throw new Exception("Payment amount cannot be zero");

        if (paymentLedgerLine.LedgerLineDate == default)
            throw new Exception("Payment date is required to create a payment journal entry");

        var costCodeById = await LoadCostCodeByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);
        if (!costCodeById.TryGetValue(paymentLedgerLine.CostCodeId, out var paymentCostCode) || !IsPaymentLedgerLine(paymentCostCode))
            throw new Exception("Payment ledger line must use a payment cost code");

        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var undepositedFundsAccountId = GetDefaultUndepositedFunds(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var lineContext = await ResolveInvoiceJournalEntryLineContextAsync(invoice, paymentLedgerLine);

        var amount = paymentLedgerLine.Amount;
        var transactionDate = ResolveInvoicePaymentJournalEntryDate(paymentLedgerLine);
        var memo = BuildInvoicePaymentMemo(invoice.InvoiceCode, paymentLedgerLine.Description);

        var undepositedFundsLine = new JournalEntryLine
        {
            ChartOfAccountId = undepositedFundsAccountId,
            CostCodeId = paymentLedgerLine.CostCodeId,
            Debit = amount > 0 ? amount : 0,
            Credit = amount < 0 ? Math.Abs(amount) : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(undepositedFundsLine, lineContext);
        var accountsReceivableLine = new JournalEntryLine
        {
            ChartOfAccountId = accountsReceivableAccountId,
            Debit = amount < 0 ? Math.Abs(amount) : 0,
            Credit = amount > 0 ? amount : 0,
            Memo = BuildAccountsReceivableMemo(invoice.InvoiceCode),
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(accountsReceivableLine, lineContext);

        return ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = transactionDate,
            AccountingPeriod = invoice.AccountingPeriod != default
                ? invoice.AccountingPeriod
                : FirstDayOfMonth(transactionDate),
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = invoice.InvoiceId,
            SourceCode = ResolveJournalEntrySourceCodeFromInvoice(invoice),
            Memo = memo,
            JournalEntryLines = new List<JournalEntryLine> { undepositedFundsLine, accountsReceivableLine },
            CreatedBy = currentUser
        }, JournalEntryKind.Payment, Perspective.Company);
    }

    private async Task<JournalEntry> CreateJournalEntryFromPrePaymentReceivedAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // PRE-PAYMENT-RECEIVED-JE-ACCOUNTS
        // Line 1 — Debit: Accounts Receivable (GetDefaultAccountsReceivable).
        // Line 2 — Credit: Pre-Payment liability (GetDefaultPrePayment).
        // END PRE-PAYMENT-RECEIVED-JE-ACCOUNTS

        await ValidatePrePaymentLedgerLineForJournalEntryAsync(invoice, paymentLedgerLine);

        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var prePaymentAccountId = GetDefaultPrePayment(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var lineContext = await ResolveInvoiceJournalEntryLineContextAsync(invoice, paymentLedgerLine);
        var amount = paymentLedgerLine.Amount;
        var transactionDate = paymentLedgerLine.LedgerLineDate;
        var memo = BuildInvoicePrePaymentMemo(invoice.InvoiceCode, paymentLedgerLine.Description);

        var accountsReceivableLine = new JournalEntryLine
        {
            // Debit Accounts Recievable
            ChartOfAccountId = accountsReceivableAccountId,
            Debit = amount > 0 ? amount : 0,
            Credit = amount < 0 ? Math.Abs(amount) : 0,
            Memo = BuildAccountsReceivableMemo(invoice.InvoiceCode),
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(accountsReceivableLine, lineContext);
        var prePaymentLine = new JournalEntryLine
        {
            // Credit Prepayment Account
            ChartOfAccountId = prePaymentAccountId,
            CostCodeId = paymentLedgerLine.CostCodeId,
            Debit = amount < 0 ? Math.Abs(amount) : 0,
            Credit = amount > 0 ? amount : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(prePaymentLine, lineContext);

        return ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = transactionDate,
            AccountingPeriod = FirstDayOfMonth(transactionDate),
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = invoice.InvoiceId,
            SourceCode = ResolveJournalEntrySourceCodeFromInvoice(invoice),
            Memo = memo,
            JournalEntryLines = new List<JournalEntryLine> { accountsReceivableLine, prePaymentLine },
            CreatedBy = currentUser
        }, JournalEntryKind.PrePaymentReceive, Perspective.Tenant);
    }

    private async Task<JournalEntry> CreateJournalEntryFromPrePaymentApplyAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // PRE-PAYMENT-APPLY-JE-ACCOUNTS (on the date of the payment)
        // Line 1 — Debit: Pre-Payment liability (GetDefaultPrePayment).
        // Line 2 — Credit: Accounts Receivable (GetDefaultAccountsReceivable).
        // END PRE-PAYMENT-APPLY-JE-ACCOUNTS (on date of accounting period)

        await ValidatePrePaymentLedgerLineForJournalEntryAsync(invoice, paymentLedgerLine);

        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var prePaymentAccountId = GetDefaultPrePayment(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var lineContext = await ResolveInvoiceJournalEntryLineContextAsync(invoice, paymentLedgerLine);
        var amount = paymentLedgerLine.Amount;
        var transactionDate = invoice.AccountingPeriod;
        var memo = BuildInvoicePrePaymentMemo(invoice.InvoiceCode, paymentLedgerLine.Description);

        var prePaymentLine = new JournalEntryLine
        {
            // Debit PrePayment Account
            ChartOfAccountId = prePaymentAccountId,
            CostCodeId = paymentLedgerLine.CostCodeId,
            Debit = amount > 0 ? amount : 0,
            Credit = amount < 0 ? Math.Abs(amount) : 0,
            Memo = memo,
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(prePaymentLine, lineContext);
        var accountsReceivableLine = new JournalEntryLine
        {
            // Credit AccountsReceiveable
            ChartOfAccountId = accountsReceivableAccountId,
            Debit = amount < 0 ? Math.Abs(amount) : 0,
            Credit = amount > 0 ? amount : 0,
            Memo = BuildAccountsReceivableMemo(invoice.InvoiceCode),
            CreatedBy = currentUser
        };
        ApplyJournalEntryLineContext(accountsReceivableLine, lineContext);

        return ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = transactionDate,
            AccountingPeriod = invoice.AccountingPeriod,
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = invoice.InvoiceId,
            SourceCode = ResolveJournalEntrySourceCodeFromInvoice(invoice),
            Memo = memo,
            JournalEntryLines = new List<JournalEntryLine> { prePaymentLine, accountsReceivableLine },
            CreatedBy = currentUser
        }, JournalEntryKind.PrePaymentApply, Perspective.Company);
    }

    private async Task ValidatePrePaymentLedgerLineForJournalEntryAsync(Invoice invoice, LedgerLine paymentLedgerLine)
    {
        if (paymentLedgerLine.Amount == 0)
            throw new Exception("Payment amount cannot be zero");

        if (paymentLedgerLine.LedgerLineDate == default)
            throw new Exception("Payment date is required to create a payment journal entry");

        if (invoice.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required to create pre-payment journal entries");

        var costCodeById = await LoadCostCodeByOfficeIdAsync(invoice.OrganizationId, invoice.OfficeId);
        if (!costCodeById.TryGetValue(paymentLedgerLine.CostCodeId, out var paymentCostCode) || !IsPaymentLedgerLine(paymentCostCode))
            throw new Exception("Payment ledger line must use a payment cost code");
    }

    private async Task DeleteJournalEntriesForInvoicePaymentLedgerLineAsync(Invoice invoice, LedgerLine paymentLedgerLine)
    {
        var entries = (await GetAllJournalEntriesForInvoiceAsync(invoice.OrganizationId, invoice.OfficeId, invoice.InvoiceId))
            .Where(entry => IsInvoicePaymentLedgerLineJournalEntry(entry, invoice, paymentLedgerLine))
            .ToList();

        foreach (var entry in entries)
            await DeleteOpenJournalEntryAsync(entry.JournalEntryId, invoice.OrganizationId);
    }

    private async Task<Guid?> ResolveInvoicePropertyIdAsync(Invoice invoice)
    {
        if (invoice.PropertyId.HasValue && invoice.PropertyId != Guid.Empty)
            return invoice.PropertyId;

        if (!invoice.ReservationId.HasValue || invoice.ReservationId == Guid.Empty)
            return null;

        if (invoice.ReservationId == SystemOrganization)
            return null;

        var reservation = await _reservationRepository.GetReservationByIdAsync(invoice.ReservationId.Value, invoice.OrganizationId);
        if (reservation == null || reservation.PropertyId == Guid.Empty)
            return null;

        return reservation.PropertyId;
    }
    #endregion

    #region Helpers
    private static bool IsInvoicePrePayment(Invoice invoice, LedgerLine paymentLedgerLine)
    {
        if (invoice.AccountingPeriod == default || paymentLedgerLine.LedgerLineDate == default)
            return false;

        return paymentLedgerLine.LedgerLineDate < invoice.AccountingPeriod;
    }

    private static bool IsPaymentLedgerLine(CostCode? costCode)
    {
        return costCode?.TransactionType == TransactionType.Payment;
    }

    private async Task<List<InvoicePaymentSplitAllocation>> GetInvoicePaymentSplitAllocationsAsync(Invoice invoice, LedgerLine paymentLedgerLine, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice)
    {
        var paymentAmount = paymentLedgerLine.Amount;
        if (paymentAmount == 0)
            return new List<InvoicePaymentSplitAllocation>();

        // Cross-month invoices allocate payment to the first accounting-period slice until it is
        // fully paid, then to the second slice. Any remainder beyond both slices stays as unapplied prepayment.
        if (!InvoiceCrossesAccountingPeriodBoundary(invoice))
            return new List<InvoicePaymentSplitAllocation>();

        if (!TryCreateCrossPeriodInvoiceSlices(invoice, out var firstPeriodInvoice, out var secondPeriodInvoice))
            return new List<InvoicePaymentSplitAllocation>();

        if (!TryResolveCrossPeriodBounds(invoice, out var firstSliceStart, out var firstSliceEnd, out var secondSliceStart, out var secondSliceEnd))
            return new List<InvoicePaymentSplitAllocation>();

        var firstAccountingPeriod = firstPeriodInvoice.AccountingPeriod;
        var secondAccountingPeriod = secondPeriodInvoice.AccountingPeriod;
        decimal firstChargeCap;
        decimal secondChargeCap;

        var postedCharges = await GetCrossPeriodChargesForPaymentSplitAsync(invoice, chartOfAccounts, accountingOffice, firstAccountingPeriod, secondAccountingPeriod);
        if (postedCharges.HasValue)
        {
            firstChargeCap = postedCharges.Value.FirstPeriodCharge;
            secondChargeCap = postedCharges.Value.SecondPeriodCharge;
        }
        else
        {
            var firstSliceDays = CountInclusiveDays(firstSliceStart, firstSliceEnd);
            var secondSliceDays = CountInclusiveDays(secondSliceStart, secondSliceEnd);
            if (firstSliceDays <= 0 || secondSliceDays <= 0)
                return new List<InvoicePaymentSplitAllocation>();

            var totalSliceDays = firstSliceDays + secondSliceDays;
            firstChargeCap = Math.Round(invoice.TotalAmount * (firstSliceDays / (decimal)totalSliceDays), 2, MidpointRounding.AwayFromZero);
            secondChargeCap = invoice.TotalAmount - firstChargeCap;
        }

        if (firstChargeCap <= 0 || secondChargeCap <= 0)
            return new List<InvoicePaymentSplitAllocation>();

        var firstPaymentAmount = Math.Min(paymentAmount, firstChargeCap);
        var remainingAfterFirst = paymentAmount - firstPaymentAmount;
        var secondPaymentAmount = Math.Min(remainingAfterFirst, secondChargeCap);
        if (firstPaymentAmount == 0 && secondPaymentAmount == 0)
            return new List<InvoicePaymentSplitAllocation>();

        var allocations = new List<InvoicePaymentSplitAllocation>();
        if (firstPaymentAmount > 0)
            allocations.Add(new InvoicePaymentSplitAllocation { AccountingPeriod = firstAccountingPeriod, Amount = firstPaymentAmount });
        if (secondPaymentAmount > 0)
            allocations.Add(new InvoicePaymentSplitAllocation { AccountingPeriod = secondAccountingPeriod, Amount = secondPaymentAmount });
        return allocations;
    }

    private async Task<(decimal FirstPeriodCharge, decimal SecondPeriodCharge)?> GetCrossPeriodChargesForPaymentSplitAsync(Invoice invoice, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, DateOnly firstAccountingPeriod, DateOnly secondAccountingPeriod)
    {
        var accountsReceivableAccountId = GetDefaultAccountsReceivable(chartOfAccounts, invoice.OfficeId, accountingOffice);
        var sourceJournalEntries = (await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = invoice.OrganizationId,
            OfficeIds = invoice.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = invoice.InvoiceId,
            IncludeVoided = false,
            IncludeUnposted = true
        })).ToList();

        if (sourceJournalEntries.Count == 0)
            return null;

        var arAmountByPeriod = sourceJournalEntries
            .Where(entry => entry.JournalEntryKindId == JournalEntryKind.Charge)
            .Select(entry => new
            {
                entry.TransactionDate,
                ArAmount = entry.JournalEntryLines
                    .Where(line => line.ChartOfAccountId == accountsReceivableAccountId)
                    .Sum(line => line.Debit - line.Credit)
            })
            .Where(item => item.ArAmount != 0)
            .GroupBy(item => item.TransactionDate)
            .ToDictionary(group => group.Key, group => Math.Abs(group.Sum(item => item.ArAmount)));

        if (!arAmountByPeriod.TryGetValue(firstAccountingPeriod, out var firstPeriodCharge)
            || !arAmountByPeriod.TryGetValue(secondAccountingPeriod, out var secondPeriodCharge)
            || firstPeriodCharge == 0
            || secondPeriodCharge == 0)
        {
            return null;
        }

        return (firstPeriodCharge, secondPeriodCharge);
    }

    private static int CountInclusiveDays(DateOnly start, DateOnly end)
        => start > end ? 0 : end.DayNumber - start.DayNumber + 1;

    private static Invoice CloneInvoiceForPaymentAccountingPeriod(Invoice source, DateOnly accountingPeriod)
    {
        return new Invoice
        {
            InvoiceId = source.InvoiceId,
            OrganizationId = source.OrganizationId,
            OfficeId = source.OfficeId,
            OfficeName = source.OfficeName,
            InvoiceCode = source.InvoiceCode,
            ReservationId = source.ReservationId,
            ReservationCode = source.ReservationCode,
            PropertyId = source.PropertyId,
            PropertyCode = source.PropertyCode,
            ContactId = source.ContactId,
            ContactName = source.ContactName,
            CompanyId = source.CompanyId,
            CompanyName = source.CompanyName,
            ResponsibleParty = source.ResponsibleParty,
            InvoiceDate = source.InvoiceDate,
            DueDate = source.DueDate,
            AccountingPeriod = accountingPeriod,
            InvoicePeriod = source.InvoicePeriod,
            TotalAmount = source.TotalAmount,
            PaidAmount = source.PaidAmount,
            Notes = source.Notes,
            IsActive = source.IsActive,
            LedgerLines = source.LedgerLines,
            CreatedOn = source.CreatedOn,
            CreatedBy = source.CreatedBy,
            ModifiedOn = source.ModifiedOn,
            ModifiedBy = source.ModifiedBy
        };
    }

    private static LedgerLine ClonePaymentLedgerLineWithAmount(LedgerLine source, decimal amount)
    {
        return new LedgerLine
        {
            LedgerLineId = source.LedgerLineId,
            InvoiceId = source.InvoiceId,
            LineNumber = source.LineNumber,
            ReservationId = source.ReservationId,
            CostCodeId = source.CostCodeId,
            Amount = amount,
            Description = source.Description,
            LedgerLineDate = source.LedgerLineDate,
            CreatedOn = source.CreatedOn,
            CreatedBy = source.CreatedBy,
            ModifiedOn = source.ModifiedOn,
            ModifiedBy = source.ModifiedBy
        };
    }

    private async Task LogInvoicePaymentSplitDecisionAsync(Invoice invoice, LedgerLine paymentLedgerLine, IReadOnlyList<InvoicePaymentSplitAllocation> splitAllocations, string? message = null)
    {
        var propertyId = await ResolveInvoicePropertyIdAsync(invoice);
        var orderedAllocations = (splitAllocations ?? Array.Empty<InvoicePaymentSplitAllocation>())
            .OrderBy(a => a.AccountingPeriod)
            .ToList();
        var firstAllocation = orderedAllocations.ElementAtOrDefault(0);
        var secondAllocation = orderedAllocations.ElementAtOrDefault(1);
        var allocationSummary = string.Join(", ", orderedAllocations.Select(allocation => $"{allocation.AccountingPeriod:MM/yyyy}={allocation.Amount:0.00}"));
        var finalMessage = string.IsNullOrWhiteSpace(message)
            ? $"Payment split allocations: {allocationSummary}"
            : $"{message} {allocationSummary}";

        await LogAccountingLogAsync(new AccountingLog
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            PropertyId = propertyId,
            InvoiceId = invoice.InvoiceId,
            OriginalAmount = paymentLedgerLine.Amount,
            RentalLine = paymentLedgerLine.Description,
            Split = orderedAllocations.Count > 1,
            FirstPeriod = firstAllocation == null ? null : firstAllocation.AccountingPeriod.ToString("MM/yyyy"),
            SecondPeriod = secondAllocation == null ? null : secondAllocation.AccountingPeriod.ToString("MM/yyyy"),
            FirstAmount = firstAllocation?.Amount,
            SecondAmount = secondAllocation?.Amount,
            Message = finalMessage
        });
    }
    #endregion
}
