using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Triggers
    public async Task<JournalEntry?> CreateJournalEntryFromWorkOrderAsync(WorkOrder workOrder, Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(workOrder.OrganizationId))
            return null;

        if (!ShouldCreateJournalEntryForWorkOrder(workOrder))
            return null;

        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = workOrder.OrganizationId,
            OfficeIds = workOrder.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.WorkOrder,
            SourceId = workOrder.WorkOrderId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        var existingEntry = existingEntries.FirstOrDefault(e => !e.IsVoided);
        if (existingEntry != null)
        {
            if (existingEntry.IsPosted)
                return existingEntry;

            await ReplaceJournalEntriesFromWorkOrderAsync(workOrder, currentUser);
            return (await _journalEntryRepository.GetJournalEntryByIdAsync(existingEntry.JournalEntryId, workOrder.OrganizationId))!;
        }

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(workOrder.OrganizationId, workOrder.OfficeId);
        var journalEntry = await BuildJournalEntryFromWorkOrderAsync(workOrder, chartOfAccounts, accountingOffice, currentUser);
        return await CreateAutoGeneratedJournalEntryAsync(journalEntry);
    }

    private async Task<JournalEntry?> CreateJournalEntryFromInvoiceOwnerShareAsync(Invoice invoice, decimal amount, Guid currentUser)
    {
        var propertyId = await ResolveInvoicePropertyIdAsync(invoice);
        if (propertyId == null || propertyId == Guid.Empty)
            return null;

        var property = await _propertyRepository.GetPropertyByIdAsync(propertyId.Value, invoice.OrganizationId);
        var propertyAgreement = await _propertyRepository.GetPropertyAgreementByPropertyIdAsync(propertyId.Value);
        if (property == null || propertyAgreement == null)
            return null;

        var accountContextTask = LoadAccountContextAsync(invoice.OrganizationId, invoice.OfficeId);
        var officeCostCodeContextTask = LoadOfficeCostCodeContextAsync(invoice.OrganizationId, invoice.OfficeId);
        await Task.WhenAll(accountContextTask, officeCostCodeContextTask);
        var (chartOfAccounts, accountingOffice) = await accountContextTask;
        var (office, costCodeById) = await officeCostCodeContextTask;

        decimal ownerAmount = 0m;
        List<JournalEntryLine>? journalEntryLines = new List<JournalEntryLine>();
        switch (property.PropertyLeaseType)
        {
            case PropertyLeaseType.PropertyManagement:
            {
                if (!TryGetInvoiceRentalLedgerLine(invoice, out _))
                    return null;

                switch (propertyAgreement.ManagementFeeType)
                {
                    case ManagementFeeType.FlatRate:
                        ownerAmount = propertyAgreement.FlatRateAmount;
                        break;

                    case ManagementFeeType.Percentage:
                        ownerAmount = amount * propertyAgreement.RevenueSplitOwner / 100m;
                        break;

                    case ManagementFeeType.Minimum:
                        ownerAmount = amount * propertyAgreement.RevenueSplitOwner / 100m;
                        if (ownerAmount < propertyAgreement.FlatRateAmount)
                            ownerAmount = propertyAgreement.FlatRateAmount;
                        break;

                    default:
                        break;
                }

                if (ownerAmount != 0)
                    journalEntryLines = BuildJournalEntryLinesForPropertyManagement(invoice, ownerAmount, property, chartOfAccounts, accountingOffice, office, costCodeById, propertyId.Value, currentUser);

                break;
            }

            case PropertyLeaseType.Direct:
            case PropertyLeaseType.ThirdParty:
            {
                return null;
            }

            default:
                return null;
        }

        if (journalEntryLines == null || journalEntryLines.Count == 0)
            return null;

        if (invoice.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required to create an owner share journal entry for an invoice");

        var existingOwnerShareEntry = await GetExistingInvoiceOwnerShareJournalEntryAsync(invoice);
        if (existingOwnerShareEntry != null)
            return existingOwnerShareEntry;

        var ownerJournalEntry = new JournalEntry
        {
            OrganizationId = invoice.OrganizationId,
            OfficeId = invoice.OfficeId,
            TransactionDate = invoice.AccountingPeriod,
            PostingDate = invoice.AccountingPeriod,
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = invoice.InvoiceId,
            Memo = $"Owner Share - {invoice.InvoiceCode}",
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };

        return await CreateAutoGeneratedJournalEntryAsync(ownerJournalEntry);
    }

    private async Task<JournalEntry?> GetExistingInvoiceOwnerShareJournalEntryAsync(Invoice invoice)
    {
        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = invoice.OrganizationId,
            OfficeIds = invoice.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.Invoice,
            SourceId = invoice.InvoiceId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        return existingEntries
            .Where(e => !e.IsVoided)
            .Where(e => e.Memo != null && e.Memo.StartsWith("Owner Share", StringComparison.OrdinalIgnoreCase))
            .Where(e => invoice.AccountingPeriod == default || e.PostingDate == invoice.AccountingPeriod)
            .FirstOrDefault();
    }
    #endregion

    #region Journal Entry
    private List<JournalEntryLine> BuildJournalEntryLinesForPropertyManagement(Invoice invoice, decimal ownerAmount, Property property, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Office? office, IReadOnlyDictionary<int, CostCode> costCodeById, Guid propertyId, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // OWNER-SHARE-JE-ACCOUNTS
        // Line 1 — Debit: Tenant rental income for the invoice rental ledger line (GetDefaultTenantIncomeByCostCodeId).
        // Line 2 — Credit: Furnished or unfurnished rent expense.
        // END OWNER-SHARE-JE-ACCOUNTS

        var journalEntryLines = new List<JournalEntryLine>();

        if (!TryGetInvoiceRentalLedgerLine(invoice, out var rentalLine))
            return journalEntryLines;

        var isFurnished = !property.Unfurnished;
        var memo = $"Owner Share - {invoice.InvoiceCode}";
        var rentalIncomeAccountId = GetDefaultTenantIncomeByCostCodeId(chartOfAccounts, invoice.OfficeId, rentalLine.CostCodeId, costCodeById, accountingOffice);
        var ownerRentExpenseCostCodeId = isFurnished ? office?.FurnishedRentExpenseCcId : office?.UnfurnishedRentExpenseCcId;
        var ownerRentExpenseAccountId = isFurnished
            ? GetDefaultFurnishedRentExpense(chartOfAccounts, invoice.OfficeId, office, costCodeById, accountingOffice)
            : GetDefaultUnfurnishedRentExpense(chartOfAccounts, invoice.OfficeId, office, costCodeById, accountingOffice);

        journalEntryLines.Add(new JournalEntryLine
        {
            ChartOfAccountId = rentalIncomeAccountId,
            CostCodeId = rentalLine.CostCodeId,
            PropertyId = propertyId,
            ReservationId = invoice.ReservationId,
            ContactId = invoice.ContactId,
            Debit = ownerAmount > 0 ? ownerAmount : 0,
            Credit = ownerAmount < 0 ? Math.Abs(ownerAmount) : 0,
            Memo = memo,
            CreatedBy = currentUser
        });

        journalEntryLines.Add(new JournalEntryLine
        {
            ChartOfAccountId = ownerRentExpenseAccountId,
            CostCodeId = ownerRentExpenseCostCodeId is > 0 ? ownerRentExpenseCostCodeId : null,
            PropertyId = propertyId,
            ReservationId = invoice.ReservationId,
            ContactId = invoice.ContactId,
            Debit = ownerAmount < 0 ? Math.Abs(ownerAmount) : 0,
            Credit = ownerAmount > 0 ? ownerAmount : 0,
            Memo = memo,
            CreatedBy = currentUser
        });

        return journalEntryLines;
    }

    private static bool ShouldCreateJournalEntryForWorkOrder(WorkOrder workOrder)
        => workOrder.WorkOrderType == WorkOrderType.Owner;

    private Task<JournalEntry> BuildJournalEntryFromWorkOrderAsync(WorkOrder workOrder, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // WORK-ORDER-JE-ACCOUNTS — not yet implemented.
        // TODO: build journal entry lines from work order items and linked receipts.
        throw new NotImplementedException("Work order journal entry build logic is not yet implemented.");
    }
    #endregion
}
