using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Journal Entry
    public async Task<List<JournalEntry>> CreateJournalEntriesFromBillPaymentDocumentAsync(Guid paymentId, Guid organizationId, Guid currentUser)
    {
        var journalEntries = new List<JournalEntry>();

        if (paymentId == Guid.Empty)
            return journalEntries;

        if (!await IsAccountingFeatureEnabledAsync(organizationId))
            return journalEntries;

        Payment? payment = null;
        if (_officeSyncCache != null && _officeSyncCache.PaymentsById.TryGetValue(paymentId, out var cachedPayment))
            payment = cachedPayment;
        else
            payment = await _accountingRepository.GetPaymentByIdAsync(paymentId, organizationId);

        if (payment == null)
            throw new Exception("Payment record not found");

        if (payment.BillAllocations.Count == 0)
            payment = await _accountingRepository.GetPaymentByIdAsync(paymentId, organizationId)
                ?? throw new Exception("Payment record not found");

        if (payment.PaymentKindId != (int)PaymentKind.Bill)
            throw new Exception("Payment is not a bill payment.");

        if (payment.BillAllocations.Count == 0)
            return journalEntries;

        if (payment.ChartOfAccountId is not > 0)
            throw new Exception("ChartOfAccountId is required for bill payment journal entries.");

        var applications = new List<BillPaymentApplication>();
        foreach (var allocation in payment.BillAllocations.OrderBy(item => item.LineNumber))
        {
            var bill = await _maintenanceRepository.GetReceiptByIdAsync(allocation.ReceiptId, organizationId)
                ?? throw new Exception($"Bill not found: {allocation.ReceiptCode}");

            bill = await LoadReceiptWithSplitsAsync(bill);
            applications.Add(new BillPaymentApplication
            {
                Bill = bill,
                AmountApplied = allocation.Amount,
                PaymentDate = payment.PaymentDate,
                ChartOfAccountId = payment.ChartOfAccountId.Value,
                Description = ResolveBillPaymentAllocationDescription(bill, allocation.Description, payment.Description),
                PaymentSequence = 0,
                CostCodeId = allocation.CostCodeId
            });
        }

        await DeleteBillPaymentJournalEntriesAsync(payment);

        var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(payment.OrganizationId, payment.OfficeId);
        var journalEntry = await BuildConsolidatedBillPaymentJournalEntryAsync(payment, applications, chartOfAccounts, accountingOffice, currentUser);

        var created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);
        if (created != null)
        {
            ApplyPaymentDocumentLink(created, payment);
            created.ModifiedBy = currentUser;
            await UpdateJournalEntryWithoutRetainedEarningsRefreshAsync(created, requireActiveLines: true);
            journalEntries.Add(created);
        }

        return journalEntries;
    }

    /// <summary>Bill payment document JE: kind BillPayment with PaymentId stamped.</summary>
    private async Task<bool> PaymentHasHealthBillPaymentJournalEntryAsync(Guid paymentId, Guid organizationId)
    {
        if (paymentId == Guid.Empty)
            return false;

        var linkedEntries = await GetJournalEntriesByPaymentIdCachedAsync(organizationId, paymentId);
        if (linkedEntries.Any(entry =>
                entry.JournalEntryKindId == JournalEntryKind.BillPayment
                && entry.PaymentId is { } linkedPaymentId
                && linkedPaymentId == paymentId))
            return true;

        Payment? payment = null;
        if (_officeSyncCache != null && _officeSyncCache.PaymentsById.TryGetValue(paymentId, out var cachedPayment))
            payment = cachedPayment;
        else
            payment = await _accountingRepository.GetPaymentByIdAsync(paymentId, organizationId);

        if (payment == null)
            return false;

        var documentEntries = await GetJournalEntriesForSourceAsync(
            payment.OrganizationId,
            payment.OfficeId,
            SourceType.BillPayment,
            paymentId);

        return documentEntries.Any(entry => entry.JournalEntryKindId == JournalEntryKind.BillPayment);
    }

    private static HashSet<Guid> GetReceiptIdsCoveredByBillPaymentDocuments(IEnumerable<Payment> billPayments)
    {
        return billPayments
            .Where(payment => payment.IsActive)
            .SelectMany(payment => payment.BillAllocations ?? [])
            .Select(allocation => allocation.ReceiptId)
            .Where(receiptId => receiptId != Guid.Empty)
            .ToHashSet();
    }

    private async Task<bool> IsBillCoveredByBillPaymentDocumentAsync(Guid receiptId, Guid organizationId, int officeId)
    {
        if (receiptId == Guid.Empty)
            return false;

        var billPayments = await _accountingRepository.GetPaymentsByOfficeIdsAsync(
            organizationId,
            officeId.ToString(),
            (int)PaymentKind.Bill);

        return GetReceiptIdsCoveredByBillPaymentDocuments(billPayments).Contains(receiptId);
    }

    private async Task DeleteLegacyBillPaymentJournalEntriesForReceiptAsync(Receipt bill)
    {
        var legacyPaymentEntries = await GetJournalEntriesForSourceAsync(
            bill.OrganizationId,
            bill.OfficeId,
            SourceType.BillPayment,
            bill.ReceiptId);

        foreach (var journalEntry in legacyPaymentEntries)
            await DeleteOpenJournalEntryAsync(journalEntry.JournalEntryId, bill.OrganizationId);
    }

    private async Task SyncBillPaymentJournalEntryAsync(
        Payment paymentSummary,
        Guid organizationId,
        Guid currentUser,
        JournalEntrySyncResult result)
    {
        if (!paymentSummary.IsActive)
        {
            result.JournalEntriesSkipped++;
            return;
        }

        if (paymentSummary.BillAllocations.Count == 0)
        {
            result.JournalEntriesSkipped++;
            return;
        }

        await CreateJournalEntriesFromBillPaymentDocumentAsync(paymentSummary.PaymentId, organizationId, currentUser);

        if (await PaymentHasHealthBillPaymentJournalEntryAsync(paymentSummary.PaymentId, organizationId))
        {
            result.JournalEntriesCreated++;
            return;
        }

        result.JournalEntriesSkipped++;

        Payment? payment = null;
        if (_officeSyncCache != null && _officeSyncCache.PaymentsById.TryGetValue(paymentSummary.PaymentId, out var cachedPayment))
            payment = cachedPayment;
        else
            payment = await _accountingRepository.GetPaymentByIdAsync(paymentSummary.PaymentId, organizationId);

        var message = $"Bill payment {ResolvePaymentDocumentCode(payment, paymentSummary)}: no BillPayment JE with PaymentId after sync.";
        await LogAccountingErrorAsync(
            trigger: "BillPaymentSkip",
            organizationId: organizationId,
            officeId: paymentSummary.OfficeId,
            sourceTypeId: (int)SourceType.BillPayment,
            sourceId: paymentSummary.PaymentId,
            documentCode: ResolvePaymentDocumentCode(payment, paymentSummary),
            accountingPeriod: null,
            amount: paymentSummary.Amount,
            message: message,
            currentUser: currentUser);
        result.Errors.Add(message);
    }
    #endregion

    #region Helpers
    private async Task DeleteBillPaymentJournalEntriesAsync(Payment payment)
    {
        var linkedEntries = await GetJournalEntriesByPaymentIdCachedAsync(payment.OrganizationId, payment.PaymentId);
        foreach (var journalEntry in linkedEntries)
            await DeleteOpenJournalEntryAsync(journalEntry.JournalEntryId, payment.OrganizationId);

        var documentEntries = await GetJournalEntriesForSourceAsync(payment.OrganizationId, payment.OfficeId, SourceType.BillPayment, payment.PaymentId);

        foreach (var journalEntry in documentEntries)
            await DeleteOpenJournalEntryAsync(journalEntry.JournalEntryId, payment.OrganizationId);
    }

    private async Task<JournalEntry> BuildConsolidatedBillPaymentJournalEntryAsync(Payment payment, IReadOnlyList<BillPaymentApplication> applications, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        if (payment.Amount == 0)
            throw new Exception("Payment amount cannot be zero");

        if (applications.Count == 0)
            throw new Exception("At least one bill allocation is required.");

        var bankAccountId = payment.ChartOfAccountId ?? 0;
        if (bankAccountId <= 0)
            throw new Exception("Chart of account is required for bill payment");

        var journalEntryLines = new List<JournalEntryLine>();
        var totalAmount = payment.Amount;
        var applicationMemos = new List<string>();
        JournalEntryLineContext? bankLineContext = null;

        foreach (var application in applications)
        {
            var bill = application.Bill
                ?? throw new Exception("Bill is required to create a bill payment journal entry.");

            if (application.AmountApplied == 0)
                continue;

            var payableOrCardAccountId = bill.BankCardId is > 0
                ? GetCreditCardAccountId(bill, chartOfAccounts, accountingOffice)
                : GetDefaultAccountsPayable(chartOfAccounts, bill.OfficeId, accountingOffice);

            var amount = application.AmountApplied;
            var applicationMemo = BuildBillPaymentApplicationMemo(bill, application.Description);
            applicationMemos.Add(applicationMemo);
            var lineContext = await ResolveReceiptJournalEntryLineContextAsync(bill);
            bankLineContext ??= lineContext;

            var payableLine = new JournalEntryLine
            {
                ChartOfAccountId = payableOrCardAccountId,
                Debit = amount > 0 ? amount : 0,
                Credit = amount < 0 ? Math.Abs(amount) : 0,
                Memo = applicationMemo,
                CreatedBy = currentUser
            };
            ApplyJournalEntryLineContext(payableLine, lineContext);

            if (application.CostCodeId is > 0)
                payableLine.CostCodeId = application.CostCodeId;

            journalEntryLines.Add(payableLine);
        }

        var bankLineMemo = BuildConsolidatedBillPaymentBankLineMemo(applications);
        if (string.IsNullOrWhiteSpace(bankLineMemo))
            bankLineMemo = payment.Description?.Trim() ?? string.Empty;

        var bankLine = new JournalEntryLine
        {
            ChartOfAccountId = bankAccountId,
            Debit = totalAmount < 0 ? Math.Abs(totalAmount) : 0,
            Credit = totalAmount > 0 ? totalAmount : 0,
            Memo = bankLineMemo,
            CreatedBy = currentUser
        };
        if (bankLineContext is { } resolvedBankLineContext)
            ApplyJournalEntryLineContext(bankLine, resolvedBankLineContext);

        journalEntryLines.Insert(0, bankLine);

        return ClassifyJournalEntry(new JournalEntry
        {
            OrganizationId = payment.OrganizationId,
            OfficeId = payment.OfficeId,
            TransactionDate = payment.PaymentDate,
            SourceTypeId = (int)SourceType.BillPayment,
            SourceId = payment.PaymentId,
            SourceCode = payment.PaymentCode,
            Memo = bankLineMemo,
            PaymentId = payment.PaymentId,
            PaymentCode = payment.PaymentCode,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        }, JournalEntryKind.BillPayment, Perspective.Company);
    }
    #endregion
}
