using RentAll.Domain.Enums;
using RentAll.Domain.Models;

namespace RentAll.Domain.Managers;

public partial class AccountingManager
{
    #region Triggers
    // Main outside trigger 
    public async Task<JournalEntry?> CreateJournalEntryFromBillAsync(Receipt bill, Guid currentUser)
        => (await CreateJournalEntryFromBillWithResultAsync(bill, currentUser)).JournalEntry;

    // Inside function that returns loggable errors
    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromBillWithResultAsync(Receipt bill, Guid currentUser)
    {
        if (!await IsAccountingFeatureEnabledAsync(bill.OrganizationId))
            return AccountingJournalEntryResult.Success();

        try
        {
            // Only bills come here, receipts go another route
            EnsureReceiptIsBill(bill);
            bill = await LoadReceiptWithSplitsAsync(bill);

            // Create the main bill JE
            var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(bill.OrganizationId, bill.OfficeId);
            var journalEntry = await BuildJournalEntryFromBillAsync(bill, chartOfAccounts, accountingOffice, currentUser);
            var created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);

            try
            {
                // If that bill is a Utility, create a second JE for owner accountability
                var ownerUtilityJournalEntry = await BuildJournalEntryFromBillForOwnerUtilityAsync(bill, chartOfAccounts, accountingOffice, currentUser);
                if (ownerUtilityJournalEntry != null)
                {
                    await CreateAutoGeneratedJournalEntryAsync(ownerUtilityJournalEntry);
                }
            }
            catch (Exception ownerUtilityEx)
            {
                var ownerUtilityMessage = $"Owner utility journal entry failed for bill {(string.IsNullOrWhiteSpace(bill.BillNumber) ? bill.ReceiptCode.Trim() : bill.BillNumber.Trim())}: {ownerUtilityEx.Message}";
                await LogAccountingErrorAsync(
                    trigger: "BillOwnerUtility",
                    organizationId: bill.OrganizationId,
                    officeId: bill.OfficeId,
                    sourceTypeId: (int)SourceType.Bill,
                    sourceId: bill.ReceiptId,
                    documentCode: string.IsNullOrWhiteSpace(bill.BillNumber) ? bill.ReceiptCode.Trim() : bill.BillNumber.Trim(),
                    accountingPeriod: bill.AccountingPeriod == default ? null : bill.AccountingPeriod,
                    amount: bill.Amount,
                    message: ownerUtilityMessage,
                    currentUser: currentUser);
                return AccountingJournalEntryResult.WarningResult(ownerUtilityMessage, created);
            }

            return AccountingJournalEntryResult.Success(created);
        }
        catch (Exception ex)
        {
            await LogAccountingErrorAsync(
                trigger: "Bill",
                organizationId: bill.OrganizationId,
                officeId: bill.OfficeId,
                sourceTypeId: (int)SourceType.Bill,
                sourceId: bill.ReceiptId,
                documentCode: string.IsNullOrWhiteSpace(bill.BillNumber) ? bill.ReceiptCode.Trim() : bill.BillNumber.Trim(),
                accountingPeriod: bill.AccountingPeriod == default ? null : bill.AccountingPeriod,
                amount: bill.Amount,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }

    public async Task<List<JournalEntry>> CreateJournalEntriesFromBillPaymentAsync(BillPayment billPayment, Guid currentUser)
    {
        var journalEntries = new List<JournalEntry>();

        if (billPayment.PaymentApplications.Count == 0)
            return journalEntries;

        foreach (var paymentApplication in billPayment.PaymentApplications)
        {
            var journalEntry = await CreateJournalEntryFromBillPaymentAsync(paymentApplication, currentUser);
            if (journalEntry != null)
                journalEntries.Add(journalEntry);
        }

        return journalEntries;
    }

    private async Task<JournalEntry?> CreateJournalEntryFromBillPaymentAsync(BillPaymentApplication paymentApplication, Guid currentUser)
        => (await CreateJournalEntryFromBillPaymentWithResultAsync(paymentApplication, currentUser)).JournalEntry;

    private async Task<AccountingJournalEntryResult> CreateJournalEntryFromBillPaymentWithResultAsync(BillPaymentApplication paymentApplication, Guid currentUser)
    {
        var bill = paymentApplication.Bill;
        if (bill == null)
            return AccountingJournalEntryResult.WarningResult("Bill is required to create a bill payment journal entry");

        if (!await IsAccountingFeatureEnabledAsync(bill.OrganizationId))
            return AccountingJournalEntryResult.Success();

        try
        {
            if (paymentApplication.PaymentSequence < 0)
                return AccountingJournalEntryResult.WarningResult("PaymentSequence is required to create a bill payment journal entry");

            if (bill.ReceiptId == Guid.Empty)
                return AccountingJournalEntryResult.WarningResult("ReceiptId is required to create a bill payment journal entry");

            var (chartOfAccounts, accountingOffice) = await LoadAccountContextAsync(bill.OrganizationId, bill.OfficeId);
            var journalEntry = await BuildJournalEntryFromBillPaymentAsync(paymentApplication, chartOfAccounts, accountingOffice, currentUser);
            var created = await CreateAutoGeneratedJournalEntryAsync(journalEntry);
            return AccountingJournalEntryResult.Success(created);
        }
        catch (Exception ex)
        {
            var billLabel = !string.IsNullOrWhiteSpace(bill.BillNumber) ? bill.BillNumber.Trim() : bill.ReceiptCode.Trim();
            await LogAccountingErrorAsync(
                trigger: "BillPayment",
                organizationId: bill.OrganizationId,
                officeId: bill.OfficeId,
                sourceTypeId: (int)SourceType.BillPayment,
                sourceId: bill.ReceiptId,
                documentCode: billLabel,
                accountingPeriod: bill.AccountingPeriod == default ? null : bill.AccountingPeriod,
                amount: paymentApplication.AmountApplied,
                message: ex.Message,
                currentUser: currentUser);
            return AccountingJournalEntryResult.WarningResult(ex.Message);
        }
    }
    #endregion

    #region Journal Entry
    private async Task<JournalEntry> BuildJournalEntryFromBillAsync(Receipt bill, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // BILL-JE-ACCOUNTS
        // Positive splits:
        //   Credit - Accounts Payable (GetDefaultAccountsPayable) for the split total.
        //   Debit  - Expense account per split as defined by the user they default to the following
        //   (GetDefaultTenantExpense, GetDefaultDepartureExpense, GetDefaultOwnerExpense, or GetDefaultCompanyExpense).
        // Negative splits (bill credits):
        //   Exact opposite
        // END BILL-JE-ACCOUNTS

        EnsureReceiptIsBill(bill);
        bill = await LoadReceiptWithSplitsAsync(bill);

        var splitLines = (bill.Splits ?? new List<ReceiptSplit>())
            .OrderBy(s => s.ReceiptSplitId)
            .ToList();
        var nonZeroSplits = splitLines.Where(split => split.Amount != 0).ToList();
        if (nonZeroSplits.Count > 0)
            splitLines = nonZeroSplits;
        else if (splitLines.Count == 0 && bill.Amount != 0)
        {
            splitLines =
            [
                new ReceiptSplit
                {
                    Amount = bill.Amount,
                    Description = bill.Description,
                    ChartOfAccountId = null
                }
            ];
        }

        if (bill.AccountingPeriod == default)
            throw new Exception("AccountingPeriod is required to create a journal entry for a bill");

        if (bill.ReceiptDate == default)
            throw new Exception("ReceiptDate is required to create a journal entry for a bill");

        var accountsPayableAccountId = GetDefaultAccountsPayable(chartOfAccounts, bill.OfficeId, accountingOffice);
        var transactionDate = ResolveBillOrReceiptJournalEntryDate(bill);
        var receiptCode = bill.ReceiptCode.Trim();
        var billDescriptionSuffix = string.IsNullOrWhiteSpace((bill.Description ?? string.Empty).Trim()) ? string.Empty : $": {(bill.Description ?? string.Empty).Trim()}";
        var propertyId = bill.PropertyIds.FirstOrDefault(id => id != Guid.Empty);
        var eligibleSplits = splitLines
            .Where(split => split.ReceiptType != ReceiptType.NonExpense)
            .Where(split => split.Amount != 0)
            .ToList();
        var positiveSplits = eligibleSplits.Where(s => s.Amount > 0).ToList();
        var negativeSplits = eligibleSplits.Where(s => s.Amount < 0).ToList();
        var journalEntryLines = new List<JournalEntryLine>();

        var positiveTotal = positiveSplits.Sum(s => s.Amount);
        if (positiveTotal > 0)
        {
            journalEntryLines.Add(new JournalEntryLine
            {
                // Credit Accounts Payable
                ChartOfAccountId = accountsPayableAccountId,
                PropertyId = propertyId == Guid.Empty ? null : propertyId,
                ContactId = bill.VendorId,
                Debit = 0,
                Credit = positiveTotal,
                Memo = receiptCode + billDescriptionSuffix,
                CreatedBy = currentUser
            });

            foreach (var split in positiveSplits)
            {
                var expenseAccountId = GetBillReceiptExpenseAccountId(split, bill.OfficeId, chartOfAccounts, accountingOffice);
                var splitDescriptionSuffix = string.IsNullOrWhiteSpace((split.Description ?? string.Empty).Trim()) ? string.Empty : $": {(split.Description ?? string.Empty).Trim()}";

                journalEntryLines.Add(new JournalEntryLine
                {
                    // Debit Expense
                    ChartOfAccountId = expenseAccountId,
                    PropertyId = propertyId == Guid.Empty ? null : propertyId,
                    ContactId = bill.VendorId,
                    Debit = split.Amount,
                    Credit = 0,
                    Memo = receiptCode + splitDescriptionSuffix,
                    CreatedBy = currentUser
                });
            }
        }

        var negativeTotal = negativeSplits.Sum(s => s.Amount);
        if (negativeTotal < 0)
        {
            journalEntryLines.Add(new JournalEntryLine
            {
                // Debit Accounts Payable
                ChartOfAccountId = accountsPayableAccountId,
                PropertyId = propertyId == Guid.Empty ? null : propertyId,
                ContactId = bill.VendorId,
                Debit = Math.Abs(negativeTotal),
                Credit = 0,
                Memo = receiptCode + billDescriptionSuffix,
                CreatedBy = currentUser
            });

            foreach (var split in negativeSplits)
            {
                var expenseAccountId = GetBillReceiptExpenseAccountId(split, bill.OfficeId, chartOfAccounts, accountingOffice);
                var splitDescriptionSuffix = string.IsNullOrWhiteSpace((split.Description ?? string.Empty).Trim()) ? string.Empty : $": {(split.Description ?? string.Empty).Trim()}";
                journalEntryLines.Add(new JournalEntryLine
                {
                    // Credit ExpenseAccountId
                    ChartOfAccountId = expenseAccountId,
                    PropertyId = propertyId == Guid.Empty ? null : propertyId,
                    ContactId = bill.VendorId,
                    Debit = 0,
                    Credit = Math.Abs(split.Amount),
                    Memo = receiptCode + splitDescriptionSuffix,
                    CreatedBy = currentUser
                });
            }
        }

        return new JournalEntry
        {
            OrganizationId = bill.OrganizationId,
            OfficeId = bill.OfficeId,
            TransactionDate = transactionDate,
            SourceTypeId = (int)SourceType.Bill,
            SourceId = bill.ReceiptId,
            Memo = receiptCode + billDescriptionSuffix,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };
    }

    private async Task<JournalEntry> BuildJournalEntryFromBillPaymentAsync(BillPaymentApplication paymentApplication, List<ChartOfAccount> chartOfAccounts, AccountingOffice? accountingOffice, Guid currentUser)
    {
        // AGENT-NOTE: DO NOT TOUCH.
        // BILL-PAYMENT-JE-ACCOUNTS
        // Line 1 — Debit: Accounts Payable (GetDefaultAccountsPayable) or the credit card account on the bill's bank card.
        // Line 2 — Credit: Bank account selected on the payment (paymentApplication.ChartOfAccountId).
        // END BILL-PAYMENT-JE-ACCOUNTS

        var bill = paymentApplication.Bill;
        if (paymentApplication.AmountApplied == 0)
            throw new Exception("Bill payment amount cannot be zero");

        if (paymentApplication.PaymentDate == default)
            throw new Exception("Payment date is required to create a bill payment journal entry");

        if (paymentApplication.ChartOfAccountId <= 0)
            throw new Exception("Chart of account is required for bill payment");

        var payableOrCardAccountId = bill.BankCardId is > 0
            ? GetCreditCardAccountId(bill, chartOfAccounts, accountingOffice)
            : GetDefaultAccountsPayable(chartOfAccounts, bill.OfficeId, accountingOffice);
        var paymentBankAccountId = paymentApplication.ChartOfAccountId;

        var amount = paymentApplication.AmountApplied;
        var transactionDate = paymentApplication.PaymentDate;
        var receiptCode = bill.ReceiptCode.Trim();
        var billDescription = string.IsNullOrWhiteSpace((bill.Description ?? string.Empty).Trim()) ? string.Empty : $": {(bill.Description ?? string.Empty).Trim()}";
        var propertyId = bill.PropertyIds.FirstOrDefault(id => id != Guid.Empty);
        var journalEntryLines = new List<JournalEntryLine>
        {
            new JournalEntryLine
            {
                // Debit Accounts Payable or Credit Card
                ChartOfAccountId = payableOrCardAccountId,
                PropertyId = propertyId == Guid.Empty ? null : propertyId,
                ContactId = bill.VendorId,
                Debit = amount > 0 ? amount : 0,
                Credit = amount < 0 ? Math.Abs(amount) : 0,
                Memo = bill.ReceiptCode.Trim() + billDescription,
                CreatedBy = currentUser
            },
            new JournalEntryLine
            {
                // Credit Payment Bank Account
                ChartOfAccountId = paymentBankAccountId,
                PropertyId = propertyId == Guid.Empty ? null : propertyId,
                ContactId = bill.VendorId,
                Debit = amount < 0 ? Math.Abs(amount) : 0,
                Credit = amount > 0 ? amount : 0,
                Memo = receiptCode + billDescription,
                CreatedBy = currentUser
            }
        };

        return new JournalEntry
        {
            OrganizationId = bill.OrganizationId,
            OfficeId = bill.OfficeId,
            TransactionDate = transactionDate,
            SourceTypeId = (int)SourceType.BillPayment,
            SourceId = bill.ReceiptId,
            Memo = receiptCode + billDescription,
            JournalEntryLines = journalEntryLines,
            CreatedBy = currentUser
        };
    }
    #endregion

    #region Helpers
    private async Task<int> GetNextBillPaymentSequenceAsync(Receipt bill)
    {
        var existingEntries = await _journalEntryRepository.GetJournalEntriesAsync(new JournalEntryGetCriteria
        {
            OrganizationId = bill.OrganizationId,
            OfficeIds = bill.OfficeId.ToString(),
            SourceTypeId = (int)SourceType.BillPayment,
            SourceId = bill.ReceiptId,
            IncludeVoided = true,
            IncludeUnposted = true
        });

        return existingEntries.Count();
    }

    private static void EnsureReceiptIsBill(Receipt bill)
    {
        if (bill.BankCardId != null)
            throw new Exception("Receipt is not a bill");
    }

    private static void EnsureBillIsUtility(Receipt bill)
    {
        if (bill.BankCardId != null || !bill.IsUtility)
            throw new Exception("Receipt is not a utility");
    }

    #endregion
}
